import type { Profession } from "../types";

// Structurally complete, but factually PLACEHOLDER.
// These profiles have not been reviewed against country-specific law and
// must not present unsupported claims about legal authority, eligibility,
// education, powers, salary or guaranteed progression.

function ph(p: Partial<Profession> & Pick<Profession, "id" | "slug" | "titleCanonical" | "titleSv" | "titleEn" | "family" | "category" | "level" | "sector" | "orientation" | "description" | "overview" | "roleFor" | "responsibilities" | "competencies" | "countries">): Profession {
  return {
    status: "placeholder",
    regulated: false,
    icon: "shield",
    recommendedAssessment: "security-career-assessment",
    ...p,
  };
}

export const policeOfficer: Profession = ph({
  id: "police-officer",
  slug: "police-officer",
  titleCanonical: "Police Officer",
  titleSv: "Polis",
  titleEn: "Police Officer",
  family: "public_safety_justice",
  category: "public_safety",
  level: "mid",
  sector: "public",
  orientation: ["operational"],
  icon: "shield",
  description: { sv: "Myndighetsutövning inom ordning, utredning och rättsvård.", en: "Public-authority role in public order, investigation and law enforcement." },
  overview: { sv: "Polisyrket är en statlig myndighetsroll vars innehåll, behörighet och utbildning skiljer sig mellan länder. Detaljer i den här guiden är under utveckling och land-specifika krav behöver granskas separat.", en: "Police work is a state-authority role whose content, eligibility and training vary between countries. Details in this guide are under development and country-specific requirements must be reviewed separately." },
  roleFor: { sv: "Passar dig som söker samhällsuppdrag, samarbete och långsiktig professionell utveckling.", en: "Suits people seeking public service, teamwork and long-term professional development." },
  responsibilities: [
    { sv: "Innehåll varierar mellan länder. Guiden är under utveckling.", en: "Content varies between countries. This guide is under development." },
  ],
  competencies: [
    { competencyId: "integrity", requiredLevel: 4, critical: true },
    { competencyId: "communication", requiredLevel: 4 },
    { competencyId: "decision_making", requiredLevel: 4 },
    { competencyId: "stress", requiredLevel: 4 },
    { competencyId: "legal_regulatory", requiredLevel: 4 },
  ],
  regulatoryNotes: { sv: "Behörighet, utbildning och befogenheter fastställs av respektive lands myndigheter. CQrityjob avgör inte lämplighet för polisyrket.", en: "Eligibility, training and powers are set by each country's authorities. CQrityjob does not determine suitability for police service." },
  countries: ["SE", "EU", "INTL"],
  educationPathways: ["se-polisprogrammet"],
  related: ["ordningsvakt", "security-investigator", "intelligence-analyst"],
  nextRoles: ["security-investigator", "intelligence-analyst", "security-manager", "security-consultant"],
  regulated: true,
});

export const militarySecuritySpecialist: Profession = ph({
  id: "military-security-specialist",
  slug: "military-security-specialist",
  titleCanonical: "Military Security Specialist",
  titleSv: "Militär säkerhetsspecialist",
  titleEn: "Military Security Specialist",
  family: "defence_national_security",
  category: "protective",
  level: "mid",
  sector: "public",
  orientation: ["operational"],
  icon: "shield",
  description: { sv: "Säkerhetsroller inom försvarsmakten – innehållet skiljer sig mellan länder.", en: "Security roles within a country's armed forces – content varies between countries." },
  overview: { sv: "Militär säkerhet är ett brett fält. Guiden är under utveckling och gör inga uttalanden om behörighet, befogenheter eller övergång till civila roller.", en: "Military security is a broad field. This guide is under development and makes no claims about eligibility, authority or transition into civilian roles." },
  roleFor: { sv: "Passar dig som är intresserad av försvar, disciplin och strukturerat arbete.", en: "Suits people interested in defence, discipline and structured work." },
  responsibilities: [
    { sv: "Ansvarsområden varierar mellan tjänster och länder.", en: "Responsibilities vary between duties and countries." },
  ],
  competencies: [
    { competencyId: "integrity", requiredLevel: 4, critical: true },
    { competencyId: "risk_awareness", requiredLevel: 4 },
    { competencyId: "planning", requiredLevel: 3 },
    { competencyId: "teamwork", requiredLevel: 4 },
    { competencyId: "stress", requiredLevel: 4 },
  ],
  regulatoryNotes: { sv: "Militärtjänst regleras av respektive lands försvarsmakt. CQrityjob avgör inte lämplighet för militärtjänst.", en: "Military service is governed by each country's armed forces. CQrityjob does not determine suitability for military service." },
  countries: ["SE", "EU", "INTL"],
  related: ["close-protection", "skyddsvakt", "data-center-security"],
  nextRoles: ["close-protection", "data-center-security", "security-manager"],
});

export const correctionalOfficer: Profession = ph({
  id: "correctional-officer",
  slug: "correctional-officer",
  titleCanonical: "Correctional Officer",
  titleSv: "Kriminalvårdare",
  titleEn: "Correctional Officer",
  family: "corrections_secure_transport",
  category: "public_safety",
  level: "entry",
  sector: "public",
  orientation: ["operational"],
  icon: "shield",
  description: { sv: "Arbete inom kriminalvården med säkerhet, omvårdnad och återanpassning.", en: "Work within correctional services combining security, care and rehabilitation." },
  overview: { sv: "Roll och behörighet fastställs av respektive lands kriminalvårdsmyndighet. Guiden är under utveckling.", en: "Role and eligibility are defined by each country's correctional authority. This guide is under development." },
  roleFor: { sv: "Passar dig som är trygg i mötet med människor i utsatta situationer.", en: "Suits people who are steady when working with people in difficult situations." },
  responsibilities: [{ sv: "Innehåll är under uppbyggnad.", en: "Content is being built." }],
  competencies: [
    { competencyId: "integrity", requiredLevel: 4, critical: true },
    { competencyId: "communication", requiredLevel: 4 },
    { competencyId: "conflict", requiredLevel: 4 },
    { competencyId: "stress", requiredLevel: 3 },
  ],
  regulated: true,
  countries: ["SE", "EU", "INTL"],
  related: ["police-officer", "security-officer"],
});

export const customsOfficer: Profession = ph({
  id: "customs-officer",
  slug: "customs-officer",
  titleCanonical: "Customs Officer",
  titleSv: "Tulltjänsteman",
  titleEn: "Customs Officer",
  family: "public_safety_justice",
  category: "public_safety",
  level: "mid",
  sector: "public",
  orientation: ["operational", "analytical"],
  icon: "truck",
  description: { sv: "Kontroll av varor och personer vid gränser samt bekämpning av smuggling.", en: "Control of goods and persons at borders and prevention of smuggling." },
  overview: { sv: "Behörighet, mandat och organisation styrs av respektive lands tullmyndighet. Guiden är under utveckling.", en: "Authority, mandate and structure are set by each country's customs administration. This guide is under development." },
  roleFor: { sv: "Passar dig som gillar noggrannhet, analys och operativ kontroll.", en: "Suits people who value precision, analysis and operational control." },
  responsibilities: [{ sv: "Innehåll är under uppbyggnad.", en: "Content is being built." }],
  competencies: [
    { competencyId: "integrity", requiredLevel: 4, critical: true },
    { competencyId: "observation", requiredLevel: 4 },
    { competencyId: "analytical", requiredLevel: 3 },
    { competencyId: "legal_regulatory", requiredLevel: 3 },
  ],
  regulated: true,
  countries: ["SE", "EU", "INTL"],
  related: ["police-officer", "intelligence-analyst"],
});

export const securityCoordinator: Profession = ph({
  id: "security-coordinator",
  slug: "security-coordinator",
  titleCanonical: "Security Coordinator",
  titleSv: "Säkerhetssamordnare",
  titleEn: "Security Coordinator",
  family: "security_leadership_governance",
  category: "corporate",
  level: "mid",
  sector: "private",
  orientation: ["operational", "leadership"],
  icon: "clipboard",
  description: { sv: "Samordning av säkerhetsarbetet i en organisation, ofta som brygga mellan operativ och strategisk nivå.", en: "Coordination of security work in an organisation, often bridging operational and strategic levels." },
  overview: { sv: "Rollen är utbredd men saknar formell reglering. Guiden är strukturellt komplett men innehållet är under utveckling.", en: "The role is widespread but not formally regulated. The guide is structurally complete but content is under development." },
  roleFor: { sv: "Passar dig som är strukturerad och trivs mellan operativa team och ledning.", en: "Suits people who are structured and thrive between operational teams and leadership." },
  responsibilities: [{ sv: "Innehåll är under uppbyggnad.", en: "Content is being built." }],
  competencies: [
    { competencyId: "communication", requiredLevel: 4 },
    { competencyId: "planning", requiredLevel: 3 },
    { competencyId: "reporting", requiredLevel: 3 },
    { competencyId: "risk_awareness", requiredLevel: 3 },
  ],
  countries: ["SE", "EU", "INTL"],
  related: ["security-officer", "security-manager"],
  nextRoles: ["security-manager"],
});

export const securityInvestigator: Profession = ph({
  id: "security-investigator",
  slug: "security-investigator",
  titleCanonical: "Security Investigator",
  titleSv: "Säkerhetsutredare",
  titleEn: "Security or Corporate Investigator",
  family: "investigations_intelligence",
  category: "investigations",
  level: "mid",
  sector: "private",
  orientation: ["analytical", "operational"],
  icon: "file-search",
  description: { sv: "Interna utredningar, säkerhetsincidenter och företagsförskingring.", en: "Internal investigations, security incidents and corporate wrongdoing." },
  overview: { sv: "Rollen är etablerad men innehåll och rättslig ram varierar. Guiden är under utveckling.", en: "The role is established but content and legal framing vary. This guide is under development." },
  roleFor: { sv: "Passar dig som är noggrann, diskret och analytisk.", en: "Suits people who are precise, discreet and analytical." },
  responsibilities: [{ sv: "Innehåll är under uppbyggnad.", en: "Content is being built." }],
  competencies: [
    { competencyId: "analytical", requiredLevel: 4, critical: true },
    { competencyId: "reporting", requiredLevel: 4 },
    { competencyId: "integrity", requiredLevel: 4, critical: true },
    { competencyId: "legal_regulatory", requiredLevel: 3 },
  ],
  countries: ["SE", "EU", "INTL"],
  certifications: ["cfe"],
  related: ["police-officer", "fraud-investigator", "intelligence-analyst"],
});

export const intelligenceAnalyst: Profession = ph({
  id: "intelligence-analyst",
  slug: "intelligence-analyst",
  titleCanonical: "Intelligence Analyst",
  titleSv: "Underrättelseanalytiker",
  titleEn: "Intelligence Analyst",
  family: "investigations_intelligence",
  category: "investigations",
  level: "mid",
  sector: "hybrid",
  orientation: ["analytical"],
  icon: "brain",
  description: { sv: "Insamling, analys och rapportering av underrättelse för beslutsfattande.", en: "Collection, analysis and reporting of intelligence for decision-making." },
  overview: { sv: "Analytikerroller finns inom myndigheter, försvar och privat sektor. Detaljer varierar och guiden är under utveckling.", en: "Analyst roles exist within government, defence and private sector. Details vary and this guide is under development." },
  roleFor: { sv: "Passar dig som gillar mönster, källkritik och strukturerad analys.", en: "Suits people who enjoy patterns, source criticism and structured analysis." },
  responsibilities: [{ sv: "Innehåll är under uppbyggnad.", en: "Content is being built." }],
  competencies: [
    { competencyId: "analytical", requiredLevel: 4, critical: true },
    { competencyId: "reporting", requiredLevel: 4 },
    { competencyId: "communication", requiredLevel: 3 },
    { competencyId: "integrity", requiredLevel: 4 },
  ],
  countries: ["SE", "EU", "INTL"],
  related: ["security-investigator", "police-officer", "soc-analyst"],
});

export const fraudInvestigator: Profession = ph({
  id: "fraud-investigator",
  slug: "fraud-investigator",
  titleCanonical: "Fraud Investigator",
  titleSv: "Bedrägeriutredare",
  titleEn: "Fraud Investigator",
  family: "investigations_intelligence",
  category: "investigations",
  level: "mid",
  sector: "private",
  orientation: ["analytical"],
  icon: "search",
  description: { sv: "Utredning av bedrägerier, oegentligheter och finansiell brottslighet.", en: "Investigation of fraud, misconduct and financial crime." },
  overview: { sv: "Rollen finns inom banker, försäkring, e-handel och myndigheter. Guiden är under utveckling.", en: "The role exists across banking, insurance, e-commerce and government. This guide is under development." },
  roleFor: { sv: "Passar dig som är analytisk, uthållig och noggrann.", en: "Suits people who are analytical, persistent and precise." },
  responsibilities: [{ sv: "Innehåll är under uppbyggnad.", en: "Content is being built." }],
  competencies: [
    { competencyId: "analytical", requiredLevel: 4, critical: true },
    { competencyId: "reporting", requiredLevel: 4 },
    { competencyId: "legal_regulatory", requiredLevel: 3 },
    { competencyId: "integrity", requiredLevel: 4, critical: true },
  ],
  countries: ["SE", "EU", "INTL"],
  certifications: ["cfe", "acams-cams"],
  related: ["aml-specialist", "security-investigator"],
});

export const socAnalyst: Profession = ph({
  id: "soc-analyst",
  slug: "soc-analyst",
  titleCanonical: "SOC Analyst",
  titleSv: "SOC-analytiker",
  titleEn: "SOC Analyst",
  family: "cyber_information_security",
  category: "cyber",
  level: "entry",
  sector: "private",
  orientation: ["technical", "analytical"],
  icon: "lock",
  description: { sv: "Övervakning, triagering och respons på cyberincidenter i en säkerhetsdriftcentral (SOC).", en: "Monitoring, triage and response to cyber incidents in a Security Operations Center (SOC)." },
  overview: { sv: "Rollen är ung och snabbrörlig. Krav och arbetssätt varierar mellan organisationer. Guiden är under utveckling.", en: "The role is young and fast-moving. Requirements and practices vary between organisations. This guide is under development." },
  roleFor: { sv: "Passar dig som är tekniskt nyfiken och lugn i incidenter.", en: "Suits people who are technically curious and calm during incidents." },
  responsibilities: [{ sv: "Innehåll är under uppbyggnad.", en: "Content is being built." }],
  competencies: [
    { competencyId: "technical", requiredLevel: 3 },
    { competencyId: "analytical", requiredLevel: 3 },
    { competencyId: "incident_mgmt", requiredLevel: 3 },
    { competencyId: "reporting", requiredLevel: 3 },
  ],
  countries: ["SE", "EU", "INTL"],
  certifications: ["cissp", "iso-27001"],
  related: ["intelligence-analyst", "security-consultant"],
});

export const securityConsultant: Profession = ph({
  id: "security-consultant",
  slug: "security-consultant",
  titleCanonical: "Security Consultant",
  titleSv: "Säkerhetskonsult",
  titleEn: "Security Consultant",
  family: "security_leadership_governance",
  category: "corporate",
  level: "senior",
  sector: "private",
  orientation: ["analytical", "leadership"],
  icon: "handshake",
  description: { sv: "Rådgivning inom säkerhet, risk och kontinuitet till kunder över branscher.", en: "Advisory work in security, risk and continuity for clients across industries." },
  overview: { sv: "Rollen är bred och tvärgående. Guiden är strukturellt komplett men innehållet är under utveckling.", en: "The role is broad and cross-cutting. The guide is structurally complete but content is under development." },
  roleFor: { sv: "Passar erfarna profiler som gillar variation, rådgivning och kundmöten.", en: "Suits experienced professionals who enjoy variety, advisory work and client engagements." },
  responsibilities: [{ sv: "Innehåll är under uppbyggnad.", en: "Content is being built." }],
  competencies: [
    { competencyId: "communication", requiredLevel: 4 },
    { competencyId: "analytical", requiredLevel: 4 },
    { competencyId: "leadership", requiredLevel: 3 },
    { competencyId: "planning", requiredLevel: 3 },
  ],
  countries: ["SE", "EU", "INTL"],
  certifications: ["asis-cpp"],
  related: ["security-manager", "risk-manager", "crisis-continuity-manager"],
});