import type { Profession } from "../types";

// Ten priority pilot profiles.
// Where sources are available, status = "researched".
// Records use IDs and relationships — no duplicated education/certification data.

export const securityOfficer: Profession = {
  id: "security-officer",
  slug: "security-officer",
  status: "researched",
  lastVerified: "2026-07-16",
  titleCanonical: "Security Officer",
  titleSv: "Väktare",
  titleEn: "Security Officer",
  aliases: [{ sv: "Bevakningsanställd", en: "Guard" }],
  family: "protective_operations",
  category: "guarding",
  level: "entry",
  sector: "private",
  orientation: ["operational"],
  icon: "shield-check",
  description: { sv: "Operativa bevakningsuppdrag inom auktoriserad bevakningsverksamhet.", en: "Operational guarding duties within authorised guarding companies." },
  overview: {
    sv: "Väktare arbetar inom auktoriserade bevakningsföretag och utför bevaknings-, ronderings- och larmuppdrag hos kund. Verksamheten och yrket regleras i Sverige av lagen (1974:191) om bevakningsföretag och Polismyndighetens föreskrifter.",
    en: "Security officers work for authorised guarding companies performing guarding, patrol and alarm response for clients. In Sweden the activity and role are regulated by the Guarding Companies Act (1974:191) and the Swedish Police Authority's regulations.",
  },
  roleFor: { sv: "Rollen passar dig som är lugn, strukturerad och trygg i mötet med människor.", en: "Suits people who are calm, structured and confident in interacting with others." },
  responsibilities: [
    { sv: "Utföra bevaknings-, rondering- och larmuppdrag enligt uppdragsinstruktion.", en: "Perform guarding, patrol and alarm response duties per assignment instructions." },
    { sv: "Rapportera händelser och avvikelser sakligt.", en: "Report events and deviations factually." },
    { sv: "Samverka med kund, kollegor och vid behov med polis.", en: "Collaborate with client, colleagues and, when needed, the police." },
  ],
  workEnvironments: [
    { sv: "Butiks-, kontors- och industrimiljöer.", en: "Retail, office and industrial environments." },
    { sv: "Rondering och larmutryckning.", en: "Patrols and alarm response." },
  ],
  industries: [
    { sv: "Bevakningsföretag, fastighet, handel, transport, industri.", en: "Guarding companies, real estate, retail, transport, industry." },
  ],
  competencies: [
    { competencyId: "integrity", requiredLevel: 3, critical: true },
    { competencyId: "observation", requiredLevel: 3 },
    { competencyId: "communication", requiredLevel: 3 },
    { competencyId: "reporting", requiredLevel: 3 },
    { competencyId: "customer_service", requiredLevel: 3 },
    { competencyId: "conflict", requiredLevel: 2 },
    { competencyId: "risk_awareness", requiredLevel: 3 },
  ],
  formalRequirements: [
    { sv: "Ålder minst 18 år och godkänd lämplighetsprövning enligt Polismyndighetens föreskrifter.", en: "Minimum age 18 and approved suitability review under Swedish Police regulations." },
    { sv: "Genomförd väktarutbildning hos auktoriserat bevakningsföretag.", en: "Completed security-officer training at an authorised guarding company." },
  ],
  regulated: true,
  regulatoryNotes: { sv: "Yrket är reglerat i Sverige. Motsvarande regelverk och benämning varierar mellan länder.", en: "The role is regulated in Sweden. Equivalent regulation and terminology vary between countries." },
  countries: ["SE"],
  educationPathways: ["se-vaktarutbildning"],
  certifications: [],
  previousRoles: [],
  nextRoles: ["ordningsvakt", "skyddsvakt", "security-coordinator"],
  related: ["ordningsvakt", "skyddsvakt", "close-protection", "data-center-security"],
  recommendedAssessment: "security-career-assessment",
  relatedJobsQuery: "security-officer",
  sources: [
    { label: { sv: "Lag (1974:191) om bevakningsföretag", en: "Guarding Companies Act (1974:191)" }, publisher: "Sveriges riksdag", url: "https://www.riksdagen.se/sv/dokument-lagar/dokument/svensk-forfattningssamling/lag-1974191-om-bevakningsforetag_sfs-1974-191" },
    { label: { sv: "Polismyndigheten – Bevakningsföretag och väktare", en: "Swedish Police – Guarding companies and security officers" }, publisher: "Polismyndigheten", url: "https://polisen.se/tjanster-tillstand/tillstand/bevakningsforetag/" },
  ],
};

export const ordningsvakt: Profession = {
  id: "ordningsvakt",
  slug: "ordningsvakt",
  status: "researched",
  lastVerified: "2026-07-16",
  titleCanonical: "Public Order Officer",
  titleSv: "Ordningsvakt",
  titleEn: "Public Order Officer",
  family: "public_safety_justice",
  category: "public_safety",
  level: "entry",
  sector: "hybrid",
  orientation: ["operational"],
  icon: "shield",
  description: { sv: "Förordnad av Polismyndigheten för att medverka till att upprätthålla allmän ordning.", en: "Appointed by the Swedish Police Authority to help maintain public order." },
  overview: {
    sv: "Ordningsvakt är en särskild ställning enligt lag (1980:578) om ordningsvakter. Ordningsvakter förordnas av Polismyndigheten och har vissa befogenheter att medverka till att upprätthålla allmän ordning på angivna platser.",
    en: "A Swedish Public Order Officer is a statutory role under the Public Order Officers Act (1980:578). Officers are appointed by the Swedish Police Authority and have limited powers to help maintain public order at designated locations.",
  },
  roleFor: { sv: "Rollen passar dig som vill arbeta operativt med allmän ordning under Polismyndighetens tillsyn.", en: "Suits people who want to work operationally with public order under Swedish Police oversight." },
  responsibilities: [
    { sv: "Medverka till att upprätthålla allmän ordning enligt förordnandet.", en: "Help maintain public order within the terms of the appointment." },
    { sv: "Rapportera och dokumentera händelser till Polismyndigheten.", en: "Report and document incidents to the Swedish Police Authority." },
  ],
  competencies: [
    { competencyId: "integrity", requiredLevel: 4, critical: true },
    { competencyId: "legal_regulatory", requiredLevel: 3, critical: true },
    { competencyId: "conflict", requiredLevel: 3 },
    { competencyId: "decision_making", requiredLevel: 3 },
    { competencyId: "communication", requiredLevel: 3 },
    { competencyId: "stress", requiredLevel: 3 },
  ],
  formalRequirements: [
    { sv: "Godkänd lämplighetsprövning och grundutbildning för ordningsvakt.", en: "Approved suitability review and basic training as a public order officer." },
    { sv: "Förordnande från Polismyndigheten.", en: "Appointment issued by the Swedish Police Authority." },
  ],
  regulated: true,
  regulatoryNotes: { sv: "Ordningsvakt är en svensk myndighetsförordnad ställning – motsvarigheter finns inte i alla länder.", en: "Swedish public order officer is a state-appointed status – equivalents do not exist in every country." },
  countries: ["SE"],
  educationPathways: ["se-ordningsvaktsutbildning"],
  related: ["security-officer", "skyddsvakt", "police-officer"],
  nextRoles: ["security-manager", "security-coordinator"],
  recommendedAssessment: "security-career-assessment",
  sources: [
    { label: { sv: "Lag (1980:578) om ordningsvakter", en: "Public Order Officers Act (1980:578)" }, publisher: "Sveriges riksdag", url: "https://www.riksdagen.se/sv/dokument-lagar/dokument/svensk-forfattningssamling/lag-1980578-om-ordningsvakter_sfs-1980-578" },
    { label: { sv: "Polismyndigheten – Ordningsvakter", en: "Swedish Police – Public order officers" }, publisher: "Polismyndigheten", url: "https://polisen.se/tjanster-tillstand/tillstand/ordningsvakt/" },
  ],
};

export const skyddsvakt: Profession = {
  id: "skyddsvakt",
  slug: "skyddsvakt",
  status: "researched",
  lastVerified: "2026-07-16",
  titleCanonical: "Protective Security Guard",
  titleSv: "Skyddsvakt",
  titleEn: "Protective Security Guard",
  family: "protective_operations",
  category: "protective",
  level: "entry",
  sector: "hybrid",
  orientation: ["operational"],
  icon: "user-check",
  description: { sv: "Bevakning av skyddsobjekt enligt skyddslagen (2010:305).", en: "Guarding of protected objects under the Swedish Protective Security Act (2010:305)." },
  overview: {
    sv: "Skyddsvakter bevakar skyddsobjekt – anläggningar och områden som är särskilt skyddsvärda enligt skyddslagen. Rollen ger vissa befogenheter inom området och kräver godkännande.",
    en: "Protective security guards guard 'skyddsobjekt' – installations and areas designated as protected under the Swedish Protective Security Act. The role carries limited powers on the site and requires approval.",
  },
  roleFor: { sv: "Passar dig som är noggrann, disciplinerad och trivs med tydliga rutiner.", en: "Suits people who are precise, disciplined and thrive on clear procedures." },
  responsibilities: [
    { sv: "Bevaka skyddsobjektet enligt uppdrag och instruktion.", en: "Guard the protected object per assignment and instruction." },
    { sv: "Utföra kontroll av personer och fordon inom skyddsområdet.", en: "Conduct checks of persons and vehicles within the protected area." },
  ],
  competencies: [
    { competencyId: "integrity", requiredLevel: 4, critical: true },
    { competencyId: "legal_regulatory", requiredLevel: 3, critical: true },
    { competencyId: "observation", requiredLevel: 4 },
    { competencyId: "reporting", requiredLevel: 3 },
    { competencyId: "risk_awareness", requiredLevel: 3 },
  ],
  formalRequirements: [
    { sv: "Godkännande som skyddsvakt och utbildning enligt skyddsobjektets krav.", en: "Approval as a protective security guard and training per the protected object's requirements." },
  ],
  regulated: true,
  regulatoryNotes: { sv: "Rollen är svensk och reglerad genom skyddslagen (2010:305) och skyddsförordningen (2010:523).", en: "This is a Swedish role regulated by the Protective Security Act (2010:305) and Regulation (2010:523)." },
  countries: ["SE"],
  educationPathways: ["se-skyddsvaktsutbildning"],
  related: ["security-officer", "ordningsvakt", "military-security-specialist", "data-center-security"],
  nextRoles: ["data-center-security", "security-coordinator"],
  recommendedAssessment: "security-career-assessment",
  sources: [
    { label: { sv: "Skyddslag (2010:305)", en: "Protective Security Act (2010:305)" }, publisher: "Sveriges riksdag", url: "https://www.riksdagen.se/sv/dokument-lagar/dokument/svensk-forfattningssamling/skyddslag-2010305_sfs-2010-305" },
    { label: { sv: "Skyddsförordning (2010:523)", en: "Protective Security Regulation (2010:523)" }, publisher: "Sveriges riksdag", url: "https://www.riksdagen.se/sv/dokument-lagar/dokument/svensk-forfattningssamling/skyddsforordning-2010523_sfs-2010-523" },
  ],
};

export const securityManager: Profession = {
  id: "security-manager",
  slug: "security-manager",
  status: "researched",
  lastVerified: "2026-07-16",
  titleCanonical: "Security Manager",
  titleSv: "Säkerhetschef",
  titleEn: "Security Manager",
  family: "security_leadership_governance",
  category: "leadership",
  level: "senior",
  sector: "private",
  orientation: ["leadership", "analytical"],
  icon: "building",
  description: { sv: "Strategiskt ansvar för säkerhet, risk och kontinuitet i en organisation.", en: "Strategic responsibility for security, risk and continuity within an organisation." },
  overview: { sv: "Säkerhetschefen leder säkerhetsfunktionen – från policy och risk till operativ leverans och kontinuitet.", en: "The Security Manager leads the security function – from policy and risk to operational delivery and continuity." },
  roleFor: { sv: "Passar erfarna säkerhetsprofiler med tydlig ledaridentitet och affärsförståelse.", en: "Suits experienced security professionals with clear leadership identity and business acumen." },
  responsibilities: [
    { sv: "Utforma och underhålla säkerhetspolicy och styrande dokument.", en: "Design and maintain security policy and governance documents." },
    { sv: "Leda risk- och sårbarhetsanalyser.", en: "Lead risk and vulnerability assessments." },
    { sv: "Ansvara för budget, leverantörer och kontinuitetsplaner.", en: "Own budget, vendors and continuity plans." },
    { sv: "Rapportera till ledning och styrelse.", en: "Report to executive management and the board." },
  ],
  competencies: [
    { competencyId: "leadership", requiredLevel: 4, critical: true },
    { competencyId: "planning", requiredLevel: 4 },
    { competencyId: "risk_awareness", requiredLevel: 4 },
    { competencyId: "decision_making", requiredLevel: 4 },
    { competencyId: "communication", requiredLevel: 4 },
    { competencyId: "analytical", requiredLevel: 3 },
    { competencyId: "legal_regulatory", requiredLevel: 3 },
  ],
  regulated: false,
  countries: ["SE", "EU", "INTL"],
  educationPathways: ["intl-university-security"],
  certifications: ["asis-cpp", "iso-31000", "iso-22301"],
  previousRoles: ["security-coordinator", "risk-manager", "security-officer"],
  nextRoles: ["security-consultant"],
  related: ["risk-manager", "crisis-continuity-manager", "security-consultant"],
  recommendedAssessment: "security-career-assessment",
  sources: [
    { label: { sv: "ASIS International – CPP", en: "ASIS International – CPP" }, publisher: "ASIS International", url: "https://www.asisonline.org/certification/certified-protection-professional-cpp/" },
  ],
};

export const securityTechnician: Profession = {
  id: "security-technician",
  slug: "security-technician",
  status: "researched",
  lastVerified: "2026-07-16",
  titleCanonical: "Security Systems Technician",
  titleSv: "Säkerhetstekniker",
  titleEn: "Security Systems Technician",
  family: "security_technology",
  category: "tech",
  level: "mid",
  sector: "private",
  orientation: ["technical"],
  icon: "cpu",
  description: { sv: "Installation, drift och underhåll av tekniska säkerhetssystem.", en: "Installation, operation and maintenance of technical security systems." },
  overview: { sv: "Säkerhetstekniker knyter ihop det fysiska och digitala – genom passersystem, kameror, larm och integrationer.", en: "Security technicians bridge the physical and digital – through access control, cameras, alarms and integrations." },
  roleFor: { sv: "Passar tekniskt lagda, noggranna och lösningsorienterade.", en: "Suits technically minded, precise and solution-oriented people." },
  responsibilities: [
    { sv: "Installera och driftsätta säkerhetssystem.", en: "Install and commission security systems." },
    { sv: "Utföra service och felsökning.", en: "Perform service and troubleshooting." },
    { sv: "Dokumentera installationer och integrationer.", en: "Document installations and integrations." },
  ],
  competencies: [
    { competencyId: "technical", requiredLevel: 4, critical: true },
    { competencyId: "problem_solving", requiredLevel: 3 },
    { competencyId: "planning", requiredLevel: 3 },
    { competencyId: "communication", requiredLevel: 3 },
    { competencyId: "reporting", requiredLevel: 3 },
  ],
  regulated: false,
  regulatoryNotes: { sv: "Vissa installationer omfattas av branschregler (t.ex. SBSC) och nationella regelverk.", en: "Certain installations fall under industry rules (e.g. SBSC in Sweden) and national regulations." },
  countries: ["SE", "INTL"],
  educationPathways: ["intl-vocational-tech"],
  certifications: ["asis-psp", "se-sbsc"],
  related: ["data-center-security", "security-manager"],
  nextRoles: ["data-center-security", "security-manager"],
  recommendedAssessment: "security-career-assessment",
  sources: [
    { label: { sv: "SBSC – Svensk Brand- och Säkerhetscertifiering", en: "SBSC – Swedish Fire and Security Certification" }, publisher: "SBSC", url: "https://sbsc.se/" },
  ],
};

export const riskManager: Profession = {
  id: "risk-manager",
  slug: "risk-manager",
  status: "researched",
  lastVerified: "2026-07-16",
  titleCanonical: "Risk Manager",
  titleSv: "Risk Manager",
  titleEn: "Risk Manager",
  family: "risk_management",
  category: "risk",
  level: "senior",
  sector: "private",
  orientation: ["analytical", "leadership"],
  icon: "alert-triangle",
  description: { sv: "Identifiering, analys och hantering av operativa och organisatoriska risker.", en: "Identification, analysis and management of operational and organisational risk." },
  overview: { sv: "Risk managers ger ledningen ett strukturerat sätt att förstå och prioritera risker – från operativ till strategisk nivå.", en: "Risk managers give leadership a structured way to understand and prioritise risk – from operational to strategic level." },
  roleFor: { sv: "Passar analytiska profiler som trivs med struktur, siffror och beslut under osäkerhet.", en: "Suits analytical people who thrive on structure, numbers and decisions under uncertainty." },
  responsibilities: [
    { sv: "Etablera och underhålla ramverk för riskhantering.", en: "Establish and maintain risk-management frameworks." },
    { sv: "Genomföra risk- och sårbarhetsanalyser.", en: "Perform risk and vulnerability assessments." },
    { sv: "Rapportera risk till ledning och styrelse.", en: "Report risk to management and the board." },
  ],
  competencies: [
    { competencyId: "analytical", requiredLevel: 4, critical: true },
    { competencyId: "risk_awareness", requiredLevel: 4, critical: true },
    { competencyId: "communication", requiredLevel: 4 },
    { competencyId: "decision_making", requiredLevel: 4 },
    { competencyId: "planning", requiredLevel: 3 },
  ],
  regulated: false,
  countries: ["SE", "EU", "INTL"],
  certifications: ["iso-31000", "crisc"],
  related: ["security-manager", "aml-specialist", "crisis-continuity-manager"],
  nextRoles: ["security-manager"],
  recommendedAssessment: "security-career-assessment",
  sources: [
    { label: { sv: "ISO 31000:2018 – Riskhantering", en: "ISO 31000:2018 – Risk Management" }, publisher: "ISO", url: "https://www.iso.org/iso-31000-risk-management.html" },
  ],
};

export const amlSpecialist: Profession = {
  id: "aml-specialist",
  slug: "aml-specialist",
  status: "researched",
  lastVerified: "2026-07-16",
  titleCanonical: "AML Specialist",
  titleSv: "AML-specialist",
  titleEn: "AML Specialist",
  family: "financial_crime_compliance",
  category: "aml",
  level: "mid",
  sector: "private",
  orientation: ["analytical"],
  icon: "scale",
  description: { sv: "Motverkan av penningtvätt, finansiell brottslighet och regelefterlevnad.", en: "Anti-money-laundering, financial-crime prevention and regulatory compliance." },
  overview: { sv: "AML-specialister skyddar det finansiella systemet genom kontroll, transaktionsövervakning och rapportering till tillsynsmyndigheter.", en: "AML specialists protect the financial system through controls, transaction monitoring and regulatory reporting." },
  roleFor: { sv: "Passar noggranna, analytiska profiler med intresse för regelverk.", en: "Suits precise, analytical people with an interest in regulation." },
  responsibilities: [
    { sv: "Övervaka transaktioner och utreda misstänkta mönster.", en: "Monitor transactions and investigate suspicious patterns." },
    { sv: "Utföra kundkännedom (KYC) och skärpta åtgärder.", en: "Perform customer due diligence (KYC) and enhanced measures." },
    { sv: "Rapportera misstänkta transaktioner enligt lag.", en: "Report suspicious transactions in line with statutory obligations." },
  ],
  competencies: [
    { competencyId: "analytical", requiredLevel: 4, critical: true },
    { competencyId: "legal_regulatory", requiredLevel: 4, critical: true },
    { competencyId: "reporting", requiredLevel: 4 },
    { competencyId: "integrity", requiredLevel: 4, critical: true },
    { competencyId: "communication", requiredLevel: 3 },
  ],
  regulated: true,
  regulatoryNotes: { sv: "Verksamheten regleras i Sverige av penningtvättslagen (2017:630) och EU:s regelverk. Krav skiljer sig mellan verksamhetstyper.", en: "In Sweden the activity is regulated by the AML Act (2017:630) and EU rules. Requirements differ between business types." },
  countries: ["SE", "EU", "INTL"],
  educationPathways: ["eu-aml-training"],
  certifications: ["acams-cams"],
  related: ["risk-manager", "fraud-investigator", "security-investigator"],
  nextRoles: ["fraud-investigator", "security-consultant"],
  recommendedAssessment: "security-career-assessment",
  sources: [
    { label: { sv: "Lag (2017:630) om åtgärder mot penningtvätt och finansiering av terrorism", en: "Swedish AML Act (2017:630)" }, publisher: "Sveriges riksdag", url: "https://www.riksdagen.se/sv/dokument-lagar/dokument/svensk-forfattningssamling/lag-2017630-om-atgarder-mot-penningtvatt-och_sfs-2017-630" },
    { label: { sv: "Finansinspektionen – Penningtvätt", en: "Swedish FSA – Money laundering" }, publisher: "Finansinspektionen", url: "https://www.fi.se/sv/bank/penningtvatt/" },
  ],
};

export const dataCenterSecurity: Profession = {
  id: "data-center-security",
  slug: "data-center-security",
  status: "researched",
  lastVerified: "2026-07-16",
  titleCanonical: "Data Center Security Specialist",
  titleSv: "Datacenter­säkerhetsspecialist",
  titleEn: "Data Center Security Specialist",
  family: "critical_infrastructure_security",
  category: "critical_infra",
  level: "mid",
  sector: "private",
  orientation: ["operational", "technical"],
  icon: "server",
  description: { sv: "Fysisk och operativ säkerhet för datacenter och kritisk digital infrastruktur.", en: "Physical and operational security for data centers and critical digital infrastructure." },
  overview: { sv: "Säkerhet i datacenter kräver stenhård rutin, teknisk förståelse och en tydlig känsla för det som inte får hända.", en: "Data center security demands rigorous routine, technical understanding and a clear sense of what must never happen." },
  roleFor: { sv: "Passar dig som gillar rutin, tekniska system och en stabil arbetsmiljö.", en: "Suits people who value routine, technical systems and a stable environment." },
  responsibilities: [
    { sv: "Utföra åtkomstkontroll och sitebevakning enligt kundens säkerhetspolicy.", en: "Perform access control and site security per client policy." },
    { sv: "Övervaka fysiska och tekniska säkerhetssystem.", en: "Monitor physical and technical security systems." },
    { sv: "Dokumentera händelser och samverka med drift och kund.", en: "Document events and collaborate with operations and client teams." },
  ],
  competencies: [
    { competencyId: "observation", requiredLevel: 4, critical: true },
    { competencyId: "reporting", requiredLevel: 3 },
    { competencyId: "technical", requiredLevel: 3 },
    { competencyId: "risk_awareness", requiredLevel: 3 },
    { competencyId: "integrity", requiredLevel: 4, critical: true },
  ],
  regulated: false,
  regulatoryNotes: { sv: "Krav på personal styrs ofta av kundens säkerhetsklassning och internationella standarder.", en: "Personnel requirements are usually driven by client security classification and international standards." },
  countries: ["SE", "EU", "INTL"],
  certifications: ["iso-27001", "asis-psp"],
  related: ["security-technician", "security-officer", "skyddsvakt"],
  nextRoles: ["security-manager", "security-consultant"],
  recommendedAssessment: "security-career-assessment",
  sources: [
    { label: { sv: "ISO/IEC 27001:2022", en: "ISO/IEC 27001:2022" }, publisher: "ISO", url: "https://www.iso.org/standard/27001" },
  ],
};

export const crisisContinuityManager: Profession = {
  id: "crisis-continuity-manager",
  slug: "crisis-continuity-manager",
  status: "researched",
  lastVerified: "2026-07-16",
  titleCanonical: "Crisis and Business Continuity Manager",
  titleSv: "Kris- och kontinuitetsansvarig",
  titleEn: "Crisis and Business Continuity Manager",
  family: "crisis_management",
  category: "emergency",
  level: "senior",
  sector: "private",
  orientation: ["leadership", "analytical"],
  icon: "siren",
  description: { sv: "Planering och ledning av kris- och incidenthantering och verksamhetskontinuitet.", en: "Planning and leading incident, crisis and business-continuity response." },
  overview: { sv: "Kris- och kontinuitetsansvariga förbereder organisationen på det som ännu inte hänt – och leder när det gör det.", en: "Crisis and continuity leaders prepare the organisation for what has not yet happened – and lead when it does." },
  roleFor: { sv: "Passar dig som är strukturerad, lugn och trygg i beslut under osäkerhet.", en: "Suits people who are structured, calm and confident making decisions under uncertainty." },
  responsibilities: [
    { sv: "Etablera kontinuitetsprogram enligt ISO 22301 eller motsvarande.", en: "Establish continuity programmes aligned to ISO 22301 or equivalent." },
    { sv: "Leda övningar, incidentrespons och efterlärande.", en: "Lead exercises, incident response and post-incident learning." },
  ],
  competencies: [
    { competencyId: "planning", requiredLevel: 4, critical: true },
    { competencyId: "leadership", requiredLevel: 4 },
    { competencyId: "decision_making", requiredLevel: 4 },
    { competencyId: "communication", requiredLevel: 4 },
    { competencyId: "risk_awareness", requiredLevel: 4 },
    { competencyId: "incident_mgmt", requiredLevel: 4, critical: true },
  ],
  regulated: false,
  countries: ["SE", "EU", "INTL"],
  educationPathways: ["intl-continuity"],
  certifications: ["iso-22301"],
  related: ["security-manager", "risk-manager"],
  nextRoles: ["security-manager"],
  recommendedAssessment: "security-career-assessment",
  sources: [
    { label: { sv: "ISO 22301:2019", en: "ISO 22301:2019" }, publisher: "ISO", url: "https://www.iso.org/standard/75106.html" },
    { label: { sv: "MSB – Myndigheten för samhällsskydd och beredskap", en: "Swedish Civil Contingencies Agency (MSB)" }, publisher: "MSB", url: "https://www.msb.se/" },
  ],
};

export const closeProtection: Profession = {
  id: "close-protection",
  slug: "close-protection",
  status: "researched",
  lastVerified: "2026-07-16",
  titleCanonical: "Close Protection Officer",
  titleSv: "Personskyddsväktare (livvakt)",
  titleEn: "Close Protection Officer",
  family: "protective_operations",
  category: "protective",
  level: "senior",
  sector: "private",
  orientation: ["operational"],
  icon: "user-check",
  description: { sv: "Personskydd för utsatta individer i olika miljöer och riskbilder.", en: "Personal protection for exposed individuals across varied environments and threat profiles." },
  overview: { sv: "Personskyddsväktare arbetar diskret, förberett och professionellt – nära individen som skyddas. I Sverige regleras yrket via lagen om bevakningsföretag och Polismyndighetens föreskrifter.", en: "Close protection officers operate discreetly, prepared and professional – close to the individual being protected. In Sweden the role is regulated via the Guarding Companies Act and the Swedish Police Authority's regulations." },
  roleFor: { sv: "Passar dig som är fysiskt och mentalt förberedd, disciplinerad och lugn under press.", en: "Suits people who are physically and mentally prepared, disciplined and calm under pressure." },
  responsibilities: [
    { sv: "Planera och genomföra personskyddsuppdrag.", en: "Plan and execute close-protection assignments." },
    { sv: "Genomföra hotbildsbedömningar och rekognosering.", en: "Perform threat assessments and reconnaissance." },
  ],
  competencies: [
    { competencyId: "risk_awareness", requiredLevel: 4, critical: true },
    { competencyId: "decision_making", requiredLevel: 4 },
    { competencyId: "planning", requiredLevel: 4 },
    { competencyId: "communication", requiredLevel: 3 },
    { competencyId: "stress", requiredLevel: 4 },
    { competencyId: "integrity", requiredLevel: 4, critical: true },
  ],
  formalRequirements: [
    { sv: "Godkänd väktarutbildning och personskyddsutbildning vid auktoriserat bevakningsföretag.", en: "Approved security-officer and close-protection training at an authorised guarding company." },
  ],
  regulated: true,
  countries: ["SE"],
  educationPathways: ["se-vaktarutbildning"],
  related: ["security-officer", "skyddsvakt", "military-security-specialist"],
  nextRoles: ["security-manager", "security-consultant"],
  recommendedAssessment: "security-career-assessment",
  sources: [
    { label: { sv: "Polismyndigheten – Bevakningsföretag och personskyddsväktare", en: "Swedish Police – Guarding companies and close protection" }, publisher: "Polismyndigheten", url: "https://polisen.se/tjanster-tillstand/tillstand/bevakningsforetag/" },
  ],
};