with research_added as (select credential_code code from public.sp_catalogue_research_records where reconciliation_outcome='added_approved')
select k, v from (
select '01 tables' k, string_agg(t||'='||(to_regclass('public.'||t) is not null)::text, ',' order by t collate "C") v from unnest(array['sp_catalogue_requests','sp_catalogue_research_records','sp_certification_definition_aliases']) t
union all select '02 rls', string_agg(relname||':'||relrowsecurity||':'||relforcerowsecurity, ',' order by relname collate "C") from pg_class where relnamespace='public'::regnamespace and relname in ('sp_catalogue_requests','sp_catalogue_research_records','sp_certification_definition_aliases')
union all select '03 grants', string_agg(table_name||':'||grantee||':'||privilege_type, ',' order by table_name collate "C", grantee collate "C", privilege_type collate "C") from information_schema.role_table_grants where table_schema='public' and table_name in ('sp_catalogue_requests','sp_catalogue_research_records','sp_certification_definition_aliases') and grantee in ('anon','authenticated','service_role','PUBLIC')
union all select '04 policies', string_agg(tablename||':'||policyname||':'||cmd||':'||array_to_string(roles,'+')||':'||coalesce(qual,''), ' ; ' order by tablename collate "C", policyname collate "C") from pg_policies where schemaname='public' and tablename in ('sp_catalogue_requests','sp_catalogue_research_records','sp_certification_definition_aliases')
union all select '05 functions', string_agg(p.proname||':'||p.prosecdef||':'||coalesce(array_to_string(p.proconfig,'+'),'')||':'||md5(p.prosrc), ' ; ' order by p.proname collate "C") from pg_proc p where p.pronamespace='public'::regnamespace and p.proname in ('sp_request_catalogue_definition','sp_admin_review_research_record','sp_admin_resolve_catalogue_request','sp_list_my_catalogue_requests','sp_catalogue_unavailable_matches','sp_catalogue_research_provenance_immutable')
union all select '06 fn_exec', string_agg(p.proname||':'||has_function_privilege('anon',p.oid,'EXECUTE')||':'||has_function_privilege('authenticated',p.oid,'EXECUTE'), ',' order by p.proname collate "C") from pg_proc p where p.pronamespace='public'::regnamespace and p.proname in ('sp_request_catalogue_definition','sp_admin_review_research_record','sp_admin_resolve_catalogue_request','sp_list_my_catalogue_requests','sp_catalogue_unavailable_matches')
union all select '07 constraints', string_agg(conname||'='||pg_get_constraintdef(oid), ' ; ' order by conname collate "C") from pg_constraint where conname in ('sp_certification_definitions_abbreviation_check','sp_certification_definitions_maintenance_policy_type_check','sp_credential_definition_reviews_professional_domain_check')
union all select '08 abbr_nullable', is_nullable from information_schema.columns where table_schema='public' and table_name='sp_certification_definitions' and column_name='abbreviation'
union all select '09 classes', string_agg(code, ',' order by code collate "C") from public.sp_credential_classes
union all select '10 outcomes', string_agg(reconciliation_outcome||'/'||catalogue_decision||'='||n, ',' order by reconciliation_outcome collate "C", catalogue_decision collate "C") from (select reconciliation_outcome, catalogue_decision, count(*) n from public.sp_catalogue_research_records group by 1,2) s
union all select '11 records_total', count(*)::text from public.sp_catalogue_research_records
union all select '12 new_definitions', count(*)::text||' inactive='||count(*) filter (where not t.is_active)||' scope_ok='||count(*) filter (where t.scope_code='global_professional' and t.jurisdiction_code is null and t.market_pack_code is null and not t.allows_no_expiry and t.legal_review_state='pending') from public.sp_credential_types t where t.code in (select code from research_added)
union all select '13 types_total', count(*)::text||' active='||count(*) filter (where is_active) from public.sp_credential_types
union all select '14 issuers', count(*)::text from public.sp_certification_issuers
union all select '15 cert_defs', count(*)::text from public.sp_certification_definitions
union all select '16 aliases', count(*)::text from public.sp_certification_definition_aliases
union all select '17 requests', count(*)::text from public.sp_catalogue_requests
union all select '18 old_types_fp', md5(string_agg(code||'|'||is_active||'|'||coalesce(scope_code,'')||'|'||coalesce(jurisdiction_code,'')||'|'||coalesce(market_pack_code,'')||'|'||coalesce(claim_type,'')||'|'||coalesce(category,'')||'|'||coalesce(symbol_label,'')||'|'||coalesce(pilot_state,'')||'|'||allows_no_expiry||'|'||coalesce(legal_review_state,''), E'\n' order by code collate "C"))||' n='||count(*) from public.sp_credential_types where code not in (select code from research_added)
union all select '19 old_defs_fp', md5(string_agg(d.credential_code||'|'||i.issuer_code||'|'||d.canonical_name_en||'|'||coalesce(d.abbreviation,'')||'|'||d.maintenance_policy_type||'|'||coalesce(d.maintenance_cycle_months::text,''), E'\n' order by d.credential_code collate "C"))||' n='||count(*) from public.sp_certification_definitions d join public.sp_certification_issuers i on i.id=d.issuer_id where d.credential_code not in (select code from research_added)
union all select '20 new_defs_fp', md5(string_agg(d.credential_code||'|'||i.issuer_code||'|'||d.canonical_name_en||'|'||coalesce(d.abbreviation,'')||'|'||d.maintenance_policy_type||'|'||coalesce(d.maintenance_cycle_months::text,''), E'\n' order by d.credential_code collate "C"))||' n='||count(*) from public.sp_certification_definitions d join public.sp_certification_issuers i on i.id=d.issuer_id where d.credential_code in (select code from research_added)
union all select '21 matched_existing_links', count(*)::text||' linked='||count(*) filter (where credential_code is not null) from public.sp_catalogue_research_records where reconciliation_outcome='matched_existing'
union all select '22 claims_untouched', (select count(*)::text from public.sp_claims where credential_code in (select code from research_added))
) q order by k;
