import type { QuestionAsset } from "../types";
import { legacyQuestion, legacyMapping } from "../legacy";

// Q9-Q16 of the `security_professional` profile -- 100% reused verbatim from
// the existing, frozen Public Assessment v2.1 content. These 8 assets are
// genuinely shared members of two Assessment Catalog definitions at once:
// unchanged inside the frozen `security-guard-foundation` 16-question run,
// and again, unchanged, as the `security_professional` profile pool inside
// the assembled Public Career Assessment. One asset, two definitions.
export const securityGuardFoundationAssets: QuestionAsset[] = [
  {
    id: "sgf-01",
    version: 1,
    status: "published",
    category: "incident-handling",
    competencies: ["comp-situational-awareness"],
    dimensions: ["risk_awareness"],
    tags: ["profile:security_professional", "scenario-based"],
    supportedAssessmentDefinitions: ["public-career-assessment", "security-guard-foundation"],
    evidenceType: "scenario-based",
    content: legacyQuestion("q3"),
    mapping: legacyMapping("q3"),
  },
  {
    id: "sgf-02",
    version: 1,
    status: "published",
    category: "documentation",
    competencies: ["comp-procedural-discipline"],
    dimensions: ["structure_documentation"],
    tags: ["profile:security_professional", "scenario-based"],
    supportedAssessmentDefinitions: ["public-career-assessment", "security-guard-foundation"],
    evidenceType: "scenario-based",
    content: legacyQuestion("q5"),
    mapping: legacyMapping("q5"),
  },
  {
    id: "sgf-03",
    version: 1,
    status: "published",
    category: "escalation-conflict-handling",
    competencies: ["comp-escalation-judgement"],
    dimensions: ["conflict_management", "communication"],
    tags: ["profile:security_professional", "scenario-based"],
    supportedAssessmentDefinitions: ["public-career-assessment", "security-guard-foundation"],
    evidenceType: "scenario-based",
    content: legacyQuestion("q7"),
    mapping: legacyMapping("q7"),
  },
  {
    id: "sgf-04",
    version: 1,
    status: "published",
    category: "operational-judgement",
    competencies: ["comp-judgement-under-uncertainty"],
    dimensions: ["independent_decision_making", "analytical_orientation"],
    tags: ["profile:security_professional", "scenario-based"],
    supportedAssessmentDefinitions: ["public-career-assessment", "security-guard-foundation"],
    evidenceType: "scenario-based",
    content: legacyQuestion("q9"),
    mapping: legacyMapping("q9"),
  },
  {
    id: "sgf-05",
    version: 1,
    status: "published",
    category: "adaptability",
    competencies: ["comp-adaptability"],
    dimensions: ["learning_development", "operational_orientation"],
    tags: ["profile:security_professional", "scenario-based"],
    supportedAssessmentDefinitions: ["public-career-assessment", "security-guard-foundation"],
    evidenceType: "scenario-based",
    content: legacyQuestion("q10"),
    mapping: legacyMapping("q10"),
  },
  {
    id: "sgf-06",
    version: 1,
    status: "published",
    category: "reporting",
    competencies: ["comp-reporting-quality"],
    dimensions: ["structure_documentation"],
    tags: ["profile:security_professional", "behavioural"],
    supportedAssessmentDefinitions: ["public-career-assessment", "security-guard-foundation"],
    evidenceType: "behavioural",
    content: legacyQuestion("q14"),
    mapping: legacyMapping("q14"),
  },
  {
    id: "sgf-07",
    version: 1,
    status: "published",
    category: "preferred-future-work-environment",
    competencies: ["comp-work-environment-preference"],
    dimensions: ["service_orientation", "communication"],
    tags: ["profile:security_professional", "preference"],
    supportedAssessmentDefinitions: ["public-career-assessment", "security-guard-foundation"],
    evidenceType: "preference",
    content: legacyQuestion("q15"),
    mapping: legacyMapping("q15"),
  },
  {
    id: "sgf-08",
    version: 1,
    status: "published",
    category: "future-career-interests",
    competencies: ["comp-work-environment-preference", "comp-career-direction-preference"],
    dimensions: [
      "analytical_orientation",
      "strategic_orientation",
      "operational_orientation",
      "technical_orientation",
      "structure_documentation",
      "service_orientation",
      "investigation_orientation",
      "leadership_orientation",
      "teamwork",
    ],
    tags: ["profile:security_professional", "preference"],
    supportedAssessmentDefinitions: ["public-career-assessment", "security-guard-foundation"],
    evidenceType: "preference",
    content: legacyQuestion("q16"),
    mapping: legacyMapping("q16"),
  },
];
