import type { ProfessionTargetProfile } from "./types";

// Target profiles for the pilot professions. All values are provisional
// hypotheses to be calibrated through user testing and subject-matter review.
// `professionId` matches the id used in @/lib/career-center (equal to slug).

export const professionProfiles: ProfessionTargetProfile[] = [
  {
    professionId: "security-officer",
    family: "guarding",
    status: "provisional",
    gate: "operational",
    targets: {
      operational_orientation: { target: 75, importance: 3 },
      risk_awareness: { target: 70, importance: 3 },
      service_orientation: { target: 70, importance: 3 },
      communication: { target: 60, importance: 2 },
      structure_documentation: { target: 60, importance: 2 },
      teamwork: { target: 60, importance: 2 },
      conflict_management: { target: 55, importance: 2 },
      learning_development: { target: 45, importance: 1 },
    },
    distinguishing: ["service_orientation", "operational_orientation"],
    potentialMismatch: ["strategic_orientation", "leadership_orientation"],
    minRelevantEvidence: 4,
    regulated: true,
  },
  {
    professionId: "ordningsvakt",
    family: "police_public",
    status: "provisional",
    gate: "operational",
    targets: {
      conflict_management: { target: 80, importance: 3 },
      communication: { target: 70, importance: 3 },
      operational_orientation: { target: 80, importance: 3 },
      independent_decision_making: { target: 70, importance: 3 },
      risk_awareness: { target: 70, importance: 2 },
      service_orientation: { target: 55, importance: 2 },
      structure_documentation: { target: 55, importance: 1 },
    },
    distinguishing: ["conflict_management", "independent_decision_making"],
    minRelevantEvidence: 4,
    regulated: true,
  },
  {
    professionId: "skyddsvakt",
    family: "defence_protective",
    status: "provisional",
    gate: "operational",
    targets: {
      risk_awareness: { target: 80, importance: 3 },
      operational_orientation: { target: 75, importance: 3 },
      structure_documentation: { target: 70, importance: 3 },
      independent_decision_making: { target: 65, importance: 2 },
      teamwork: { target: 55, importance: 1 },
    },
    distinguishing: ["risk_awareness", "structure_documentation"],
    minRelevantEvidence: 4,
    regulated: true,
  },
  {
    professionId: "security-manager",
    family: "corporate",
    status: "provisional",
    gate: "leadership_strategic",
    targets: {
      leadership_orientation: { target: 90, importance: 3 },
      strategic_orientation: { target: 85, importance: 3 },
      risk_awareness: { target: 75, importance: 3 },
      independent_decision_making: { target: 70, importance: 2 },
      communication: { target: 70, importance: 2 },
      structure_documentation: { target: 70, importance: 2 },
      analytical_orientation: { target: 60, importance: 2 },
    },
    distinguishing: ["leadership_orientation", "strategic_orientation"],
    potentialMismatch: ["technical_orientation", "service_orientation"],
    minRelevantEvidence: 5,
  },
  {
    professionId: "security-technician",
    family: "physical_technical",
    status: "provisional",
    gate: "technical",
    targets: {
      technical_orientation: { target: 85, importance: 3 },
      analytical_orientation: { target: 65, importance: 2 },
      structure_documentation: { target: 65, importance: 2 },
      learning_development: { target: 65, importance: 2 },
      operational_orientation: { target: 55, importance: 2 },
    },
    distinguishing: ["technical_orientation"],
    potentialMismatch: ["leadership_orientation"],
    minRelevantEvidence: 3,
  },
  {
    professionId: "risk-manager",
    family: "risk_crisis",
    status: "provisional",
    gate: "none",
    targets: {
      analytical_orientation: { target: 80, importance: 3 },
      strategic_orientation: { target: 75, importance: 3 },
      risk_awareness: { target: 85, importance: 3 },
      structure_documentation: { target: 75, importance: 3 },
      communication: { target: 60, importance: 2 },
      leadership_orientation: { target: 55, importance: 1 },
    },
    distinguishing: ["analytical_orientation", "risk_awareness", "strategic_orientation"],
    potentialMismatch: ["operational_orientation"],
    minRelevantEvidence: 4,
  },
  {
    professionId: "aml-specialist",
    family: "financial_crime",
    status: "provisional",
    gate: "investigative_analytical",
    targets: {
      analytical_orientation: { target: 80, importance: 3 },
      investigation_orientation: { target: 80, importance: 3 },
      structure_documentation: { target: 75, importance: 3 },
      risk_awareness: { target: 65, importance: 2 },
      learning_development: { target: 60, importance: 2 },
    },
    distinguishing: ["investigation_orientation", "analytical_orientation"],
    minRelevantEvidence: 3,
  },
  {
    professionId: "data-center-security",
    family: "critical_infra",
    status: "provisional",
    gate: "operational",
    targets: {
      operational_orientation: { target: 70, importance: 3 },
      technical_orientation: { target: 70, importance: 3 },
      risk_awareness: { target: 70, importance: 3 },
      structure_documentation: { target: 70, importance: 2 },
      teamwork: { target: 55, importance: 2 },
    },
    distinguishing: ["technical_orientation", "operational_orientation"],
    minRelevantEvidence: 3,
  },
  {
    professionId: "crisis-continuity-manager",
    family: "risk_crisis",
    status: "provisional",
    gate: "leadership_strategic",
    targets: {
      strategic_orientation: { target: 80, importance: 3 },
      risk_awareness: { target: 85, importance: 3 },
      communication: { target: 70, importance: 3 },
      structure_documentation: { target: 70, importance: 2 },
      independent_decision_making: { target: 70, importance: 2 },
      teamwork: { target: 60, importance: 2 },
      leadership_orientation: { target: 70, importance: 2 },
    },
    distinguishing: ["risk_awareness", "strategic_orientation"],
    minRelevantEvidence: 4,
  },
  {
    professionId: "close-protection",
    family: "defence_protective",
    status: "provisional",
    gate: "operational",
    targets: {
      operational_orientation: { target: 80, importance: 3 },
      risk_awareness: { target: 85, importance: 3 },
      independent_decision_making: { target: 75, importance: 3 },
      communication: { target: 65, importance: 2 },
      conflict_management: { target: 65, importance: 2 },
      structure_documentation: { target: 55, importance: 1 },
    },
    distinguishing: ["independent_decision_making", "risk_awareness"],
    minRelevantEvidence: 4,
    regulated: true,
  },
  // Placeholder professions with provisional profiles
  {
    professionId: "soc-analyst",
    family: "cyber_infosec",
    status: "placeholder",
    gate: "technical",
    targets: {
      technical_orientation: { target: 75, importance: 3 },
      analytical_orientation: { target: 80, importance: 3 },
      structure_documentation: { target: 65, importance: 2 },
      investigation_orientation: { target: 60, importance: 2 },
      learning_development: { target: 65, importance: 2 },
    },
    distinguishing: ["technical_orientation", "analytical_orientation"],
    minRelevantEvidence: 3,
  },
  {
    professionId: "intelligence-analyst",
    family: "investigations_intel",
    status: "placeholder",
    gate: "investigative_analytical",
    targets: {
      analytical_orientation: { target: 85, importance: 3 },
      investigation_orientation: { target: 80, importance: 3 },
      structure_documentation: { target: 70, importance: 2 },
      strategic_orientation: { target: 60, importance: 2 },
    },
    distinguishing: ["analytical_orientation", "investigation_orientation"],
    minRelevantEvidence: 3,
  },
  {
    professionId: "fraud-investigator",
    family: "investigations_intel",
    status: "placeholder",
    gate: "investigative_analytical",
    targets: {
      investigation_orientation: { target: 85, importance: 3 },
      analytical_orientation: { target: 80, importance: 3 },
      structure_documentation: { target: 70, importance: 2 },
      communication: { target: 55, importance: 2 },
    },
    distinguishing: ["investigation_orientation"],
    minRelevantEvidence: 3,
  },
  {
    professionId: "security-investigator",
    family: "investigations_intel",
    status: "placeholder",
    gate: "investigative_analytical",
    targets: {
      investigation_orientation: { target: 80, importance: 3 },
      analytical_orientation: { target: 70, importance: 3 },
      communication: { target: 60, importance: 2 },
      structure_documentation: { target: 65, importance: 2 },
      independent_decision_making: { target: 60, importance: 2 },
    },
    distinguishing: ["investigation_orientation"],
    minRelevantEvidence: 3,
  },
  {
    professionId: "security-consultant",
    family: "consulting_specialist",
    status: "placeholder",
    gate: "none",
    targets: {
      strategic_orientation: { target: 70, importance: 3 },
      communication: { target: 70, importance: 3 },
      analytical_orientation: { target: 70, importance: 3 },
      structure_documentation: { target: 60, importance: 2 },
      leadership_orientation: { target: 55, importance: 2 },
      risk_awareness: { target: 65, importance: 2 },
      learning_development: { target: 60, importance: 2 },
    },
    distinguishing: ["strategic_orientation", "analytical_orientation"],
    minRelevantEvidence: 4,
  },
  {
    professionId: "security-coordinator",
    family: "corporate",
    status: "placeholder",
    gate: "none",
    targets: {
      structure_documentation: { target: 75, importance: 3 },
      communication: { target: 75, importance: 3 },
      teamwork: { target: 70, importance: 3 },
      operational_orientation: { target: 65, importance: 2 },
      risk_awareness: { target: 60, importance: 2 },
      service_orientation: { target: 55, importance: 1 },
      learning_development: { target: 55, importance: 1 },
    },
    distinguishing: ["structure_documentation", "communication", "teamwork"],
    potentialMismatch: [],
    minRelevantEvidence: 3,
  },
];

export const professionProfileById: Record<string, ProfessionTargetProfile> =
  Object.fromEntries(professionProfiles.map((p) => [p.professionId, p]));