import type { TestPersona } from "./types";

// Deterministic answer patterns used to validate result diversity.
// Answer IDs and rating scales come from src/lib/assessment-content.ts.
export const testPersonas: TestPersona[] = [
  {
    id: "A_operational_service",
    name: { sv: "Persona A – Operativ och service", en: "Persona A – Operational and service-oriented" },
    description: {
      sv: "Praktiskt lagd, gillar möten med människor och att skydda.",
      en: "Hands-on, enjoys public interaction and protecting people.",
    },
    answers: {
      q1: "protect",
      q2: 4,
      q3: 3,
      q4: "deesc",
      q5: 2,
      q6: 2,
      q7: ["field", "public", "datacenter"],
      q8: 4,
      q9: "core",
      q10: "rules",
      q11: 4,
      q12: 4,
      q13: 3,
      q14: "hands",
      q15: ["physec", "crisis"],
      q16: 2,
    },
    expectedTopFamilies: ["protective_operations", "public_safety_justice", "critical_infrastructure_security", "protective_operations"],
    disallowedTop: ["security-manager", "risk-manager", "security-consultant"],
  },
  {
    id: "B_technical_analytical",
    name: { sv: "Persona B – Teknisk och analytisk", en: "Persona B – Technical and analytical" },
    description: {
      sv: "Nyfiken på teknik, gillar data och strukturerad problemlösning.",
      en: "Curious about technology and structured problem-solving.",
    },
    answers: {
      q1: "tech",
      q2: 3,
      q3: 2,
      q4: "protocol",
      q5: 5,
      q6: 5,
      q7: ["datacenter", "office"],
      q8: 4,
      q9: "limited",
      q10: "data",
      q11: 4,
      q12: 3,
      q13: 3,
      q14: "read",
      q15: ["cyber", "compliance"],
      q16: 3,
    },
    expectedTopFamilies: ["security_technology", "cyber_information_security", "critical_infrastructure_security"],
    disallowedTop: ["security-manager"],
  },
  {
    id: "C_strategic_leader",
    name: { sv: "Persona C – Strategisk ledare", en: "Persona C – Strategic leader" },
    description: {
      sv: "Vill leda, planera långsiktigt och driva beslut.",
      en: "Wants to lead, plan long-term and drive decisions.",
    },
    answers: {
      q1: "lead",
      q2: 5,
      q3: 5,
      q4: "delegate",
      q5: 4,
      q6: 3,
      q7: ["corporate", "office"],
      q8: 4,
      q9: "core",
      q10: "data",
      q11: 5,
      q12: 4,
      q13: 5,
      q14: "course",
      q15: ["strategy", "crisis"],
      q16: 5,
    },
    expectedTopFamilies: ["security_leadership_governance", "risk_management", "security_leadership_governance"],
  },
  {
    id: "D_investigative_detail",
    name: { sv: "Persona D – Utredande och noggrann", en: "Persona D – Investigative and detail-oriented" },
    description: {
      sv: "Metodisk, gillar granskning och mönsterigenkänning.",
      en: "Methodical, enjoys scrutiny and pattern recognition.",
    },
    answers: {
      q1: "problem",
      q2: 3,
      q3: 3,
      q4: "protocol",
      q5: 5,
      q6: 3,
      q7: ["office", "gov"],
      q8: 4,
      q9: "limited",
      q10: "data",
      q11: 3,
      q12: 3,
      q13: 4,
      q14: "read",
      q15: ["invest", "compliance"],
      q16: 3,
    },
    expectedTopFamilies: ["financial_crime_compliance", "investigations_intelligence"],
    disallowedTop: ["security-manager"],
  },
  {
    id: "E_student_exploring",
    name: { sv: "Persona E – Student som utforskar", en: "Persona E – Student exploring security" },
    description: {
      sv: "Undersöker branschen, inga starka signaler ännu.",
      en: "Exploring the industry, no strong signals yet.",
    },
    answers: {
      q1: "protect",
      q2: 3,
      q3: 3,
      q5: 3,
      q6: 3,
      q9: "ok",
      q11: 3,
      q13: 3,
      q16: 2,
    },
    expectedTopFamilies: [
      "protective_operations",
      "public_safety_justice",
      "critical_infrastructure_security",
      "security_technology",
      "cyber_information_security",
    ],
    disallowedTop: ["security-manager", "risk-manager", "crisis-continuity-manager", "security-consultant"],
  },
  {
    id: "F_operational_protective",
    name: { sv: "Persona F – Operativ skyddsprofil", en: "Persona F – Operational protective profile" },
    description: {
      sv: "Fältorienterad med hög riskmedvetenhet och självständighet.",
      en: "Field-oriented with high risk awareness and independence.",
    },
    answers: {
      q1: "protect",
      q2: 4,
      q3: 3,
      q4: "act",
      q5: 3,
      q6: 2,
      q7: ["field", "gov"],
      q8: 5,
      q9: "ok",
      q10: "gut",
      q11: 5,
      q12: 2,
      q13: 3,
      q14: "hands",
      q15: ["physec", "crisis"],
      q16: 3,
    },
    expectedTopFamilies: ["protective_operations", "protective_operations", "public_safety_justice"],
    disallowedTop: ["security-manager", "security-consultant"],
  },
  // --- New reliability personas (Sprint 06A.1) ---
  {
    id: "G_coordinator",
    name: { sv: "Persona G – Koordinatorprofil", en: "Persona G – Coordinator profile" },
    description: {
      sv: "Hög struktur, kommunikation och samarbete. Måttligt ledarskap.",
      en: "High structure, communication and teamwork. Moderate leadership.",
    },
    answers: {
      q1: "problem",
      q2: 5,
      q3: 3,
      q4: "protocol",
      q5: 4,
      q6: 3,
      q7: ["office", "corporate"],
      q8: 3,
      q9: "core",
      q10: "team",
      q11: 4,
      q12: 5,
      q13: 4,
      q14: "mentor",
      q15: ["compliance", "crisis"],
      q16: 3,
    },
    expectedTopFamilies: ["security_leadership_governance", "risk_management", "security_leadership_governance"],
    disallowedTop: ["security-manager"],
  },
  {
    id: "H_strategic_manager",
    name: {
      sv: "Persona H – Erfaren strategisk chef",
      en: "Persona H – Senior strategic manager",
    },
    description: {
      sv: "Starkt ledarskap, strategi, riskmedvetenhet, planering och självständighet.",
      en: "Strong leadership, strategy, risk awareness, planning and independence.",
    },
    answers: {
      q1: "lead",
      q2: 5,
      q3: 5,
      q4: "delegate",
      q5: 5,
      q6: 2,
      q7: ["corporate", "office"],
      q8: 5,
      q9: "core",
      q10: "data",
      q11: 5,
      q12: 3,
      q13: 5,
      q14: "course",
      q15: ["strategy", "crisis"],
      q16: 5,
    },
    expectedTopFamilies: ["security_leadership_governance"],
    disallowedTop: [],
  },
  {
    id: "I_incomplete",
    name: { sv: "Persona I – Ofullständig bedömning", en: "Persona I – Incomplete assessment" },
    description: {
      sv: "Endast ett fåtal frågor besvarade.",
      en: "Only a small number of questions answered.",
    },
    answers: {
      q1: "protect",
      q8: 4,
      q11: 3,
    },
    expectedTopFamilies: [
      "protective_operations",
      "public_safety_justice",
      "critical_infrastructure_security",
      "protective_operations",
      "security_technology",
      "cyber_information_security",
      "investigations_intelligence",
      "financial_crime_compliance",
      "security_leadership_governance",
      "risk_management",
      "security_leadership_governance",
    ],
    disallowedTop: ["security-manager"],
  },
  {
    id: "J_conflicting",
    name: { sv: "Persona J – Motstridig profil", en: "Persona J – Conflicting profile" },
    description: {
      sv: "Starkt tekniskt och operativt intresse men lågt ledarskap och strategi.",
      en: "Strong technical and operational interest but low leadership and strategy.",
    },
    answers: {
      q1: "tech",
      q2: 3,
      q3: 1,
      q4: "protocol",
      q5: 4,
      q6: 5,
      q7: ["datacenter", "field"],
      q8: 4,
      q9: "limited",
      q10: "rules",
      q11: 4,
      q12: 3,
      q13: 2,
      q14: "hands",
      q15: ["physec", "cyber"],
      q16: 2,
    },
    expectedTopFamilies: [
      "security_technology",
      "cyber_information_security",
      "critical_infrastructure_security",
      "protective_operations",
      "protective_operations",
    ],
    disallowedTop: ["security-manager", "risk-manager", "crisis-continuity-manager", "security-consultant"],
  },
  {
    id: "K_broad_positive",
    name: {
      sv: "Persona K – Genomgående positiva svar",
      en: "Persona K – Broad positive responder",
    },
    description: {
      sv: "Väljer överlag positiva alternativ utan tydlig profil.",
      en: "Selects broadly positive options with no clear profile.",
    },
    answers: {
      q1: "protect",
      q2: 5,
      q3: 4,
      q4: "deesc",
      q5: 4,
      q6: 4,
      q7: ["office", "field", "public"],
      q8: 4,
      q9: "core",
      q10: "team",
      q11: 4,
      q12: 4,
      q13: 4,
      q14: "mentor",
      q15: ["physec", "compliance", "crisis"],
      q16: 4,
    },
    expectedTopFamilies: [
      "protective_operations",
      "public_safety_justice",
      "critical_infrastructure_security",
      "security_technology",
      "security_leadership_governance",
      "risk_management",
      "security_leadership_governance",
      "protective_operations",
    ],
    disallowedTop: ["security-manager"],
  },
];