import type { TestPersona } from "./types";

// Deterministic answer patterns used to validate result diversity.
// Answer IDs and rating scales come from src/lib/assessment-content.ts
// (Public Assessment v2.0). Recalibrated for v2.0's question set -- an
// intentional, approved versioned replacement of the v1 persona answers
// (same persona identities/narratives, new answers matching the new
// question semantics), per docs/job-intelligence/public-assessment-v2-questions.md.
export const testPersonas: TestPersona[] = [
  {
    id: "A_operational_service",
    name: {
      sv: "Persona A – Operativ och service",
      en: "Persona A – Operational and service-oriented",
    },
    description: {
      sv: "Praktiskt lagd, gillar möten med människor och att skydda.",
      en: "Hands-on, enjoys public interaction and protecting people.",
    },
    answers: {
      q1: "mostly",
      q2: "follow_procedure",
      q3: "unusual_person",
      q4: "proactive",
      q5: "use_own_this_time",
      q6: "facts_and_read",
      q7: "escalate_now",
      q8: "pause_then_continue",
      q9: "best_available",
      q10: "adjust_with_guidance",
      q11: "normal_pace",
      q12: "triage_and_flag",
      q13: "discuss_and_agree",
      q14: "immediate_brief",
      q15: "core",
      q16: ["field", "public", "datacenter"],
    },
    expectedTopFamilies: [
      "protective_operations",
      "public_safety_justice",
      "critical_infrastructure_security",
      "protective_operations",
    ],
    disallowedTop: ["security-manager", "risk-manager", "security-consultant"],
  },
  {
    id: "B_technical_analytical",
    name: { sv: "Persona B – Teknisk och analytisk", en: "Persona B – Technical and analytical" },
    description: {
      sv: "Nyfiken på teknik, gillar data och strukturerad problemlösning.",
      en: "Curious about technology and structured problem-solving.",
    },
    answers: {
      q1: "mostly",
      q2: "follow_procedure",
      q3: "unexplained",
      q4: "proactive",
      q5: "follow_and_raise",
      q6: "next_steps",
      q7: "gather_more",
      q8: "pause_then_continue",
      q9: "pause_briefly",
      q10: "adjust_with_guidance",
      q11: "normal_pace",
      q12: "fastest_first",
      q13: "defer_to_them",
      q14: "immediate_detailed",
      q15: "limited",
      q16: ["datacenter", "office", "casework"],
    },
    expectedTopFamilies: [
      "security_technology",
      "cyber_information_security",
      "critical_infrastructure_security",
    ],
    disallowedTop: ["security-manager"],
  },
  {
    id: "C_strategic_leader",
    name: { sv: "Persona C – Strategisk ledare", en: "Persona C – Strategic leader" },
    description: {
      sv: "Vill leda, planera långsiktigt och driva beslut.",
      en: "Wants to lead, plan long-term and drive decisions.",
    },
    answers: {
      q1: "mostly",
      q2: "raise_privately",
      q3: "unusual_person",
      q4: "proactive",
      q5: "follow_and_note",
      q6: "next_steps",
      q7: "escalate_now",
      q8: "continue_alert",
      q9: "best_available",
      q10: "adjust_with_guidance",
      q11: "fast_proactive",
      q12: "triage_and_flag",
      q13: "discuss_and_agree",
      q14: "immediate_brief",
      q15: "core",
      q16: ["corporate", "office", "coordination"],
    },
    expectedTopFamilies: [
      "security_leadership_governance",
      "risk_management",
      "security_leadership_governance",
    ],
  },
  {
    id: "D_investigative_detail",
    name: {
      sv: "Persona D – Utredande och noggrann",
      en: "Persona D – Investigative and detail-oriented",
    },
    description: {
      sv: "Metodisk, gillar granskning och mönsterigenkänning.",
      en: "Methodical, enjoys scrutiny and pattern recognition.",
    },
    answers: {
      q1: "mostly",
      q2: "follow_procedure",
      q3: "unexplained",
      q4: "proactive",
      q5: "follow_and_raise",
      q6: "next_steps",
      q7: "gather_more",
      q8: "pause_then_continue",
      q9: "pause_briefly",
      q10: "adjust_with_guidance",
      q11: "slower_than_liked",
      q12: "fastest_first",
      q13: "discuss_and_agree",
      q14: "immediate_detailed",
      q15: "limited",
      q16: ["office", "gov", "casework"],
    },
    expectedTopFamilies: ["financial_crime_compliance", "investigations_intelligence"],
    disallowedTop: ["security-manager"],
  },
  {
    id: "E_student_exploring",
    name: { sv: "Persona E – Student som utforskar", en: "Persona E – Student exploring security" },
    description: {
      sv: "Undersöker branschen, inga starka signaler ännu.",
      en: "Exploring the industry, no strong signals yet.",
    },
    answers: {
      q1: "mostly",
      q4: "task_focused",
      q6: "next_steps",
      q8: "pause_then_continue",
      q11: "slower_than_liked",
      q13: "defer_to_them",
      q15: "capable",
    },
    expectedTopFamilies: [
      "protective_operations",
      "public_safety_justice",
      "critical_infrastructure_security",
      "security_technology",
      "cyber_information_security",
    ],
    disallowedTop: [
      "security-manager",
      "risk-manager",
      "crisis-continuity-manager",
      "security-consultant",
    ],
  },
  {
    id: "F_operational_protective",
    name: {
      sv: "Persona F – Operativ skyddsprofil",
      en: "Persona F – Operational protective profile",
    },
    description: {
      sv: "Fältorienterad med hög riskmedvetenhet och självständighet.",
      en: "Field-oriented with high risk awareness and independence.",
    },
    answers: {
      q1: "mostly",
      q2: "follow_procedure",
      q3: "unusual_person",
      q4: "proactive",
      q5: "use_own_this_time",
      q6: "whatever_urgent",
      q7: "escalate_now",
      q8: "pause_then_continue",
      q9: "best_available",
      q10: "adjust_with_guidance",
      q11: "normal_pace",
      q12: "fastest_first",
      q13: "split_and_go_own_way",
      q14: "immediate_brief",
      q15: "capable",
      q16: ["field", "gov"],
    },
    expectedTopFamilies: [
      "protective_operations",
      "protective_operations",
      "public_safety_justice",
    ],
    disallowedTop: ["security-manager", "security-consultant"],
  },
  {
    id: "G_coordinator",
    name: { sv: "Persona G – Koordinatorprofil", en: "Persona G – Coordinator profile" },
    description: {
      sv: "Hög struktur, kommunikation och samarbete. Måttligt ledarskap.",
      en: "High structure, communication and teamwork. Moderate leadership.",
    },
    answers: {
      q1: "always",
      q2: "follow_procedure",
      q3: "unusual_person",
      q4: "proactive",
      q5: "follow_and_note",
      q6: "facts_and_read",
      q7: "gather_more",
      q8: "pause_then_continue",
      q9: "pause_briefly",
      q10: "adjust_with_guidance",
      q11: "normal_pace",
      q12: "triage_and_flag",
      q13: "discuss_and_agree",
      q14: "immediate_detailed",
      q15: "core",
      q16: ["office", "corporate", "coordination"],
    },
    expectedTopFamilies: [
      "security_leadership_governance",
      "risk_management",
      "security_leadership_governance",
    ],
    disallowedTop: ["security-manager"],
  },
  {
    id: "H_strategic_manager",
    name: {
      sv: "Persona H – Erfaren strategisk chef",
      en: "Persona H – Senior strategic manager",
    },
    description: {
      sv: "Starkt ledarskap, strategi, riskmedvetenhet, planering och självständighet.",
      en: "Strong leadership, strategy, risk awareness, planning and independence.",
    },
    answers: {
      q1: "always",
      q2: "raise_privately",
      q3: "unusual_person",
      q4: "proactive",
      q5: "follow_and_raise",
      q6: "whatever_urgent",
      q7: "escalate_now",
      q8: "continue_alert",
      q9: "best_available",
      q10: "adjust_with_guidance",
      q11: "fast_proactive",
      q12: "fastest_first",
      q13: "discuss_and_agree",
      q14: "immediate_brief",
      q15: "core",
      q16: ["corporate", "office", "coordination"],
    },
    expectedTopFamilies: ["security_leadership_governance"],
    disallowedTop: [],
  },
  {
    id: "I_incomplete",
    name: { sv: "Persona I – Ofullständig bedömning", en: "Persona I – Incomplete assessment" },
    description: {
      sv: "Endast ett fåtal frågor besvarade.",
      en: "Only a small number of questions answered.",
    },
    answers: {
      q4: "proactive",
      q11: "slower_than_liked",
      q15: "capable",
    },
    expectedTopFamilies: [
      "protective_operations",
      "public_safety_justice",
      "critical_infrastructure_security",
      "protective_operations",
      "security_technology",
      "cyber_information_security",
      "investigations_intelligence",
      "financial_crime_compliance",
      "security_leadership_governance",
      "risk_management",
      "security_leadership_governance",
    ],
    disallowedTop: ["security-manager"],
  },
  {
    id: "J_conflicting",
    name: { sv: "Persona J – Motstridig profil", en: "Persona J – Conflicting profile" },
    description: {
      sv: "Starkt tekniskt och operativt intresse men lågt ledarskap och strategi.",
      en: "Strong technical and operational interest but low leadership and strategy.",
    },
    answers: {
      q1: "mostly",
      q2: "let_it_go",
      q3: "schedule_only",
      q4: "proactive",
      q5: "follow_and_note",
      q6: "facts_first",
      q7: "gather_more",
      q8: "pause_then_continue",
      q9: "pause_briefly",
      q10: "adjust_with_guidance",
      q11: "normal_pace",
      q12: "fastest_first",
      q13: "split_and_go_own_way",
      q14: "immediate_brief",
      q15: "limited",
      q16: ["datacenter", "field"],
    },
    expectedTopFamilies: [
      "security_technology",
      "cyber_information_security",
      "critical_infrastructure_security",
      "protective_operations",
      "protective_operations",
    ],
    disallowedTop: [
      "security-manager",
      "risk-manager",
      "crisis-continuity-manager",
      "security-consultant",
    ],
  },
  {
    id: "K_broad_positive",
    name: {
      sv: "Persona K – Genomgående positiva svar",
      en: "Persona K – Broad positive responder",
    },
    description: {
      sv: "Väljer överlag positiva alternativ utan tydlig profil.",
      en: "Selects broadly positive options with no clear profile.",
    },
    answers: {
      q1: "always",
      q2: "follow_procedure",
      q3: "unusual_person",
      q4: "proactive",
      q5: "follow_and_note",
      q6: "facts_and_read",
      q7: "escalate_now",
      q8: "pause_then_continue",
      q9: "best_available",
      q10: "adjust_with_guidance",
      q11: "normal_pace",
      q12: "triage_and_flag",
      q13: "discuss_and_agree",
      q14: "immediate_brief",
      q15: "core",
      q16: ["office", "field", "public"],
    },
    expectedTopFamilies: [
      "protective_operations",
      "public_safety_justice",
      "critical_infrastructure_security",
      "security_technology",
      "security_leadership_governance",
      "risk_management",
      "security_leadership_governance",
      "protective_operations",
    ],
    disallowedTop: ["security-manager"],
  },
];
