import type { TestPersona } from "./types";

// Deterministic answer patterns used to validate result diversity.
// Answer IDs and rating scales come from src/lib/assessment-content.ts.
export const testPersonas: TestPersona[] = [
  {
    id: "A_operational_service",
    name: { sv: "Persona A – Operativ och service", en: "Persona A – Operational and service-oriented" },
    description: {
      sv: "Praktiskt lagd, gillar möten med människor och att skydda.",
      en: "Hands-on, enjoys public interaction and protecting people.",
    },
    answers: {
      q1: "protect",
      q2: 4,
      q3: 3,
      q4: "deesc",
      q5: 2,
      q6: 2,
      q7: ["field", "public", "datacenter"],
      q8: 4,
      q9: "core",
      q10: "rules",
      q11: 4,
      q12: 4,
      q13: 3,
      q14: "hands",
      q15: ["physec", "crisis"],
      q16: 2,
    },
    expectedTopFamilies: ["guarding", "police_public", "critical_infra", "defence_protective"],
    disallowedTop: ["security-manager", "risk-manager", "security-consultant"],
  },
  {
    id: "B_technical_analytical",
    name: { sv: "Persona B – Teknisk och analytisk", en: "Persona B – Technical and analytical" },
    description: {
      sv: "Nyfiken på teknik, gillar data och strukturerad problemlösning.",
      en: "Curious about technology and structured problem-solving.",
    },
    answers: {
      q1: "tech",
      q2: 3,
      q3: 2,
      q4: "protocol",
      q5: 5,
      q6: 5,
      q7: ["datacenter", "office"],
      q8: 4,
      q9: "limited",
      q10: "data",
      q11: 4,
      q12: 3,
      q13: 3,
      q14: "read",
      q15: ["cyber", "compliance"],
      q16: 3,
    },
    expectedTopFamilies: ["physical_technical", "cyber_infosec", "critical_infra"],
    disallowedTop: ["security-manager"],
  },
  {
    id: "C_strategic_leader",
    name: { sv: "Persona C – Strategisk ledare", en: "Persona C – Strategic leader" },
    description: {
      sv: "Vill leda, planera långsiktigt och driva beslut.",
      en: "Wants to lead, plan long-term and drive decisions.",
    },
    answers: {
      q1: "lead",
      q2: 5,
      q3: 5,
      q4: "delegate",
      q5: 4,
      q6: 3,
      q7: ["corporate", "office"],
      q8: 4,
      q9: "core",
      q10: "data",
      q11: 5,
      q12: 4,
      q13: 5,
      q14: "course",
      q15: ["strategy", "crisis"],
      q16: 5,
    },
    expectedTopFamilies: ["corporate", "risk_crisis", "consulting_specialist"],
  },
  {
    id: "D_investigative_detail",
    name: { sv: "Persona D – Utredande och noggrann", en: "Persona D – Investigative and detail-oriented" },
    description: {
      sv: "Metodisk, gillar granskning och mönsterigenkänning.",
      en: "Methodical, enjoys scrutiny and pattern recognition.",
    },
    answers: {
      q1: "problem",
      q2: 3,
      q3: 3,
      q4: "protocol",
      q5: 5,
      q6: 3,
      q7: ["office", "gov"],
      q8: 4,
      q9: "limited",
      q10: "data",
      q11: 3,
      q12: 3,
      q13: 4,
      q14: "read",
      q15: ["invest", "compliance"],
      q16: 3,
    },
    expectedTopFamilies: ["financial_crime", "investigations_intel"],
    disallowedTop: ["security-manager"],
  },
  {
    id: "E_student_exploring",
    name: { sv: "Persona E – Student som utforskar", en: "Persona E – Student exploring security" },
    description: {
      sv: "Undersöker branschen, inga starka signaler ännu.",
      en: "Exploring the industry, no strong signals yet.",
    },
    answers: {
      q1: "protect",
      q2: 3,
      q3: 3,
      q5: 3,
      q6: 3,
      q9: "ok",
      q11: 3,
      q13: 3,
      q16: 2,
    },
    expectedTopFamilies: [
      "guarding",
      "police_public",
      "critical_infra",
      "physical_technical",
      "cyber_infosec",
    ],
    disallowedTop: ["security-manager", "risk-manager", "crisis-continuity-manager", "security-consultant"],
  },
  {
    id: "F_operational_protective",
    name: { sv: "Persona F – Operativ skyddsprofil", en: "Persona F – Operational protective profile" },
    description: {
      sv: "Fältorienterad med hög riskmedvetenhet och självständighet.",
      en: "Field-oriented with high risk awareness and independence.",
    },
    answers: {
      q1: "protect",
      q2: 4,
      q3: 3,
      q4: "act",
      q5: 3,
      q6: 2,
      q7: ["field", "gov"],
      q8: 5,
      q9: "ok",
      q10: "gut",
      q11: 5,
      q12: 2,
      q13: 3,
      q14: "hands",
      q15: ["physec", "crisis"],
      q16: 3,
    },
    expectedTopFamilies: ["defence_protective", "guarding", "police_public"],
    disallowedTop: ["security-manager", "security-consultant"],
  },
];