import type { Certification, CertificationId } from "./types";

export const certifications: readonly Certification[] = [
  {
    id: "asis-cpp",
    status: "researched",
    lastVerified: "2026-07-16",
    shortName: "CPP",
    fullName: { sv: "Certified Protection Professional (CPP)", en: "Certified Protection Professional (CPP)" },
    issuer: { sv: "ASIS International", en: "ASIS International" },
    scope: ["INTL"],
    careerLevel: "senior",
    experienceRequirement: { sv: "Flera års relevant erfarenhet inom säkerhetshantering – exakta krav publiceras av utgivaren.", en: "Several years of relevant experience in security management – exact requirements published by the issuer." },
    validity: { sv: "Certifikatet upprätthålls via kontinuerlig kompetensutveckling enligt utgivarens regler.", en: "Maintained through continuing professional education per issuer rules." },
    relatedProfessions: ["security-manager", "security-consultant"],
    officialSource: {
      label: { sv: "ASIS CPP", en: "ASIS CPP" },
      publisher: "ASIS International",
      url: "https://www.asisonline.org/certification/certified-protection-professional-cpp/",
    },
  },
  {
    id: "asis-psp",
    status: "researched",
    lastVerified: "2026-07-16",
    shortName: "PSP",
    fullName: { sv: "Physical Security Professional (PSP)", en: "Physical Security Professional (PSP)" },
    issuer: { sv: "ASIS International", en: "ASIS International" },
    scope: ["INTL"],
    careerLevel: "mid",
    relatedProfessions: ["security-technician", "data-center-security"],
    officialSource: {
      label: { sv: "ASIS PSP", en: "ASIS PSP" },
      publisher: "ASIS International",
      url: "https://www.asisonline.org/certification/physical-security-professional-psp/",
    },
  },
  {
    id: "acams-cams",
    status: "researched",
    lastVerified: "2026-07-16",
    shortName: "CAMS",
    fullName: { sv: "Certified Anti-Money Laundering Specialist (CAMS)", en: "Certified Anti-Money Laundering Specialist (CAMS)" },
    issuer: { sv: "ACAMS", en: "ACAMS" },
    scope: ["INTL"],
    careerLevel: "mid",
    relatedProfessions: ["aml-specialist", "fraud-investigator"],
    officialSource: {
      label: { sv: "ACAMS CAMS", en: "ACAMS CAMS" },
      publisher: "ACAMS",
      url: "https://www.acams.org/en/certifications/certified-anti-money-laundering-specialist-cams",
    },
  },
  {
    id: "iso-22301",
    status: "researched",
    lastVerified: "2026-07-16",
    fullName: { sv: "ISO 22301 – Ledningssystem för kontinuitetshantering", en: "ISO 22301 – Business Continuity Management Systems" },
    issuer: { sv: "ISO / ackrediterade certifieringsorgan", en: "ISO / accredited certification bodies" },
    scope: ["INTL"],
    careerLevel: "senior",
    relatedProfessions: ["crisis-continuity-manager", "security-manager"],
    officialSource: {
      label: { sv: "ISO 22301:2019", en: "ISO 22301:2019" },
      publisher: "International Organization for Standardization",
      url: "https://www.iso.org/standard/75106.html",
    },
  },
  {
    id: "iso-31000",
    status: "researched",
    lastVerified: "2026-07-16",
    fullName: { sv: "ISO 31000 – Riskhantering", en: "ISO 31000 – Risk Management" },
    issuer: { sv: "ISO", en: "ISO" },
    scope: ["INTL"],
    careerLevel: "senior",
    relatedProfessions: ["risk-manager", "security-manager"],
    officialSource: {
      label: { sv: "ISO 31000:2018", en: "ISO 31000:2018" },
      publisher: "International Organization for Standardization",
      url: "https://www.iso.org/iso-31000-risk-management.html",
    },
  },
  {
    id: "iso-27001",
    status: "researched",
    lastVerified: "2026-07-16",
    fullName: { sv: "ISO/IEC 27001 – Informationssäkerhet", en: "ISO/IEC 27001 – Information Security Management" },
    issuer: { sv: "ISO/IEC", en: "ISO/IEC" },
    scope: ["INTL"],
    careerLevel: "senior",
    relatedProfessions: ["data-center-security", "soc-analyst", "security-manager"],
    officialSource: {
      label: { sv: "ISO/IEC 27001:2022", en: "ISO/IEC 27001:2022" },
      publisher: "International Organization for Standardization",
      url: "https://www.iso.org/standard/27001",
    },
  },
  {
    id: "se-sbsc",
    status: "researched",
    lastVerified: "2026-07-16",
    fullName: { sv: "SBSC-certifiering (bransch)", en: "SBSC industry certification (Sweden)" },
    issuer: { sv: "Svensk Brand- och Säkerhetscertifiering (SBSC)", en: "Svensk Brand- och Säkerhetscertifiering (SBSC)" },
    scope: ["SE"],
    careerLevel: "mid",
    relatedProfessions: ["security-technician"],
    officialSource: {
      label: { sv: "SBSC", en: "SBSC" },
      publisher: "SBSC",
      url: "https://sbsc.se/",
    },
  },
  {
    id: "crisc",
    status: "placeholder",
    shortName: "CRISC",
    fullName: { sv: "Certified in Risk and Information Systems Control (CRISC)", en: "Certified in Risk and Information Systems Control (CRISC)" },
    issuer: { sv: "ISACA", en: "ISACA" },
    scope: ["INTL"],
    careerLevel: "senior",
    relatedProfessions: ["risk-manager", "soc-analyst"],
  },
  {
    id: "cissp",
    status: "placeholder",
    shortName: "CISSP",
    fullName: { sv: "Certified Information Systems Security Professional", en: "Certified Information Systems Security Professional" },
    issuer: { sv: "(ISC)²", en: "(ISC)²" },
    scope: ["INTL"],
    careerLevel: "senior",
    relatedProfessions: ["soc-analyst", "security-manager"],
  },
  {
    id: "cfe",
    status: "placeholder",
    shortName: "CFE",
    fullName: { sv: "Certified Fraud Examiner (CFE)", en: "Certified Fraud Examiner (CFE)" },
    issuer: { sv: "ACFE", en: "ACFE" },
    scope: ["INTL"],
    careerLevel: "mid",
    relatedProfessions: ["fraud-investigator", "security-investigator"],
  },
];

export function getCertification(id: CertificationId) {
  return certifications.find((c) => c.id === id);
}