import type { Competency, CompetencyId } from "./types";

export const competencies: readonly Competency[] = [
  { id: "integrity", status: "researched", lastVerified: "2026-07-16", category: "behavioural", icon: "shield-check",
    name: { sv: "Integritet och yrkesetik", en: "Integrity and Professional Ethics" },
    definition: { sv: "Att agera ärligt och i linje med lagar, policyer och rollens förtroendeuppgift.", en: "Acting honestly and in line with laws, policies and the trust the role carries." },
    observableBehaviours: [
      { sv: "Hanterar känslig information korrekt.", en: "Handles sensitive information correctly." },
      { sv: "Rapporterar avvikelser även när det är obekvämt.", en: "Reports deviations even when uncomfortable." },
    ],
  },
  { id: "communication", status: "researched", lastVerified: "2026-07-16", category: "communication", icon: "message",
    name: { sv: "Kommunikation", en: "Communication" },
    definition: { sv: "Tydlig, proportionerlig kommunikation muntligt och skriftligt.", en: "Clear, proportionate written and verbal communication." } },
  { id: "observation", status: "researched", lastVerified: "2026-07-16", category: "operational", icon: "eye",
    name: { sv: "Observation och uppmärksamhet", en: "Observation and Attention" },
    definition: { sv: "Notera relevanta detaljer och förändringar i omgivningen.", en: "Notice relevant details and changes in the environment." } },
  { id: "reporting", status: "researched", lastVerified: "2026-07-16", category: "operational", icon: "clipboard",
    name: { sv: "Rapportering och dokumentation", en: "Reporting and Documentation" },
    definition: { sv: "Producera saklig, korrekt och användbar dokumentation.", en: "Produce factual, accurate and useful documentation." } },
  { id: "customer_service", status: "researched", lastVerified: "2026-07-16", category: "service", icon: "user-check",
    name: { sv: "Bemötande och service", en: "Customer Service" },
    definition: { sv: "Professionellt bemötande i mötet med människor.", en: "Professional interaction with people." } },
  { id: "teamwork", status: "researched", lastVerified: "2026-07-16", category: "behavioural", icon: "users",
    name: { sv: "Samarbete", en: "Teamwork" },
    definition: { sv: "Bidra effektivt i team och över funktioner.", en: "Contribute effectively across teams and functions." } },
  { id: "conflict", status: "researched", lastVerified: "2026-07-16", category: "operational", icon: "handshake",
    name: { sv: "Konflikthantering", en: "Conflict Management" },
    definition: { sv: "Deeskalera situationer och hantera motstridiga intressen.", en: "De-escalate situations and manage conflicting interests." } },
  { id: "decision_making", status: "researched", lastVerified: "2026-07-16", category: "behavioural", icon: "target",
    name: { sv: "Beslutsförmåga", en: "Decision Making" },
    definition: { sv: "Fatta genomtänkta beslut under osäkerhet och press.", en: "Make sound decisions under uncertainty and pressure." } },
  { id: "stress", status: "researched", lastVerified: "2026-07-16", category: "behavioural", icon: "activity",
    name: { sv: "Stresshantering", en: "Stress Management" },
    definition: { sv: "Bibehålla omdöme och prestation i pressade situationer.", en: "Maintain judgment and performance under pressure." } },
  { id: "risk_awareness", status: "researched", lastVerified: "2026-07-16", category: "risk_safety", icon: "radar",
    name: { sv: "Riskmedvetenhet", en: "Risk Awareness" },
    definition: { sv: "Identifiera, bedöma och agera på risker.", en: "Identify, evaluate and act on risk." } },
  { id: "incident_mgmt", status: "researched", lastVerified: "2026-07-16", category: "operational", icon: "siren",
    name: { sv: "Incidenthantering", en: "Incident Management" },
    definition: { sv: "Strukturerat hantera incidenter från upptäckt till uppföljning.", en: "Handle incidents from detection through follow-up in a structured way." } },
  { id: "analytical", status: "researched", lastVerified: "2026-07-16", category: "analytical", icon: "brain",
    name: { sv: "Analytiskt tänkande", en: "Analytical Thinking" },
    definition: { sv: "Strukturera information, hitta mönster och dra slutsatser.", en: "Structure information, find patterns and draw conclusions." } },
  { id: "leadership", status: "researched", lastVerified: "2026-07-16", category: "leadership", icon: "landmark",
    name: { sv: "Ledarskap", en: "Leadership" },
    definition: { sv: "Skapa riktning, engagera team och leverera resultat.", en: "Set direction, engage teams and deliver outcomes." } },
  { id: "planning", status: "researched", lastVerified: "2026-07-16", category: "leadership", icon: "wrench",
    name: { sv: "Planering", en: "Planning" },
    definition: { sv: "Planera arbete, resurser och prioriteringar över tid.", en: "Plan work, resources and priorities over time." } },
  { id: "technical", status: "researched", lastVerified: "2026-07-16", category: "technical", icon: "cpu",
    name: { sv: "Teknisk förståelse", en: "Technical Understanding" },
    definition: { sv: "Förstå tekniska säkerhetssystem och integrationer.", en: "Understand technical security systems and integrations." } },
  { id: "security_awareness", status: "researched", lastVerified: "2026-07-16", category: "risk_safety", icon: "shield",
    name: { sv: "Säkerhetsmedvetenhet", en: "Security Awareness" },
    definition: { sv: "Grundläggande förståelse för hot, sårbarheter och skyddsåtgärder.", en: "Foundational understanding of threats, vulnerabilities and controls." } },
  { id: "legal_regulatory", status: "researched", lastVerified: "2026-07-16", category: "regulatory", icon: "gavel",
    name: { sv: "Juridisk och regulatorisk förståelse", en: "Legal and Regulatory Understanding" },
    definition: { sv: "Förstå relevanta lagar, föreskrifter och myndighetskrav.", en: "Understand relevant laws, regulations and authority requirements." } },
  { id: "problem_solving", status: "researched", lastVerified: "2026-07-16", category: "analytical", icon: "brain",
    name: { sv: "Problemlösning", en: "Problem Solving" },
    definition: { sv: "Bryta ner problem och hitta praktiska lösningar.", en: "Break down problems and find practical solutions." } },
];

export function getCompetency(id: CompetencyId) {
  return competencies.find((c) => c.id === id);
}