import {
  Shield,
  ShieldCheck,
  Building2,
  Cpu,
  AlertTriangle,
  Scale,
  UserCheck,
  Server,
  Siren,
  Search,
  Radar,
  Lock,
  Landmark,
  Users,
  Wrench,
  Compass,
  Briefcase,
  Eye,
  MessageSquare,
  ClipboardCheck,
  Handshake,
  Brain,
  Activity,
  BookOpen,
  Gavel,
  FileSearch,
  Network,
  BarChart3,
  Target,
  Anchor,
  Truck,
  Globe,
  type LucideIcon,
} from "lucide-react";

const registry: Record<string, LucideIcon> = {
  shield: Shield,
  "shield-check": ShieldCheck,
  building: Building2,
  cpu: Cpu,
  "alert-triangle": AlertTriangle,
  scale: Scale,
  "user-check": UserCheck,
  server: Server,
  siren: Siren,
  search: Search,
  radar: Radar,
  lock: Lock,
  landmark: Landmark,
  users: Users,
  wrench: Wrench,
  compass: Compass,
  briefcase: Briefcase,
  eye: Eye,
  message: MessageSquare,
  clipboard: ClipboardCheck,
  handshake: Handshake,
  brain: Brain,
  activity: Activity,
  book: BookOpen,
  gavel: Gavel,
  "file-search": FileSearch,
  network: Network,
  chart: BarChart3,
  target: Target,
  anchor: Anchor,
  truck: Truck,
  globe: Globe,
};

export function icon(name?: string): LucideIcon {
  if (!name) return ShieldCheck;
  return registry[name] ?? ShieldCheck;
}

export type IconName = keyof typeof registry;