/**
 * BESKT PR 2 negative controls: every material assertion of the governed-
 * content guard must detect a planted defect in the real computation --
 * the migration's function bodies, DDL, triggers and grants, the rollback,
 * the runner registration and the release bookkeeping -- never a comment
 * or an error-message string. Each mutation changes exactly one thing, the
 * guard must fail with the named diagnostic, and every file is restored
 * byte-for-byte (proved by the shared runner).
 */
import { runControls, type Mutation } from "./runner";

const MIG = "supabase/migrations/20261108090000_beskt_governed_method_content.sql";
const RB = "supabase/rollback/20261108090000_beskt_governed_method_content_rollback.sql";
const DB = "scripts/db-test.sh";
const ADR = "docs/architecture/beskt-recruitment-method-discovery.md";
const STATE = "supabase/release-state.json";
const GUARD = "beskt-governed-content:check";
const SUITE = "supabase/tests/beskt_governed_content_test.sql";
const RB_SUITE = "supabase/tests/scp_a_rollback_test.sql";
const TYPES = "src/integrations/supabase/types.ts";
const ROLE_PACKS = "src/lib/interview-intelligence/role-packs.functions.ts";

const anchorComponent = (component: string, what: string): Mutation => ({
  id: `BESKT-NC-DB-ANCHOR-${component}`,
  defect: `a missing ${what} component no longer blocks publication (downgraded to advisory)`,
  file: MIG,
  find: `SELECT 'ANCHOR_COMPONENT_MISSING_${component}', 'blocking',`,
  replace: `SELECT 'ANCHOR_COMPONENT_MISSING_${component}', 'advisory',`,
  guard: GUARD,
  expect: "BESKT-DB-ANCHOR-COMPONENTS",
});

const MUTATIONS: readonly Mutation[] = [
  // ---- RLS, grants, execute ------------------------------------------------
  {
    id: "BESKT-NC-DB-FORCE-RLS",
    defect: "FORCE RLS is removed from the review table",
    file: MIG,
    find: "ALTER TABLE public.beskt_method_reviews          FORCE ROW LEVEL SECURITY;",
    replace: "ALTER TABLE public.beskt_method_reviews          NO FORCE ROW LEVEL SECURITY;",
    guard: GUARD,
    expect: "BESKT-DB-FORCE-RLS",
  },
  {
    id: "BESKT-NC-DB-ANON-EXECUTE",
    defect: "anon is granted execution of the publish RPC",
    file: MIG,
    find: "GRANT EXECUTE ON FUNCTION public.beskt_publish_version(uuid, uuid, integer, text) TO authenticated, service_role;",
    replace:
      "GRANT EXECUTE ON FUNCTION public.beskt_publish_version(uuid, uuid, integer, text) TO anon, authenticated, service_role;",
    guard: GUARD,
    expect: "BESKT-DB-ANON-EXECUTE",
  },
  {
    id: "BESKT-NC-DB-INTERNAL-EXECUTE",
    defect: "the event writer becomes callable by authenticated",
    file: MIG,
    find: "GRANT EXECUTE ON FUNCTION public.beskt_record_event(uuid, uuid, text, text, text, text, text, integer, uuid, text, jsonb, jsonb)\n  TO service_role;",
    replace:
      "GRANT EXECUTE ON FUNCTION public.beskt_record_event(uuid, uuid, text, text, text, text, text, integer, uuid, text, jsonb, jsonb)\n  TO authenticated, service_role;",
    guard: GUARD,
    expect: "BESKT-DB-ANON-EXECUTE",
  },
  {
    id: "BESKT-NC-DB-TABLE-GRANT",
    defect: "authenticated is granted INSERT on the ledger",
    file: MIG,
    find: "GRANT SELECT ON public.beskt_method_events           TO authenticated;",
    replace: "GRANT SELECT, INSERT ON public.beskt_method_events   TO authenticated;",
    guard: GUARD,
    expect: "BESKT-DB-TABLE-GRANTS",
  },
  {
    id: "BESKT-NC-DB-OPEN-POLICY",
    defect: "the item read policy becomes unconditional",
    file: MIG,
    find: "CREATE POLICY beskt_items_governance_read ON public.beskt_items\n  FOR SELECT TO authenticated USING (public.scp_interview_can_read(auth.uid()));",
    replace:
      "CREATE POLICY beskt_items_governance_read ON public.beskt_items\n  FOR SELECT TO authenticated USING (true);",
    guard: GUARD,
    expect: "BESKT-DB-TABLE-GRANTS",
  },
  {
    id: "BESKT-NC-DB-SEARCH-PATH",
    defect: "the publish RPC loses its pinned search_path",
    file: MIG,
    find: "  _reason text DEFAULT NULL)\nRETURNS jsonb\nLANGUAGE plpgsql\nSECURITY DEFINER\nSET search_path = public\nAS $$\nDECLARE\n  _request_hash text;\n  _replay jsonb;\n  _v public.beskt_method_versions%ROWTYPE;\n  _hash text;\n  _blockers text;",
    replace:
      "  _reason text DEFAULT NULL)\nRETURNS jsonb\nLANGUAGE plpgsql\nSECURITY DEFINER\nAS $$\nDECLARE\n  _request_hash text;\n  _replay jsonb;\n  _v public.beskt_method_versions%ROWTYPE;\n  _hash text;\n  _blockers text;",
    guard: GUARD,
    expect: "BESKT-DB-DEFINER-SEARCH-PATH",
  },
  // ---- the old flow --------------------------------------------------------
  {
    id: "BESKT-NC-DB-PACK-KIND-FILTER",
    defect: "the startable list stops filtering on pack_kind",
    file: MIG,
    find: "     WHERE p.pack_kind = 'role_interview'   -- BESKT PR 2: never a BESKT method\n       AND b.basis IS NOT NULL",
    replace: "     WHERE b.basis IS NOT NULL",
    guard: GUARD,
    expect: "BESKT-DB-PACK-KIND",
  },
  {
    id: "BESKT-NC-DB-START-BASIS-FILTER",
    defect: "the shared start basis stops joining on pack_kind",
    file: MIG,
    find: "   WHERE v.id = _pack_version_id\n     AND p.pack_kind = 'role_interview';",
    replace: "   WHERE v.id = _pack_version_id;",
    guard: GUARD,
    expect: "BESKT-DB-PACK-KIND",
  },
  {
    id: "BESKT-NC-DB-ROLE-BY-KIND",
    defect: "a BESKT method may carry a fake canonical role",
    file: MIG,
    find: "    OR (pack_kind = 'beskt_method' AND role_id IS NULL));",
    replace: "    OR (pack_kind = 'beskt_method'));",
    guard: GUARD,
    expect: "BESKT-DB-PACK-KIND",
  },
  {
    id: "BESKT-NC-DB-VERSION-SPINE-OPEN",
    defect: "the role-interview version trigger stops refusing other kinds",
    file: MIG,
    find: "  IF _kind IS DISTINCT FROM 'role_interview' THEN\n    RAISE EXCEPTION\n      'SCP_INTERVIEW_PACK_KIND_MISMATCH",
    replace: "  IF false THEN\n    RAISE EXCEPTION\n      'SCP_INTERVIEW_PACK_KIND_MISMATCH",
    guard: GUARD,
    expect: "BESKT-DB-PACK-KIND",
  },
  {
    id: "BESKT-NC-DB-OLD-VALIDATOR",
    defect: "the role-interview validator validates a BESKT pack against the 0-4 contract",
    file: MIG,
    find: "  IF NOT EXISTS (SELECT 1 FROM public.scp_interview_packs p\n                  WHERE p.id = _v.pack_id AND p.pack_kind = 'role_interview') THEN\n    RETURN QUERY SELECT 'PACK_KIND_NOT_ROLE_INTERVIEW'::text, 'blocking'::text,",
    replace:
      "  IF false THEN\n    RETURN QUERY SELECT 'PACK_KIND_NOT_ROLE_INTERVIEW'::text, 'blocking'::text,",
    guard: GUARD,
    expect: "BESKT-DB-OLD-VALIDATOR",
  },
  // ---- scoring and runtime data --------------------------------------------
  {
    id: "BESKT-NC-DB-SCORE-COLUMN",
    defect: "an option gains a risk weight",
    file: MIG,
    find: "  label_sv text,\n  label_en text,\n  UNIQUE (item_id, option_key)",
    replace:
      "  label_sv text,\n  label_en text,\n  risk_weight integer,\n  UNIQUE (item_id, option_key)",
    guard: GUARD,
    expect: "BESKT-DB-FORBIDDEN-COLUMNS",
  },
  {
    id: "BESKT-NC-DB-JSONB-CONTENT",
    defect: "an item gains an opaque jsonb attribute bag",
    file: MIG,
    find: "  discuss_orally_allowed boolean NOT NULL DEFAULT true,\n",
    replace:
      "  discuss_orally_allowed boolean NOT NULL DEFAULT true,\n  attributes jsonb NOT NULL DEFAULT '{}'::jsonb,\n",
    guard: GUARD,
    expect: "BESKT-DB-FORBIDDEN-COLUMNS",
  },
  {
    id: "BESKT-NC-DB-CANDIDATE-TABLE",
    defect: "a candidate response table is smuggled into PR 2",
    file: MIG,
    find: "CREATE INDEX beskt_method_events_pack_idx ON public.beskt_method_events (pack_id, seq DESC);",
    replace:
      "CREATE TABLE public.beskt_candidate_responses (\n  id uuid PRIMARY KEY DEFAULT gen_random_uuid()\n);\nCREATE INDEX beskt_method_events_pack_idx ON public.beskt_method_events (pack_id, seq DESC);",
    guard: GUARD,
    expect: "BESKT-DB-TABLES",
  },
  // ---- hash ----------------------------------------------------------------
  {
    id: "BESKT-NC-DB-HASH-MD5",
    defect: "the content hash falls back to md5",
    file: MIG,
    find: "  SELECT encode(sha256(convert_to(public.beskt_canonical_content(_method_version_id)::text, 'UTF8')), 'hex');",
    replace: "  SELECT md5(public.beskt_canonical_content(_method_version_id)::text);",
    guard: GUARD,
    expect: "BESKT-DB-HASH",
  },
  {
    id: "BESKT-NC-DB-HASH-UNORDERED",
    defect: "the routing rules aggregate follows heap order",
    file: MIG,
    find: "        ORDER BY r.rule_key)\n        FROM public.beskt_routing_rules r",
    replace: "        )\n        FROM public.beskt_routing_rules r",
    guard: GUARD,
    expect: "BESKT-DB-HASH",
  },
  // ---- validator: states, components, gates, activation ----------------------
  {
    id: "BESKT-NC-DB-EVIDENCE-STATE",
    defect: "conflicting_information is no longer a required evidence state",
    file: MIG,
    find: "    'external_verification_needed', 'conflicting_information',\n    'insufficient_basis', 'not_applicable'];\n  _review_gates",
    replace:
      "    'external_verification_needed',\n    'insufficient_basis', 'not_applicable'];\n  _review_gates",
    guard: GUARD,
    expect: "BESKT-DB-EVIDENCE-STATES",
  },
  {
    id: "BESKT-NC-DB-EVIDENCE-LEVEL",
    defect: "a numeric risk level joins the anchor state vocabulary",
    file: MIG,
    find: "    'insufficient_basis', 'not_applicable')),\n\n  -- The seven governed components",
    replace:
      "    'insufficient_basis', 'not_applicable', 'risk_level_4')),\n\n  -- The seven governed components",
    guard: GUARD,
    expect: "BESKT-DB-EVIDENCE-STATES",
  },
  anchorComponent("DEFINITION", "definition"),
  anchorComponent("INCLUSION_CRITERIA", "inclusion-criteria"),
  anchorComponent("EXCLUSION_CRITERIA", "exclusion-criteria"),
  anchorComponent("SUPPORTING_EVIDENCE_EXAMPLES", "supporting-evidence-examples"),
  anchorComponent("COUNTER_EVIDENCE_AND_PROTECTIVE_FACTORS", "counter-evidence/protective-factors"),
  anchorComponent("PROHIBITED_INFERENCES", "prohibited-inferences"),
  anchorComponent("REQUIRED_NEXT_ACTION", "required-next-action"),
  {
    id: "BESKT-NC-DB-STALE-REVIEW-HASH",
    defect: "a stale review counts towards publication",
    file: MIG,
    find: "           AND rv.decision = 'approved'\n           AND rv.content_hash_at_review = _hash\n           AND rv.review_cycle_at_review = _v.review_cycle) THEN",
    replace: "           AND rv.decision = 'approved') THEN",
    guard: GUARD,
    expect: "BESKT-DB-REVIEW-GATES",
  },
  {
    id: "BESKT-NC-DB-FOUR-GATES",
    defect: "data_protection is dropped from the review gates",
    file: MIG,
    find: "  _review_gates text[] := ARRAY[\n    'personnel_security', 'senior_hr', 'recruitment',\n    'employment_privacy_legal', 'data_protection'];",
    replace:
      "  _review_gates text[] := ARRAY[\n    'personnel_security', 'senior_hr', 'recruitment',\n    'employment_privacy_legal'];",
    guard: GUARD,
    expect: "BESKT-DB-REVIEW-GATES",
  },
  {
    id: "BESKT-NC-DB-SELF-REVIEW",
    defect: "the author may review their own method",
    file: MIG,
    find: "  IF _v.created_by IS NOT NULL AND _v.created_by = NEW.reviewer_id THEN\n    RAISE EXCEPTION\n      'BESKT_SELF_REVIEW",
    replace: "  IF false THEN\n    RAISE EXCEPTION\n      'BESKT_SELF_REVIEW",
    guard: GUARD,
    expect: "BESKT-DB-REVIEW-GATES",
  },
  {
    id: "BESKT-NC-DB-PUBLISH-WITHOUT-VALIDATOR",
    defect: "publication no longer runs the validator with the review gates",
    file: MIG,
    find: "    FROM public.beskt_method_validate(_method_version_id, true) bv",
    replace: "    FROM public.beskt_method_validate(_method_version_id, false) bv",
    guard: GUARD,
    expect: "BESKT-DB-REVIEW-GATES",
  },
  {
    id: "BESKT-NC-DB-SV-GATE-LAWFUL-BASIS",
    defect: "the lawful-basis activation requirement is no longer required",
    file: MIG,
    find: "                      AND a.requirement_key = 'lawful_basis_recorded') THEN",
    replace: "                      AND true) THEN",
    guard: GUARD,
    expect: "BESKT-DB-SV-GATES",
  },
  {
    id: "BESKT-NC-DB-SV-GATE-OWNER",
    defect: "the authorised-security-owner requirement is no longer required",
    file: MIG,
    find: "                      AND a.requirement_key = 'authorised_security_owner_assigned'\n                      AND a.satisfied_by_role = 'authorised_security_function') THEN",
    replace: "                      AND a.satisfied_by_role = 'authorised_security_function') THEN",
    guard: GUARD,
    expect: "BESKT-DB-SV-GATES",
  },
  {
    id: "BESKT-NC-DB-SV-GATE-ATTESTED",
    defect: "the security-sensitive-role requirement is no longer required",
    file: MIG,
    find: "                      AND a.requirement_key = 'security_sensitive_role_attested')\n       OR EXISTS",
    replace: "                      AND true)\n       OR EXISTS",
    guard: GUARD,
    expect: "BESKT-DB-SV-GATES",
  },
  // ---- routing -------------------------------------------------------------
  {
    id: "BESKT-NC-DB-CROSS-VERSION-ROUTE",
    defect: "a route may connect items of another version",
    file: MIG,
    find: "    IF _src.method_version_id IS DISTINCT FROM NEW.method_version_id\n       OR _tgt.method_version_id IS DISTINCT FROM NEW.method_version_id THEN",
    replace: "    IF false THEN",
    guard: GUARD,
    expect: "BESKT-DB-CROSS-VERSION",
  },
  {
    id: "BESKT-NC-DB-MODE-ESCALATION-GUARD",
    defect: "a recruitment-support rule may route into security-vetting content at write time",
    file: MIG,
    find: "    IF NEW.applies_mode = 'recruitment_support'\n       AND (_tgt.permitted_mode = 'security_vetting_support'\n            OR _src.permitted_mode = 'security_vetting_support') THEN",
    replace:
      "    IF NEW.applies_mode = 'security_vetting_support'\n       AND (_tgt.permitted_mode = 'security_vetting_support'\n            OR _src.permitted_mode = 'security_vetting_support') THEN",
    guard: GUARD,
    expect: "BESKT-DB-MODE-ESCALATION",
  },
  {
    id: "BESKT-NC-DB-MODE-ESCALATION-VALIDATOR",
    defect: "the validator stops re-proving the mode boundary on the stored graph",
    file: MIG,
    find: "       AND r.applies_mode = 'recruitment_support'\n       AND (ti.permitted_mode = 'security_vetting_support' OR si.permitted_mode = 'security_vetting_support');",
    replace:
      "       AND r.applies_mode = 'security_vetting_support'\n       AND (ti.permitted_mode = 'security_vetting_support' OR si.permitted_mode = 'security_vetting_support');",
    guard: GUARD,
    expect: "BESKT-DB-MODE-ESCALATION",
  },
  {
    id: "BESKT-NC-DB-OMISSION-CONDITION",
    defect: "an omitted answer becomes a routing condition",
    file: MIG,
    find: "    CHECK (condition_kind IN ('always', 'option_selected', 'boolean_equals')),",
    replace:
      "    CHECK (condition_kind IN ('always', 'option_selected', 'boolean_equals', 'omitted')),",
    guard: GUARD,
    expect: "BESKT-DB-OMISSION-NEUTRAL",
  },
  {
    id: "BESKT-NC-DB-OMISSION-RESOLVER",
    defect:
      "the resolver fires an option rule on any non-empty answer, including a discuss-orally state",
    file: MIG,
    find: "      WHEN 'option_selected' THEN\n        _answer IS NOT NULL\n        AND _answer ->> 'kind' = 'option'",
    replace: "      WHEN 'option_selected' THEN\n        _answer IS NOT NULL",
    guard: GUARD,
    expect: "BESKT-DB-OMISSION-NEUTRAL",
  },
  {
    id: "BESKT-NC-DB-ROUTE-CYCLE",
    defect: "cycles no longer block publication",
    file: MIG,
    find: "    SELECT 1 FROM walk WHERE walk.node = walk.origin) THEN\n    RETURN QUERY SELECT 'ROUTE_CYCLE'::text, 'blocking'::text,",
    replace:
      "    SELECT 1 FROM walk WHERE walk.node = walk.origin) THEN\n    RETURN QUERY SELECT 'ROUTE_CYCLE'::text, 'advisory'::text,",
    guard: GUARD,
    expect: "BESKT-DB-ROUTING",
  },
  // ---- idempotency and revision ---------------------------------------------
  {
    id: "BESKT-NC-DB-STALE-REVISION",
    defect: "a stale expected revision is accepted",
    file: MIG,
    find: "  IF _v.revision <> _expected_revision THEN\n    RAISE EXCEPTION 'BESKT_STALE_REVISION",
    replace: "  IF false THEN\n    RAISE EXCEPTION 'BESKT_STALE_REVISION",
    guard: GUARD,
    expect: "BESKT-DB-STALE-REVISION",
  },
  {
    id: "BESKT-NC-DB-REPLAY-PAYLOAD",
    defect: "a replay with a changed payload is served the old result",
    file: MIG,
    find: "  IF _receipt.request_hash IS DISTINCT FROM _request_hash THEN\n    RAISE EXCEPTION 'BESKT_OPERATION_PAYLOAD_MISMATCH",
    replace: "  IF false THEN\n    RAISE EXCEPTION 'BESKT_OPERATION_PAYLOAD_MISMATCH",
    guard: GUARD,
    expect: "BESKT-DB-REPLAY",
  },
  {
    id: "BESKT-NC-DB-REPLAY-AFTER-CAS",
    defect: "the touch RPC checks the compare-and-swap before answering a replay",
    file: MIG,
    find: "  -- Replay is answered BEFORE the compare-and-swap.\n  _replay := public.beskt_operation_begin(_operation_id, _request_hash);\n  IF _replay IS NOT NULL THEN RETURN _replay; END IF;\n\n  IF NOT public.scp_interview_can_edit(auth.uid()) THEN\n    RAISE EXCEPTION 'BESKT_NOT_EDITOR: editing a method version requires the platform content editor role.'\n      USING ERRCODE = 'insufficient_privilege';\n  END IF;\n\n  _v := public.beskt_lock_version(_method_version_id, _expected_revision);",
    replace:
      "  IF NOT public.scp_interview_can_edit(auth.uid()) THEN\n    RAISE EXCEPTION 'BESKT_NOT_EDITOR: editing a method version requires the platform content editor role.'\n      USING ERRCODE = 'insufficient_privilege';\n  END IF;\n\n  _v := public.beskt_lock_version(_method_version_id, _expected_revision);\n  _replay := public.beskt_operation_begin(_operation_id, _request_hash);\n  IF _replay IS NOT NULL THEN RETURN _replay; END IF;",
    guard: GUARD,
    expect: "BESKT-DB-REPLAY",
  },
  {
    id: "BESKT-NC-DB-REPLAY-BROKEN",
    defect: "the review RPC never answers a replay",
    file: MIG,
    find: "    'rationale', _rationale));\n  _replay := public.beskt_operation_begin(_operation_id, _request_hash);\n  IF _replay IS NOT NULL THEN RETURN _replay; END IF;",
    replace:
      "    'rationale', _rationale));\n  _replay := public.beskt_operation_begin(_operation_id, _request_hash);",
    guard: GUARD,
    expect: "BESKT-DB-REPLAY",
  },
  {
    id: "BESKT-NC-DB-OPERATION-NOT-UNIQUE",
    defect: "an operation id may be recorded twice",
    file: MIG,
    find: "CREATE UNIQUE INDEX beskt_method_events_operation_idx\n  ON public.beskt_method_events (operation_id) WHERE operation_id IS NOT NULL;",
    replace:
      "CREATE INDEX beskt_method_events_operation_idx\n  ON public.beskt_method_events (operation_id) WHERE operation_id IS NOT NULL;",
    guard: GUARD,
    expect: "BESKT-DB-REPLAY",
  },
  // ---- immutability and append-only ------------------------------------------
  {
    id: "BESKT-NC-DB-REVIEW-UPDATE",
    defect: "reviews become updatable (the trigger only covers DELETE)",
    file: MIG,
    find: "CREATE TRIGGER beskt_method_reviews_append_only\n  BEFORE UPDATE OR DELETE ON public.beskt_method_reviews",
    replace:
      "CREATE TRIGGER beskt_method_reviews_append_only\n  BEFORE DELETE ON public.beskt_method_reviews",
    guard: GUARD,
    expect: "BESKT-DB-APPEND-ONLY",
  },
  {
    id: "BESKT-NC-DB-EVENT-DELETE",
    defect: "events become deletable (the trigger only covers UPDATE)",
    file: MIG,
    find: "CREATE TRIGGER beskt_method_events_append_only\n  BEFORE UPDATE OR DELETE ON public.beskt_method_events",
    replace:
      "CREATE TRIGGER beskt_method_events_append_only\n  BEFORE UPDATE ON public.beskt_method_events",
    guard: GUARD,
    expect: "BESKT-DB-APPEND-ONLY",
  },
  {
    id: "BESKT-NC-DB-PUBLISHED-CHILD",
    defect: "children of a published version become editable",
    file: MIG,
    find: "  IF _status NOT IN ('draft', 'in_review') THEN\n    RAISE EXCEPTION\n      'BESKT_PUBLISHED_IMMUTABLE: % cannot be modified",
    replace:
      "  IF _status NOT IN ('draft', 'in_review', 'published') THEN\n    RAISE EXCEPTION\n      'BESKT_PUBLISHED_IMMUTABLE: % cannot be modified",
    guard: GUARD,
    expect: "BESKT-DB-PUBLISHED-IMMUTABLE",
  },
  {
    id: "BESKT-NC-DB-UNGUARDED-CHILD",
    defect: "the options table loses its child guard on UPDATE",
    file: MIG,
    find: "CREATE TRIGGER beskt_item_options_child_guard\n  BEFORE INSERT OR UPDATE OR DELETE ON public.beskt_item_options",
    replace:
      "CREATE TRIGGER beskt_item_options_child_guard\n  BEFORE INSERT OR DELETE ON public.beskt_item_options",
    guard: GUARD,
    expect: "BESKT-DB-PUBLISHED-IMMUTABLE",
  },
  {
    id: "BESKT-NC-DB-REVISION-REGRESSION",
    defect: "an older revision may overwrite newer content",
    file: MIG,
    find: "  IF NEW.revision < OLD.revision THEN\n    RAISE EXCEPTION 'BESKT_REVISION_REGRESSION",
    replace: "  IF false THEN\n    RAISE EXCEPTION 'BESKT_REVISION_REGRESSION",
    guard: GUARD,
    expect: "BESKT-DB-PUBLISHED-IMMUTABLE",
  },
  // ---- the read contract -----------------------------------------------------
  {
    id: "BESKT-NC-DB-READ-SECURITY-VETTING",
    defect: "internal QA may read security-vetting content",
    file: MIG,
    find: "           WHERE v.id = _method_version_id\n             AND v.content_status = 'published'\n             AND v.mode = 'recruitment_support')",
    replace:
      "           WHERE v.id = _method_version_id\n             AND v.content_status = 'published')",
    guard: GUARD,
    expect: "BESKT-DB-READ-CONTRACT",
  },
  {
    id: "BESKT-NC-DB-READ-DRAFTS",
    defect: "the read contract returns drafts",
    file: MIG,
    find: "  IF _v.content_status <> 'published' THEN\n    RAISE EXCEPTION 'BESKT_NOT_PUBLISHED",
    replace: "  IF false THEN\n    RAISE EXCEPTION 'BESKT_NOT_PUBLISHED",
    guard: GUARD,
    expect: "BESKT-DB-READ-CONTRACT",
  },
  // ---- registration, rollback, bookkeeping, PR 1 -----------------------------
  {
    id: "BESKT-NC-DB-ROLLBACK-NOT-EXERCISED",
    defect: "db-test.sh stops applying the rollback file",
    file: DB,
    find: 'BG_RB="$(psql -1 -v ON_ERROR_STOP=1 -d "$TEST_DB" \\\n  -f supabase/rollback/20261108090000_beskt_governed_method_content_rollback.sql 2>&1)"',
    replace:
      'BG_RB="$(psql -d "$TEST_DB" -c "SELECT \'BESKT_GOVERNED_CONTENT_ROLLBACK ok\'" 2>&1)"',
    guard: GUARD,
    expect: "BESKT-DB-SUITE",
  },
  {
    id: "BESKT-NC-DB-SUITE-FLOOR",
    defect: "the suite's assertion floor is lowered to nothing",
    file: DB,
    find: '  if [ "$BG_PASSED" -lt 380 ]; then',
    replace: '  if [ "$BG_PASSED" -lt 1 ]; then',
    guard: GUARD,
    expect: "BESKT-DB-SUITE",
  },
  {
    id: "BESKT-NC-DB-ROLLBACK-ROLE",
    defect: "the rollback leaves role_id nullable",
    file: RB,
    find: "ALTER TABLE public.scp_interview_packs ALTER COLUMN role_id SET NOT NULL;\n",
    replace: "",
    guard: GUARD,
    expect: "BESKT-DB-ROLLBACK",
  },
  {
    id: "BESKT-NC-DB-HOSTED-CLAIM",
    defect: "release-state.json claims the migration is applied on the owner project",
    file: STATE,
    find: '      "file": "20261108090000_beskt_governed_method_content.sql",\n      "hostedState": "pending",',
    replace:
      '      "file": "20261108090000_beskt_governed_method_content.sql",\n      "hostedState": "applied",',
    guard: GUARD,
    expect: "BESKT-DB-NO-HOSTED",
  },
  {
    id: "BESKT-NC-DB-PR1-CONTRACT",
    defect: "PR 1's contract is weakened to inherit the role-interview scoring",
    file: ADR,
    find: '"inheritRoleInterviewScoring": false',
    replace: '"inheritRoleInterviewScoring": true',
    guard: GUARD,
    expect: "BESKT-DB-PR1-CONTRACT",
  },

  // ---- correction 1: approvals bind to hash AND review cycle ---------------------
  {
    id: "BESKT-NC-DB-CYCLE-VALIDATOR",
    defect: "the validator accepts approvals from an earlier review cycle",
    file: MIG,
    find: "           AND rv.content_hash_at_review = _hash\n           AND rv.review_cycle_at_review = _v.review_cycle) THEN",
    replace: "           AND rv.content_hash_at_review = _hash) THEN",
    guard: GUARD,
    expect: "BESKT-DB-REVIEW-GATES",
  },
  {
    id: "BESKT-NC-DB-CYCLE-TRIGGER",
    defect: "the review row no longer has to name the current review cycle",
    file: MIG,
    find: "     OR NEW.revision_at_review IS DISTINCT FROM _v.revision\n     OR NEW.review_cycle_at_review IS DISTINCT FROM _v.review_cycle THEN",
    replace: "     OR NEW.revision_at_review IS DISTINCT FROM _v.revision THEN",
    guard: GUARD,
    expect: "BESKT-DB-REVIEW-GATES",
  },
  {
    id: "BESKT-NC-DB-CYCLE-NOT-OPENED",
    defect: "re-submission no longer opens a new review cycle",
    file: MIG,
    find: "         review_cycle = _v.review_cycle + 1, updated_at = now()",
    replace: "         review_cycle = _v.review_cycle, updated_at = now()",
    guard: GUARD,
    expect: "BESKT-DB-REVIEW-CYCLE",
  },
  {
    id: "BESKT-NC-DB-REJECTION-KEEPS-CYCLE",
    defect: "a rejection no longer ends the cycle by returning the version to draft",
    file: MIG,
    find: "  IF _decision = 'rejected' THEN\n    _new_status := 'draft';",
    replace: "  IF _decision = 'rejected' THEN\n    _new_status := 'in_review';",
    guard: GUARD,
    expect: "BESKT-DB-REVIEW-CYCLE",
  },
  // ---- correction 2: gate-specific reviewer authority ------------------------
  {
    id: "BESKT-NC-DB-GRANT-RPC",
    defect: "the reviewer role alone opens every gate in the RPC",
    file: MIG,
    find: "  IF NOT public.beskt_holds_grant(auth.uid(), _gate) THEN\n    RAISE EXCEPTION 'BESKT_GATE_NOT_GRANTED",
    replace: "  IF false THEN\n    RAISE EXCEPTION 'BESKT_GATE_NOT_GRANTED",
    guard: GUARD,
    expect: "BESKT-DB-GATE-GRANTS",
  },
  {
    id: "BESKT-NC-DB-GRANT-TRIGGER",
    defect: "a BYPASSRLS writer can record a gate nobody granted",
    file: MIG,
    find: "  IF NOT public.beskt_holds_grant(NEW.reviewer_id, NEW.gate) THEN\n    RAISE EXCEPTION\n      'BESKT_GATE_NOT_GRANTED",
    replace: "  IF false THEN\n    RAISE EXCEPTION\n      'BESKT_GATE_NOT_GRANTED",
    guard: GUARD,
    expect: "BESKT-DB-GATE-GRANTS",
  },
  {
    id: "BESKT-NC-DB-GRANT-REVOKED-COUNTS",
    defect: "a revoked grant still opens its gate",
    file: MIG,
    find: "       AND g.grant_kind = _grant_kind\n       AND g.revoked_at IS NULL\n",
    replace: "       AND g.grant_kind = _grant_kind\n",
    guard: GUARD,
    expect: "BESKT-DB-GATE-GRANTS",
  },
  {
    id: "BESKT-NC-DB-GRANT-EXPIRED-COUNTS",
    defect: "an expired grant still opens its gate",
    file: MIG,
    find: "       AND (g.valid_until IS NULL OR g.valid_until > now()));",
    replace: "       AND (g.valid_until IS NULL OR g.valid_until > g.valid_from));",
    guard: GUARD,
    expect: "BESKT-DB-GATE-GRANTS",
  },
  {
    id: "BESKT-NC-DB-GRANT-WRONG-KIND",
    defect: "a grant of any kind opens every gate",
    file: MIG,
    find: "     WHERE g.user_id = _user_id\n       AND g.grant_kind = _grant_kind\n",
    replace: "     WHERE g.user_id = _user_id\n",
    guard: GUARD,
    expect: "BESKT-DB-GATE-GRANTS",
  },
  {
    id: "BESKT-NC-DB-GRANT-BY-ANYONE",
    defect: "any signed-in user can grant themselves a gate",
    file: MIG,
    find: "  IF NOT public.is_platform_admin(auth.uid()) THEN\n    RAISE EXCEPTION 'BESKT_NOT_PLATFORM_ADMIN: governance grants are made by a platform admin only.'",
    replace:
      "  IF false THEN\n    RAISE EXCEPTION 'BESKT_NOT_PLATFORM_ADMIN: governance grants are made by a platform admin only.'",
    guard: GUARD,
    expect: "BESKT-DB-GATE-GRANTS",
  },
  {
    id: "BESKT-NC-DB-GRANT-CLIENT-WRITE",
    defect: "authenticated is granted INSERT on the mapping",
    file: MIG,
    find: "GRANT SELECT ON public.beskt_governance_grants       TO authenticated;",
    replace: "GRANT SELECT, INSERT ON public.beskt_governance_grants TO authenticated;",
    guard: GUARD,
    expect: "BESKT-DB-TABLE-GRANTS",
  },
  {
    id: "BESKT-NC-DB-GRANT-DELETABLE",
    defect: "a governance grant can be deleted",
    file: MIG,
    find: "  IF TG_OP = 'DELETE' THEN\n    RAISE EXCEPTION 'BESKT_GRANT_APPEND_ONLY: a governance grant is never deleted; revoke it instead.'",
    replace:
      "  IF TG_OP = 'DELETE' THEN\n    RETURN OLD;\n    RAISE EXCEPTION 'BESKT_GRANT_APPEND_ONLY: a governance grant is never deleted; revoke it instead.'",
    guard: GUARD,
    expect: "BESKT-DB-GATE-GRANTS",
  },
  // ---- correction 3: synthetic_internal_only read contract -----------------------
  {
    id: "BESKT-NC-DB-READ-EMPLOYER-BRANCH",
    defect: "an active employer member may read published content again",
    file: MIG,
    find: "    -- Governance readers: every state, both modes.\n    public.scp_interview_can_read(auth.uid())",
    replace:
      "    -- Governance readers: every state, both modes.\n    public.scp_interview_can_read(auth.uid())\n    OR EXISTS (SELECT 1 FROM public.employer_memberships em WHERE em.user_id = auth.uid() AND em.status = 'active')",
    guard: GUARD,
    expect: "BESKT-DB-READ-CONTRACT",
  },
  {
    id: "BESKT-NC-DB-READ-PARTIAL-DOCUMENT",
    defect:
      "access_class is no longer enforced on the items, so a document could be returned in part",
    file: MIG,
    find: "        AND NOT EXISTS (\n          SELECT 1 FROM public.beskt_items i\n           WHERE i.method_version_id = _method_version_id\n             AND NOT (i.access_class = ANY (public.beskt_reader_access_classes(auth.uid()))))));",
    replace: "        ));",
    guard: GUARD,
    expect: "BESKT-DB-READ-CONTRACT",
  },
  {
    id: "BESKT-NC-DB-READ-QA-SECURITY-CLASS",
    defect: "internal QA is given the authorised_security_function access class",
    file: MIG,
    find: "      ARRAY['recruiter', 'beskt_interviewer', 'independent_assessor', 'accountable_process_owner']\n    ELSE '{}'::text[]",
    replace:
      "      ARRAY['recruiter', 'beskt_interviewer', 'independent_assessor', 'authorised_security_function', 'accountable_process_owner']\n    ELSE '{}'::text[]",
    guard: GUARD,
    expect: "BESKT-DB-READ-CONTRACT",
  },
  {
    id: "BESKT-NC-DB-HASH-EXECUTABLE",
    defect: "the content hash function becomes callable by authenticated",
    file: MIG,
    find: "GRANT EXECUTE ON FUNCTION public.beskt_method_content_hash(uuid) TO service_role;",
    replace:
      "GRANT EXECUTE ON FUNCTION public.beskt_method_content_hash(uuid) TO authenticated, service_role;",
    guard: GUARD,
    expect: "BESKT-DB-ANON-EXECUTE",
  },
  // ---- correction 4: no re-parenting, parent keys immutable ------------------
  {
    id: "BESKT-NC-DB-REPARENT-OLD-OWNER",
    defect: "the child guard no longer resolves the OLD owner of a re-parented row",
    file: MIG,
    find: "      _version_id := _row.method_version_id;\n      IF TG_OP = 'UPDATE' THEN _old_version_id := OLD.method_version_id; END IF;",
    replace: "      _version_id := _row.method_version_id;",
    guard: GUARD,
    expect: "BESKT-DB-REPARENT",
  },
  {
    id: "BESKT-NC-DB-REPARENT-OLD-OWNER-OPTION",
    defect: "the child guard no longer resolves the OLD owner of a re-parented option",
    file: MIG,
    find: "      IF TG_OP = 'UPDATE' THEN\n        SELECT i.method_version_id INTO _old_version_id FROM public.beskt_items i WHERE i.id = OLD.item_id;\n      END IF;",
    replace: "",
    guard: GUARD,
    expect: "BESKT-DB-REPARENT",
  },
  {
    id: "BESKT-NC-DB-REPARENT-FROZEN-ALLOWED",
    defect: "a child of a published version may be moved under a draft",
    file: MIG,
    find: "    IF _status IS NULL OR _status NOT IN ('draft', 'in_review') THEN\n      RAISE EXCEPTION\n        'BESKT_PUBLISHED_IMMUTABLE: % cannot be re-parented away",
    replace:
      "    IF false THEN\n      RAISE EXCEPTION\n        'BESKT_PUBLISHED_IMMUTABLE: % cannot be re-parented away",
    guard: GUARD,
    expect: "BESKT-DB-REPARENT",
  },
  {
    id: "BESKT-NC-DB-PARENT-VERSION-MUTABLE",
    defect: "method_version_id becomes mutable in every child family",
    file: MIG,
    find: "    ELSIF NEW.method_version_id IS DISTINCT FROM OLD.method_version_id THEN\n      RAISE EXCEPTION 'BESKT_PARENT_IMMUTABLE: % cannot be moved to another method version.', TG_TABLE_NAME",
    replace:
      "    ELSIF false THEN\n      RAISE EXCEPTION 'BESKT_PARENT_IMMUTABLE: % cannot be moved to another method version.', TG_TABLE_NAME",
    guard: GUARD,
    expect: "BESKT-DB-REPARENT",
  },
  {
    id: "BESKT-NC-DB-PARENT-ITEM-SECTION",
    defect: "an item may be moved to another section or profile",
    file: MIG,
    find: "      IF NEW.section_id IS DISTINCT FROM OLD.section_id\n         OR NEW.exposure_profile_id IS DISTINCT FROM OLD.exposure_profile_id THEN\n        RAISE EXCEPTION 'BESKT_PARENT_IMMUTABLE: an item",
    replace: "      IF false THEN\n        RAISE EXCEPTION 'BESKT_PARENT_IMMUTABLE: an item",
    guard: GUARD,
    expect: "BESKT-DB-REPARENT",
  },
  {
    id: "BESKT-NC-DB-PARENT-PROMPT-ITEM",
    defect: "a prompt may be re-pointed at another profile or item",
    file: MIG,
    find: "      IF NEW.exposure_profile_id IS DISTINCT FROM OLD.exposure_profile_id\n         OR NEW.item_id IS DISTINCT FROM OLD.item_id THEN\n        RAISE EXCEPTION 'BESKT_PARENT_IMMUTABLE: a prompt",
    replace: "      IF false THEN\n        RAISE EXCEPTION 'BESKT_PARENT_IMMUTABLE: a prompt",
    guard: GUARD,
    expect: "BESKT-DB-REPARENT",
  },
  {
    id: "BESKT-NC-DB-PARENT-ROUTE-OPTION",
    defect: "a routing rule may be re-pointed at another option",
    file: MIG,
    find: "         OR NEW.target_item_id IS DISTINCT FROM OLD.target_item_id\n         OR NEW.condition_option_id IS DISTINCT FROM OLD.condition_option_id THEN",
    replace: "         OR NEW.target_item_id IS DISTINCT FROM OLD.target_item_id THEN",
    guard: GUARD,
    expect: "BESKT-DB-REPARENT",
  },
  {
    id: "BESKT-NC-DB-PARENT-OPTION-ITEM",
    defect: "an option may be moved to another item",
    file: MIG,
    find: "      IF NEW.item_id IS DISTINCT FROM OLD.item_id THEN\n        RAISE EXCEPTION 'BESKT_PARENT_IMMUTABLE: an option cannot be moved to another item.'",
    replace:
      "      IF false THEN\n        RAISE EXCEPTION 'BESKT_PARENT_IMMUTABLE: an option cannot be moved to another item.'",
    guard: GUARD,
    expect: "BESKT-DB-REPARENT",
  },
  // ---- correction 5: no direct-DML bypass on the identity table ---------------
  {
    id: "BESKT-NC-DB-PACK-INSERT-UNSCOPED",
    defect: "an editor may INSERT a BESKT identity directly",
    file: MIG,
    find: "  FOR INSERT TO authenticated\n  WITH CHECK (public.scp_interview_can_edit(auth.uid()) AND pack_kind = 'role_interview');",
    replace:
      "  FOR INSERT TO authenticated\n  WITH CHECK (public.scp_interview_can_edit(auth.uid()));",
    guard: GUARD,
    expect: "BESKT-DB-PACK-DML",
  },
  {
    id: "BESKT-NC-DB-PACK-UPDATE-UNSCOPED",
    defect: "an editor may UPDATE a BESKT identity directly",
    file: MIG,
    find: "  USING (public.scp_interview_can_edit(auth.uid()) AND pack_kind = 'role_interview')\n  WITH CHECK (public.scp_interview_can_edit(auth.uid()) AND pack_kind = 'role_interview');",
    replace:
      "  USING (public.scp_interview_can_edit(auth.uid()))\n  WITH CHECK (public.scp_interview_can_edit(auth.uid()) AND pack_kind = 'role_interview');",
    guard: GUARD,
    expect: "BESKT-DB-PACK-DML",
  },
  {
    id: "BESKT-NC-DB-PACK-IDENTITY-MUTABLE",
    defect: "a BESKT identity's metadata can be rewritten by a direct UPDATE",
    file: MIG,
    find: "  IF OLD.pack_kind = 'beskt_method'\n     AND coalesce(current_setting('beskt.governed_transition', true), '') <> 'on'",
    replace:
      "  IF false\n     AND coalesce(current_setting('beskt.governed_transition', true), '') <> 'on'",
    guard: GUARD,
    expect: "BESKT-DB-PACK-DML",
  },
  {
    id: "BESKT-NC-DB-LIST-ROLE-PACKS",
    defect: "listRolePacks() lists BESKT method identities as role packs",
    file: ROLE_PACKS,
    find: '        .not("role_id", "is", null)\n',
    replace: "",
    guard: GUARD,
    expect: "BESKT-DB-PACK-DML",
  },
  {
    id: "BESKT-NC-DB-TYPES-STALE",
    defect: "the generated types no longer describe pack_kind",
    file: TYPES,
    find: "          name_sv: string\n          pack_kind: string\n          purpose_sv: string\n          role_id: string | null\n          slug: string\n        }\n        Insert: {",
    replace:
      "          name_sv: string\n          purpose_sv: string\n          role_id: string | null\n          slug: string\n        }\n        Insert: {",
    guard: GUARD,
    expect: "BESKT-DB-TYPES",
  },
  // ---- correction 6: unambiguous canonical hash --------------------------------
  {
    id: "BESKT-NC-DB-HASH-DELIMITED-FIELDS",
    defect:
      "two wording fields are joined with a delimiter again, so 'a|b'+'c' and 'a'+'b|c' collide",
    file: MIG,
    find: "          'wording_sv', i.wording_sv, 'wording_en', i.wording_en,\n          'purpose_sv', i.purpose_sv, 'purpose_en', i.purpose_en,\n          'permitted_mode', i.permitted_mode, 'phase', i.phase, 'answer_type', i.answer_type,",
    replace:
      "          'wording', concat_ws('|', i.wording_sv, i.wording_en),\n          'purpose_sv', i.purpose_sv, 'purpose_en', i.purpose_en,\n          'permitted_mode', i.permitted_mode, 'phase', i.phase, 'answer_type', i.answer_type,",
    guard: GUARD,
    expect: "BESKT-DB-HASH",
  },
  {
    id: "BESKT-NC-DB-HASH-UNTYPED",
    defect: "the canonical document loses its schema name",
    file: MIG,
    find: "    'schema', 'beskt_canonical_content_v2',",
    replace: "    'schema', 'beskt_canonical_content',",
    guard: GUARD,
    expect: "BESKT-DB-HASH",
  },
  {
    id: "BESKT-NC-DB-HASH-UNSORTED-ARRAY",
    defect: "an item's prohibited inferences are hashed in stored order",
    file: MIG,
    find: "          'prohibited_inferences', public.beskt_sorted_array(i.prohibited_inferences))",
    replace: "          'prohibited_inferences', to_jsonb(i.prohibited_inferences))",
    guard: GUARD,
    expect: "BESKT-DB-HASH",
  },
  // ---- correction 7: one open version under a real race ------------------------
  {
    id: "BESKT-NC-DB-LOCK-AFTER-CHECK",
    defect:
      "the per-method lock is taken after the open-version check, so two sessions can both pass it",
    file: MIG,
    find: "  PERFORM pg_advisory_xact_lock(hashtextextended('beskt_method:' || _pack_id::text, 0));\n\n  IF EXISTS (SELECT 1 FROM public.beskt_method_versions v\n              WHERE v.pack_id = _pack_id AND v.content_status IN ('draft', 'in_review')) THEN\n    RAISE EXCEPTION 'BESKT_OPEN_VERSION_EXISTS: this method already has a version in draft or review.'\n      USING ERRCODE = 'check_violation';\n  END IF;",
    replace:
      "  IF EXISTS (SELECT 1 FROM public.beskt_method_versions v\n              WHERE v.pack_id = _pack_id AND v.content_status IN ('draft', 'in_review')) THEN\n    RAISE EXCEPTION 'BESKT_OPEN_VERSION_EXISTS: this method already has a version in draft or review.'\n      USING ERRCODE = 'check_violation';\n  END IF;\n\n  PERFORM pg_advisory_xact_lock(hashtextextended('beskt_method:' || _pack_id::text, 0));",
    guard: GUARD,
    expect: "BESKT-DB-ONE-OPEN-VERSION",
  },
  {
    id: "BESKT-NC-DB-ONE-OPEN-INDEX",
    defect: "the one-open-version index is no longer unique",
    file: MIG,
    find: "CREATE UNIQUE INDEX beskt_method_versions_one_open_idx",
    replace: "CREATE INDEX beskt_method_versions_one_open_idx",
    guard: GUARD,
    expect: "BESKT-DB-ONE-OPEN-VERSION",
  },
  {
    id: "BESKT-NC-DB-RACE-NOT-WAITED",
    defect: "db-test.sh no longer requires the second session to have waited on the lock",
    file: DB,
    find: '  if [ "$BGR_B_MS" -lt 1500 ]; then',
    replace: '  if [ "$BGR_B_MS" -lt 0 ]; then',
    guard: GUARD,
    expect: "BESKT-DB-ONE-OPEN-VERSION",
  },
  {
    id: "BESKT-NC-DB-RACE-NOT-REFUSED",
    defect: "db-test.sh no longer requires the second session to be refused",
    file: DB,
    find: '  if [ -n "$BGR_ID_B" ] || ! grep -q "BESKT_OPEN_VERSION_EXISTS" /tmp/bgr_b.out; then',
    replace: '  if [ -n "$BGR_ID_B" ] && ! grep -q "VID=" /tmp/bgr_b.out; then',
    guard: GUARD,
    expect: "BESKT-DB-ONE-OPEN-VERSION",
  },
  // ---- correction 8: no cross-coupling between exposure profiles -----------------
  {
    id: "BESKT-NC-DB-CROSS-PROFILE-PROMPT",
    defect: "a prompt may probe an item of another exposure profile",
    file: MIG,
    find: "      IF _item_profile IS DISTINCT FROM NEW.exposure_profile_id THEN\n        RAISE EXCEPTION 'BESKT_CROSS_PROFILE_REFERENCE: a prompt",
    replace:
      "      IF false THEN\n        RAISE EXCEPTION 'BESKT_CROSS_PROFILE_REFERENCE: a prompt",
    guard: GUARD,
    expect: "BESKT-DB-CROSS-PROFILE",
  },
  {
    id: "BESKT-NC-DB-CROSS-PROFILE-ROUTE",
    defect: "a routing rule may connect items of two exposure profiles",
    file: MIG,
    find: "    IF _src.exposure_profile_id IS DISTINCT FROM _tgt.exposure_profile_id THEN\n      RAISE EXCEPTION 'BESKT_CROSS_PROFILE_REFERENCE: a routing rule",
    replace:
      "    IF false THEN\n      RAISE EXCEPTION 'BESKT_CROSS_PROFILE_REFERENCE: a routing rule",
    guard: GUARD,
    expect: "BESKT-DB-CROSS-PROFILE",
  },
  {
    id: "BESKT-NC-DB-CROSS-PROFILE-VALIDATOR",
    defect: "a forced cross-profile route no longer blocks publication",
    file: MIG,
    find: "    SELECT 'ROUTE_CROSS_PROFILE', 'blocking',",
    replace: "    SELECT 'ROUTE_CROSS_PROFILE', 'advisory',",
    guard: GUARD,
    expect: "BESKT-DB-CROSS-PROFILE",
  },
  {
    id: "BESKT-NC-DB-CROSS-PROFILE-RESOLVER",
    defect:
      "a forced cross-profile show rule hides its target from its own profile's unconditional set",
    file: MIG,
    find: "          AND r.target_item_id = i.id AND r.action = 'show'\n          AND si.exposure_profile_id = _exposure_profile_id\n",
    replace: "          AND r.target_item_id = i.id AND r.action = 'show'\n",
    guard: GUARD,
    expect: "BESKT-DB-CROSS-PROFILE",
  },
  {
    id: "BESKT-NC-DB-CROSS-PROFILE-RESOLVER-FIRES",
    defect: "the resolver fires a rule whose source lies in another profile",
    file: MIG,
    find: "    IF _r.source_profile <> _exposure_profile_id OR _r.target_profile <> _exposure_profile_id\n       OR NOT _r.target_permitted THEN",
    replace:
      "    IF _r.target_profile <> _exposure_profile_id\n       OR NOT _r.target_permitted THEN",
    guard: GUARD,
    expect: "BESKT-DB-CROSS-PROFILE",
  },
  // ---- correction 9: PEACE Evaluation, interviewer-oriented, no score -----------
  {
    id: "BESKT-NC-DB-EVALUATION-CANDIDATE",
    defect: "an evaluation prompt may be addressed to the candidate",
    file: MIG,
    find: "    CHECK ((peace_stage IN ('planning', 'evaluation')) = (addressee = 'interviewer')),",
    replace: "    CHECK ((peace_stage IN ('planning')) = (addressee = 'interviewer')),",
    guard: GUARD,
    expect: "BESKT-DB-PEACE-EVALUATION",
  },
  {
    id: "BESKT-NC-DB-EVALUATION-NOT-REQUIRED",
    defect: "the interviewer self-review step is no longer required by the validator",
    file: MIG,
    find: "    'closure_next_step', 'interviewer_self_review'];",
    replace: "    'closure_next_step'];",
    guard: GUARD,
    expect: "BESKT-DB-PEACE-EVALUATION",
  },
  {
    id: "BESKT-NC-DB-EVALUATION-STAGE",
    defect: "the self-review prompt kind is bound to closure instead of evaluation",
    file: MIG,
    find: "    WHEN 'interviewer_self_review'      THEN 'evaluation'",
    replace: "    WHEN 'interviewer_self_review'      THEN 'closure'",
    guard: GUARD,
    expect: "BESKT-DB-PEACE-EVALUATION",
  },
  // ---- correction 10: rollback and suite hygiene --------------------------------
  {
    id: "BESKT-NC-DB-ROLLBACK-CASCADE",
    defect: "the rollback drops the version table with CASCADE",
    file: RB,
    find: "DROP TABLE IF EXISTS public.beskt_method_versions;",
    replace: "DROP TABLE IF EXISTS public.beskt_method_versions CASCADE;",
    guard: GUARD,
    expect: "BESKT-DB-ROLLBACK",
  },
  {
    id: "BESKT-NC-DB-ROLLBACK-ORDER",
    defect: "the rollback drops the version table before its children",
    file: RB,
    find: "DROP TABLE IF EXISTS public.beskt_method_events;\nDROP TABLE IF EXISTS public.beskt_method_reviews;\n",
    replace:
      "DROP TABLE IF EXISTS public.beskt_method_versions;\nDROP TABLE IF EXISTS public.beskt_method_events;\nDROP TABLE IF EXISTS public.beskt_method_reviews;\n",
    guard: GUARD,
    expect: "BESKT-DB-ROLLBACK",
  },
  {
    id: "BESKT-NC-DB-ROLLBACK-NO-DEPENDENCY-CHECK",
    defect: "the rollback no longer refuses when outside catalogue objects depend on the domain",
    file: RB,
    find: "    RAISE EXCEPTION 'BESKT_ROLLBACK BLOCKED: catalogue objects outside the domain depend on it (%). A CASCADE would remove them silently; reconcile first.', _offender;",
    replace: "    RAISE NOTICE 'dependencies ignored (%)', _offender;",
    guard: GUARD,
    expect: "BESKT-DB-ROLLBACK",
  },
  {
    id: "BESKT-NC-DB-ROLLBACK-SUITE-CASCADE",
    defect: "the documented rollback procedure drops a BESKT table with CASCADE again",
    file: RB_SUITE,
    find: "DROP TABLE IF EXISTS public.beskt_governance_grants;",
    replace: "DROP TABLE IF EXISTS public.beskt_governance_grants CASCADE;",
    guard: GUARD,
    expect: "BESKT-DB-SUITE",
  },
  {
    id: "BESKT-NC-DB-SUITE-COUNTS-ECHO",
    defect: "the suite's closing echo is counted as an assertion again",
    file: SUITE,
    find: "\\echo '    BESKT governed-content assertions passed'",
    replace: "\\echo '    ok  BESKT governed-content assertions passed'",
    guard: GUARD,
    expect: "BESKT-DB-SUITE",
  },
  {
    id: "BESKT-NC-DB-SUITE-CYCLE-TEST",
    defect: "the review-cycle behaviour test is removed from the suite",
    file: SUITE,
    find: "'B3.30c publication is refused: five approvals at the identical hash from the ended cycle do not carry over'",
    replace:
      "'B3.30x publication is refused: five approvals at the identical hash from the ended cycle do not carry over'",
    guard: GUARD,
    expect: "BESKT-DB-SUITE",
  },

  // ---- review 2, blocker 1: governance helpers are internal -----------------------
  {
    id: "BESKT-NC-DB-HOLDS-GRANT-EXECUTABLE",
    defect: "any signed-in user can ask who holds which gate",
    file: MIG,
    find: "GRANT EXECUTE ON FUNCTION public.beskt_holds_grant(uuid, text) TO service_role;",
    replace:
      "GRANT EXECUTE ON FUNCTION public.beskt_holds_grant(uuid, text) TO authenticated, service_role;",
    guard: GUARD,
    expect: "BESKT-DB-ANON-EXECUTE",
  },
  {
    id: "BESKT-NC-DB-ACCESS-CLASSES-EXECUTABLE",
    defect: "any signed-in user can read another user's access classes",
    file: MIG,
    find: "GRANT EXECUTE ON FUNCTION public.beskt_reader_access_classes(uuid) TO service_role;",
    replace:
      "GRANT EXECUTE ON FUNCTION public.beskt_reader_access_classes(uuid) TO authenticated, service_role;",
    guard: GUARD,
    expect: "BESKT-DB-ANON-EXECUTE",
  },
  // ---- review 2, blocker 2: no direct grant writes, service_role included ----------
  {
    id: "BESKT-NC-DB-GRANT-DIRECT-INSERT",
    defect: "a fabricated grant can be inserted directly",
    file: MIG,
    find: "  IF TG_OP = 'INSERT' AND NOT _governed THEN\n    RAISE EXCEPTION 'BESKT_GRANT_UNGOVERNED_WRITE",
    replace: "  IF false THEN\n    RAISE EXCEPTION 'BESKT_GRANT_UNGOVERNED_WRITE",
    guard: GUARD,
    expect: "BESKT-DB-GATE-GRANTS",
  },
  {
    id: "BESKT-NC-DB-GRANT-DIRECT-REVOCATION",
    defect: "the first revocation can be written outside beskt_revoke_governance",
    file: MIG,
    find: "  IF NOT _governed THEN\n    RAISE EXCEPTION 'BESKT_GRANT_UNGOVERNED_WRITE: a governance grant is revoked only",
    replace:
      "  IF false THEN\n    RAISE EXCEPTION 'BESKT_GRANT_UNGOVERNED_WRITE: a governance grant is revoked only",
    guard: GUARD,
    expect: "BESKT-DB-GATE-GRANTS",
  },
  {
    id: "BESKT-NC-DB-GRANT-TRIGGER-NO-INSERT",
    defect: "the grant guard no longer fires on INSERT",
    file: MIG,
    find: "CREATE TRIGGER beskt_governance_grants_append_only\n  BEFORE INSERT OR UPDATE OR DELETE ON public.beskt_governance_grants",
    replace:
      "CREATE TRIGGER beskt_governance_grants_append_only\n  BEFORE UPDATE OR DELETE ON public.beskt_governance_grants",
    guard: GUARD,
    expect: "BESKT-DB-GATE-GRANTS",
  },
  {
    id: "BESKT-NC-DB-GRANT-MARKER-LEFT-ON",
    defect: "the grant RPC leaves the governed marker on after its write",
    file: MIG,
    find: "  RETURNING id INTO _id;\n  PERFORM set_config('beskt.governance_grant_write', 'off', true);",
    replace: "  RETURNING id INTO _id;",
    guard: GUARD,
    expect: "BESKT-DB-GATE-GRANTS",
  },
  // ---- review 2, blocker 3: child writes serialise against publication -----------
  {
    id: "BESKT-NC-DB-CHILD-NO-LOCK",
    defect: "the child guard reads the owning version's status without locking it",
    file: MIG,
    find: "    PERFORM 1 FROM public.beskt_method_versions v WHERE v.id = _lock_id FOR SHARE;",
    replace: "    PERFORM 1 FROM public.beskt_method_versions v WHERE v.id = _lock_id;",
    guard: GUARD,
    expect: "BESKT-DB-CHILD-LOCK",
  },
  {
    id: "BESKT-NC-DB-CHILD-RACE-NOT-WAITED",
    defect: "db-test.sh no longer requires publication to have waited on the child's lock",
    file: DB,
    find: '  if [ "$BGP_B_MS" -lt 1500 ]; then # (A) publication waited',
    replace: '  if [ "$BGP_B_MS" -lt 0 ]; then # (A) publication waited',
    guard: GUARD,
    expect: "BESKT-DB-CHILD-LOCK",
  },
  {
    id: "BESKT-NC-DB-CHILD-RACE-BYTES",
    defect: "db-test.sh no longer requires the published bytes to hash to the approved hash",
    file: DB,
    find: '  if [ "$BGP_STATUS" != "published ${BGP_HASH} true" ] || [ "$BGP_LATE" != "0" ]; then',
    replace: '  if [ "$BGP_LATE" != "0" ]; then',
    guard: GUARD,
    expect: "BESKT-DB-CHILD-LOCK",
  },
  // ---- review 2, blocker 4: a method has many versions ----------------------------
  {
    id: "BESKT-NC-DB-PACK-ID-UNIQUE",
    defect: "pack_id alone is unique again (a partial index PostgREST reads as one-to-one)",
    file: MIG,
    find: "  ON public.beskt_method_versions (pack_id, open_slot);",
    replace:
      "  ON public.beskt_method_versions (pack_id) WHERE content_status IN ('draft', 'in_review');",
    guard: GUARD,
    expect: "BESKT-DB-ONE-OPEN-VERSION",
  },
  {
    id: "BESKT-NC-DB-TYPES-ONE-TO-ONE",
    defect: "the generated types declare a method's versions as one-to-one",
    file: TYPES,
    find: '            foreignKeyName: "beskt_method_versions_pack_id_fkey"\n            columns: ["pack_id"]\n            isOneToOne: false',
    replace:
      '            foreignKeyName: "beskt_method_versions_pack_id_fkey"\n            columns: ["pack_id"]\n            isOneToOne: true',
    guard: GUARD,
    expect: "BESKT-DB-TYPES",
  },
  // ---- review 2, blocker 5: no scoring through content ---------------------------
  {
    id: "BESKT-NC-DB-SCORING-ITEM-ADVISORY",
    defect: "a scoring instruction in an item no longer blocks publication",
    file: MIG,
    find: "    SELECT 'ITEM_INSTRUCTS_SCORING', 'blocking',",
    replace: "    SELECT 'ITEM_INSTRUCTS_SCORING', 'advisory',",
    guard: GUARD,
    expect: "BESKT-DB-NO-SCORING",
  },
  {
    id: "BESKT-NC-DB-SCORING-PROMPT-ADVISORY",
    defect: "a scoring instruction in a prompt no longer blocks publication",
    file: MIG,
    find: "    SELECT 'PROMPT_INSTRUCTS_SCORING', 'blocking',",
    replace: "    SELECT 'PROMPT_INSTRUCTS_SCORING', 'advisory',",
    guard: GUARD,
    expect: "BESKT-DB-NO-SCORING",
  },
  {
    id: "BESKT-NC-DB-SCORING-ANCHOR-ADVISORY",
    defect: "a scoring instruction in an anchor no longer blocks publication",
    file: MIG,
    find: "    SELECT 'ANCHOR_INSTRUCTS_SCORING', 'blocking',",
    replace: "    SELECT 'ANCHOR_INSTRUCTS_SCORING', 'advisory',",
    guard: GUARD,
    expect: "BESKT-DB-NO-SCORING",
  },
  {
    id: "BESKT-NC-DB-SCORING-NO-SWEDISH",
    defect: "the detector no longer reads Swedish rating, points or ranking instructions",
    file: MIG,
    find: "'\\m(betyg|betygsätt\\w*|betygsatt\\w*|poäng\\w*|gradera\\w*|graderas|ranka\\w*|rankad\\w*|rangordn\\w*|lämplighet\\w*",
    replace: "'\\m(lämplighet\\w*",
    guard: GUARD,
    expect: "BESKT-DB-NO-SCORING",
  },
  {
    id: "BESKT-NC-DB-SCORING-NO-SUITABILITY",
    defect: "the detector no longer reads suitability or verdict instructions",
    file: MIG,
    find: "|suitability|suitable|unsuitable|verdict|",
    replace: "|",
    guard: GUARD,
    expect: "BESKT-DB-NO-SCORING",
  },
  // ---- review 2, blocker 6: routing reads shown sources and moves forward ---------
  {
    id: "BESKT-NC-DB-ROUTING-HIDDEN-SOURCE",
    defect: "a rule fires on an answer for a hidden or skipped source",
    file: MIG,
    find: "    IF NOT (_r.source_item_id = ANY (_shown)) THEN\n      CONTINUE;\n    END IF;\n",
    replace: "",
    guard: GUARD,
    expect: "BESKT-DB-ROUTING",
  },
  {
    id: "BESKT-NC-DB-ROUTING-BACKWARD-GUARD",
    defect: "a rule may target an item before its source at write time",
    file: MIG,
    find: "    IF (_tgt.section_order, _tgt.display_order, _tgt.item_key)\n       <= (_src.section_order, _src.display_order, _src.item_key) THEN\n      RAISE EXCEPTION 'BESKT_ROUTE_BACKWARD",
    replace: "    IF false THEN\n      RAISE EXCEPTION 'BESKT_ROUTE_BACKWARD",
    guard: GUARD,
    expect: "BESKT-DB-ROUTING",
  },
  {
    id: "BESKT-NC-DB-ROUTING-BACKWARD-VALIDATOR",
    defect: "a forced backward edge no longer blocks publication",
    file: MIG,
    find: "    SELECT 'ROUTE_TARGET_BEFORE_SOURCE', 'blocking',",
    replace: "    SELECT 'ROUTE_TARGET_BEFORE_SOURCE', 'advisory',",
    guard: GUARD,
    expect: "BESKT-DB-ROUTING",
  },
  // ---- review 2: rollback refuses row-type dependencies before dropping ----------
  {
    id: "BESKT-NC-DB-ROLLBACK-ROWTYPE-IGNORED",
    defect: "the rollback no longer refuses a function whose signature names a BESKT row type",
    file: RB,
    find: "    RAISE EXCEPTION 'BESKT_ROLLBACK BLOCKED: objects outside the domain depend on a BESKT row type (%). Reconcile first.', _offender;",
    replace: "    RAISE NOTICE 'row-type dependencies ignored (%)', _offender;",
    guard: GUARD,
    expect: "BESKT-DB-ROLLBACK",
  },
  {
    id: "BESKT-NC-DB-ROLLBACK-NOT-ONE-TRANSACTION",
    defect:
      "db-test.sh applies the rollback statement by statement, so a refusal could leave it half-dropped",
    file: DB,
    find: 'BG_RB="$(psql -1 -v ON_ERROR_STOP=1 -d "$TEST_DB" \\',
    replace: 'BG_RB="$(psql -v ON_ERROR_STOP=1 -d "$TEST_DB" \\',
    guard: GUARD,
    expect: "BESKT-DB-ROLLBACK",
  },
  {
    id: "BESKT-NC-DB-ROLLBACK-DEPENDENCY-NOT-PLANTED",
    defect: "db-test.sh no longer requires the refused rollback to have dropped nothing",
    file: DB,
    find: '  if [ "$BGD_AFTER" != "$BGD_BEFORE" ] || [ "$BGD_SHAPE_OK" -ne 1 ]; then',
    replace: '  if [ "$BGD_SHAPE_OK" -ne 1 ]; then',
    guard: GUARD,
    expect: "BESKT-DB-ROLLBACK",
  },
  {
    id: "BESKT-NC-DB-SUITE-NO-FIXTURE",
    defect: "the suite stops sharing the fixture the races are planted from",
    file: SUITE,
    find: "\\ir beskt_governed_content_fixture.sql",
    replace: "\\ir beskt_governed_content_fixture_v1.sql",
    guard: GUARD,
    expect: "BESKT-DB-SUITE",
  },
];

runControls("beskt-governed-content", MUTATIONS);
