import { runControls, type Mutation } from "./runner";

const guard = "passport-social-image:check";
const DRAWING = "src/components/security-passport/social/SocialCardSvg.tsx";
const MODEL = "src/lib/security-passport/social.ts";
const CHANNELS = "src/lib/security-passport/share-channels.ts";
const mutations: readonly Mutation[] = [
  {
    id: "SOCIAL-QR-WITHOUT-LINK",
    defect: "the image draws the QR code it was handed even when the holder chose no link",
    file: DRAWING,
    find: "const qr = link ? p.qrDataUrl : null;",
    replace: "const qr = p.qrDataUrl;",
    guard,
    expect: "no link and no QR code when the model carries none",
  },
  {
    id: "SOCIAL-RAISED-TO-VERIFIED",
    defect: "every shield on the image is drawn as verified, whatever the credential's standing",
    file: DRAWING,
    find: "<ShieldMark state={c.state} size={r(shield)} />",
    replace: '<ShieldMark state="verified" size={r(shield)} />',
    guard,
    expect: "each shield wears its own state",
  },
  {
    id: "SOCIAL-HISTORY-PUBLISHED",
    defect: "an expired credential is drawn on the image that cannot be recalled",
    file: MODEL,
    find: 'return credential.lifecycle === "active";',
    replace: "return credential.lifecycle.length > 0;",
    guard,
    expect: "a credential that is no longer current is never drawn",
  },
  {
    id: "SOCIAL-NO-SNAPSHOT-LINE",
    defect: "an image without a link no longer says it is a snapshot",
    file: "src/lib/security-passport/share-image.ts",
    find: 'snapshotNote: pt("social.snapshotNote"),',
    replace: 'snapshotNote: "",',
    guard,
    expect: "an image without a link says it is a snapshot",
  },
  {
    id: "SOCIAL-SELECTION-CUT",
    defect: "the image quietly keeps the first three of the holder's selection and drops the rest",
    file: MODEL,
    find: "  const drawn = credentials.filter(isSocialPublishable).map((c) => ({",
    replace: "  const drawn = credentials.filter(isSocialPublishable).slice(0, 3).map((c) => ({",
    guard,
    expect: "every selected credential that is current is drawn, in the order given: none is cut",
  },
  {
    id: "SOCIAL-IMAGE-OVERFULL",
    defect: "a selection of more than three is crammed onto one image instead of a set",
    file: MODEL,
    find: "  if (count === 1) return [{ ...model, page: null }];",
    replace: "  if (count >= 1) return [{ ...model, page: null }];",
    guard,
    expect: "more than one image holds becomes a set, three to an image",
  },
  {
    id: "SOCIAL-SET-UNMARKED",
    defect: "an image of a set no longer says which of the set it is",
    file: DRAWING,
    find: "        ? `${p.strings.brand.toUpperCase()} · ${page.index} / ${page.count}`\n",
    replace: "        ? p.strings.brand.toUpperCase()\n",
    guard,
    expect: "says it is image 1 of 3",
  },
  {
    id: "SOCIAL-PRIVATE-ON-IMAGE",
    defect: "the issuer a credential was stated with is printed on the public image",
    file: MODEL,
    find: "    nameSv: c.title,\n    nameEn: c.title,",
    replace: '    nameSv: `${c.title} ${c.issuer ?? ""}`,\n    nameEn: c.title,',
    guard,
    expect: "none of it is drawn",
  },
  {
    id: "SOCIAL-PLATFORM-CLAIMS-ATTACHED",
    defect: "a platform button tells the holder the image went along when only a page was opened",
    file: CHANNELS,
    find: '          ? "social.ready.postMany"\n          : "social.ready.post",',
    replace: '          ? "social.device.doneMany"\n          : "social.device.done",',
    guard,
    expect: "never claims the image went along; says to add it",
  },
  {
    id: "SOCIAL-DEVICE-SHARE-WITHOUT-FILES",
    defect: "the device share sheet is given the sentence but not the image files",
    file: CHANNELS,
    find: "    files: [...files],",
    replace: "    files: [],",
    guard,
    expect: "the device share is handed the image files themselves",
  },
  {
    id: "SOCIAL-LINK-IMPLICIT",
    defect: "downloading the image quietly creates a public link as well",
    file: "src/components/security-passport/live/SocialShareFlow.tsx",
    find: "  function download() {\n    if (!files) return;",
    replace: "  function download() {\n    link.onCreate();\n    if (!files) return;",
    guard,
    expect: "the social flow creates a link from one place",
  },
  {
    id: "SOCIAL-NAME-OVERFLOW",
    defect: "a holder's long name runs past the edge of the card instead of being drawn smaller",
    file: DRAWING,
    find: "  const nameSize = Math.min(fullName, headW / (widestName * BOLD_CHAR_EM));",
    replace: "  const nameSize = fullName;",
    guard,
    expect: "the holder's long name stays inside the card",
  },
  {
    id: "SOCIAL-CREDENTIAL-NAME-OVERFLOW",
    defect: "one long word in a credential's name runs into the next column",
    file: DRAWING,
    find: "        if (line.length * 21 * u * 0.58 > slotW - 16 * u) columnsFit = false;\n",
    replace: "",
    guard,
    expect: "every line of a credential's name stays inside its own column",
  },
  {
    id: "SOCIAL-WORD-OVERFLOW",
    defect: "a long trust word runs into the next column instead of the card being drawn smaller",
    file: DRAWING,
    find: "      if (word.length * (17 * u * 0.72 + 2.4 * u) > slotW - 16 * u) columnsFit = false;\n",
    replace: "",
    guard,
    expect: "every trust word stays inside its own column",
  },
  {
    id: "SOCIAL-PLACE-OVERFLOW",
    defect: "a long place name runs into the next column instead of the card being drawn smaller",
    file: DRAWING,
    find: "        if (markW + 8 * u + labelW > slotW - 16 * u) columnsFit = false;\n",
    replace: "",
    guard,
    expect: "every place stays inside its own column",
  },
];

runControls("social-image", mutations);
