import { chromium, expect } from "@playwright/test";
const build = await Bun.build({ entrypoints: [".temp/strict-note-probe.tsx"], target: "browser", define: { "process.env.NODE_ENV": '"development"' } });
if (!build.success) throw Error("LOCAL_PROBE_BUILD_FAILED");
const browser = await chromium.launch({ headless: true });
try {
  const page = await browser.newPage();
  await page.route("**/*", route => route.abort());
  await page.setContent('<div id="old"></div><div id="new"></div><div id="cases"></div>');
  await page.addScriptTag({ content: await build.outputs[0].text() });
  await page.waitForFunction(() => (window as any).__noteProbe.oldWrites.length > 0);
  await expect(page.locator("#old-note")).toHaveValue("Synthetic saved Q8");
  await expect(page.locator("#new-note")).toHaveValue("Synthetic saved Q8");
  expect(await page.evaluate(() => (window as any).__noteProbe.oldWrites)).toEqual([""]);
  expect(await page.evaluate(() => (window as any).__noteProbe.newWrites)).toEqual([]);
  await page.evaluate(() => (window as any).__noteProbe.newRoot.unmount());
  expect(await page.evaluate(() => (window as any).__noteProbe.newWrites)).toEqual([]);
  await page.evaluate(() => (window as any).__noteProbe.mountNew());
  await page.locator("#new-note").fill("");
  await page.evaluate(() => (window as any).__noteProbe.newRoot.unmount());
  expect(await page.evaluate(() => (window as any).__noteProbe.newWrites)).toEqual([""]);
  await page.evaluate(() => { (window as any).__noteProbe.newWrites = []; (window as any).__noteProbe.mountNew(); });
  await page.locator("#new-note").fill("Synthetic Q8 human edit");
  await page.locator("#other-question").click();
  await expect(page.locator("#new-note")).toHaveValue("Synthetic saved Q7");
  await page.evaluate(() => (window as any).__noteProbe.newRoot.unmount());
  expect(await page.evaluate(() => (window as any).__noteProbe.newWrites)).toEqual([]);
  await expect(page.locator("#case-note")).toHaveValue("Synthetic case A stored");
  const caseA = await page.locator("#case-instance").innerText();
  await page.locator("#case-note").fill("Synthetic case A human draft");
  await page.evaluate(async () => { await (window as any).__noteProbe.caseRouter.preloadRoute({ to: "/case/$caseId", params: { caseId: "B" } }); });
  await page.evaluate(async () => { await (window as any).__noteProbe.caseRouter.navigate({ to: "/case/$caseId", params: { caseId: "B" } }); });
  await expect(page.locator("#case-note")).toHaveValue("Synthetic case B stored");
  await expect(page.locator("#case-known")).toHaveText("B-note-id");
  const caseB = await page.locator("#case-instance").innerText();
  expect(caseB).not.toBe(caseA);
  await page.locator("#case-note").fill("Synthetic case B human draft");
  await page.evaluate(async () => { await (window as any).__noteProbe.caseRouter.navigate({ to: "/case/$caseId", params: { caseId: "B" }, search: { question: "shared-Q2" } }); });
  await expect(page.locator("#case-note")).toHaveValue("Synthetic case B human draft");
  await expect(page.locator("#case-instance")).toHaveText(caseB);
  const evidence = { kind: "isolated_chromium_react19_development_strictmode_causal_probe", actualAuthOrStorage: false, checks: { oldInitialBlankCleanupReproduced: true, newInitialReplayAndUnmountNoWrite: true, explicitHumanClearStillWritten: true, priorQuestionDraftNeverWrittenIntoNewTarget: true, cachedCaseSwitchRemountsDraftAndObservedNoteId: true, withinCaseQuestionSearchKeepsCoordinator: true } };
  await Bun.write(".temp/strict-note-probe-evidence.json", JSON.stringify(evidence, null, 2) + "\n");
  console.log(JSON.stringify(evidence));
} finally { await browser.close(); }
