// Authentication target lock.
//
// ── THE REGRESSION THIS GUARDS ─────────────────────────────────────────
//
// backend-target-lock-check.ts proves that the DATA plane names the owner
// Supabase project. Nothing proved the same about the AUTH plane, and that gap
// is exactly how Google sign-in broke in the 2026-08-29 cutover.
//
// Email/password went through the shared Supabase client, so it followed
// VITE_SUPABASE_URL to the owner project and kept working. Google did not: it
// called `lovable.auth.signInWithOAuth()` from @lovable.dev/cloud-auth-js,
// which posts to the same-origin Lovable hosting endpoint `/~oauth/initiate`.
// That endpoint stamps in the Lovable Cloud project id and hands off to
// oauth.lovable.app, which resolves its provider configuration from the Lovable
// Cloud backend — the project that was disconnected in the cutover. Every
// attempt came back with
//
//   #error=invalid_request&error_description=provider 'google' is not supported
//
// before Google ever opened. The user was bounced to an authenticated route
// with no session, the guard sent them back to the login page, the hash was
// dropped, and the button looked like it did nothing.
//
// The invariant: EVERY interactive sign-in in this application resolves through
// the one shared Supabase client, so authentication and data always name the
// same project and one person keeps one identity. A provider reached through a
// hosting-platform broker is, by construction, pointed at whatever backend that
// platform is connected to — which is not something this repository controls.
//
// Plain TS script matching this repository's scripts/*-check.ts convention (no
// JS/TS unit-test runner is configured here). Credential-free, no network
// access. Run via `bun run auth-provider-target:check`.

import { readFileSync, readdirSync, existsSync } from "node:fs";
import path from "node:path";

const errors: string[] = [];
function expect(condition: boolean, message: string): void {
  if (!condition) errors.push(message);
}

const root = path.resolve(import.meta.dir, "..");
const srcRoot = path.join(root, "src");

/** Every .ts/.tsx file under src/, so a new sign-in path cannot be added in a
 *  file this guard did not know to look at. */
function sourceFiles(dir: string): string[] {
  const out: string[] = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      out.push(...sourceFiles(full));
    } else if (/\.tsx?$/.test(entry.name)) {
      out.push(full);
    }
  }
  return out;
}

const files = sourceFiles(srcRoot);
const rel = (f: string) => path.relative(root, f);

// The Lovable-generated broker module itself. It is marked "auto-generated by
// Lovable. Do not modify it", so it is left on disk rather than deleted and
// re-created on the next sync. It is inert while nothing imports it, and rule 1
// below is what enforces that — so the module is exempt from the rules that
// describe how a *sign-in path* must be written, and from nothing else.
const GENERATED_BROKER_MODULE = "src/integrations/lovable/index.ts";
const isGeneratedBroker = (f: string) => rel(f) === GENERATED_BROKER_MODULE;

// -----------------------------------------------------------------------
// 1. Nothing in the application imports the Lovable Cloud auth broker.
//
//    The module is left on disk because Lovable generates it, but importing it
//    re-points sign-in at the disconnected Lovable Cloud backend.
// -----------------------------------------------------------------------
for (const file of files) {
  const source = readFileSync(file, "utf8");
  // The import ban applies to every file without exception, including the
  // generated module itself: nothing may pull the broker into the app.
  expect(
    !/from\s+["'](@\/integrations\/lovable|\.\.?\/[^"']*integrations\/lovable)["']/.test(source),
    `${rel(file)} imports the Lovable Cloud auth broker. Sign-in must go through @/integrations/supabase/client so authentication names the same project as the data (see docs — 2026-08-29 cutover).`,
  );
  if (isGeneratedBroker(file)) continue;
  expect(
    !source.includes("@lovable.dev/cloud-auth-js"),
    `${rel(file)} imports @lovable.dev/cloud-auth-js directly. Its OAuth broker resolves providers from the Lovable Cloud backend, which is no longer this application's backend.`,
  );
  expect(
    !source.includes("/~oauth/initiate"),
    `${rel(file)} references the Lovable hosting OAuth broker endpoint /~oauth/initiate. OAuth must go to the project's own Supabase Auth.`,
  );
}

// -----------------------------------------------------------------------
// 2. Every OAuth sign-in call is made on the shared Supabase client.
// -----------------------------------------------------------------------
const oauthCallers = files
  .filter((f) => !isGeneratedBroker(f))
  .filter((f) => readFileSync(f, "utf8").includes("signInWithOAuth"));
expect(
  oauthCallers.length > 0,
  "no signInWithOAuth call found in src/ — the Google sign-in path has disappeared entirely",
);

for (const file of oauthCallers) {
  const source = readFileSync(file, "utf8");

  // The receiver of every signInWithOAuth call must be the shared client.
  for (const match of source.matchAll(/([A-Za-z_$][\w$.]*)\s*\.\s*signInWithOAuth\s*\(/g)) {
    expect(
      match[1] === "supabase.auth",
      `${rel(file)} calls ${match[1]}.signInWithOAuth(...). Every OAuth sign-in must be supabase.auth.signInWithOAuth(...) on the shared client from @/integrations/supabase/client.`,
    );
  }

  expect(
    source.includes('from "@/integrations/supabase/client"'),
    `${rel(file)} signs in with OAuth but does not import the shared Supabase client`,
  );

  // A second browser client would be a second project binding — the exact
  // workaround this regression must not be "fixed" with.
  expect(
    !source.includes("createClient("),
    `${rel(file)} constructs its own Supabase client. Sign-in must reuse the single shared client so one person keeps one identity.`,
  );
}

// -----------------------------------------------------------------------
// 3. The known Google entry points still offer Google, through Supabase.
//
//    Named explicitly so that "fixing" the failure by deleting the button is
//    caught rather than passing silently.
// -----------------------------------------------------------------------
const googleEntryPoints = [
  // The single front door (/login and /signup both render it). The four
  // audience-named routes are compatibility redirects and carry no Google
  // button of their own.
  "src/components/auth/UnifiedAuthForm.tsx",
  "src/routes/admin.login.tsx",
];
for (const relPath of googleEntryPoints) {
  const full = path.join(root, relPath);
  if (!existsSync(full)) {
    errors.push(`${relPath} is missing — it carries a Google sign-in entry point`);
    continue;
  }
  const source = readFileSync(full, "utf8");
  expect(
    source.includes("supabase.auth.signInWithOAuth"),
    `${relPath} must sign in with supabase.auth.signInWithOAuth(...)`,
  );
  expect(
    /provider:\s*"google"/.test(source),
    `${relPath} must still offer Google as a sign-in provider`,
  );
  // redirectTo is what brings the person back to where they were going; the
  // Lovable-broker call used redirect_uri, which Supabase Auth ignores.
  expect(
    /redirectTo:/.test(source),
    `${relPath} must pass options.redirectTo — Supabase Auth ignores redirect_uri, and without it the return lands on the Site URL`,
  );
  expect(
    !/redirect_uri:/.test(source),
    `${relPath} still passes redirect_uri, which is the Lovable broker's parameter name. Supabase Auth reads options.redirectTo.`,
  );
}

// -----------------------------------------------------------------------
// 4. The single shared client is the only thing binding the browser to a
//    project, and it reads that binding from the environment.
// -----------------------------------------------------------------------
const clientPath = path.join(root, "src/integrations/supabase/client.ts");
expect(existsSync(clientPath), "src/integrations/supabase/client.ts must exist");
if (existsSync(clientPath)) {
  const client = readFileSync(clientPath, "utf8");
  expect(
    client.includes("VITE_SUPABASE_URL"),
    "the shared client must resolve its project from VITE_SUPABASE_URL, never a hard-coded host",
  );
  expect(
    !/[a-z0-9]{20}\.supabase\.co/.test(client),
    "the shared client must not hard-code a Supabase project host",
  );
}

// -----------------------------------------------------------------------
// Report
// -----------------------------------------------------------------------
if (errors.length > 0) {
  console.error(`auth-provider-target:check FAILED (${errors.length} issue(s)):`);
  for (const e of errors) console.error(`  - ${e}`);
  process.exit(1);
}

console.log("auth-provider-target:check OK");
console.log(`  OAuth sign-in call sites: ${oauthCallers.length}`);
console.log("  all sign-in resolves through the shared Supabase client");
