/**
 * Guard: the /mcp endpoint must never become anonymous again.
 *
 * The Lovable MCP Vite plugin regenerates src/routes/mcp.ts on every build and
 * mounts the CQrityjob MCP server with no authentication at all. Its tools
 * expose the authored question bank, the dimension model, per-profession target
 * dimension profiles (the calibration matrix) and the matching engine.
 *
 * Lovable also writes into this working tree directly, so "we removed it once"
 * is not a durable state. This check makes a silent regeneration fail CI.
 *
 * Run: bun run mcp-exposure:check
 */

import { readFileSync } from "node:fs";

const failures: string[] = [];

/** Both files deliberately DISCUSS the plugin they must not register, so the
 *  code checks run against comment-stripped source. */
function stripComments(source: string): string {
  const blockComment = new RegExp("/\\*[\\s\\S]*?\\*/", "g");
  const lineComment = new RegExp("^\\s*//.*$", "gm");
  return source.replace(blockComment, "").replace(lineComment, "");
}

const viteConfig = stripComments(readFileSync("vite.config.ts", "utf8"));
if (/mcpPlugin\s*\(/.test(viteConfig) || /mcp-js\/stacks\/tanstack\/vite/.test(viteConfig)) {
  failures.push(
    "vite.config.ts registers the MCP generator plugin again.\n" +
      "      The plugin regenerates src/routes/mcp.ts WITHOUT authentication and refuses\n" +
      "      to coexist with a user-authored route. Remove it, or make an explicit owner\n" +
      "      decision to reopen an anonymous MCP endpoint.",
  );
}

const routeRaw = readFileSync("src/routes/mcp.ts", "utf8");
const route = stripComments(routeRaw);

// The generator's banner is itself a comment, so this one reads the raw file.
if (/AUTO-GENERATED by @lovable\.dev\/mcp-js/.test(routeRaw)) {
  failures.push(
    "src/routes/mcp.ts has been regenerated by the plugin (its banner is back).\n" +
      "      The generated route has no access control. Restore the owned, gated version.",
  );
}

if (!/CQRITYJOB_MCP_ENABLED/.test(route)) {
  failures.push(
    "src/routes/mcp.ts no longer reads CQRITYJOB_MCP_ENABLED.\n" +
      "      The endpoint must be closed unless explicitly enabled server-side.",
  );
}

if (/VITE_CQRITYJOB_MCP|VITE_MCP/.test(route)) {
  failures.push(
    "src/routes/mcp.ts gates on a VITE_ variable.\n" +
      "      VITE_ values are inlined into the client bundle, so a VITE_ token publishes\n" +
      "      the secret it is meant to protect. Use a server-side variable.",
  );
}

if (failures.length) {
  console.error(`FAIL: ${failures.length} MCP exposure violation(s)\n`);
  for (const f of failures) console.error(`  !!  ${f}\n`);
  process.exit(1);
}

console.log("OK: /mcp is closed by default and the generator plugin is not registered.");
