/**
 * Guard: no MCP route (/mcp or the SDK's side routes) may become anonymous again.
 *
 * The Lovable MCP Vite plugin regenerates src/routes/mcp.ts on every build and
 * mounts the CQrityjob MCP server with no authentication at all. Its tools
 * expose the authored question bank, the dimension model, per-profession target
 * dimension profiles (the calibration matrix) and the matching engine.
 *
 * Lovable also writes into this working tree directly, so "we removed it once"
 * is not a durable state. This check makes a silent regeneration fail CI.
 *
 * Run: bun run mcp-exposure:check
 */

import { readFileSync } from "node:fs";

const failures: string[] = [];

/** Both files deliberately DISCUSS the plugin they must not register, so the
 *  code checks run against comment-stripped source. */
function stripComments(source: string): string {
  const blockComment = new RegExp("/\\*[\\s\\S]*?\\*/", "g");
  const lineComment = new RegExp("^\\s*//.*$", "gm");
  return source.replace(blockComment, "").replace(lineComment, "");
}

const viteConfig = stripComments(readFileSync("vite.config.ts", "utf8"));
if (/mcpPlugin\s*\(/.test(viteConfig) || /mcp-js\/stacks\/tanstack\/vite/.test(viteConfig)) {
  failures.push(
    "vite.config.ts registers the MCP generator plugin again.\n" +
      "      The plugin regenerates src/routes/mcp.ts WITHOUT authentication and refuses\n" +
      "      to coexist with a user-authored route. Remove it, or make an explicit owner\n" +
      "      decision to reopen an anonymous MCP endpoint.",
  );
}

// Every route that mounts the MCP server — the endpoint AND the side routes
// the SDK adds — must be owned (no generator banner) and pass the shared gate.
// The side routes once answered anonymously while /mcp itself was closed.
const MCP_ROUTES = [
  "src/routes/mcp.ts",
  "src/routes/[.mcp]/list-tools.ts",
  "src/routes/[.mcp]/invoke-tool/$tool.ts",
  "src/routes/[.well-known]/oauth-protected-resource.ts",
];

for (const file of MCP_ROUTES) {
  const raw = readFileSync(file, "utf8");
  const code = stripComments(raw);
  // The generator's banner is itself a comment, so this one reads the raw file.
  if (/AUTO-GENERATED by @lovable\.dev\/mcp-js/.test(raw)) {
    failures.push(
      `${file} has been regenerated by the plugin (its banner is back).\n` +
        "      The generated route has no access control. Restore the owned, gated version.",
    );
  }
  if (!/mcpAccessDenied\(ctx\.request\)/.test(code) || !/if \(denied\) return denied;/.test(code)) {
    failures.push(
      `${file} does not refuse the request through mcpAccessDenied() before mounting the MCP handler.`,
    );
  }
  if (/VITE_CQRITYJOB_MCP|VITE_MCP/.test(code)) {
    failures.push(
      `${file} gates on a VITE_ variable.\n` +
        "      VITE_ values are inlined into the client bundle, so a VITE_ token publishes\n" +
        "      the secret it is meant to protect. Use a server-side variable.",
    );
  }
}

const gate = stripComments(readFileSync("src/lib/mcp/access.ts", "utf8"));
if (!/process\.env\.CQRITYJOB_MCP_ENABLED !== "true"\) return false/.test(gate)) {
  failures.push(
    'src/lib/mcp/access.ts no longer closes the server unless CQRITYJOB_MCP_ENABLED is "true".',
  );
}
if (
  !/CQRITYJOB_MCP_TOKEN/.test(gate) ||
  !/expected\.length < MIN_TOKEN_LENGTH\) return false/.test(gate)
) {
  failures.push(
    "src/lib/mcp/access.ts no longer requires a configured bearer token of minimum length.\n" +
      "      Enabled-without-a-token opens the tools to the internet.",
  );
}
if (/VITE_/.test(gate)) {
  failures.push(
    "src/lib/mcp/access.ts reads a VITE_ variable, which is inlined into the client bundle.",
  );
}

if (failures.length) {
  console.error(`FAIL: ${failures.length} MCP exposure violation(s)\n`);
  for (const f of failures) console.error(`  !!  ${f}\n`);
  process.exit(1);
}

console.log(
  "OK: /mcp and every MCP side route are closed by default behind one token gate, and the generator plugin is not registered.",
);
