/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SecurityCareerAssessmentRouteImport } from './routes/security-career-assessment'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as EmployersRouteImport } from './routes/employers'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as CareerCenterRouteImport } from './routes/career-center'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AssessmentRouteImport } from './routes/assessment'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JobsIndexRouteImport } from './routes/jobs.index'
import { Route as CareerCenterIndexRouteImport } from './routes/career-center.index'
import { Route as JobsSlugRouteImport } from './routes/jobs.$slug'
import { Route as DevCareerAssessmentCalibrationRouteImport } from './routes/dev.career-assessment-calibration'
import { Route as CareerCenterStartRouteImport } from './routes/career-center.start'
import { Route as CareerCenterProfessionRouteImport } from './routes/career-center.$profession'
import { Route as AuthenticatedMyCareerRouteImport } from './routes/_authenticated.my-career'
import { Route as AuthenticatedJourneyRouteImport } from './routes/_authenticated.journey'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AuthenticatedMyCareerIndexRouteImport } from './routes/_authenticated.my-career.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated.admin.index'
import { Route as JobsProfessionProfessionSlugRouteImport } from './routes/jobs.profession.$professionSlug'
import { Route as JobsFamilyFamilyIdRouteImport } from './routes/jobs.family.$familyId'
import { Route as AuthenticatedJourneyTargetIdRouteImport } from './routes/_authenticated.journey.$targetId'
import { Route as AuthenticatedAdminJobsRouteImport } from './routes/_authenticated.admin.jobs'
import { Route as AuthenticatedAdminEmployersRouteImport } from './routes/_authenticated.admin.employers'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as AuthenticatedAdminJobsIndexRouteImport } from './routes/_authenticated.admin.jobs.index'
import { Route as AuthenticatedMyCareerReportsRunIdRouteImport } from './routes/_authenticated.my-career.reports.$runId'
import { Route as AuthenticatedAdminJobsIdRouteImport } from './routes/_authenticated.admin.jobs.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityCareerAssessmentRoute =
  SecurityCareerAssessmentRouteImport.update({
    id: '/security-career-assessment',
    path: '/security-career-assessment',
    getParentRoute: () => rootRouteImport,
  } as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployersRoute = EmployersRouteImport.update({
  id: '/employers',
  path: '/employers',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerCenterRoute = CareerCenterRouteImport.update({
  id: '/career-center',
  path: '/career-center',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentRoute = AssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JobsRoute,
} as any)
const CareerCenterIndexRoute = CareerCenterIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CareerCenterRoute,
} as any)
const JobsSlugRoute = JobsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => JobsRoute,
} as any)
const DevCareerAssessmentCalibrationRoute =
  DevCareerAssessmentCalibrationRouteImport.update({
    id: '/dev/career-assessment-calibration',
    path: '/dev/career-assessment-calibration',
    getParentRoute: () => rootRouteImport,
  } as any)
const CareerCenterStartRoute = CareerCenterStartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => CareerCenterRoute,
} as any)
const CareerCenterProfessionRoute = CareerCenterProfessionRouteImport.update({
  id: '/$profession',
  path: '/$profession',
  getParentRoute: () => CareerCenterRoute,
} as any)
const AuthenticatedMyCareerRoute = AuthenticatedMyCareerRouteImport.update({
  id: '/my-career',
  path: '/my-career',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedJourneyRoute = AuthenticatedJourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedMyCareerIndexRoute =
  AuthenticatedMyCareerIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedMyCareerRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const JobsProfessionProfessionSlugRoute =
  JobsProfessionProfessionSlugRouteImport.update({
    id: '/profession/$professionSlug',
    path: '/profession/$professionSlug',
    getParentRoute: () => JobsRoute,
  } as any)
const JobsFamilyFamilyIdRoute = JobsFamilyFamilyIdRouteImport.update({
  id: '/family/$familyId',
  path: '/family/$familyId',
  getParentRoute: () => JobsRoute,
} as any)
const AuthenticatedJourneyTargetIdRoute =
  AuthenticatedJourneyTargetIdRouteImport.update({
    id: '/$targetId',
    path: '/$targetId',
    getParentRoute: () => AuthenticatedJourneyRoute,
  } as any)
const AuthenticatedAdminJobsRoute = AuthenticatedAdminJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminEmployersRoute =
  AuthenticatedAdminEmployersRouteImport.update({
    id: '/employers',
    path: '/employers',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminJobsIndexRoute =
  AuthenticatedAdminJobsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminJobsRoute,
  } as any)
const AuthenticatedMyCareerReportsRunIdRoute =
  AuthenticatedMyCareerReportsRunIdRouteImport.update({
    id: '/reports/$runId',
    path: '/reports/$runId',
    getParentRoute: () => AuthenticatedMyCareerRoute,
  } as any)
const AuthenticatedAdminJobsIdRoute =
  AuthenticatedAdminJobsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminJobsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/assessment': typeof AssessmentRoute
  '/auth': typeof AuthRoute
  '/career-center': typeof CareerCenterRouteWithChildren
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/employers': typeof EmployersRoute
  '/jobs': typeof JobsRouteWithChildren
  '/mcp': typeof McpRoute
  '/security-career-assessment': typeof SecurityCareerAssessmentRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/journey': typeof AuthenticatedJourneyRouteWithChildren
  '/my-career': typeof AuthenticatedMyCareerRouteWithChildren
  '/career-center/$profession': typeof CareerCenterProfessionRoute
  '/career-center/start': typeof CareerCenterStartRoute
  '/dev/career-assessment-calibration': typeof DevCareerAssessmentCalibrationRoute
  '/jobs/$slug': typeof JobsSlugRoute
  '/career-center/': typeof CareerCenterIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/employers': typeof AuthenticatedAdminEmployersRoute
  '/admin/jobs': typeof AuthenticatedAdminJobsRouteWithChildren
  '/journey/$targetId': typeof AuthenticatedJourneyTargetIdRoute
  '/jobs/family/$familyId': typeof JobsFamilyFamilyIdRoute
  '/jobs/profession/$professionSlug': typeof JobsProfessionProfessionSlugRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/my-career/': typeof AuthenticatedMyCareerIndexRoute
  '/admin/jobs/$id': typeof AuthenticatedAdminJobsIdRoute
  '/my-career/reports/$runId': typeof AuthenticatedMyCareerReportsRunIdRoute
  '/admin/jobs/': typeof AuthenticatedAdminJobsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/assessment': typeof AssessmentRoute
  '/auth': typeof AuthRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/employers': typeof EmployersRoute
  '/mcp': typeof McpRoute
  '/security-career-assessment': typeof SecurityCareerAssessmentRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/journey': typeof AuthenticatedJourneyRouteWithChildren
  '/career-center/$profession': typeof CareerCenterProfessionRoute
  '/career-center/start': typeof CareerCenterStartRoute
  '/dev/career-assessment-calibration': typeof DevCareerAssessmentCalibrationRoute
  '/jobs/$slug': typeof JobsSlugRoute
  '/career-center': typeof CareerCenterIndexRoute
  '/jobs': typeof JobsIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/employers': typeof AuthenticatedAdminEmployersRoute
  '/journey/$targetId': typeof AuthenticatedJourneyTargetIdRoute
  '/jobs/family/$familyId': typeof JobsFamilyFamilyIdRoute
  '/jobs/profession/$professionSlug': typeof JobsProfessionProfessionSlugRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/my-career': typeof AuthenticatedMyCareerIndexRoute
  '/admin/jobs/$id': typeof AuthenticatedAdminJobsIdRoute
  '/my-career/reports/$runId': typeof AuthenticatedMyCareerReportsRunIdRoute
  '/admin/jobs': typeof AuthenticatedAdminJobsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/assessment': typeof AssessmentRoute
  '/auth': typeof AuthRoute
  '/career-center': typeof CareerCenterRouteWithChildren
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/employers': typeof EmployersRoute
  '/jobs': typeof JobsRouteWithChildren
  '/mcp': typeof McpRoute
  '/security-career-assessment': typeof SecurityCareerAssessmentRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/journey': typeof AuthenticatedJourneyRouteWithChildren
  '/_authenticated/my-career': typeof AuthenticatedMyCareerRouteWithChildren
  '/career-center/$profession': typeof CareerCenterProfessionRoute
  '/career-center/start': typeof CareerCenterStartRoute
  '/dev/career-assessment-calibration': typeof DevCareerAssessmentCalibrationRoute
  '/jobs/$slug': typeof JobsSlugRoute
  '/career-center/': typeof CareerCenterIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/admin/employers': typeof AuthenticatedAdminEmployersRoute
  '/_authenticated/admin/jobs': typeof AuthenticatedAdminJobsRouteWithChildren
  '/_authenticated/journey/$targetId': typeof AuthenticatedJourneyTargetIdRoute
  '/jobs/family/$familyId': typeof JobsFamilyFamilyIdRoute
  '/jobs/profession/$professionSlug': typeof JobsProfessionProfessionSlugRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/my-career/': typeof AuthenticatedMyCareerIndexRoute
  '/_authenticated/admin/jobs/$id': typeof AuthenticatedAdminJobsIdRoute
  '/_authenticated/my-career/reports/$runId': typeof AuthenticatedMyCareerReportsRunIdRoute
  '/_authenticated/admin/jobs/': typeof AuthenticatedAdminJobsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/assessment'
    | '/auth'
    | '/career-center'
    | '/careers'
    | '/contact'
    | '/employers'
    | '/jobs'
    | '/mcp'
    | '/security-career-assessment'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin'
    | '/journey'
    | '/my-career'
    | '/career-center/$profession'
    | '/career-center/start'
    | '/dev/career-assessment-calibration'
    | '/jobs/$slug'
    | '/career-center/'
    | '/jobs/'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/employers'
    | '/admin/jobs'
    | '/journey/$targetId'
    | '/jobs/family/$familyId'
    | '/jobs/profession/$professionSlug'
    | '/admin/'
    | '/my-career/'
    | '/admin/jobs/$id'
    | '/my-career/reports/$runId'
    | '/admin/jobs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/assessment'
    | '/auth'
    | '/careers'
    | '/contact'
    | '/employers'
    | '/mcp'
    | '/security-career-assessment'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/journey'
    | '/career-center/$profession'
    | '/career-center/start'
    | '/dev/career-assessment-calibration'
    | '/jobs/$slug'
    | '/career-center'
    | '/jobs'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/employers'
    | '/journey/$targetId'
    | '/jobs/family/$familyId'
    | '/jobs/profession/$professionSlug'
    | '/admin'
    | '/my-career'
    | '/admin/jobs/$id'
    | '/my-career/reports/$runId'
    | '/admin/jobs'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/assessment'
    | '/auth'
    | '/career-center'
    | '/careers'
    | '/contact'
    | '/employers'
    | '/jobs'
    | '/mcp'
    | '/security-career-assessment'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/admin'
    | '/_authenticated/journey'
    | '/_authenticated/my-career'
    | '/career-center/$profession'
    | '/career-center/start'
    | '/dev/career-assessment-calibration'
    | '/jobs/$slug'
    | '/career-center/'
    | '/jobs/'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/admin/employers'
    | '/_authenticated/admin/jobs'
    | '/_authenticated/journey/$targetId'
    | '/jobs/family/$familyId'
    | '/jobs/profession/$professionSlug'
    | '/_authenticated/admin/'
    | '/_authenticated/my-career/'
    | '/_authenticated/admin/jobs/$id'
    | '/_authenticated/my-career/reports/$runId'
    | '/_authenticated/admin/jobs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  AssessmentRoute: typeof AssessmentRoute
  AuthRoute: typeof AuthRoute
  CareerCenterRoute: typeof CareerCenterRouteWithChildren
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  EmployersRoute: typeof EmployersRoute
  JobsRoute: typeof JobsRouteWithChildren
  McpRoute: typeof McpRoute
  SecurityCareerAssessmentRoute: typeof SecurityCareerAssessmentRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DevCareerAssessmentCalibrationRoute: typeof DevCareerAssessmentCalibrationRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security-career-assessment': {
      id: '/security-career-assessment'
      path: '/security-career-assessment'
      fullPath: '/security-career-assessment'
      preLoaderRoute: typeof SecurityCareerAssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employers': {
      id: '/employers'
      path: '/employers'
      fullPath: '/employers'
      preLoaderRoute: typeof EmployersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career-center': {
      id: '/career-center'
      path: '/career-center'
      fullPath: '/career-center'
      preLoaderRoute: typeof CareerCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment': {
      id: '/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof JobsRoute
    }
    '/career-center/': {
      id: '/career-center/'
      path: '/'
      fullPath: '/career-center/'
      preLoaderRoute: typeof CareerCenterIndexRouteImport
      parentRoute: typeof CareerCenterRoute
    }
    '/jobs/$slug': {
      id: '/jobs/$slug'
      path: '/$slug'
      fullPath: '/jobs/$slug'
      preLoaderRoute: typeof JobsSlugRouteImport
      parentRoute: typeof JobsRoute
    }
    '/dev/career-assessment-calibration': {
      id: '/dev/career-assessment-calibration'
      path: '/dev/career-assessment-calibration'
      fullPath: '/dev/career-assessment-calibration'
      preLoaderRoute: typeof DevCareerAssessmentCalibrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career-center/start': {
      id: '/career-center/start'
      path: '/start'
      fullPath: '/career-center/start'
      preLoaderRoute: typeof CareerCenterStartRouteImport
      parentRoute: typeof CareerCenterRoute
    }
    '/career-center/$profession': {
      id: '/career-center/$profession'
      path: '/$profession'
      fullPath: '/career-center/$profession'
      preLoaderRoute: typeof CareerCenterProfessionRouteImport
      parentRoute: typeof CareerCenterRoute
    }
    '/_authenticated/my-career': {
      id: '/_authenticated/my-career'
      path: '/my-career'
      fullPath: '/my-career'
      preLoaderRoute: typeof AuthenticatedMyCareerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/journey': {
      id: '/_authenticated/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof AuthenticatedJourneyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/my-career/': {
      id: '/_authenticated/my-career/'
      path: '/'
      fullPath: '/my-career/'
      preLoaderRoute: typeof AuthenticatedMyCareerIndexRouteImport
      parentRoute: typeof AuthenticatedMyCareerRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/jobs/profession/$professionSlug': {
      id: '/jobs/profession/$professionSlug'
      path: '/profession/$professionSlug'
      fullPath: '/jobs/profession/$professionSlug'
      preLoaderRoute: typeof JobsProfessionProfessionSlugRouteImport
      parentRoute: typeof JobsRoute
    }
    '/jobs/family/$familyId': {
      id: '/jobs/family/$familyId'
      path: '/family/$familyId'
      fullPath: '/jobs/family/$familyId'
      preLoaderRoute: typeof JobsFamilyFamilyIdRouteImport
      parentRoute: typeof JobsRoute
    }
    '/_authenticated/journey/$targetId': {
      id: '/_authenticated/journey/$targetId'
      path: '/$targetId'
      fullPath: '/journey/$targetId'
      preLoaderRoute: typeof AuthenticatedJourneyTargetIdRouteImport
      parentRoute: typeof AuthenticatedJourneyRoute
    }
    '/_authenticated/admin/jobs': {
      id: '/_authenticated/admin/jobs'
      path: '/jobs'
      fullPath: '/admin/jobs'
      preLoaderRoute: typeof AuthenticatedAdminJobsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/employers': {
      id: '/_authenticated/admin/employers'
      path: '/employers'
      fullPath: '/admin/employers'
      preLoaderRoute: typeof AuthenticatedAdminEmployersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/jobs/': {
      id: '/_authenticated/admin/jobs/'
      path: '/'
      fullPath: '/admin/jobs/'
      preLoaderRoute: typeof AuthenticatedAdminJobsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminJobsRoute
    }
    '/_authenticated/my-career/reports/$runId': {
      id: '/_authenticated/my-career/reports/$runId'
      path: '/reports/$runId'
      fullPath: '/my-career/reports/$runId'
      preLoaderRoute: typeof AuthenticatedMyCareerReportsRunIdRouteImport
      parentRoute: typeof AuthenticatedMyCareerRoute
    }
    '/_authenticated/admin/jobs/$id': {
      id: '/_authenticated/admin/jobs/$id'
      path: '/$id'
      fullPath: '/admin/jobs/$id'
      preLoaderRoute: typeof AuthenticatedAdminJobsIdRouteImport
      parentRoute: typeof AuthenticatedAdminJobsRoute
    }
  }
}

interface AuthenticatedAdminJobsRouteChildren {
  AuthenticatedAdminJobsIdRoute: typeof AuthenticatedAdminJobsIdRoute
  AuthenticatedAdminJobsIndexRoute: typeof AuthenticatedAdminJobsIndexRoute
}

const AuthenticatedAdminJobsRouteChildren: AuthenticatedAdminJobsRouteChildren =
  {
    AuthenticatedAdminJobsIdRoute: AuthenticatedAdminJobsIdRoute,
    AuthenticatedAdminJobsIndexRoute: AuthenticatedAdminJobsIndexRoute,
  }

const AuthenticatedAdminJobsRouteWithChildren =
  AuthenticatedAdminJobsRoute._addFileChildren(
    AuthenticatedAdminJobsRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminEmployersRoute: typeof AuthenticatedAdminEmployersRoute
  AuthenticatedAdminJobsRoute: typeof AuthenticatedAdminJobsRouteWithChildren
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminEmployersRoute: AuthenticatedAdminEmployersRoute,
  AuthenticatedAdminJobsRoute: AuthenticatedAdminJobsRouteWithChildren,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedJourneyRouteChildren {
  AuthenticatedJourneyTargetIdRoute: typeof AuthenticatedJourneyTargetIdRoute
}

const AuthenticatedJourneyRouteChildren: AuthenticatedJourneyRouteChildren = {
  AuthenticatedJourneyTargetIdRoute: AuthenticatedJourneyTargetIdRoute,
}

const AuthenticatedJourneyRouteWithChildren =
  AuthenticatedJourneyRoute._addFileChildren(AuthenticatedJourneyRouteChildren)

interface AuthenticatedMyCareerRouteChildren {
  AuthenticatedMyCareerIndexRoute: typeof AuthenticatedMyCareerIndexRoute
  AuthenticatedMyCareerReportsRunIdRoute: typeof AuthenticatedMyCareerReportsRunIdRoute
}

const AuthenticatedMyCareerRouteChildren: AuthenticatedMyCareerRouteChildren = {
  AuthenticatedMyCareerIndexRoute: AuthenticatedMyCareerIndexRoute,
  AuthenticatedMyCareerReportsRunIdRoute:
    AuthenticatedMyCareerReportsRunIdRoute,
}

const AuthenticatedMyCareerRouteWithChildren =
  AuthenticatedMyCareerRoute._addFileChildren(
    AuthenticatedMyCareerRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedJourneyRoute: typeof AuthenticatedJourneyRouteWithChildren
  AuthenticatedMyCareerRoute: typeof AuthenticatedMyCareerRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedJourneyRoute: AuthenticatedJourneyRouteWithChildren,
  AuthenticatedMyCareerRoute: AuthenticatedMyCareerRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface CareerCenterRouteChildren {
  CareerCenterProfessionRoute: typeof CareerCenterProfessionRoute
  CareerCenterStartRoute: typeof CareerCenterStartRoute
  CareerCenterIndexRoute: typeof CareerCenterIndexRoute
}

const CareerCenterRouteChildren: CareerCenterRouteChildren = {
  CareerCenterProfessionRoute: CareerCenterProfessionRoute,
  CareerCenterStartRoute: CareerCenterStartRoute,
  CareerCenterIndexRoute: CareerCenterIndexRoute,
}

const CareerCenterRouteWithChildren = CareerCenterRoute._addFileChildren(
  CareerCenterRouteChildren,
)

interface JobsRouteChildren {
  JobsSlugRoute: typeof JobsSlugRoute
  JobsIndexRoute: typeof JobsIndexRoute
  JobsFamilyFamilyIdRoute: typeof JobsFamilyFamilyIdRoute
  JobsProfessionProfessionSlugRoute: typeof JobsProfessionProfessionSlugRoute
}

const JobsRouteChildren: JobsRouteChildren = {
  JobsSlugRoute: JobsSlugRoute,
  JobsIndexRoute: JobsIndexRoute,
  JobsFamilyFamilyIdRoute: JobsFamilyFamilyIdRoute,
  JobsProfessionProfessionSlugRoute: JobsProfessionProfessionSlugRoute,
}

const JobsRouteWithChildren = JobsRoute._addFileChildren(JobsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  AssessmentRoute: AssessmentRoute,
  AuthRoute: AuthRoute,
  CareerCenterRoute: CareerCenterRouteWithChildren,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  EmployersRoute: EmployersRoute,
  JobsRoute: JobsRouteWithChildren,
  McpRoute: McpRoute,
  SecurityCareerAssessmentRoute: SecurityCareerAssessmentRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DevCareerAssessmentCalibrationRoute: DevCareerAssessmentCalibrationRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
