/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SecurityCareerAssessmentRouteImport } from './routes/security-career-assessment'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as EmployersRouteImport } from './routes/employers'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as CareerCenterRouteImport } from './routes/career-center'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AssessmentRouteImport } from './routes/assessment'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CareerCenterIndexRouteImport } from './routes/career-center.index'
import { Route as DevCareerAssessmentCalibrationRouteImport } from './routes/dev.career-assessment-calibration'
import { Route as CareerCenterStartRouteImport } from './routes/career-center.start'
import { Route as CareerCenterProfessionRouteImport } from './routes/career-center.$profession'
import { Route as AuthenticatedJourneyRouteImport } from './routes/_authenticated.journey'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated.admin.index'
import { Route as AuthenticatedJourneyTargetIdRouteImport } from './routes/_authenticated.journey.$targetId'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityCareerAssessmentRoute =
  SecurityCareerAssessmentRouteImport.update({
    id: '/security-career-assessment',
    path: '/security-career-assessment',
    getParentRoute: () => rootRouteImport,
  } as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployersRoute = EmployersRouteImport.update({
  id: '/employers',
  path: '/employers',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerCenterRoute = CareerCenterRouteImport.update({
  id: '/career-center',
  path: '/career-center',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentRoute = AssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerCenterIndexRoute = CareerCenterIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CareerCenterRoute,
} as any)
const DevCareerAssessmentCalibrationRoute =
  DevCareerAssessmentCalibrationRouteImport.update({
    id: '/dev/career-assessment-calibration',
    path: '/dev/career-assessment-calibration',
    getParentRoute: () => rootRouteImport,
  } as any)
const CareerCenterStartRoute = CareerCenterStartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => CareerCenterRoute,
} as any)
const CareerCenterProfessionRoute = CareerCenterProfessionRouteImport.update({
  id: '/$profession',
  path: '/$profession',
  getParentRoute: () => CareerCenterRoute,
} as any)
const AuthenticatedJourneyRoute = AuthenticatedJourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedJourneyTargetIdRoute =
  AuthenticatedJourneyTargetIdRouteImport.update({
    id: '/$targetId',
    path: '/$targetId',
    getParentRoute: () => AuthenticatedJourneyRoute,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/assessment': typeof AssessmentRoute
  '/auth': typeof AuthRoute
  '/career-center': typeof CareerCenterRouteWithChildren
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/employers': typeof EmployersRoute
  '/jobs': typeof JobsRoute
  '/mcp': typeof McpRoute
  '/security-career-assessment': typeof SecurityCareerAssessmentRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/journey': typeof AuthenticatedJourneyRouteWithChildren
  '/career-center/$profession': typeof CareerCenterProfessionRoute
  '/career-center/start': typeof CareerCenterStartRoute
  '/dev/career-assessment-calibration': typeof DevCareerAssessmentCalibrationRoute
  '/career-center/': typeof CareerCenterIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/journey/$targetId': typeof AuthenticatedJourneyTargetIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/assessment': typeof AssessmentRoute
  '/auth': typeof AuthRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/employers': typeof EmployersRoute
  '/jobs': typeof JobsRoute
  '/mcp': typeof McpRoute
  '/security-career-assessment': typeof SecurityCareerAssessmentRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/journey': typeof AuthenticatedJourneyRouteWithChildren
  '/career-center/$profession': typeof CareerCenterProfessionRoute
  '/career-center/start': typeof CareerCenterStartRoute
  '/dev/career-assessment-calibration': typeof DevCareerAssessmentCalibrationRoute
  '/career-center': typeof CareerCenterIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/journey/$targetId': typeof AuthenticatedJourneyTargetIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/assessment': typeof AssessmentRoute
  '/auth': typeof AuthRoute
  '/career-center': typeof CareerCenterRouteWithChildren
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/employers': typeof EmployersRoute
  '/jobs': typeof JobsRoute
  '/mcp': typeof McpRoute
  '/security-career-assessment': typeof SecurityCareerAssessmentRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/journey': typeof AuthenticatedJourneyRouteWithChildren
  '/career-center/$profession': typeof CareerCenterProfessionRoute
  '/career-center/start': typeof CareerCenterStartRoute
  '/dev/career-assessment-calibration': typeof DevCareerAssessmentCalibrationRoute
  '/career-center/': typeof CareerCenterIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/journey/$targetId': typeof AuthenticatedJourneyTargetIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/assessment'
    | '/auth'
    | '/career-center'
    | '/careers'
    | '/contact'
    | '/employers'
    | '/jobs'
    | '/mcp'
    | '/security-career-assessment'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin'
    | '/journey'
    | '/career-center/$profession'
    | '/career-center/start'
    | '/dev/career-assessment-calibration'
    | '/career-center/'
    | '/.mcp/invoke-tool/$tool'
    | '/journey/$targetId'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/assessment'
    | '/auth'
    | '/careers'
    | '/contact'
    | '/employers'
    | '/jobs'
    | '/mcp'
    | '/security-career-assessment'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/journey'
    | '/career-center/$profession'
    | '/career-center/start'
    | '/dev/career-assessment-calibration'
    | '/career-center'
    | '/.mcp/invoke-tool/$tool'
    | '/journey/$targetId'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/assessment'
    | '/auth'
    | '/career-center'
    | '/careers'
    | '/contact'
    | '/employers'
    | '/jobs'
    | '/mcp'
    | '/security-career-assessment'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/admin'
    | '/_authenticated/journey'
    | '/career-center/$profession'
    | '/career-center/start'
    | '/dev/career-assessment-calibration'
    | '/career-center/'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/journey/$targetId'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  AssessmentRoute: typeof AssessmentRoute
  AuthRoute: typeof AuthRoute
  CareerCenterRoute: typeof CareerCenterRouteWithChildren
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  EmployersRoute: typeof EmployersRoute
  JobsRoute: typeof JobsRoute
  McpRoute: typeof McpRoute
  SecurityCareerAssessmentRoute: typeof SecurityCareerAssessmentRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DevCareerAssessmentCalibrationRoute: typeof DevCareerAssessmentCalibrationRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security-career-assessment': {
      id: '/security-career-assessment'
      path: '/security-career-assessment'
      fullPath: '/security-career-assessment'
      preLoaderRoute: typeof SecurityCareerAssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employers': {
      id: '/employers'
      path: '/employers'
      fullPath: '/employers'
      preLoaderRoute: typeof EmployersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career-center': {
      id: '/career-center'
      path: '/career-center'
      fullPath: '/career-center'
      preLoaderRoute: typeof CareerCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment': {
      id: '/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career-center/': {
      id: '/career-center/'
      path: '/'
      fullPath: '/career-center/'
      preLoaderRoute: typeof CareerCenterIndexRouteImport
      parentRoute: typeof CareerCenterRoute
    }
    '/dev/career-assessment-calibration': {
      id: '/dev/career-assessment-calibration'
      path: '/dev/career-assessment-calibration'
      fullPath: '/dev/career-assessment-calibration'
      preLoaderRoute: typeof DevCareerAssessmentCalibrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career-center/start': {
      id: '/career-center/start'
      path: '/start'
      fullPath: '/career-center/start'
      preLoaderRoute: typeof CareerCenterStartRouteImport
      parentRoute: typeof CareerCenterRoute
    }
    '/career-center/$profession': {
      id: '/career-center/$profession'
      path: '/$profession'
      fullPath: '/career-center/$profession'
      preLoaderRoute: typeof CareerCenterProfessionRouteImport
      parentRoute: typeof CareerCenterRoute
    }
    '/_authenticated/journey': {
      id: '/_authenticated/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof AuthenticatedJourneyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/journey/$targetId': {
      id: '/_authenticated/journey/$targetId'
      path: '/$targetId'
      fullPath: '/journey/$targetId'
      preLoaderRoute: typeof AuthenticatedJourneyTargetIdRouteImport
      parentRoute: typeof AuthenticatedJourneyRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedJourneyRouteChildren {
  AuthenticatedJourneyTargetIdRoute: typeof AuthenticatedJourneyTargetIdRoute
}

const AuthenticatedJourneyRouteChildren: AuthenticatedJourneyRouteChildren = {
  AuthenticatedJourneyTargetIdRoute: AuthenticatedJourneyTargetIdRoute,
}

const AuthenticatedJourneyRouteWithChildren =
  AuthenticatedJourneyRoute._addFileChildren(AuthenticatedJourneyRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedJourneyRoute: typeof AuthenticatedJourneyRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedJourneyRoute: AuthenticatedJourneyRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface CareerCenterRouteChildren {
  CareerCenterProfessionRoute: typeof CareerCenterProfessionRoute
  CareerCenterStartRoute: typeof CareerCenterStartRoute
  CareerCenterIndexRoute: typeof CareerCenterIndexRoute
}

const CareerCenterRouteChildren: CareerCenterRouteChildren = {
  CareerCenterProfessionRoute: CareerCenterProfessionRoute,
  CareerCenterStartRoute: CareerCenterStartRoute,
  CareerCenterIndexRoute: CareerCenterIndexRoute,
}

const CareerCenterRouteWithChildren = CareerCenterRoute._addFileChildren(
  CareerCenterRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  AssessmentRoute: AssessmentRoute,
  AuthRoute: AuthRoute,
  CareerCenterRoute: CareerCenterRouteWithChildren,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  EmployersRoute: EmployersRoute,
  JobsRoute: JobsRoute,
  McpRoute: McpRoute,
  SecurityCareerAssessmentRoute: SecurityCareerAssessmentRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DevCareerAssessmentCalibrationRoute: DevCareerAssessmentCalibrationRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
