-- ============================================================================
-- The TRUST conduct layer — how the interviewer behaves, as governed content
-- ============================================================================
--
-- The live Copilot already showed 5E and the prohibited areas. It did not say
-- how to actually run the conversation, so the sequencing lived in whatever the
-- interviewer remembered. That is the gap this closes, and it closes it as
-- DATA rather than as a paragraph in the application: six ordered steps and a
-- list of things that must never be attempted, both pinned to the TRUST method
-- version so an interview can be audited against the conduct it was run under.
--
-- Three properties this migration exists to guarantee:
--
--   1. DETERMINISTIC. These are rows. Nothing generates them, no model is
--      consulted, and the Understand stage's zero-AI boundary is untouched.
--   2. ORDERED AND COMPLETE. Exactly six steps, ordinals 1-6, no gaps and no
--      duplicates, enforced by constraints and re-checked at the end.
--   3. BILINGUAL. Both columns are NOT NULL. Conduct guidance an interviewer
--      cannot read is not guidance, and the prohibitions least of all.
--
-- What the prohibitions are for: this is a structured interview about work
-- examples, not an interrogation. The named techniques below come from
-- investigative and deception-detection traditions where the goal is to obtain
-- an admission. Importing them into hiring produces pressure, not evidence, and
-- the inferences they invite -- credibility, cooperation, personality -- are
-- exactly the ones this engine refuses to make anywhere else. Naming them
-- specifically matters: "be fair" is advice, "do not use minimization" is a
-- boundary someone can be held to.
-- ============================================================================

CREATE TABLE public.scp_interview_conduct_steps (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  method_id uuid NOT NULL REFERENCES public.scp_interview_methods(id) ON DELETE CASCADE,

  step_key text NOT NULL CHECK (step_key IN (
    'invite', 'listen', 'reflect', 'clarify', 'substantiate', 'confirm')),
  ordinal integer NOT NULL CHECK (ordinal BETWEEN 1 AND 6),

  label_sv text NOT NULL,
  label_en text NOT NULL,
  guidance_sv text NOT NULL,
  guidance_en text NOT NULL,

  created_at timestamptz NOT NULL DEFAULT now(),

  UNIQUE (method_id, step_key),
  UNIQUE (method_id, ordinal)
);

COMMENT ON TABLE public.scp_interview_conduct_steps IS
  'The interviewer conduct sequence, as governed content pinned to a TRUST '
  'method version. Rendered during the live interview and generated by '
  'nothing: the Understand stage permits zero AI tasks, and this table is how '
  'the interviewer gets support there without a model being involved.';

CREATE TABLE public.scp_interview_conduct_prohibitions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  method_id uuid NOT NULL REFERENCES public.scp_interview_methods(id) ON DELETE CASCADE,

  prohibition_key text NOT NULL,
  statement_sv text NOT NULL,
  statement_en text NOT NULL,
  display_order integer NOT NULL DEFAULT 1,

  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (method_id, prohibition_key)
);

COMMENT ON TABLE public.scp_interview_conduct_prohibitions IS
  'What an interviewer must never attempt, named specifically enough to be '
  'held to. Separate from scp_interview_prohibited_areas, which is about '
  'SUBJECTS that may not be asked about; this is about TECHNIQUES that may not '
  'be used, whatever the subject.';

CREATE INDEX scp_interview_conduct_steps_method_idx
  ON public.scp_interview_conduct_steps (method_id, ordinal);
CREATE INDEX scp_interview_conduct_prohibitions_method_idx
  ON public.scp_interview_conduct_prohibitions (method_id, display_order);


-- ────────────────────────────────────────────────────────────────────────────
-- Grants and RLS. Same shape as the method practices these sit beside: an
-- active employer member may READ, nobody but the platform may write. Note the
-- REVOKE before every GRANT -- default privileges on this project hand new
-- tables to anon otherwise.
-- ────────────────────────────────────────────────────────────────────────────
ALTER TABLE public.scp_interview_conduct_steps ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.scp_interview_conduct_prohibitions ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON public.scp_interview_conduct_steps FROM PUBLIC, anon, authenticated;
REVOKE ALL ON public.scp_interview_conduct_prohibitions FROM PUBLIC, anon, authenticated;
GRANT SELECT ON public.scp_interview_conduct_steps TO authenticated;
GRANT SELECT ON public.scp_interview_conduct_prohibitions TO authenticated;
GRANT ALL ON public.scp_interview_conduct_steps TO service_role;
GRANT ALL ON public.scp_interview_conduct_prohibitions TO service_role;

CREATE POLICY scp_interview_conduct_steps_read ON public.scp_interview_conduct_steps
  FOR SELECT TO authenticated USING (
    public.scp_interview_can_read(auth.uid())
    OR EXISTS (SELECT 1 FROM public.employer_memberships em
                WHERE em.user_id = auth.uid() AND em.status = 'active'));

CREATE POLICY scp_interview_conduct_prohibitions_read ON public.scp_interview_conduct_prohibitions
  FOR SELECT TO authenticated USING (
    public.scp_interview_can_read(auth.uid())
    OR EXISTS (SELECT 1 FROM public.employer_memberships em
                WHERE em.user_id = auth.uid() AND em.status = 'active'));


-- ────────────────────────────────────────────────────────────────────────────
-- The six steps. Inserted for every method, so a case pinned to any TRUST
-- version renders the conduct it was run under.
-- ────────────────────────────────────────────────────────────────────────────
INSERT INTO public.scp_interview_conduct_steps
  (method_id, step_key, ordinal, label_sv, label_en, guidance_sv, guidance_en)
SELECT m.id, v.step_key, v.ordinal, v.label_sv, v.label_en, v.guidance_sv, v.guidance_en
  FROM public.scp_interview_methods m
 CROSS JOIN (VALUES
  ('invite', 1,
   'Bjud in',
   'Invite',
   'Ställ frågan som den står och be om ETT konkret exempel från arbetslivet. Ett verkligt exempel, inte hur personen brukar göra eller skulle göra.',
   'Ask the question as it stands, and ask for ONE concrete example from working life. A real example — not what the person usually does, or would do.'),

  ('listen', 2,
   'Lyssna',
   'Listen',
   'Låt personen berätta färdigt. Avbryt inte i onödan, fyll inte i åt personen och rätta inte ordningen. Tystnad är tillåten — den som tänker behöver tid.',
   'Let the person finish. Do not interrupt unnecessarily, do not finish their sentences, and do not correct the order they tell it in. Silence is allowed — thinking takes time.'),

  ('reflect', 3,
   'Återge',
   'Reflect',
   'Sammanfatta kort med dina egna ord vad du uppfattade, och fråga om du förstod rätt. Detta är en kontroll av DIN förståelse, inte ett test av personen.',
   'Briefly summarise in your own words what you understood, and ask whether you got it right. This checks YOUR understanding; it is not a test of the person.'),

  ('clarify', 4,
   'Klargör',
   'Clarify',
   'Fråga neutralt vad personen själv gjorde. "Vad gjorde du?" — inte "varför gjorde du inte". Skilj personens eget agerande från vad gruppen eller någon annan gjorde.',
   'Ask neutrally what the person themselves did. "What did you do?" — not "why didn''t you". Separate their own actions from what the team or someone else did.'),

  ('substantiate', 5,
   'Underbygg',
   'Substantiate',
   'Fyll i det som saknas för att exemplet ska gå att förstå: situationen, handlingen och det observerbara resultatet. Fråga om det som faktiskt hände, inte om vad personen tror om sig själv.',
   'Fill in what is missing for the example to be understandable: the situation, the action and the observable result. Ask about what actually happened, not about what the person believes about themselves.'),

  ('confirm', 6,
   'Bekräfta',
   'Confirm',
   'Sammanfatta exemplet och låt personen rätta eller lägga till. Det personen korrigerar är också information — anteckna korrigeringen, ta inte bort det första.',
   'Summarise the example and let the person correct or add to it. What they correct is information too — record the correction rather than deleting the first version.')
) AS v(step_key, ordinal, label_sv, label_en, guidance_sv, guidance_en);


-- ────────────────────────────────────────────────────────────────────────────
-- What must never be attempted. Named specifically, because a named technique
-- is a boundary and "be fair" is only advice.
-- ────────────────────────────────────────────────────────────────────────────
INSERT INTO public.scp_interview_conduct_prohibitions
  (method_id, prohibition_key, statement_sv, statement_en, display_order)
SELECT m.id, v.k, v.sv, v.en, v.ord
  FROM public.scp_interview_methods m
 CROSS JOIN (VALUES
  ('deception_detection',
   'Ingen bedömning av om personen ljuger, och ingen slutsats om trovärdighet.',
   'No judgement of whether the person is lying, and no conclusion about credibility.', 1),

  ('behavioural_cues',
   'Ingen tolkning av kroppsspråk, blick, röst, pauser, nervositet eller andra beteendesignaler.',
   'No interpretation of body language, gaze, voice, pauses, nervousness or other behavioural cues.', 2),

  ('confrontation',
   'Ingen konfrontation och inget mål om erkännande. Detta är inte ett förhör.',
   'No confrontation and no objective of obtaining an admission. This is not an interrogation.', 3),

  ('fabricated_evidence',
   'Inget dolt eller påhittat underlag, och ingen antydan om bevis som inte finns.',
   'No concealed or fabricated material, and no suggestion of evidence that does not exist.', 4),

  ('interrogation_techniques',
   'Inga förhörstekniker: Scharff, Reid, maximering/minimering eller kontextmanipulation.',
   'No interrogation techniques: Scharff, Reid, maximization/minimization, or context manipulation.', 5),

  ('resistance_labels',
   'Inga etiketter om motstånd, samarbetsvilja eller undvikande.',
   'No labels about resistance, cooperativeness or evasiveness.', 6),

  ('personality_inference',
   'Ingen personlighetsbedömning och ingen slutsats om skyddade egenskaper utifrån språk, brytning, namn, foto eller beteende.',
   'No personality assessment, and no conclusion about protected characteristics from language, accent, name, photograph or behaviour.', 7),

  ('scoring_and_recommendation',
   'Ingen poängsättning, rangordning, lämplighetsbedömning eller rekommendation att anställa eller avvisa.',
   'No scoring, ranking, suitability judgement, or recommendation to hire or reject.', 8)
) AS v(k, sv, en, ord);


-- ────────────────────────────────────────────────────────────────────────────
-- Self-check. The conduct layer is either complete and readable, or the
-- migration fails: half a sequence on an interviewer's screen is worse than
-- none, because it looks finished.
-- ────────────────────────────────────────────────────────────────────────────
DO $$
DECLARE _methods integer; _bad integer;
BEGIN
  SELECT count(*) INTO _methods FROM public.scp_interview_methods;

  -- Six steps per method, ordinals 1-6, no gaps.
  SELECT count(*) INTO _bad FROM (
    SELECT s.method_id
      FROM public.scp_interview_conduct_steps s
     GROUP BY s.method_id
    HAVING count(*) <> 6
        OR array_agg(s.ordinal ORDER BY s.ordinal) <> ARRAY[1,2,3,4,5,6]
        OR array_agg(s.step_key ORDER BY s.ordinal)
           <> ARRAY['invite','listen','reflect','clarify','substantiate','confirm']
  ) q;
  IF _bad > 0 OR (SELECT count(DISTINCT method_id) FROM public.scp_interview_conduct_steps) <> _methods THEN
    RAISE EXCEPTION
      'SCP_IV_CONDUCT: the conduct sequence is incomplete on % method(s). Six '
      'ordered steps, invite through confirm, or none.', greatest(_bad, 1);
  END IF;

  -- Eight prohibitions per method, and every one of them readable twice.
  IF (SELECT count(*) FROM public.scp_interview_conduct_prohibitions) <> _methods * 8 THEN
    RAISE EXCEPTION 'SCP_IV_CONDUCT: expected 8 conduct prohibitions per method.';
  END IF;

  SELECT count(*) INTO _bad FROM public.scp_interview_conduct_steps
   WHERE btrim(label_en) = '' OR btrim(guidance_en) = ''
      OR btrim(label_sv) = '' OR btrim(guidance_sv) = '';
  IF _bad > 0 THEN
    RAISE EXCEPTION 'SCP_IV_CONDUCT: % conduct step(s) do not read in both languages.', _bad;
  END IF;

  SELECT count(*) INTO _bad FROM public.scp_interview_conduct_prohibitions
   WHERE btrim(statement_en) = '' OR btrim(statement_sv) = '';
  IF _bad > 0 THEN
    RAISE EXCEPTION 'SCP_IV_CONDUCT: % conduct prohibition(s) do not read in both languages.', _bad;
  END IF;

  -- The named techniques must actually be named. A generic "be fair" list
  -- would pass every count above while prohibiting nothing in particular.
  IF NOT EXISTS (SELECT 1 FROM public.scp_interview_conduct_prohibitions
                  WHERE statement_en ILIKE '%Scharff%' AND statement_en ILIKE '%Reid%'
                    AND statement_en ILIKE '%minimization%') THEN
    RAISE EXCEPTION
      'SCP_IV_CONDUCT: the interrogation techniques must be named explicitly. '
      'A named technique is a boundary; "be fair" is advice.';
  END IF;

  RAISE NOTICE
    'SCP_IV_CONDUCT: six ordered conduct steps and eight named prohibitions '
    'on % method(s), in both languages, generated by nothing.', _methods;
END $$;
