-- Governed organisation roles and source review, linked to existing definitions.
-- No new credential or organisation identities; no personal-data backfill.
BEGIN;
CREATE TABLE public.sp_credential_definition_reviews (
 credential_code text PRIMARY KEY REFERENCES public.sp_credential_types(code),
 professional_domain text NOT NULL CHECK (professional_domain IN ('security_operations','security_management','physical_security','information_security','investigation','financial_crime')),
 source_url text NOT NULL CHECK (source_url LIKE 'https://%'),
 checked_on date NOT NULL,
 validity_sv text NOT NULL,
 validity_en text NOT NULL
);
CREATE TABLE public.sp_credential_organisation_roles (
 credential_code text NOT NULL REFERENCES public.sp_credential_types(code),
 role text NOT NULL CHECK (role IN ('issuer','regulator','training_provider','verification_authority')),
 authority_id uuid REFERENCES public.sp_authorities(id),
 certification_issuer_id uuid REFERENCES public.sp_certification_issuers(id),
 document_specific boolean NOT NULL DEFAULT false,
 source_url text NOT NULL CHECK (source_url LIKE 'https://%'),
 checked_on date NOT NULL,
 PRIMARY KEY (credential_code,role),
 CHECK (num_nonnulls(authority_id,certification_issuer_id) + document_specific::int = 1)
);
CREATE INDEX ON public.sp_credential_organisation_roles(authority_id);
CREATE INDEX ON public.sp_credential_organisation_roles(certification_issuer_id);
ALTER TABLE public.sp_credential_definition_reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sp_credential_definition_reviews FORCE ROW LEVEL SECURITY;
ALTER TABLE public.sp_credential_organisation_roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sp_credential_organisation_roles FORCE ROW LEVEL SECURITY;
REVOKE ALL ON public.sp_credential_definition_reviews,public.sp_credential_organisation_roles FROM PUBLIC,anon,authenticated,service_role;
GRANT SELECT ON public.sp_credential_definition_reviews,public.sp_credential_organisation_roles TO authenticated;
CREATE POLICY sp_definition_reviews_read ON public.sp_credential_definition_reviews FOR SELECT TO authenticated USING (true);
CREATE POLICY sp_organisation_roles_read ON public.sp_credential_organisation_roles FOR SELECT TO authenticated USING (true);
INSERT INTO public.sp_credential_definition_reviews VALUES
('INTL_ACAMS_CAMS','financial_crime','https://www.acams.org/en/certifications/cams-certification','2026-09-16','Treårig omcertifiering, fortbildning och medlemskap enligt ACAMS. Kontrollera aktuell status separat.','CAMS is maintained on a three-year recertification cycle with recertification credits earned within it. No official public holder-verification lookup was confirmed on review, so none is recorded.'),
('INTL_ACFE_CFE','investigation','https://www.acfe.com/cfe-credential','2026-09-16','Årlig fortbildning och aktuellt medlemskap krävs enligt ACFE. Ett utbildningsdatum bevisar inte aktuell status.','The CFE credential is maintained by an ANNUAL continuing-education compliance obligation, not by a fixed multi-year expiry. The ACFE''s Find a CFE directory is opt-in: absence from it is not evidence that a credential is invalid.'),
('INTL_ASIS_APP','security_management','https://www.asisonline.org/certification/associate-protection-professional-app/','2026-09-16','Treårig omcertifiering med fortbildning enligt ASIS. Bevisets aktuella status måste kontrolleras separat.','ASIS board certifications are maintained on a three-year recertification cycle, with continuing professional education recorded through the issuer''s own portal. The cycle is the programme''s; it is not this holder''s expiry date.'),
('INTL_ASIS_CPP','security_management','https://www.asisonline.org/certification/certified-protection-professional-cpp/','2026-09-16','Treårig omcertifiering med fortbildning enligt ASIS. Bevisets aktuella status måste kontrolleras separat.','ASIS board certifications are maintained on a three-year recertification cycle, with continuing professional education recorded through the issuer''s own portal. The cycle is the programme''s; it is not this holder''s expiry date.'),
('INTL_ASIS_PCI','investigation','https://www.asisonline.org/certification/professional-certified-investigator-pci/','2026-09-16','Treårig omcertifiering med fortbildning enligt ASIS. Bevisets aktuella status måste kontrolleras separat.','ASIS board certifications are maintained on a three-year recertification cycle, with continuing professional education recorded through the issuer''s own portal. The cycle is the programme''s; it is not this holder''s expiry date.'),
('INTL_ASIS_PSP','physical_security','https://www.asisonline.org/certification/physical-security-professional/','2026-09-16','Treårig omcertifiering med fortbildning enligt ASIS. Bevisets aktuella status måste kontrolleras separat.','ASIS board certifications are maintained on a three-year recertification cycle, with continuing professional education recorded through the issuer''s own portal. The cycle is the programme''s; it is not this holder''s expiry date.'),
('INTL_ISACA_CISA','information_security','https://www.isaca.org/credentialing/cisa','2026-09-16','Årliga krav och treårig fortbildningscykel enligt ISACA. Kontrollera aktuell status separat.','ISACA certifications carry an annual CPE minimum and an annual maintenance fee, alongside 120 CPE hours across a three-year reporting period. Annual standing can end BEFORE the three-year date printed on the certificate, so the printed date is not current standing.'),
('INTL_ISACA_CISM','information_security','https://www.isaca.org/credentialing/cism','2026-09-16','Årliga krav och treårig fortbildningscykel enligt ISACA. Kontrollera aktuell status separat.','ISACA certifications carry an annual CPE minimum and an annual maintenance fee, alongside 120 CPE hours across a three-year reporting period. Annual standing can end BEFORE the three-year date printed on the certificate, so the printed date is not current standing.'),
('INTL_ISACA_CRISC','information_security','https://www.isaca.org/credentialing/crisc','2026-09-16','Årliga krav och treårig fortbildningscykel enligt ISACA. Kontrollera aktuell status separat.','ISACA certifications carry an annual CPE minimum and an annual maintenance fee, alongside 120 CPE hours across a three-year reporting period. Annual standing can end BEFORE the three-year date printed on the certificate, so the printed date is not current standing.'),
('INTL_ISC2_CC','information_security','https://www.isc2.org/certifications/cc','2026-09-16','Treårig certifieringscykel med fortbildning och avgifter enligt ISC2. Ett cykeldatum bevisar inte aktuell status.','ISC2 certifications run on a three-year cycle AND carry a separate annual maintenance obligation. Both must be in good standing; either alone says nothing about the holder''s current status. CPE totals are credential-specific.'),
('INTL_ISC2_CCSP','information_security','https://www.isc2.org/certifications/ccsp','2026-09-16','Treårig certifieringscykel med fortbildning och avgifter enligt ISC2. Ett cykeldatum bevisar inte aktuell status.','ISC2 certifications run on a three-year cycle AND carry a separate annual maintenance obligation. Both must be in good standing; either alone says nothing about the holder''s current status. CPE totals are credential-specific.'),
('INTL_ISC2_CGRC','information_security','https://www.isc2.org/certifications/cgrc','2026-09-16','Treårig certifieringscykel med fortbildning och avgifter enligt ISC2. Ett cykeldatum bevisar inte aktuell status.','ISC2 certifications run on a three-year cycle AND carry a separate annual maintenance obligation. Both must be in good standing; either alone says nothing about the holder''s current status. CPE totals are credential-specific.'),
('INTL_ISC2_CISSP','information_security','https://www.isc2.org/certifications/cissp','2026-09-16','Treårig certifieringscykel med fortbildning och avgifter enligt ISC2. Ett cykeldatum bevisar inte aktuell status.','ISC2 certifications run on a three-year cycle AND carry a separate annual maintenance obligation. Both must be in good standing; either alone says nothing about the holder''s current status. CPE totals are credential-specific.'),
('INTL_ISC2_SSCP','information_security','https://www.isc2.org/certifications/sscp','2026-09-16','Treårig certifieringscykel med fortbildning och avgifter enligt ISC2. Ett cykeldatum bevisar inte aktuell status.','ISC2 certifications run on a three-year cycle AND carry a separate annual maintenance obligation. Both must be in good standing; either alone says nothing about the holder''s current status. CPE totals are credential-specific.'),
('OV','security_operations','https://polisen.se/lagar-och-regler/ordningsvakter/utbildning-till-ordningsvakt/','2026-09-16','Förordnande är skilt från utbildning och gäller högst fem år. Transportutbildning ersätter inte polisens beslut om en transport.','Appointment is separate from training and lasts at most five years. Transport training does not replace the police decision for a transport.'),
('OV_REFRESHER','security_operations','https://polisen.se/lagar-och-regler/ordningsvakter/utbildning-till-ordningsvakt/','2026-09-16','Förordnande är skilt från utbildning och gäller högst fem år. Transportutbildning ersätter inte polisens beslut om en transport.','Appointment is separate from training and lasts at most five years. Transport training does not replace the police decision for a transport.'),
('OV_TRAINING','security_operations','https://polisen.se/lagar-och-regler/ordningsvakter/utbildning-till-ordningsvakt/','2026-09-16','Förordnande är skilt från utbildning och gäller högst fem år. Transportutbildning ersätter inte polisens beslut om en transport.','Appointment is separate from training and lasts at most five years. Transport training does not replace the police decision for a transport.'),
('OV_TRANSPORT','security_operations','https://polisen.se/lagar-och-regler/ordningsvakter/utbildning-till-ordningsvakt/','2026-09-16','Förordnande är skilt från utbildning och gäller högst fem år. Transportutbildning ersätter inte polisens beslut om en transport.','Appointment is separate from training and lasts at most five years. Transport training does not replace the police decision for a transport.'),
('SE_PERSONNEL_APPROVAL','security_operations','https://www.lansstyrelsen.se/ostergotland/samhalle/tillstand-for-att-utova-verksamhet/bevakningsforetag.html','2026-09-16','Använd datum och villkor i det enskilda beviset. Saknat slutdatum betyder inte livslång giltighet.','Use the dates and conditions on the individual record; a missing expiry is not lifetime validity.'),
('SV','security_operations','https://www.lansstyrelsen.se/download/18.4dec946918b853a3b1e4901/1698847159075/Ans%C3%B6kan%20om%20godk%C3%A4nnande%20av%20skyddsvakt%202023.pdf','2026-09-16','Civilt skyddsvaktsgodkännande gäller högst fem år och angiven anställning, uppdrag eller skyddsobjekt. Omfattning krävs; inte valbart utan stöd för detta.','Civilian protective-security-guard approval is limited to at most five years and the specified employment, assignment or protected sites. Scope remains required; not selectable without that support.'),
('UK_SIA_LICENCE_CCTV','security_operations','https://www.gov.uk/guidance/apply-for-an-sia-licence','2026-09-16','SIA-licenser gäller tre år, utom fordonsblockering (endast Nordirland), som gäller ett år. Status kan ändras före slutdatum; kontrollera SIA:s register.','SIA licences last three years, except vehicle immobilisation (Northern Ireland only), which lasts one year. Status can change before expiry; check the SIA register.'),
('UK_SIA_LICENCE_CP','security_operations','https://www.gov.uk/guidance/apply-for-an-sia-licence','2026-09-16','SIA-licenser gäller tre år, utom fordonsblockering (endast Nordirland), som gäller ett år. Status kan ändras före slutdatum; kontrollera SIA:s register.','SIA licences last three years, except vehicle immobilisation (Northern Ireland only), which lasts one year. Status can change before expiry; check the SIA register.'),
('UK_SIA_LICENCE_CVIT','security_operations','https://www.gov.uk/guidance/apply-for-an-sia-licence','2026-09-16','SIA-licenser gäller tre år, utom fordonsblockering (endast Nordirland), som gäller ett år. Status kan ändras före slutdatum; kontrollera SIA:s register.','SIA licences last three years, except vehicle immobilisation (Northern Ireland only), which lasts one year. Status can change before expiry; check the SIA register.'),
('UK_SIA_LICENCE_DS','security_operations','https://www.gov.uk/guidance/apply-for-an-sia-licence','2026-09-16','SIA-licenser gäller tre år, utom fordonsblockering (endast Nordirland), som gäller ett år. Status kan ändras före slutdatum; kontrollera SIA:s register.','SIA licences last three years, except vehicle immobilisation (Northern Ireland only), which lasts one year. Status can change before expiry; check the SIA register.'),
('UK_SIA_LICENCE_KH','security_operations','https://www.gov.uk/guidance/apply-for-an-sia-licence','2026-09-16','SIA-licenser gäller tre år, utom fordonsblockering (endast Nordirland), som gäller ett år. Status kan ändras före slutdatum; kontrollera SIA:s register.','SIA licences last three years, except vehicle immobilisation (Northern Ireland only), which lasts one year. Status can change before expiry; check the SIA register.'),
('UK_SIA_LICENCE_NFL','security_operations','https://www.gov.uk/guidance/apply-for-an-sia-licence','2026-09-16','SIA-licenser gäller tre år, utom fordonsblockering (endast Nordirland), som gäller ett år. Status kan ändras före slutdatum; kontrollera SIA:s register.','SIA licences last three years, except vehicle immobilisation (Northern Ireland only), which lasts one year. Status can change before expiry; check the SIA register.'),
('UK_SIA_LICENCE_SG','security_operations','https://www.gov.uk/guidance/apply-for-an-sia-licence','2026-09-16','SIA-licenser gäller tre år, utom fordonsblockering (endast Nordirland), som gäller ett år. Status kan ändras före slutdatum; kontrollera SIA:s register.','SIA licences last three years, except vehicle immobilisation (Northern Ireland only), which lasts one year. Status can change before expiry; check the SIA register.'),
('UK_SIA_LICENCE_VI','security_operations','https://www.gov.uk/guidance/apply-for-an-sia-licence','2026-09-16','SIA-licenser gäller tre år, utom fordonsblockering (endast Nordirland), som gäller ett år. Status kan ändras före slutdatum; kontrollera SIA:s register.','SIA licences last three years, except vehicle immobilisation (Northern Ireland only), which lasts one year. Status can change before expiry; check the SIA register.'),
('UK_SIA_QUAL_CCTV','security_operations','https://www.gov.uk/guidance/check-what-training-you-need-to-get-an-sia-licence','2026-09-16','Examensutfärdare och godkänd utbildare är olika roller. SIA bedriver inte utbildningen. Kontrollera beviset och aktuella utbildningskrav för respektive licens.','Qualification awarding organisation and approved training provider are separate. SIA does not deliver training. Check the document and current licence-specific qualification requirements.'),
('UK_SIA_QUAL_CP','security_operations','https://www.gov.uk/guidance/check-what-training-you-need-to-get-an-sia-licence','2026-09-16','Examensutfärdare och godkänd utbildare är olika roller. SIA bedriver inte utbildningen. Kontrollera beviset och aktuella utbildningskrav för respektive licens.','Qualification awarding organisation and approved training provider are separate. SIA does not deliver training. Check the document and current licence-specific qualification requirements.'),
('UK_SIA_QUAL_CVIT','security_operations','https://www.gov.uk/guidance/check-what-training-you-need-to-get-an-sia-licence','2026-09-16','Examensutfärdare och godkänd utbildare är olika roller. SIA bedriver inte utbildningen. Kontrollera beviset och aktuella utbildningskrav för respektive licens.','Qualification awarding organisation and approved training provider are separate. SIA does not deliver training. Check the document and current licence-specific qualification requirements.'),
('UK_SIA_QUAL_DS','security_operations','https://www.gov.uk/guidance/check-what-training-you-need-to-get-an-sia-licence','2026-09-16','Examensutfärdare och godkänd utbildare är olika roller. SIA bedriver inte utbildningen. Kontrollera beviset och aktuella utbildningskrav för respektive licens.','Qualification awarding organisation and approved training provider are separate. SIA does not deliver training. Check the document and current licence-specific qualification requirements.'),
('UK_SIA_QUAL_SG','security_operations','https://www.gov.uk/guidance/check-what-training-you-need-to-get-an-sia-licence','2026-09-16','Examensutfärdare och godkänd utbildare är olika roller. SIA bedriver inte utbildningen. Kontrollera beviset och aktuella utbildningskrav för respektive licens.','Qualification awarding organisation and approved training provider are separate. SIA does not deliver training. Check the document and current licence-specific qualification requirements.'),
('UK_SIA_TOP_UP','security_operations','https://www.gov.uk/guidance/check-what-training-you-need-to-get-an-sia-licence','2026-09-16','Examensutfärdare och godkänd utbildare är olika roller. SIA bedriver inte utbildningen. Kontrollera beviset och aktuella utbildningskrav för respektive licens.','Qualification awarding organisation and approved training provider are separate. SIA does not deliver training. Check the document and current licence-specific qualification requirements.'),
('VU1','security_operations','https://www.bya.se/yrken/vaktare-stationar-ronderande/','2026-09-16','Utbildningsbevis från den faktiska auktoriserade utbildaren. VU1 följs av praktisk yrkesträning och VU2. Fortbildningskrav innebär inte att det historiska kursbeviset automatiskt löper ut.','Training record issued by the actual authorised training provider. VU1 is followed by practical training and VU2. Continuing training requirements do not imply automatic expiry of the historic course record.'),
('VU2','security_operations','https://www.bya.se/yrken/vaktare-stationar-ronderande/','2026-09-16','Utbildningsbevis från den faktiska auktoriserade utbildaren. VU1 följs av praktisk yrkesträning och VU2. Fortbildningskrav innebär inte att det historiska kursbeviset automatiskt löper ut.','Training record issued by the actual authorised training provider. VU1 is followed by practical training and VU2. Continuing training requirements do not imply automatic expiry of the historic course record.');
INSERT INTO public.sp_credential_organisation_roles VALUES ('INTL_ACAMS_CAMS','issuer',NULL,(SELECT id FROM public.sp_certification_issuers WHERE issuer_code='ACAMS'),false,'https://www.acams.org/en/certifications/cams-certification','2026-09-16');
INSERT INTO public.sp_credential_organisation_roles VALUES ('INTL_ACAMS_CAMS','verification_authority',NULL,(SELECT id FROM public.sp_certification_issuers WHERE issuer_code='ACAMS'),false,'https://www.acams.org/en/certifications/cams-certification','2026-09-16');
INSERT INTO public.sp_credential_organisation_roles VALUES ('INTL_ACFE_CFE','issuer',NULL,(SELECT id FROM public.sp_certification_issuers WHERE issuer_code='ACFE'),false,'https://www.acfe.com/cfe-credential','2026-09-16');
INSERT INTO public.sp_credential_organisation_roles VALUES ('INTL_ACFE_CFE','verification_authority',NULL,(SELECT id FROM public.sp_certification_issuers WHERE issuer_code='ACFE'),false,'https://www.acfe.com/cfe-credential','2026-09-16');
INSERT INTO public.sp_credential_organisation_roles VALUES ('INTL_ASIS_APP','issuer',NULL,(SELECT id FROM public.sp_certification_issuers WHERE issuer_code='ASIS'),false,'https://www.asisonline.org/certification/associate-protection-professional-app/','2026-09-16');
INSERT INTO public.sp_credential_organisation_roles VALUES ('INTL_ASIS_APP','verification_authority',NULL,(SELECT id FROM public.sp_certification_issuers WHERE issuer_code='ASIS'),false,'https://www.asisonline.org/certification/associate-protection-professional-app/','2026-09-16');
INSERT INTO public.sp_credential_organisation_roles VALUES ('INTL_ASIS_CPP','issuer',NULL,(SELECT id FROM public.sp_certification_issuers WHERE issuer_code='ASIS'),false,'https://www.asisonline.org/certification/certified-protection-professional-cpp/','2026-09-16');
INSERT INTO public.sp_credential_organisation_roles VALUES ('INTL_ASIS_CPP','verification_authority',NULL,(SELECT id FROM public.sp_certification_issuers WHERE issuer_code='ASIS'),false,'https://www.asisonline.org/certification/certified-protection-professional-cpp/','2026-09-16');
INSERT INTO public.sp_credential_organisation_roles VALUES ('INTL_ASIS_PCI','issuer',NULL,(SELECT id FROM public.sp_certification_issuers WHERE issuer_code='ASIS'),false,'https://www.asisonline.org/certification/professional-certified-investigator-pci/','2026-09-16');
INSERT INTO public.sp_credential_organisation_roles VALUES ('INTL_ASIS_PCI','verification_authority',NULL,(SELECT id FROM public.sp_certification_issuers WHERE issuer_code='ASIS'),false,'https://www.asisonline.org/certification/professional-certified-investigator-pci/','2026-09-16');
INSERT INTO public.sp_credential_organisation_roles VALUES ('INTL_ASIS_PSP','issuer',NULL,(SELECT id FROM public.sp_certification_issuers WHERE issuer_code='ASIS'),false,'https://www.asisonline.org/certification/physical-security-professional/','2026-09-16');
INSERT INTO public.sp_credential_organisation_roles VALUES ('INTL_ASIS_PSP','verification_authority',NULL,(SELECT id FROM public.sp_certification_issuers WHERE issuer_code='ASIS'),false,'https://www.asisonline.org/certification/physical-security-professional/','2026-09-16');
INSERT INTO public.sp_credential_organisation_roles VALUES ('INTL_ISACA_CISA','issuer',NULL,(SELECT id FROM public.sp_certification_issuers WHERE issuer_code='ISACA'),false,'https://www.isaca.org/credentialing/cisa','2026-09-16');
INSERT INTO public.sp_credential_organisation_roles VALUES ('INTL_ISACA_CISA','verification_authority',NULL,(SELECT id FROM public.sp_certification_issuers WHERE issuer_code='ISACA'),false,'https://www.isaca.org/credentialing/cisa','2026-09-16');
INSERT INTO public.sp_credential_organisation_roles VALUES ('INTL_ISACA_CISM','issuer',NULL,(SELECT id FROM public.sp_certification_issuers WHERE issuer_code='ISACA'),false,'https://www.isaca.org/credentialing/cism','2026-09-16');
INSERT INTO public.sp_credential_organisation_roles VALUES ('INTL_ISACA_CISM','verification_authority',NULL,(SELECT id FROM public.sp_certification_issuers WHERE issuer_code='ISACA'),false,'https://www.isaca.org/credentialing/cism','2026-09-16');
INSERT INTO public.sp_credential_organisation_roles VALUES ('INTL_ISACA_CRISC','issuer',NULL,(SELECT id FROM public.sp_certification_issuers WHERE issuer_code='ISACA'),false,'https://www.isaca.org/credentialing/crisc','2026-09-16');
INSERT INTO public.sp_credential_organisation_roles VALUES ('INTL_ISACA_CRISC','verification_authority',NULL,(SELECT id FROM public.sp_certification_issuers WHERE issuer_code='ISACA'),false,'https://www.isaca.org/credentialing/crisc','2026-09-16');
INSERT INTO public.sp_credential_organisation_roles VALUES ('INTL_ISC2_CC','issuer',NULL,(SELECT id FROM public.sp_certification_issuers WHERE issuer_code='ISC2'),false,'https://www.isc2.org/certifications/cc','2026-09-16');
INSERT INTO public.sp_credential_organisation_roles VALUES ('INTL_ISC2_CC','verification_authority',NULL,(SELECT id FROM public.sp_certification_issuers WHERE issuer_code='ISC2'),false,'https://www.isc2.org/certifications/cc','2026-09-16');
INSERT INTO public.sp_credential_organisation_roles VALUES ('INTL_ISC2_CCSP','issuer',NULL,(SELECT id FROM public.sp_certification_issuers WHERE issuer_code='ISC2'),false,'https://www.isc2.org/certifications/ccsp','2026-09-16');
INSERT INTO public.sp_credential_organisation_roles VALUES ('INTL_ISC2_CCSP','verification_authority',NULL,(SELECT id FROM public.sp_certification_issuers WHERE issuer_code='ISC2'),false,'https://www.isc2.org/certifications/ccsp','2026-09-16');
INSERT INTO public.sp_credential_organisation_roles VALUES ('INTL_ISC2_CGRC','issuer',NULL,(SELECT id FROM public.sp_certification_issuers WHERE issuer_code='ISC2'),false,'https://www.isc2.org/certifications/cgrc','2026-09-16');
INSERT INTO public.sp_credential_organisation_roles VALUES ('INTL_ISC2_CGRC','verification_authority',NULL,(SELECT id FROM public.sp_certification_issuers WHERE issuer_code='ISC2'),false,'https://www.isc2.org/certifications/cgrc','2026-09-16');
INSERT INTO public.sp_credential_organisation_roles VALUES ('INTL_ISC2_CISSP','issuer',NULL,(SELECT id FROM public.sp_certification_issuers WHERE issuer_code='ISC2'),false,'https://www.isc2.org/certifications/cissp','2026-09-16');
INSERT INTO public.sp_credential_organisation_roles VALUES ('INTL_ISC2_CISSP','verification_authority',NULL,(SELECT id FROM public.sp_certification_issuers WHERE issuer_code='ISC2'),false,'https://www.isc2.org/certifications/cissp','2026-09-16');
INSERT INTO public.sp_credential_organisation_roles VALUES ('INTL_ISC2_SSCP','issuer',NULL,(SELECT id FROM public.sp_certification_issuers WHERE issuer_code='ISC2'),false,'https://www.isc2.org/certifications/sscp','2026-09-16');
INSERT INTO public.sp_credential_organisation_roles VALUES ('INTL_ISC2_SSCP','verification_authority',NULL,(SELECT id FROM public.sp_certification_issuers WHERE issuer_code='ISC2'),false,'https://www.isc2.org/certifications/sscp','2026-09-16');
INSERT INTO public.sp_credential_organisation_roles VALUES ('OV','issuer',(SELECT id FROM public.sp_authorities WHERE code='SE_POLISMYNDIGHETEN'),NULL,false,'https://polisen.se/lagar-och-regler/ordningsvakter/utbildning-till-ordningsvakt/','2026-09-16');
INSERT INTO public.sp_credential_organisation_roles VALUES ('OV','regulator',(SELECT id FROM public.sp_authorities WHERE code='SE_POLISMYNDIGHETEN'),NULL,false,'https://polisen.se/lagar-och-regler/ordningsvakter/utbildning-till-ordningsvakt/','2026-09-16');
INSERT INTO public.sp_credential_organisation_roles VALUES ('OV','verification_authority',(SELECT id FROM public.sp_authorities WHERE code='SE_POLISMYNDIGHETEN'),NULL,false,'https://polisen.se/lagar-och-regler/ordningsvakter/utbildning-till-ordningsvakt/','2026-09-16');
INSERT INTO public.sp_credential_organisation_roles VALUES ('OV_REFRESHER','issuer',(SELECT id FROM public.sp_authorities WHERE code='SE_POLISMYNDIGHETEN'),NULL,false,'https://polisen.se/lagar-och-regler/ordningsvakter/utbildning-till-ordningsvakt/','2026-09-16');
INSERT INTO public.sp_credential_organisation_roles VALUES ('OV_REFRESHER','regulator',(SELECT id FROM public.sp_authorities WHERE code='SE_POLISMYNDIGHETEN'),NULL,false,'https://polisen.se/lagar-och-regler/ordningsvakter/utbildning-till-ordningsvakt/','2026-09-16');
INSERT INTO public.sp_credential_organisation_roles VALUES ('OV_REFRESHER','verification_authority',(SELECT id FROM public.sp_authorities WHERE code='SE_POLISMYNDIGHETEN'),NULL,false,'https://polisen.se/lagar-och-regler/ordningsvakter/utbildning-till-ordningsvakt/','2026-09-16');
INSERT INTO public.sp_credential_organisation_roles VALUES ('OV_REFRESHER','training_provider',(SELECT id FROM public.sp_authorities WHERE code='SE_POLISMYNDIGHETEN'),NULL,false,'https://polisen.se/lagar-och-regler/ordningsvakter/utbildning-till-ordningsvakt/','2026-09-16');
INSERT INTO public.sp_credential_organisation_roles VALUES ('OV_TRAINING','issuer',(SELECT id FROM public.sp_authorities WHERE code='SE_POLISMYNDIGHETEN'),NULL,false,'https://polisen.se/lagar-och-regler/ordningsvakter/utbildning-till-ordningsvakt/','2026-09-16');
INSERT INTO public.sp_credential_organisation_roles VALUES ('OV_TRAINING','regulator',(SELECT id FROM public.sp_authorities WHERE code='SE_POLISMYNDIGHETEN'),NULL,false,'https://polisen.se/lagar-och-regler/ordningsvakter/utbildning-till-ordningsvakt/','2026-09-16');
INSERT INTO public.sp_credential_organisation_roles VALUES ('OV_TRAINING','verification_authority',(SELECT id FROM public.sp_authorities WHERE code='SE_POLISMYNDIGHETEN'),NULL,false,'https://polisen.se/lagar-och-regler/ordningsvakter/utbildning-till-ordningsvakt/','2026-09-16');
INSERT INTO public.sp_credential_organisation_roles VALUES ('OV_TRAINING','training_provider',(SELECT id FROM public.sp_authorities WHERE code='SE_POLISMYNDIGHETEN'),NULL,false,'https://polisen.se/lagar-och-regler/ordningsvakter/utbildning-till-ordningsvakt/','2026-09-16');
INSERT INTO public.sp_credential_organisation_roles VALUES ('OV_TRANSPORT','issuer',(SELECT id FROM public.sp_authorities WHERE code='SE_POLISMYNDIGHETEN'),NULL,false,'https://polisen.se/lagar-och-regler/ordningsvakter/utbildning-till-ordningsvakt/','2026-09-16');
INSERT INTO public.sp_credential_organisation_roles VALUES ('OV_TRANSPORT','regulator',(SELECT id FROM public.sp_authorities WHERE code='SE_POLISMYNDIGHETEN'),NULL,false,'https://polisen.se/lagar-och-regler/ordningsvakter/utbildning-till-ordningsvakt/','2026-09-16');
INSERT INTO public.sp_credential_organisation_roles VALUES ('OV_TRANSPORT','verification_authority',(SELECT id FROM public.sp_authorities WHERE code='SE_POLISMYNDIGHETEN'),NULL,false,'https://polisen.se/lagar-och-regler/ordningsvakter/utbildning-till-ordningsvakt/','2026-09-16');
INSERT INTO public.sp_credential_organisation_roles VALUES ('OV_TRANSPORT','training_provider',(SELECT id FROM public.sp_authorities WHERE code='SE_POLISMYNDIGHETEN'),NULL,false,'https://polisen.se/lagar-och-regler/ordningsvakter/utbildning-till-ordningsvakt/','2026-09-16');
INSERT INTO public.sp_credential_organisation_roles VALUES ('SE_PERSONNEL_APPROVAL','issuer',(SELECT id FROM public.sp_authorities WHERE code='SE_LANSSTYRELSEN'),NULL,false,'https://www.lansstyrelsen.se/ostergotland/samhalle/tillstand-for-att-utova-verksamhet/bevakningsforetag.html','2026-09-16');
INSERT INTO public.sp_credential_organisation_roles VALUES ('SE_PERSONNEL_APPROVAL','verification_authority',(SELECT id FROM public.sp_authorities WHERE code='SE_LANSSTYRELSEN'),NULL,false,'https://www.lansstyrelsen.se/ostergotland/samhalle/tillstand-for-att-utova-verksamhet/bevakningsforetag.html','2026-09-16');
INSERT INTO public.sp_credential_organisation_roles VALUES ('SE_PERSONNEL_APPROVAL','regulator',(SELECT id FROM public.sp_authorities WHERE code='SE_POLISMYNDIGHETEN'),NULL,false,'https://www.lansstyrelsen.se/ostergotland/samhalle/tillstand-for-att-utova-verksamhet/bevakningsforetag.html','2026-09-16');
INSERT INTO public.sp_credential_organisation_roles VALUES ('SV','issuer',(SELECT id FROM public.sp_authorities WHERE code='SE_LANSSTYRELSEN'),NULL,false,'https://www.lansstyrelsen.se/download/18.4dec946918b853a3b1e4901/1698847159075/Ans%C3%B6kan%20om%20godk%C3%A4nnande%20av%20skyddsvakt%202023.pdf','2026-09-16');
INSERT INTO public.sp_credential_organisation_roles VALUES ('SV','verification_authority',(SELECT id FROM public.sp_authorities WHERE code='SE_LANSSTYRELSEN'),NULL,false,'https://www.lansstyrelsen.se/download/18.4dec946918b853a3b1e4901/1698847159075/Ans%C3%B6kan%20om%20godk%C3%A4nnande%20av%20skyddsvakt%202023.pdf','2026-09-16');
INSERT INTO public.sp_credential_organisation_roles VALUES ('SV','regulator',(SELECT id FROM public.sp_authorities WHERE code='SE_POLISMYNDIGHETEN'),NULL,false,'https://www.lansstyrelsen.se/download/18.4dec946918b853a3b1e4901/1698847159075/Ans%C3%B6kan%20om%20godk%C3%A4nnande%20av%20skyddsvakt%202023.pdf','2026-09-16');
INSERT INTO public.sp_credential_organisation_roles VALUES ('UK_SIA_LICENCE_CCTV','regulator',(SELECT id FROM public.sp_authorities WHERE code='GB_SIA'),NULL,false,'https://www.gov.uk/guidance/apply-for-an-sia-licence','2026-09-16');
INSERT INTO public.sp_credential_organisation_roles VALUES ('UK_SIA_LICENCE_CCTV','issuer',(SELECT id FROM public.sp_authorities WHERE code='GB_SIA'),NULL,false,'https://www.gov.uk/guidance/apply-for-an-sia-licence','2026-09-16');
INSERT INTO public.sp_credential_organisation_roles VALUES ('UK_SIA_LICENCE_CCTV','verification_authority',(SELECT id FROM public.sp_authorities WHERE code='GB_SIA'),NULL,false,'https://www.gov.uk/guidance/apply-for-an-sia-licence','2026-09-16');
INSERT INTO public.sp_credential_organisation_roles VALUES ('UK_SIA_LICENCE_CP','regulator',(SELECT id FROM public.sp_authorities WHERE code='GB_SIA'),NULL,false,'https://www.gov.uk/guidance/apply-for-an-sia-licence','2026-09-16');
INSERT INTO public.sp_credential_organisation_roles VALUES ('UK_SIA_LICENCE_CP','issuer',(SELECT id FROM public.sp_authorities WHERE code='GB_SIA'),NULL,false,'https://www.gov.uk/guidance/apply-for-an-sia-licence','2026-09-16');
INSERT INTO public.sp_credential_organisation_roles VALUES ('UK_SIA_LICENCE_CP','verification_authority',(SELECT id FROM public.sp_authorities WHERE code='GB_SIA'),NULL,false,'https://www.gov.uk/guidance/apply-for-an-sia-licence','2026-09-16');
INSERT INTO public.sp_credential_organisation_roles VALUES ('UK_SIA_LICENCE_CVIT','regulator',(SELECT id FROM public.sp_authorities WHERE code='GB_SIA'),NULL,false,'https://www.gov.uk/guidance/apply-for-an-sia-licence','2026-09-16');
INSERT INTO public.sp_credential_organisation_roles VALUES ('UK_SIA_LICENCE_CVIT','issuer',(SELECT id FROM public.sp_authorities WHERE code='GB_SIA'),NULL,false,'https://www.gov.uk/guidance/apply-for-an-sia-licence','2026-09-16');
INSERT INTO public.sp_credential_organisation_roles VALUES ('UK_SIA_LICENCE_CVIT','verification_authority',(SELECT id FROM public.sp_authorities WHERE code='GB_SIA'),NULL,false,'https://www.gov.uk/guidance/apply-for-an-sia-licence','2026-09-16');
INSERT INTO public.sp_credential_organisation_roles VALUES ('UK_SIA_LICENCE_DS','regulator',(SELECT id FROM public.sp_authorities WHERE code='GB_SIA'),NULL,false,'https://www.gov.uk/guidance/apply-for-an-sia-licence','2026-09-16');
INSERT INTO public.sp_credential_organisation_roles VALUES ('UK_SIA_LICENCE_DS','issuer',(SELECT id FROM public.sp_authorities WHERE code='GB_SIA'),NULL,false,'https://www.gov.uk/guidance/apply-for-an-sia-licence','2026-09-16');
INSERT INTO public.sp_credential_organisation_roles VALUES ('UK_SIA_LICENCE_DS','verification_authority',(SELECT id FROM public.sp_authorities WHERE code='GB_SIA'),NULL,false,'https://www.gov.uk/guidance/apply-for-an-sia-licence','2026-09-16');
INSERT INTO public.sp_credential_organisation_roles VALUES ('UK_SIA_LICENCE_KH','regulator',(SELECT id FROM public.sp_authorities WHERE code='GB_SIA'),NULL,false,'https://www.gov.uk/guidance/apply-for-an-sia-licence','2026-09-16');
INSERT INTO public.sp_credential_organisation_roles VALUES ('UK_SIA_LICENCE_KH','issuer',(SELECT id FROM public.sp_authorities WHERE code='GB_SIA'),NULL,false,'https://www.gov.uk/guidance/apply-for-an-sia-licence','2026-09-16');
INSERT INTO public.sp_credential_organisation_roles VALUES ('UK_SIA_LICENCE_KH','verification_authority',(SELECT id FROM public.sp_authorities WHERE code='GB_SIA'),NULL,false,'https://www.gov.uk/guidance/apply-for-an-sia-licence','2026-09-16');
INSERT INTO public.sp_credential_organisation_roles VALUES ('UK_SIA_LICENCE_NFL','regulator',(SELECT id FROM public.sp_authorities WHERE code='GB_SIA'),NULL,false,'https://www.gov.uk/guidance/apply-for-an-sia-licence','2026-09-16');
INSERT INTO public.sp_credential_organisation_roles VALUES ('UK_SIA_LICENCE_NFL','issuer',(SELECT id FROM public.sp_authorities WHERE code='GB_SIA'),NULL,false,'https://www.gov.uk/guidance/apply-for-an-sia-licence','2026-09-16');
INSERT INTO public.sp_credential_organisation_roles VALUES ('UK_SIA_LICENCE_NFL','verification_authority',(SELECT id FROM public.sp_authorities WHERE code='GB_SIA'),NULL,false,'https://www.gov.uk/guidance/apply-for-an-sia-licence','2026-09-16');
INSERT INTO public.sp_credential_organisation_roles VALUES ('UK_SIA_LICENCE_SG','regulator',(SELECT id FROM public.sp_authorities WHERE code='GB_SIA'),NULL,false,'https://www.gov.uk/guidance/apply-for-an-sia-licence','2026-09-16');
INSERT INTO public.sp_credential_organisation_roles VALUES ('UK_SIA_LICENCE_SG','issuer',(SELECT id FROM public.sp_authorities WHERE code='GB_SIA'),NULL,false,'https://www.gov.uk/guidance/apply-for-an-sia-licence','2026-09-16');
INSERT INTO public.sp_credential_organisation_roles VALUES ('UK_SIA_LICENCE_SG','verification_authority',(SELECT id FROM public.sp_authorities WHERE code='GB_SIA'),NULL,false,'https://www.gov.uk/guidance/apply-for-an-sia-licence','2026-09-16');
INSERT INTO public.sp_credential_organisation_roles VALUES ('UK_SIA_LICENCE_VI','regulator',(SELECT id FROM public.sp_authorities WHERE code='GB_SIA'),NULL,false,'https://www.gov.uk/guidance/apply-for-an-sia-licence','2026-09-16');
INSERT INTO public.sp_credential_organisation_roles VALUES ('UK_SIA_LICENCE_VI','issuer',(SELECT id FROM public.sp_authorities WHERE code='GB_SIA'),NULL,false,'https://www.gov.uk/guidance/apply-for-an-sia-licence','2026-09-16');
INSERT INTO public.sp_credential_organisation_roles VALUES ('UK_SIA_LICENCE_VI','verification_authority',(SELECT id FROM public.sp_authorities WHERE code='GB_SIA'),NULL,false,'https://www.gov.uk/guidance/apply-for-an-sia-licence','2026-09-16');
INSERT INTO public.sp_credential_organisation_roles VALUES ('UK_SIA_QUAL_CCTV','regulator',(SELECT id FROM public.sp_authorities WHERE code='GB_SIA'),NULL,false,'https://www.gov.uk/guidance/check-what-training-you-need-to-get-an-sia-licence','2026-09-16');
INSERT INTO public.sp_credential_organisation_roles VALUES ('UK_SIA_QUAL_CCTV','issuer',NULL,NULL,true,'https://www.gov.uk/guidance/check-what-training-you-need-to-get-an-sia-licence','2026-09-16');
INSERT INTO public.sp_credential_organisation_roles VALUES ('UK_SIA_QUAL_CCTV','training_provider',NULL,NULL,true,'https://www.gov.uk/guidance/check-what-training-you-need-to-get-an-sia-licence','2026-09-16');
INSERT INTO public.sp_credential_organisation_roles VALUES ('UK_SIA_QUAL_CCTV','verification_authority',NULL,NULL,true,'https://www.gov.uk/guidance/check-what-training-you-need-to-get-an-sia-licence','2026-09-16');
INSERT INTO public.sp_credential_organisation_roles VALUES ('UK_SIA_QUAL_CP','regulator',(SELECT id FROM public.sp_authorities WHERE code='GB_SIA'),NULL,false,'https://www.gov.uk/guidance/check-what-training-you-need-to-get-an-sia-licence','2026-09-16');
INSERT INTO public.sp_credential_organisation_roles VALUES ('UK_SIA_QUAL_CP','issuer',NULL,NULL,true,'https://www.gov.uk/guidance/check-what-training-you-need-to-get-an-sia-licence','2026-09-16');
INSERT INTO public.sp_credential_organisation_roles VALUES ('UK_SIA_QUAL_CP','training_provider',NULL,NULL,true,'https://www.gov.uk/guidance/check-what-training-you-need-to-get-an-sia-licence','2026-09-16');
INSERT INTO public.sp_credential_organisation_roles VALUES ('UK_SIA_QUAL_CP','verification_authority',NULL,NULL,true,'https://www.gov.uk/guidance/check-what-training-you-need-to-get-an-sia-licence','2026-09-16');
INSERT INTO public.sp_credential_organisation_roles VALUES ('UK_SIA_QUAL_CVIT','regulator',(SELECT id FROM public.sp_authorities WHERE code='GB_SIA'),NULL,false,'https://www.gov.uk/guidance/check-what-training-you-need-to-get-an-sia-licence','2026-09-16');
INSERT INTO public.sp_credential_organisation_roles VALUES ('UK_SIA_QUAL_CVIT','issuer',NULL,NULL,true,'https://www.gov.uk/guidance/check-what-training-you-need-to-get-an-sia-licence','2026-09-16');
INSERT INTO public.sp_credential_organisation_roles VALUES ('UK_SIA_QUAL_CVIT','training_provider',NULL,NULL,true,'https://www.gov.uk/guidance/check-what-training-you-need-to-get-an-sia-licence','2026-09-16');
INSERT INTO public.sp_credential_organisation_roles VALUES ('UK_SIA_QUAL_CVIT','verification_authority',NULL,NULL,true,'https://www.gov.uk/guidance/check-what-training-you-need-to-get-an-sia-licence','2026-09-16');
INSERT INTO public.sp_credential_organisation_roles VALUES ('UK_SIA_QUAL_DS','regulator',(SELECT id FROM public.sp_authorities WHERE code='GB_SIA'),NULL,false,'https://www.gov.uk/guidance/check-what-training-you-need-to-get-an-sia-licence','2026-09-16');
INSERT INTO public.sp_credential_organisation_roles VALUES ('UK_SIA_QUAL_DS','issuer',NULL,NULL,true,'https://www.gov.uk/guidance/check-what-training-you-need-to-get-an-sia-licence','2026-09-16');
INSERT INTO public.sp_credential_organisation_roles VALUES ('UK_SIA_QUAL_DS','training_provider',NULL,NULL,true,'https://www.gov.uk/guidance/check-what-training-you-need-to-get-an-sia-licence','2026-09-16');
INSERT INTO public.sp_credential_organisation_roles VALUES ('UK_SIA_QUAL_DS','verification_authority',NULL,NULL,true,'https://www.gov.uk/guidance/check-what-training-you-need-to-get-an-sia-licence','2026-09-16');
INSERT INTO public.sp_credential_organisation_roles VALUES ('UK_SIA_QUAL_SG','regulator',(SELECT id FROM public.sp_authorities WHERE code='GB_SIA'),NULL,false,'https://www.gov.uk/guidance/check-what-training-you-need-to-get-an-sia-licence','2026-09-16');
INSERT INTO public.sp_credential_organisation_roles VALUES ('UK_SIA_QUAL_SG','issuer',NULL,NULL,true,'https://www.gov.uk/guidance/check-what-training-you-need-to-get-an-sia-licence','2026-09-16');
INSERT INTO public.sp_credential_organisation_roles VALUES ('UK_SIA_QUAL_SG','training_provider',NULL,NULL,true,'https://www.gov.uk/guidance/check-what-training-you-need-to-get-an-sia-licence','2026-09-16');
INSERT INTO public.sp_credential_organisation_roles VALUES ('UK_SIA_QUAL_SG','verification_authority',NULL,NULL,true,'https://www.gov.uk/guidance/check-what-training-you-need-to-get-an-sia-licence','2026-09-16');
INSERT INTO public.sp_credential_organisation_roles VALUES ('UK_SIA_TOP_UP','regulator',(SELECT id FROM public.sp_authorities WHERE code='GB_SIA'),NULL,false,'https://www.gov.uk/guidance/check-what-training-you-need-to-get-an-sia-licence','2026-09-16');
INSERT INTO public.sp_credential_organisation_roles VALUES ('UK_SIA_TOP_UP','issuer',NULL,NULL,true,'https://www.gov.uk/guidance/check-what-training-you-need-to-get-an-sia-licence','2026-09-16');
INSERT INTO public.sp_credential_organisation_roles VALUES ('UK_SIA_TOP_UP','training_provider',NULL,NULL,true,'https://www.gov.uk/guidance/check-what-training-you-need-to-get-an-sia-licence','2026-09-16');
INSERT INTO public.sp_credential_organisation_roles VALUES ('UK_SIA_TOP_UP','verification_authority',NULL,NULL,true,'https://www.gov.uk/guidance/check-what-training-you-need-to-get-an-sia-licence','2026-09-16');
INSERT INTO public.sp_credential_organisation_roles VALUES ('VU1','issuer',NULL,NULL,true,'https://www.bya.se/yrken/vaktare-stationar-ronderande/','2026-09-16');
INSERT INTO public.sp_credential_organisation_roles VALUES ('VU1','regulator',(SELECT id FROM public.sp_authorities WHERE code='SE_POLISMYNDIGHETEN'),NULL,false,'https://www.bya.se/yrken/vaktare-stationar-ronderande/','2026-09-16');
INSERT INTO public.sp_credential_organisation_roles VALUES ('VU1','training_provider',NULL,NULL,true,'https://www.bya.se/yrken/vaktare-stationar-ronderande/','2026-09-16');
INSERT INTO public.sp_credential_organisation_roles VALUES ('VU1','verification_authority',NULL,NULL,true,'https://www.bya.se/yrken/vaktare-stationar-ronderande/','2026-09-16');
INSERT INTO public.sp_credential_organisation_roles VALUES ('VU2','issuer',NULL,NULL,true,'https://www.bya.se/yrken/vaktare-stationar-ronderande/','2026-09-16');
INSERT INTO public.sp_credential_organisation_roles VALUES ('VU2','regulator',(SELECT id FROM public.sp_authorities WHERE code='SE_POLISMYNDIGHETEN'),NULL,false,'https://www.bya.se/yrken/vaktare-stationar-ronderande/','2026-09-16');
INSERT INTO public.sp_credential_organisation_roles VALUES ('VU2','training_provider',NULL,NULL,true,'https://www.bya.se/yrken/vaktare-stationar-ronderande/','2026-09-16');
INSERT INTO public.sp_credential_organisation_roles VALUES ('VU2','verification_authority',NULL,NULL,true,'https://www.bya.se/yrken/vaktare-stationar-ronderande/','2026-09-16');

CREATE OR REPLACE FUNCTION public.sp_credential_payload_v2(_holder uuid,_ids uuid[],_fields text[],_purpose text,_locale text,_expires timestamptz,_created timestamptz)
RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path='' AS $$
DECLARE _p public.sp_passport_profiles%ROWTYPE; _name text;
BEGIN
 SELECT * INTO _p FROM public.sp_passport_profiles WHERE holder_user_id=_holder;
 IF NOT FOUND THEN RETURN jsonb_build_object('status','unavailable'); END IF;
 SELECT display_name INTO _name FROM public.profiles WHERE id=_holder;
 RETURN jsonb_build_object('status','active','package','selected_merits','schema_version',2,'focus','passport',
 'purpose',_purpose,'locale',_locale,'expires_at',_expires,'authorised_at',_created,
 'holder',CASE WHEN NOT 'holder_name'=ANY(_fields) OR _p.privacy_mode='anonymous' THEN NULL
   WHEN _p.privacy_mode='initials' THEN regexp_replace(coalesce(_name,''),'(\S)\S*','\1.','g') ELSE _name END,
 'privacy_mode',CASE WHEN 'holder_name'=ANY(_fields) THEN _p.privacy_mode ELSE 'anonymous' END,
 'profession_slug',NULL,'jurisdiction',NULL,'sub_jurisdiction',NULL,
 'verified_experience','[]'::jsonb,'verified_experience_days',0,
 'last_updated',(SELECT max(updated_at) FROM public.sp_claims WHERE holder_user_id=_holder AND id=ANY(_ids)),
 'verified_claims',coalesce((SELECT jsonb_agg(jsonb_build_object(
   'key','c'||c.ord,'type',c.claim_type,'title',c.title,'credential_code',c.credential_code,
   'issuer',(SELECT coalesce(a.name_local,i.display_name) FROM public.sp_credential_organisation_roles r LEFT JOIN public.sp_authorities a ON a.id=r.authority_id LEFT JOIN public.sp_certification_issuers i ON i.id=r.certification_issuer_id WHERE r.credential_code=c.credential_code AND r.role='issuer'),'jurisdiction',c.jurisdiction_code,'sub_jurisdiction',c.sub_jurisdiction_code,
   'scope_limited',nullif(btrim(c.authorisation_scope),'') IS NOT NULL,'authorisation_scope',NULL,
   'issued_on',c.issued_on,'valid_until',c.valid_until,
   'assertion',CASE WHEN c.assertion_level='verified' AND (v.id IS NULL OR (v.valid_until IS NOT NULL AND v.valid_until<current_date))
      THEN 'document_provided' ELSE c.assertion_level::text END,
   'lifecycle',CASE WHEN c.lifecycle_state='active' AND c.valid_until<current_date THEN 'expired' ELSE c.lifecycle_state::text END,
   'verified_at',CASE WHEN v.id IS NOT NULL AND (v.valid_until IS NULL OR v.valid_until>=current_date) THEN c.verified_at END,
   'verification_method',CASE WHEN c.assertion_level='verified' AND (v.valid_until IS NULL OR v.valid_until>=current_date) THEN v.verification_method END,
   'verifier_organisation',CASE WHEN c.assertion_level='verified' AND (v.valid_until IS NULL OR v.valid_until>=current_date) THEN v.decider_organisation END,
   'credential_identifier',CASE WHEN 'identifier'=ANY(_fields) THEN c.credential_reference END,
   'credential_class',m.credential_class,'original_language',m.original_language,
   'issuing_country',m.issuing_country_code,'issuing_jurisdiction',m.issuing_jurisdiction_code,
   'validity_jurisdiction',m.validity_jurisdiction_code,'no_expiry',m.no_expiry) ORDER BY c.ord)
 FROM (SELECT c.*,row_number() OVER(ORDER BY c.issued_on DESC NULLS LAST,c.id) ord FROM public.sp_claims c
   WHERE c.holder_user_id=_holder AND c.id=ANY(_ids) AND c.lifecycle_state IN ('active','expired','revoked')
   AND public.sp_is_passport_credential(c.claim_type,c.credential_code)) c
 LEFT JOIN public.sp_credential_details m ON m.claim_id=c.id
 LEFT JOIN LATERAL (SELECT d.* FROM public.sp_verification_decisions d JOIN public.sp_verification_requests r ON r.id=d.request_id
    WHERE r.claim_id=c.id ORDER BY d.decided_at DESC,d.id DESC LIMIT 1) latest ON true
 LEFT JOIN public.sp_verification_decisions v ON v.id=latest.id AND v.decision='approved'
 ),'[]'::jsonb));
END $$;
REVOKE ALL ON FUNCTION public.sp_credential_payload_v2(uuid,uuid[],text[],text,text,timestamptz,timestamptz) FROM PUBLIC,anon,authenticated,service_role;
COMMIT;
