-- Owner Approval Gate item 2: CID02 Leadership item-bank coverage fix.
--
-- CID02 had only one primary evidence source across the whole 20-question
-- instrument (CQ13), while materially contributing to two profession
-- centrals (SP006 Sakerhetssamordnare, SP007 Sakerhetschef) -- their
-- absolute leadership placement rested on a single question. CQ06 and
-- CQ09 each already carried a genuine, direct-observed-behaviour CID02
-- tertiary loading (not a stated preference -- 'taking direction of a
-- situation', 'convening the affected people and driving to a
-- resolution'), underweighted relative to its actual evidentiary strength.
-- Promoted both from tertiary (weight 0.15) to secondary (weight 0.3) in
-- src/lib/career-discovery/v31/option-matrix.ts. No question wording,
-- option text, dimension spans or option values changed -- only the role
-- of two existing loadings.
--
-- This is a new OPTION_MATRIX_VERSION ('v3.1-draft-2', up from
-- 'v3.1-draft-1'), not an in-place edit of the original, already-applied
-- 20260730100000_career_discovery_v3_1_instrument.sql migration -- that
-- migration's v3.1-draft-1 rows stay exactly as they are, so any report
-- snapshot frozen under v3.1-draft-1 remains reproducible byte-for-byte.
-- This migration inserts the complete, current 164-row option matrix
-- (162 rows unchanged in content, 2 rows with role/role_weight corrected)
-- under the new version tag -- new candidates score under v3.1-draft-2,
-- nothing already recorded is touched.
--
-- Generated programmatically from option-matrix.ts's own FLAT_LOADINGS
-- export (see scripts/career-discovery-v31-check.ts group 11 for the
-- parity check against this file), not hand-typed, so it cannot drift
-- from the TypeScript source of truth.

-- 164 rows for scoring_version = 'v3.1-draft-2'
INSERT INTO public.cd_option_loadings
  (scoring_version, question_id, option_id, dimension_id, role, role_weight, value, rationale)
VALUES
  ('v3.1-draft-2', 'CQ02', 'CQ02_A', 'CID04', 'primary', 0.7, 1, 'Declared primary. The item is a trade-off between four kinds of work, and the technical option is the one that engages with a system directly.'),
  ('v3.1-draft-2', 'CQ02', 'CQ02_A', 'CID03', 'secondary', 0.3, 0.8, 'Declared secondary. Every option involves some degree of working out what is going on, which is analysis.'),
  ('v3.1-draft-2', 'CQ02', 'CQ02_A', 'CID11', 'tertiary', 0.15, 0.35, 'One option is explicitly about making work traceable through procedures and records, which is the structure dimension stated as a preferred task.'),
  ('v3.1-draft-2', 'CQ02', 'CQ02_A', 'CID07', 'tertiary', 0.15, 0.2, 'One option moves the work away from its object and onto the person receiving it, which is communication chosen over subject matter.'),
  ('v3.1-draft-2', 'CQ02', 'CQ02_A', 'CID08', 'tertiary', 0.15, 0.2, 'Choosing to help someone understand something difficult is service motivation expressed as a task preference rather than as a stated value.'),
  ('v3.1-draft-2', 'CQ02', 'CQ02_B', 'CID04', 'primary', 0.7, 0.45, 'Declared primary. The item is a trade-off between four kinds of work, and the technical option is the one that engages with a system directly.'),
  ('v3.1-draft-2', 'CQ02', 'CQ02_B', 'CID03', 'secondary', 0.3, 1, 'Declared secondary. Every option involves some degree of working out what is going on, which is analysis.'),
  ('v3.1-draft-2', 'CQ02', 'CQ02_B', 'CID11', 'tertiary', 0.15, 0.55, 'One option is explicitly about making work traceable through procedures and records, which is the structure dimension stated as a preferred task.'),
  ('v3.1-draft-2', 'CQ02', 'CQ02_B', 'CID07', 'tertiary', 0.15, 0.25, 'One option moves the work away from its object and onto the person receiving it, which is communication chosen over subject matter.'),
  ('v3.1-draft-2', 'CQ02', 'CQ02_B', 'CID08', 'tertiary', 0.15, 0.15, 'Choosing to help someone understand something difficult is service motivation expressed as a task preference rather than as a stated value.'),
  ('v3.1-draft-2', 'CQ02', 'CQ02_C', 'CID04', 'primary', 0.7, 0.35, 'Declared primary. The item is a trade-off between four kinds of work, and the technical option is the one that engages with a system directly.'),
  ('v3.1-draft-2', 'CQ02', 'CQ02_C', 'CID03', 'secondary', 0.3, 0.5, 'Declared secondary. Every option involves some degree of working out what is going on, which is analysis.'),
  ('v3.1-draft-2', 'CQ02', 'CQ02_C', 'CID11', 'tertiary', 0.15, 1, 'One option is explicitly about making work traceable through procedures and records, which is the structure dimension stated as a preferred task.'),
  ('v3.1-draft-2', 'CQ02', 'CQ02_C', 'CID07', 'tertiary', 0.15, 0.35, 'One option moves the work away from its object and onto the person receiving it, which is communication chosen over subject matter.'),
  ('v3.1-draft-2', 'CQ02', 'CQ02_C', 'CID08', 'tertiary', 0.15, 0.4, 'Choosing to help someone understand something difficult is service motivation expressed as a task preference rather than as a stated value.'),
  ('v3.1-draft-2', 'CQ02', 'CQ02_D', 'CID04', 'primary', 0.7, 0.15, 'Declared primary. The item is a trade-off between four kinds of work, and the technical option is the one that engages with a system directly.'),
  ('v3.1-draft-2', 'CQ02', 'CQ02_D', 'CID03', 'secondary', 0.3, 0.35, 'Declared secondary. Every option involves some degree of working out what is going on, which is analysis.'),
  ('v3.1-draft-2', 'CQ02', 'CQ02_D', 'CID11', 'tertiary', 0.15, 0.3, 'One option is explicitly about making work traceable through procedures and records, which is the structure dimension stated as a preferred task.'),
  ('v3.1-draft-2', 'CQ02', 'CQ02_D', 'CID07', 'tertiary', 0.15, 1, 'One option moves the work away from its object and onto the person receiving it, which is communication chosen over subject matter.'),
  ('v3.1-draft-2', 'CQ02', 'CQ02_D', 'CID08', 'tertiary', 0.15, 1, 'Choosing to help someone understand something difficult is service motivation expressed as a task preference rather than as a stated value.'),
  ('v3.1-draft-2', 'CQ03', 'CQ03_A', 'CID15', 'primary', 0.7, 0.65, 'Declared primary. All four options are responsible, so the item measures which responsible instinct fires first, not whether the candidate acts.'),
  ('v3.1-draft-2', 'CQ03', 'CQ03_A', 'CID06', 'secondary', 0.3, 0.85, 'Declared secondary. A skipped control is a risk event, and the options differ in how directly they address the exposure it created.'),
  ('v3.1-draft-2', 'CQ03', 'CQ03_A', 'CID10', 'tertiary', 0.15, 1, 'Establishing what may have been affected before deciding anything is investigative work: gather the facts, then judge.'),
  ('v3.1-draft-2', 'CQ03', 'CQ03_A', 'CID11', 'tertiary', 0.15, 0.4, 'Reporting and documenting according to procedure is the structure dimension observed as behaviour rather than self-reported as a preference.'),
  ('v3.1-draft-2', 'CQ03', 'CQ03_A', 'CID07', 'tertiary', 0.15, 0.2, 'Raising it directly with the person responsible requires initiating a difficult conversation, which is communication under real cost.'),
  ('v3.1-draft-2', 'CQ03', 'CQ03_A', 'CID09', 'tertiary', 0.15, 0.3, 'Telling a colleague their step was skipped means accepting resistance rather than routing around it, which is the boundary-setting dimension.'),
  ('v3.1-draft-2', 'CQ03', 'CQ03_B', 'CID15', 'primary', 0.7, 0.8, 'Declared primary. All four options are responsible, so the item measures which responsible instinct fires first, not whether the candidate acts.'),
  ('v3.1-draft-2', 'CQ03', 'CQ03_B', 'CID06', 'secondary', 0.3, 0.55, 'Declared secondary. A skipped control is a risk event, and the options differ in how directly they address the exposure it created.'),
  ('v3.1-draft-2', 'CQ03', 'CQ03_B', 'CID10', 'tertiary', 0.15, 0.45, 'Establishing what may have been affected before deciding anything is investigative work: gather the facts, then judge.'),
  ('v3.1-draft-2', 'CQ03', 'CQ03_B', 'CID11', 'tertiary', 0.15, 0.3, 'Reporting and documenting according to procedure is the structure dimension observed as behaviour rather than self-reported as a preference.'),
  ('v3.1-draft-2', 'CQ03', 'CQ03_B', 'CID07', 'tertiary', 0.15, 1, 'Raising it directly with the person responsible requires initiating a difficult conversation, which is communication under real cost.'),
  ('v3.1-draft-2', 'CQ03', 'CQ03_B', 'CID09', 'tertiary', 0.15, 1, 'Telling a colleague their step was skipped means accepting resistance rather than routing around it, which is the boundary-setting dimension.'),
  ('v3.1-draft-2', 'CQ03', 'CQ03_C', 'CID15', 'primary', 0.7, 1, 'Declared primary. All four options are responsible, so the item measures which responsible instinct fires first, not whether the candidate acts.'),
  ('v3.1-draft-2', 'CQ03', 'CQ03_C', 'CID06', 'secondary', 0.3, 0.7, 'Declared secondary. A skipped control is a risk event, and the options differ in how directly they address the exposure it created.'),
  ('v3.1-draft-2', 'CQ03', 'CQ03_C', 'CID10', 'tertiary', 0.15, 0.6, 'Establishing what may have been affected before deciding anything is investigative work: gather the facts, then judge.'),
  ('v3.1-draft-2', 'CQ03', 'CQ03_C', 'CID11', 'tertiary', 0.15, 1, 'Reporting and documenting according to procedure is the structure dimension observed as behaviour rather than self-reported as a preference.'),
  ('v3.1-draft-2', 'CQ03', 'CQ03_C', 'CID07', 'tertiary', 0.15, 0.4, 'Raising it directly with the person responsible requires initiating a difficult conversation, which is communication under real cost.'),
  ('v3.1-draft-2', 'CQ03', 'CQ03_C', 'CID09', 'tertiary', 0.15, 0.55, 'Telling a colleague their step was skipped means accepting resistance rather than routing around it, which is the boundary-setting dimension.'),
  ('v3.1-draft-2', 'CQ03', 'CQ03_D', 'CID15', 'primary', 0.7, 0.85, 'Declared primary. All four options are responsible, so the item measures which responsible instinct fires first, not whether the candidate acts.'),
  ('v3.1-draft-2', 'CQ03', 'CQ03_D', 'CID06', 'secondary', 0.3, 1, 'Declared secondary. A skipped control is a risk event, and the options differ in how directly they address the exposure it created.'),
  ('v3.1-draft-2', 'CQ03', 'CQ03_D', 'CID10', 'tertiary', 0.15, 0.55, 'Establishing what may have been affected before deciding anything is investigative work: gather the facts, then judge.'),
  ('v3.1-draft-2', 'CQ03', 'CQ03_D', 'CID11', 'tertiary', 0.15, 0.55, 'Reporting and documenting according to procedure is the structure dimension observed as behaviour rather than self-reported as a preference.'),
  ('v3.1-draft-2', 'CQ03', 'CQ03_D', 'CID07', 'tertiary', 0.15, 0.3, 'Raising it directly with the person responsible requires initiating a difficult conversation, which is communication under real cost.'),
  ('v3.1-draft-2', 'CQ03', 'CQ03_D', 'CID09', 'tertiary', 0.15, 0.7, 'Telling a colleague their step was skipped means accepting resistance rather than routing around it, which is the boundary-setting dimension.'),
  ('v3.1-draft-2', 'CQ06', 'CQ06_A', 'CID16', 'primary', 0.7, 0.9, 'Declared primary. The options differ in how much pressure each response absorbs before offloading the decision to someone else or to a group.'),
  ('v3.1-draft-2', 'CQ06', 'CQ06_A', 'CID10', 'secondary', 0.3, 1, 'Declared secondary. Conflicting accounts are an evidence problem, and the options differ in how much they try to establish before acting.'),
  ('v3.1-draft-2', 'CQ06', 'CQ06_A', 'CID12', 'tertiary', 0.15, 0.45, 'Deciding how to proceed and owning the outcome is independent decision-making observed at the moment it costs something.'),
  ('v3.1-draft-2', 'CQ06', 'CQ06_A', 'CID09', 'tertiary', 0.15, 0.55, 'Two people contradicting each other is a live disagreement, and the options differ in willingness to engage with it directly.'),
  ('v3.1-draft-2', 'CQ06', 'CQ06_A', 'CID02', 'secondary', 0.3, 0.35, 'Taking direction of a situation, or convening the people in it, is leadership expressed as behaviour rather than as stated ambition. Promoted from tertiary (Owner Approval Gate item 2, OPTION_MATRIX_VERSION v3.1-draft-2): this is direct observed leadership behaviour, not a stated preference, and CID02 previously had only one primary source across the whole instrument.'),
  ('v3.1-draft-2', 'CQ06', 'CQ06_B', 'CID16', 'primary', 0.7, 1, 'Declared primary. The options differ in how much pressure each response absorbs before offloading the decision to someone else or to a group.'),
  ('v3.1-draft-2', 'CQ06', 'CQ06_B', 'CID10', 'secondary', 0.3, 0.6, 'Declared secondary. Conflicting accounts are an evidence problem, and the options differ in how much they try to establish before acting.'),
  ('v3.1-draft-2', 'CQ06', 'CQ06_B', 'CID12', 'tertiary', 0.15, 0.85, 'Deciding how to proceed and owning the outcome is independent decision-making observed at the moment it costs something.'),
  ('v3.1-draft-2', 'CQ06', 'CQ06_B', 'CID09', 'tertiary', 0.15, 0.45, 'Two people contradicting each other is a live disagreement, and the options differ in willingness to engage with it directly.'),
  ('v3.1-draft-2', 'CQ06', 'CQ06_B', 'CID02', 'secondary', 0.3, 0.4, 'Taking direction of a situation, or convening the people in it, is leadership expressed as behaviour rather than as stated ambition. Promoted from tertiary (Owner Approval Gate item 2, OPTION_MATRIX_VERSION v3.1-draft-2): this is direct observed leadership behaviour, not a stated preference, and CID02 previously had only one primary source across the whole instrument.'),
  ('v3.1-draft-2', 'CQ06', 'CQ06_C', 'CID16', 'primary', 0.7, 0.8, 'Declared primary. The options differ in how much pressure each response absorbs before offloading the decision to someone else or to a group.'),
  ('v3.1-draft-2', 'CQ06', 'CQ06_C', 'CID10', 'secondary', 0.3, 0.25, 'Declared secondary. Conflicting accounts are an evidence problem, and the options differ in how much they try to establish before acting.'),
  ('v3.1-draft-2', 'CQ06', 'CQ06_C', 'CID12', 'tertiary', 0.15, 1, 'Deciding how to proceed and owning the outcome is independent decision-making observed at the moment it costs something.'),
  ('v3.1-draft-2', 'CQ06', 'CQ06_C', 'CID09', 'tertiary', 0.15, 0.85, 'Two people contradicting each other is a live disagreement, and the options differ in willingness to engage with it directly.'),
  ('v3.1-draft-2', 'CQ06', 'CQ06_C', 'CID02', 'secondary', 0.3, 1, 'Taking direction of a situation, or convening the people in it, is leadership expressed as behaviour rather than as stated ambition. Promoted from tertiary (Owner Approval Gate item 2, OPTION_MATRIX_VERSION v3.1-draft-2): this is direct observed leadership behaviour, not a stated preference, and CID02 previously had only one primary source across the whole instrument.'),
  ('v3.1-draft-2', 'CQ06', 'CQ06_D', 'CID16', 'primary', 0.7, 0.6, 'Declared primary. The options differ in how much pressure each response absorbs before offloading the decision to someone else or to a group.'),
  ('v3.1-draft-2', 'CQ06', 'CQ06_D', 'CID10', 'secondary', 0.3, 0.55, 'Declared secondary. Conflicting accounts are an evidence problem, and the options differ in how much they try to establish before acting.'),
  ('v3.1-draft-2', 'CQ06', 'CQ06_D', 'CID12', 'tertiary', 0.15, 0.3, 'Deciding how to proceed and owning the outcome is independent decision-making observed at the moment it costs something.'),
  ('v3.1-draft-2', 'CQ06', 'CQ06_D', 'CID09', 'tertiary', 0.15, 1, 'Two people contradicting each other is a live disagreement, and the options differ in willingness to engage with it directly.'),
  ('v3.1-draft-2', 'CQ06', 'CQ06_D', 'CID02', 'secondary', 0.3, 0.85, 'Taking direction of a situation, or convening the people in it, is leadership expressed as behaviour rather than as stated ambition. Promoted from tertiary (Owner Approval Gate item 2, OPTION_MATRIX_VERSION v3.1-draft-2): this is direct observed leadership behaviour, not a stated preference, and CID02 previously had only one primary source across the whole instrument.'),
  ('v3.1-draft-2', 'CQ09', 'CQ09_A', 'CID05', 'primary', 0.7, 0.15, 'Declared primary. The options run from solving the instance to removing the cause, which is exactly the short-to-long horizon this dimension describes.'),
  ('v3.1-draft-2', 'CQ09', 'CQ09_A', 'CID06', 'secondary', 0.3, 0.4, 'Declared secondary. A recurring problem is an unmanaged risk, and the options differ in how much they treat it as one.'),
  ('v3.1-draft-2', 'CQ09', 'CQ09_A', 'CID02', 'secondary', 0.3, 0.25, 'Convening the affected people and driving to a resolution is coordination and influence, measured without asking whether the candidate wants to manage. Promoted from tertiary (Owner Approval Gate item 2, OPTION_MATRIX_VERSION v3.1-draft-2): direct observed leadership behaviour, same reasoning as CQ06.'),
  ('v3.1-draft-2', 'CQ09', 'CQ09_A', 'CID11', 'tertiary', 0.15, 0.2, 'Building a routine so the problem cannot recur is the structure dimension applied preventively rather than administratively.'),
  ('v3.1-draft-2', 'CQ09', 'CQ09_A', 'CID01', 'tertiary', 0.15, 1, 'Solving it on the spot every time is hands-on, situation-near work: responsiveness rather than an absence of strategy.'),
  ('v3.1-draft-2', 'CQ09', 'CQ09_B', 'CID05', 'primary', 0.7, 1, 'Declared primary. The options run from solving the instance to removing the cause, which is exactly the short-to-long horizon this dimension describes.'),
  ('v3.1-draft-2', 'CQ09', 'CQ09_B', 'CID06', 'secondary', 0.3, 0.85, 'Declared secondary. A recurring problem is an unmanaged risk, and the options differ in how much they treat it as one.'),
  ('v3.1-draft-2', 'CQ09', 'CQ09_B', 'CID02', 'secondary', 0.3, 0.35, 'Convening the affected people and driving to a resolution is coordination and influence, measured without asking whether the candidate wants to manage. Promoted from tertiary (Owner Approval Gate item 2, OPTION_MATRIX_VERSION v3.1-draft-2): direct observed leadership behaviour, same reasoning as CQ06.'),
  ('v3.1-draft-2', 'CQ09', 'CQ09_B', 'CID11', 'tertiary', 0.15, 0.55, 'Building a routine so the problem cannot recur is the structure dimension applied preventively rather than administratively.'),
  ('v3.1-draft-2', 'CQ09', 'CQ09_B', 'CID01', 'tertiary', 0.15, 0.35, 'Solving it on the spot every time is hands-on, situation-near work: responsiveness rather than an absence of strategy.'),
  ('v3.1-draft-2', 'CQ09', 'CQ09_C', 'CID05', 'primary', 0.7, 0.7, 'Declared primary. The options run from solving the instance to removing the cause, which is exactly the short-to-long horizon this dimension describes.'),
  ('v3.1-draft-2', 'CQ09', 'CQ09_C', 'CID06', 'secondary', 0.3, 0.55, 'Declared secondary. A recurring problem is an unmanaged risk, and the options differ in how much they treat it as one.'),
  ('v3.1-draft-2', 'CQ09', 'CQ09_C', 'CID02', 'secondary', 0.3, 1, 'Convening the affected people and driving to a resolution is coordination and influence, measured without asking whether the candidate wants to manage. Promoted from tertiary (Owner Approval Gate item 2, OPTION_MATRIX_VERSION v3.1-draft-2): direct observed leadership behaviour, same reasoning as CQ06.'),
  ('v3.1-draft-2', 'CQ09', 'CQ09_C', 'CID11', 'tertiary', 0.15, 0.45, 'Building a routine so the problem cannot recur is the structure dimension applied preventively rather than administratively.'),
  ('v3.1-draft-2', 'CQ09', 'CQ09_C', 'CID01', 'tertiary', 0.15, 0.5, 'Solving it on the spot every time is hands-on, situation-near work: responsiveness rather than an absence of strategy.'),
  ('v3.1-draft-2', 'CQ09', 'CQ09_D', 'CID05', 'primary', 0.7, 0.85, 'Declared primary. The options run from solving the instance to removing the cause, which is exactly the short-to-long horizon this dimension describes.'),
  ('v3.1-draft-2', 'CQ09', 'CQ09_D', 'CID06', 'secondary', 0.3, 1, 'Declared secondary. A recurring problem is an unmanaged risk, and the options differ in how much they treat it as one.'),
  ('v3.1-draft-2', 'CQ09', 'CQ09_D', 'CID02', 'secondary', 0.3, 0.4, 'Convening the affected people and driving to a resolution is coordination and influence, measured without asking whether the candidate wants to manage. Promoted from tertiary (Owner Approval Gate item 2, OPTION_MATRIX_VERSION v3.1-draft-2): direct observed leadership behaviour, same reasoning as CQ06.'),
  ('v3.1-draft-2', 'CQ09', 'CQ09_D', 'CID11', 'tertiary', 0.15, 1, 'Building a routine so the problem cannot recur is the structure dimension applied preventively rather than administratively.'),
  ('v3.1-draft-2', 'CQ09', 'CQ09_D', 'CID01', 'tertiary', 0.15, 0.3, 'Solving it on the spot every time is hands-on, situation-near work: responsiveness rather than an absence of strategy.'),
  ('v3.1-draft-2', 'CQ12', 'CQ12_A', 'CID15', 'primary', 0.7, 0.85, 'Declared primary. All four responses to being wrong are creditable, so the item distinguishes style — verify, revise openly, consult, or understand the original reasoning.'),
  ('v3.1-draft-2', 'CQ12', 'CQ12_A', 'CID14', 'secondary', 0.3, 0.65, 'Declared secondary. Being corrected is a learning event, and the options differ in how much they treat it as one.'),
  ('v3.1-draft-2', 'CQ12', 'CQ12_A', 'CID12', 'tertiary', 0.15, 1, 'Working through the new information alone before changing anything is independent judgement; asking someone to look at it together is deliberately not.'),
  ('v3.1-draft-2', 'CQ12', 'CQ12_A', 'CID13', 'tertiary', 0.15, 0.25, 'Bringing in a second perspective on your own possible error is collaboration chosen at the point where it is least comfortable.'),
  ('v3.1-draft-2', 'CQ12', 'CQ12_B', 'CID15', 'primary', 0.7, 1, 'Declared primary. All four responses to being wrong are creditable, so the item distinguishes style — verify, revise openly, consult, or understand the original reasoning.'),
  ('v3.1-draft-2', 'CQ12', 'CQ12_B', 'CID14', 'secondary', 0.3, 0.85, 'Declared secondary. Being corrected is a learning event, and the options differ in how much they treat it as one.'),
  ('v3.1-draft-2', 'CQ12', 'CQ12_B', 'CID12', 'tertiary', 0.15, 0.85, 'Working through the new information alone before changing anything is independent judgement; asking someone to look at it together is deliberately not.'),
  ('v3.1-draft-2', 'CQ12', 'CQ12_B', 'CID13', 'tertiary', 0.15, 0.55, 'Bringing in a second perspective on your own possible error is collaboration chosen at the point where it is least comfortable.'),
  ('v3.1-draft-2', 'CQ12', 'CQ12_C', 'CID15', 'primary', 0.7, 0.8, 'Declared primary. All four responses to being wrong are creditable, so the item distinguishes style — verify, revise openly, consult, or understand the original reasoning.'),
  ('v3.1-draft-2', 'CQ12', 'CQ12_C', 'CID14', 'secondary', 0.3, 0.9, 'Declared secondary. Being corrected is a learning event, and the options differ in how much they treat it as one.'),
  ('v3.1-draft-2', 'CQ12', 'CQ12_C', 'CID12', 'tertiary', 0.15, 0.2, 'Working through the new information alone before changing anything is independent judgement; asking someone to look at it together is deliberately not.'),
  ('v3.1-draft-2', 'CQ12', 'CQ12_C', 'CID13', 'tertiary', 0.15, 1, 'Bringing in a second perspective on your own possible error is collaboration chosen at the point where it is least comfortable.'),
  ('v3.1-draft-2', 'CQ12', 'CQ12_D', 'CID15', 'primary', 0.7, 0.75, 'Declared primary. All four responses to being wrong are creditable, so the item distinguishes style — verify, revise openly, consult, or understand the original reasoning.'),
  ('v3.1-draft-2', 'CQ12', 'CQ12_D', 'CID14', 'secondary', 0.3, 1, 'Declared secondary. Being corrected is a learning event, and the options differ in how much they treat it as one.'),
  ('v3.1-draft-2', 'CQ12', 'CQ12_D', 'CID12', 'tertiary', 0.15, 0.6, 'Working through the new information alone before changing anything is independent judgement; asking someone to look at it together is deliberately not.'),
  ('v3.1-draft-2', 'CQ12', 'CQ12_D', 'CID13', 'tertiary', 0.15, 0.35, 'Bringing in a second perspective on your own possible error is collaboration chosen at the point where it is least comfortable.'),
  ('v3.1-draft-2', 'CQ15', 'CQ15_A', 'CID01', 'primary', 0.7, 1, 'Declared primary. The options differ in distance from the daily operation, which is what this dimension measures.'),
  ('v3.1-draft-2', 'CQ15', 'CQ15_A', 'CID13', 'secondary', 0.3, 0.55, 'Declared secondary. Environment and company are inseparable: choosing a team is choosing shared responsibility.'),
  ('v3.1-draft-2', 'CQ15', 'CQ15_A', 'CID12', 'tertiary', 0.15, 0.4, 'Preferring own responsibility and uninterrupted time is autonomy stated as a working condition rather than as a decision-making claim.'),
  ('v3.1-draft-2', 'CQ15', 'CQ15_A', 'CID04', 'tertiary', 0.15, 0.3, 'Choosing to be close to systems you are responsible for is technical orientation expressed as where you want to sit, not as what you enjoy.'),
  ('v3.1-draft-2', 'CQ15', 'CQ15_A', 'CID08', 'tertiary', 0.15, 0.7, 'Environments close to daily operations and to a team are where being useful to people is most immediate. Supporting evidence only; no environment is the strongest possible statement of service motivation.'),
  ('v3.1-draft-2', 'CQ15', 'CQ15_A', 'CID02', 'tertiary', 0.15, 0.35, 'Preferring a shared-goal environment with close contact is consistent with leadership orientation without being decisive for it. Supporting evidence only.'),
  ('v3.1-draft-2', 'CQ15', 'CQ15_B', 'CID01', 'primary', 0.7, 0.55, 'Declared primary. The options differ in distance from the daily operation, which is what this dimension measures.'),
  ('v3.1-draft-2', 'CQ15', 'CQ15_B', 'CID13', 'secondary', 0.3, 1, 'Declared secondary. Environment and company are inseparable: choosing a team is choosing shared responsibility.'),
  ('v3.1-draft-2', 'CQ15', 'CQ15_B', 'CID12', 'tertiary', 0.15, 0.3, 'Preferring own responsibility and uninterrupted time is autonomy stated as a working condition rather than as a decision-making claim.'),
  ('v3.1-draft-2', 'CQ15', 'CQ15_B', 'CID04', 'tertiary', 0.15, 0.3, 'Choosing to be close to systems you are responsible for is technical orientation expressed as where you want to sit, not as what you enjoy.'),
  ('v3.1-draft-2', 'CQ15', 'CQ15_B', 'CID08', 'tertiary', 0.15, 0.65, 'Environments close to daily operations and to a team are where being useful to people is most immediate. Supporting evidence only; no environment is the strongest possible statement of service motivation.'),
  ('v3.1-draft-2', 'CQ15', 'CQ15_B', 'CID02', 'tertiary', 0.15, 0.7, 'Preferring a shared-goal environment with close contact is consistent with leadership orientation without being decisive for it. Supporting evidence only.'),
  ('v3.1-draft-2', 'CQ15', 'CQ15_C', 'CID01', 'primary', 0.7, 0.3, 'Declared primary. The options differ in distance from the daily operation, which is what this dimension measures.'),
  ('v3.1-draft-2', 'CQ15', 'CQ15_C', 'CID13', 'secondary', 0.3, 0.2, 'Declared secondary. Environment and company are inseparable: choosing a team is choosing shared responsibility.'),
  ('v3.1-draft-2', 'CQ15', 'CQ15_C', 'CID12', 'tertiary', 0.15, 1, 'Preferring own responsibility and uninterrupted time is autonomy stated as a working condition rather than as a decision-making claim.'),
  ('v3.1-draft-2', 'CQ15', 'CQ15_C', 'CID04', 'tertiary', 0.15, 0.6, 'Choosing to be close to systems you are responsible for is technical orientation expressed as where you want to sit, not as what you enjoy.'),
  ('v3.1-draft-2', 'CQ15', 'CQ15_C', 'CID08', 'tertiary', 0.15, 0.25, 'Environments close to daily operations and to a team are where being useful to people is most immediate. Supporting evidence only; no environment is the strongest possible statement of service motivation.'),
  ('v3.1-draft-2', 'CQ15', 'CQ15_C', 'CID02', 'tertiary', 0.15, 0.2, 'Preferring a shared-goal environment with close contact is consistent with leadership orientation without being decisive for it. Supporting evidence only.'),
  ('v3.1-draft-2', 'CQ15', 'CQ15_D', 'CID01', 'primary', 0.7, 0.45, 'Declared primary. The options differ in distance from the daily operation, which is what this dimension measures.'),
  ('v3.1-draft-2', 'CQ15', 'CQ15_D', 'CID13', 'secondary', 0.3, 0.35, 'Declared secondary. Environment and company are inseparable: choosing a team is choosing shared responsibility.'),
  ('v3.1-draft-2', 'CQ15', 'CQ15_D', 'CID12', 'tertiary', 0.15, 0.65, 'Preferring own responsibility and uninterrupted time is autonomy stated as a working condition rather than as a decision-making claim.'),
  ('v3.1-draft-2', 'CQ15', 'CQ15_D', 'CID04', 'tertiary', 0.15, 1, 'Choosing to be close to systems you are responsible for is technical orientation expressed as where you want to sit, not as what you enjoy.'),
  ('v3.1-draft-2', 'CQ15', 'CQ15_D', 'CID08', 'tertiary', 0.15, 0.3, 'Environments close to daily operations and to a team are where being useful to people is most immediate. Supporting evidence only; no environment is the strongest possible statement of service motivation.'),
  ('v3.1-draft-2', 'CQ15', 'CQ15_D', 'CID02', 'tertiary', 0.15, 0.3, 'Preferring a shared-goal environment with close contact is consistent with leadership orientation without being decisive for it. Supporting evidence only.'),
  ('v3.1-draft-2', 'CQ17', 'CQ17_A', 'CID10', 'primary', 0.7, 1, 'Declared primary. The options differ in how much each prioritises establishing what actually happened over other legitimate follow-ups.'),
  ('v3.1-draft-2', 'CQ17', 'CQ17_A', 'CID03', 'secondary', 0.3, 0.85, 'Declared secondary. Both establishing the cause and judging recurrence require reasoning from incomplete information.'),
  ('v3.1-draft-2', 'CQ17', 'CQ17_A', 'CID14', 'tertiary', 0.15, 0.6, 'Turning an incident into something the organisation learns from is the learning dimension applied outward rather than to oneself.'),
  ('v3.1-draft-2', 'CQ17', 'CQ17_A', 'CID11', 'tertiary', 0.15, 0.45, 'Securing the record before memory degrades is a genuinely expert instinct and is the structure dimension under time pressure.'),
  ('v3.1-draft-2', 'CQ17', 'CQ17_A', 'CID06', 'tertiary', 0.15, 0.7, 'Asking whether it can happen again and what that would mean is risk awareness applied to a concrete event rather than in the abstract.'),
  ('v3.1-draft-2', 'CQ17', 'CQ17_B', 'CID10', 'primary', 0.7, 0.7, 'Declared primary. The options differ in how much each prioritises establishing what actually happened over other legitimate follow-ups.'),
  ('v3.1-draft-2', 'CQ17', 'CQ17_B', 'CID03', 'secondary', 0.3, 0.45, 'Declared secondary. Both establishing the cause and judging recurrence require reasoning from incomplete information.'),
  ('v3.1-draft-2', 'CQ17', 'CQ17_B', 'CID14', 'tertiary', 0.15, 0.4, 'Turning an incident into something the organisation learns from is the learning dimension applied outward rather than to oneself.'),
  ('v3.1-draft-2', 'CQ17', 'CQ17_B', 'CID11', 'tertiary', 0.15, 1, 'Securing the record before memory degrades is a genuinely expert instinct and is the structure dimension under time pressure.'),
  ('v3.1-draft-2', 'CQ17', 'CQ17_B', 'CID06', 'tertiary', 0.15, 0.6, 'Asking whether it can happen again and what that would mean is risk awareness applied to a concrete event rather than in the abstract.'),
  ('v3.1-draft-2', 'CQ17', 'CQ17_C', 'CID10', 'primary', 0.7, 0.55, 'Declared primary. The options differ in how much each prioritises establishing what actually happened over other legitimate follow-ups.'),
  ('v3.1-draft-2', 'CQ17', 'CQ17_C', 'CID03', 'secondary', 0.3, 0.9, 'Declared secondary. Both establishing the cause and judging recurrence require reasoning from incomplete information.'),
  ('v3.1-draft-2', 'CQ17', 'CQ17_C', 'CID14', 'tertiary', 0.15, 0.5, 'Turning an incident into something the organisation learns from is the learning dimension applied outward rather than to oneself.'),
  ('v3.1-draft-2', 'CQ17', 'CQ17_C', 'CID11', 'tertiary', 0.15, 0.5, 'Securing the record before memory degrades is a genuinely expert instinct and is the structure dimension under time pressure.'),
  ('v3.1-draft-2', 'CQ17', 'CQ17_C', 'CID06', 'tertiary', 0.15, 1, 'Asking whether it can happen again and what that would mean is risk awareness applied to a concrete event rather than in the abstract.'),
  ('v3.1-draft-2', 'CQ17', 'CQ17_D', 'CID10', 'primary', 0.7, 0.45, 'Declared primary. The options differ in how much each prioritises establishing what actually happened over other legitimate follow-ups.'),
  ('v3.1-draft-2', 'CQ17', 'CQ17_D', 'CID03', 'secondary', 0.3, 0.6, 'Declared secondary. Both establishing the cause and judging recurrence require reasoning from incomplete information.'),
  ('v3.1-draft-2', 'CQ17', 'CQ17_D', 'CID14', 'tertiary', 0.15, 1, 'Turning an incident into something the organisation learns from is the learning dimension applied outward rather than to oneself.'),
  ('v3.1-draft-2', 'CQ17', 'CQ17_D', 'CID11', 'tertiary', 0.15, 0.55, 'Securing the record before memory degrades is a genuinely expert instinct and is the structure dimension under time pressure.'),
  ('v3.1-draft-2', 'CQ17', 'CQ17_D', 'CID06', 'tertiary', 0.15, 0.75, 'Asking whether it can happen again and what that would mean is risk awareness applied to a concrete event rather than in the abstract.'),
  ('v3.1-draft-2', 'CQ20', 'CQ20_A', 'CID08', 'primary', 0.7, 1, 'Declared primary. The options differ in how much the satisfaction comes from someone else being better off.'),
  ('v3.1-draft-2', 'CQ20', 'CQ20_A', 'CID05', 'secondary', 0.3, 0.25, 'Declared secondary. Finding meaning in something working better tomorrow than yesterday is a long-horizon orientation.'),
  ('v3.1-draft-2', 'CQ20', 'CQ20_A', 'CID02', 'tertiary', 0.15, 0.3, 'Satisfaction from having supported someone who then moved forward is the ''developing others'' clause of this dimension, observed as motivation rather than ambition.'),
  ('v3.1-draft-2', 'CQ20', 'CQ20_A', 'CID14', 'tertiary', 0.15, 0.35, 'Finding a day meaningful because you learned something you could not do before is the learning dimension stated without apology.'),
  ('v3.1-draft-2', 'CQ20', 'CQ20_A', 'CID13', 'tertiary', 0.15, 0.55, 'Locating meaning in what the team delivered rather than in personal output is collaboration expressed as what counts as a good day.'),
  ('v3.1-draft-2', 'CQ20', 'CQ20_B', 'CID08', 'primary', 0.7, 0.55, 'Declared primary. The options differ in how much the satisfaction comes from someone else being better off.'),
  ('v3.1-draft-2', 'CQ20', 'CQ20_B', 'CID05', 'secondary', 0.3, 1, 'Declared secondary. Finding meaning in something working better tomorrow than yesterday is a long-horizon orientation.'),
  ('v3.1-draft-2', 'CQ20', 'CQ20_B', 'CID02', 'tertiary', 0.15, 0.5, 'Satisfaction from having supported someone who then moved forward is the ''developing others'' clause of this dimension, observed as motivation rather than ambition.'),
  ('v3.1-draft-2', 'CQ20', 'CQ20_B', 'CID14', 'tertiary', 0.15, 0.65, 'Finding a day meaningful because you learned something you could not do before is the learning dimension stated without apology.'),
  ('v3.1-draft-2', 'CQ20', 'CQ20_B', 'CID13', 'tertiary', 0.15, 0.45, 'Locating meaning in what the team delivered rather than in personal output is collaboration expressed as what counts as a good day.'),
  ('v3.1-draft-2', 'CQ20', 'CQ20_C', 'CID08', 'primary', 0.7, 0.75, 'Declared primary. The options differ in how much the satisfaction comes from someone else being better off.'),
  ('v3.1-draft-2', 'CQ20', 'CQ20_C', 'CID05', 'secondary', 0.3, 0.6, 'Declared secondary. Finding meaning in something working better tomorrow than yesterday is a long-horizon orientation.'),
  ('v3.1-draft-2', 'CQ20', 'CQ20_C', 'CID02', 'tertiary', 0.15, 1, 'Satisfaction from having supported someone who then moved forward is the ''developing others'' clause of this dimension, observed as motivation rather than ambition.'),
  ('v3.1-draft-2', 'CQ20', 'CQ20_C', 'CID14', 'tertiary', 0.15, 0.7, 'Finding a day meaningful because you learned something you could not do before is the learning dimension stated without apology.'),
  ('v3.1-draft-2', 'CQ20', 'CQ20_C', 'CID13', 'tertiary', 0.15, 1, 'Locating meaning in what the team delivered rather than in personal output is collaboration expressed as what counts as a good day.'),
  ('v3.1-draft-2', 'CQ20', 'CQ20_D', 'CID08', 'primary', 0.7, 0.3, 'Declared primary. The options differ in how much the satisfaction comes from someone else being better off.'),
  ('v3.1-draft-2', 'CQ20', 'CQ20_D', 'CID05', 'secondary', 0.3, 0.45, 'Declared secondary. Finding meaning in something working better tomorrow than yesterday is a long-horizon orientation.'),
  ('v3.1-draft-2', 'CQ20', 'CQ20_D', 'CID02', 'tertiary', 0.15, 0.25, 'Satisfaction from having supported someone who then moved forward is the ''developing others'' clause of this dimension, observed as motivation rather than ambition.'),
  ('v3.1-draft-2', 'CQ20', 'CQ20_D', 'CID14', 'tertiary', 0.15, 1, 'Finding a day meaningful because you learned something you could not do before is the learning dimension stated without apology.'),
  ('v3.1-draft-2', 'CQ20', 'CQ20_D', 'CID13', 'tertiary', 0.15, 0.25, 'Locating meaning in what the team delivered rather than in personal output is collaboration expressed as what counts as a good day.')
ON CONFLICT (scoring_version, question_id, option_id, dimension_id) DO NOTHING;
