-- ============================================================================
-- TRUST conduct guidance for Target, Ready and Trace
-- ============================================================================
--
-- The conduct sequence added in 20261002090000 covers Understand -- the live
-- conversation. This covers the three stages either side of it, and it is the
-- same kind of thing: deterministic governed rows, pinned to a TRUST method
-- version, generated by nothing.
--
-- One table rather than five, because these are all the same shape (an ordered
-- bilingual line of guidance shown on one surface) and five near-identical
-- tables would be five places to forget to translate. `surface` says where a
-- row belongs; nothing about a row's meaning is encoded anywhere else.
--
-- What this is NOT: a second methodology. There is no new acronym, no new
-- stage, no parallel module. Every row hangs off an existing TRUST stage and
-- changes no stage binding and no AI task permission. Understand still permits
-- zero model calls, and every row here is content a human reads.
--
-- On provenance: this guidance is CQrityjob's own governed design. It is a
-- research-grounded design hypothesis under controlled validation, not a
-- validated instrument, and no row here registers a research claim. In
-- particular, no secondary commercial overview of interview techniques is
-- recorded as validation of anything: where a primary source is eventually
-- traced and independently verified, it enters through scp_research_claims in
-- draft and stays there until a qualified human approves it.
-- ============================================================================

CREATE TABLE public.scp_interview_conduct_guidance (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  method_id uuid NOT NULL REFERENCES public.scp_interview_methods(id) ON DELETE CASCADE,

  -- Which TRUST stage this belongs to. Recorded explicitly rather than derived
  -- from `surface`, so a stage binding is auditable on its own.
  trust_stage text NOT NULL CHECK (trust_stage IN ('target', 'ready', 'understand', 'structure', 'trace')),

  surface text NOT NULL CHECK (surface IN (
    'target_purpose',          -- what this interview is for
    'target_evidence_class',   -- the five things that must not be conflated
    'ready_plan',              -- how the interviewer will conduct it
    'recall_prompt',           -- permitted neutral prompts
    'trace_self_review',       -- the interviewer reviews their own conduct
    'trace_closure')),         -- closing the case honestly

  guidance_key text NOT NULL,
  statement_sv text NOT NULL,
  statement_en text NOT NULL,
  display_order integer NOT NULL DEFAULT 1,

  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (method_id, surface, guidance_key)
);

COMMENT ON TABLE public.scp_interview_conduct_guidance IS
  'Deterministic governed interviewer guidance for the TRUST stages either '
  'side of the live conversation. Rows, not generation. Changes no stage '
  'binding and no AI task permission; adds no methodology beside TRUST.';

CREATE INDEX scp_interview_conduct_guidance_lookup_idx
  ON public.scp_interview_conduct_guidance (method_id, surface, display_order);

ALTER TABLE public.scp_interview_conduct_guidance ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON public.scp_interview_conduct_guidance FROM PUBLIC, anon, authenticated;
GRANT SELECT ON public.scp_interview_conduct_guidance TO authenticated;
GRANT ALL ON public.scp_interview_conduct_guidance TO service_role;

CREATE POLICY scp_interview_conduct_guidance_read ON public.scp_interview_conduct_guidance
  FOR SELECT TO authenticated USING (
    public.scp_interview_can_read(auth.uid())
    OR EXISTS (SELECT 1 FROM public.employer_memberships em
                WHERE em.user_id = auth.uid() AND em.status = 'active'));


INSERT INTO public.scp_interview_conduct_guidance
  (method_id, trust_stage, surface, guidance_key, statement_sv, statement_en, display_order)
SELECT m.id, v.stage, v.surface, v.k, v.sv, v.en, v.ord
  FROM public.scp_interview_methods m
 CROSS JOIN (VALUES

  -- ── TARGET ── what this interview is for, stated before it starts ────────
  ('target', 'target_purpose', 'establish', 1,
   'Vad som ska klarläggas: vilken rollrelaterad information intervjun ska ge underlag om.',
   'What must be established: which role-related information this interview is meant to produce material about.'),
  ('target', 'target_purpose', 'evidence_sought', 2,
   'Vilken evidens som söks: konkreta arbetslivsexempel kopplade till paketets frågor.',
   'What evidence is sought: concrete working-life examples tied to the pack''s questions.'),
  ('target', 'target_purpose', 'verify_elsewhere', 3,
   'Vad som måste verifieras via annan källa: intyg, referens eller behörighet kontrolleras inte i ett samtal.',
   'What must be verified through another source: certificates, references and authorisations are not checked in a conversation.'),
  ('target', 'target_purpose', 'must_not_infer', 4,
   'Vad som inte får härledas ur intervjun: personlighet, trovärdighet, lämplighet eller anställningsbeslut.',
   'What must not be inferred from the interview: personality, credibility, suitability, or an employment decision.'),

  -- ── TARGET ── the five things a reader must never conflate ──────────────
  ('target', 'target_evidence_class', 'established_requirement', 1,
   'Fastställt krav — står i rollen och är godkänt av innehållsägaren.',
   'Established requirement — stated in the role and approved by the content owner.'),
  ('target', 'target_evidence_class', 'candidate_statement', 2,
   'Kandidatens uppgift — vad personen sagt. Det är en uppgift, inte ett fastställt faktum.',
   'Candidate statement — what the person said. That is a statement, not an established fact.'),
  ('target', 'target_evidence_class', 'supporting_example', 3,
   'Underbyggande exempel — en konkret händelse som personen beskrivit och som du bekräftat som evidens.',
   'Supporting example — a concrete event the person described, which you confirmed as evidence.'),
  ('target', 'target_evidence_class', 'verification_point', 4,
   'Olöst verifieringspunkt — något som behöver kontrolleras någon annanstans innan det kan användas.',
   'Unresolved verification point — something that must be checked elsewhere before it can be used.'),
  ('target', 'target_evidence_class', 'human_interpretation', 5,
   'Mänsklig tolkning — din bedömning. Den är din, den är märkt som din, och den ersätter inte de fyra ovan.',
   'Human interpretation — your judgement. It is yours, it is labelled as yours, and it does not replace the four above.'),

  -- ── READY ── the conduct plan the interviewer approves before starting ──
  ('ready', 'ready_plan', 'information_gathering', 1,
   'Arbeta informationsinhämtande och icke-konfrontativt. Målet är ett användbart underlag, inte ett erkännande.',
   'Work in an information-gathering, non-adversarial way. The goal is usable material, not an admission.'),
  ('ready', 'ready_plan', 'explain_process', 2,
   'Förklara upplägget och bevara personens självbestämmande: vad som ska hända, varför, och att personen får avstå eller pausa.',
   'Explain the process and preserve the person''s autonomy: what will happen, why, and that they may decline or pause.'),
  ('ready', 'ready_plan', 'open_before_clarifying', 3,
   'Ställ öppna frågor före klargörande frågor. Klargör det som faktiskt sades, inte det du förväntade dig.',
   'Ask open questions before clarification questions. Clarify what was actually said, not what you expected.'),
  ('ready', 'ready_plan', 'listen_without_interrupting', 4,
   'Lyssna utan onödiga avbrott. Låt pauser vara pauser.',
   'Listen without unnecessary interruption. Let pauses be pauses.'),
  ('ready', 'ready_plan', 'reflect_before_interpreting', 5,
   'Återge personens innebörd innan du tolkar den. Kontrollera att du förstod rätt.',
   'Reflect the person''s meaning back before interpreting it. Check that you understood correctly.'),
  ('ready', 'ready_plan', 'neutral_clarification', 6,
   'Klargör neutralt. "Vad gjorde du?" — inte "varför gjorde du inte".',
   'Clarify neutrally. "What did you do?" — not "why didn''t you".'),
  ('ready', 'ready_plan', 'summarise_allow_correction', 7,
   'Sammanfatta och låt personen rätta. Det som rättas är också information.',
   'Summarise and let the person correct you. What gets corrected is information too.'),
  ('ready', 'ready_plan', 'no_leading_or_pressure', 8,
   'Undvik ledande, pressande eller suggestiva formuleringar, och upprepa inte en fråga för att skapa motsägelse.',
   'Avoid leading, pressuring or suggestive wording, and do not repeat a question in order to manufacture an inconsistency.'),

  -- ── READY ── the permitted neutral prompts, written out ─────────────────
  ('ready', 'recall_prompt', 'before', 1,
   'Vad hände direkt före det här?',
   'What happened immediately before this?'),
  ('ready', 'recall_prompt', 'own_action', 2,
   'Vad gjorde du själv?',
   'What did you personally do?'),
  ('ready', 'recall_prompt', 'next', 3,
   'Vad hände sedan?',
   'What happened next?'),
  ('ready', 'recall_prompt', 'observable_result', 4,
   'Vad blev det observerbara resultatet?',
   'What was the observable result?'),
  ('ready', 'recall_prompt', 'differently_today', 5,
   'Vad skulle du göra annorlunda idag?',
   'What would you do differently today?'),

  -- ── TRACE ── the interviewer reviews their own conduct, not the person ──
  ('trace', 'trace_self_review', 'led', 1,
   'Ledde jag kandidaten?',
   'Did I lead the candidate?'),
  ('trace', 'trace_self_review', 'interrupted', 2,
   'Avbröt jag i onödan?',
   'Did I interrupt unnecessarily?'),
  ('trace', 'trace_self_review', 'pressure', 3,
   'Utövade jag press?',
   'Did I apply pressure?'),
  ('trace', 'trace_self_review', 'interpretation_as_evidence', 4,
   'Blandade jag ihop min tolkning med evidens?',
   'Did I confuse my interpretation with evidence?'),
  ('trace', 'trace_self_review', 'allowed_correction', 5,
   'Lät jag kandidaten rätta och komplettera?',
   'Did I allow the candidate to correct and add information?'),

  -- ── TRACE ── closing honestly ───────────────────────────────────────────
  ('trace', 'trace_closure', 'unresolved_items', 1,
   'Lista kvarstående verifieringspunkter öppet. En olöst punkt är en olöst punkt, inte en negativ signal.',
   'List the remaining verification points openly. An unresolved point is an unresolved point, not a negative signal.'),
  ('trace', 'trace_closure', 'inconsistency', 2,
   'Om något behöver klargöras: visa det öppet och ställ en neutral fråga. Motsägelse är inte oärlighet.',
   'If something needs clarifying: show it openly and ask a neutral question. An inconsistency is not dishonesty.'),
  ('trace', 'trace_closure', 'candidate_completion', 3,
   'Ge kandidaten möjlighet att komplettera eller rätta innan underlaget stängs, när det är rimligt.',
   'Give the candidate an opportunity to complete or correct the record before it is closed, where that is reasonable.')

) AS v(stage, surface, k, ord, sv, en);


-- ────────────────────────────────────────────────────────────────────────────
-- Self-check.
-- ────────────────────────────────────────────────────────────────────────────
DO $$
DECLARE _methods integer; _bad integer; _expected integer;
BEGIN
  SELECT count(*) INTO _methods FROM public.scp_interview_methods;
  _expected := _methods * 30;  -- 4 + 5 + 8 + 5 + 5 + 3

  IF (SELECT count(*) FROM public.scp_interview_conduct_guidance) <> _expected THEN
    RAISE EXCEPTION 'SCP_IV_GUIDANCE: expected % rows, found %.',
      _expected, (SELECT count(*) FROM public.scp_interview_conduct_guidance);
  END IF;

  SELECT count(*) INTO _bad FROM public.scp_interview_conduct_guidance
   WHERE btrim(statement_sv) = '' OR btrim(statement_en) = '';
  IF _bad > 0 THEN
    RAISE EXCEPTION 'SCP_IV_GUIDANCE: % row(s) do not read in both languages.', _bad;
  END IF;

  -- Every surface must be populated. A surface that silently has no rows is a
  -- blank panel on a recruiter's screen that looks like a finished feature.
  IF (SELECT count(DISTINCT surface) FROM public.scp_interview_conduct_guidance) <> 6 THEN
    RAISE EXCEPTION 'SCP_IV_GUIDANCE: not every guidance surface has content.';
  END IF;

  -- The stage bindings are unchanged by this migration, and this guidance must
  -- not have quietly introduced an Understand-stage row: Understand's support
  -- is the conduct sequence table, and its zero-AI boundary is not touched
  -- from here.
  IF EXISTS (SELECT 1 FROM public.scp_interview_conduct_guidance WHERE trust_stage = 'understand') THEN
    RAISE EXCEPTION 'SCP_IV_GUIDANCE: Understand guidance belongs in scp_interview_conduct_steps.';
  END IF;

  RAISE NOTICE
    'SCP_IV_GUIDANCE: % governed guidance rows across Target, Ready and Trace, '
    'in both languages, generated by nothing.', _expected;
END $$;
