-- Created with supabase migration new; only the filename was moved forward
-- to the next canonical slot because this repository's ledger leads the clock.
--
-- Automatic receipts for received applications ("Autosvar vid mottagen
-- ansökan"), per recruitment.
--
-- ── WHAT IT IS, AND IS NOT ────────────────────────────────────────────────
--
-- When a candidate's application has been SAVED CORRECTLY -- the row, the
-- required answers and the rest of the same transaction -- the recruitment
-- may send one message back: "we have received your application". It is a
-- fixed text the employer wrote (or the standard text), rendered with the
-- candidate's name, the vacancy, the company and a link to the application.
-- It is not generated by a model, it says nothing about the candidate's
-- chances, and it moves nothing: the application stays exactly where it is.
--
-- ── WHERE IT LIVES ───────────────────────────────────────────────────────
--
-- In the message history that already exists (recruitment_messages), as a
-- message of kind 'receipt': the candidate sees it under Mina ansökningar
-- exactly like a message a person sent, the employer sees it on the
-- application with its delivery status, and the e-mail copy goes through
-- the same claim / settle pair the workspace already uses. Nothing is
-- stored twice and nothing is retried from a second queue.
--
-- ── THE FOUR RULES ───────────────────────────────────────────────────────
--
--   ONE PER APPLICATION, AT THE COMMIT   a deferred constraint trigger
--       writes the receipt at COMMIT of the application's own transaction,
--       after 20261208090000's required-answers backstop has had its say.
--       A submission that fails or is abandoned never commits, so it never
--       has a receipt. A partial unique index makes a second receipt for
--       the same application impossible, whatever the client does.
--   NOTHING RETROACTIVE   the trigger fires on INSERT only. Switching the
--       receipt on, or changing its text, changes what FUTURE applications
--       get; no existing application is written to.
--   THE TEXT USED IS THE TEXT KEPT   the receipt row holds the rendered
--       subject and body in the language it was sent in. A later change to
--       the template does not change it.
--   THE E-MAIL IS A SECOND CHANNEL WITH ITS OWN TRUTH   the row is created
--       with the e-mail not yet attempted. The server sends it after the
--       commit and settles the outcome; a claim that was never settled is
--       reported as UNKNOWN, never silently treated as "nothing was sent",
--       and is retried only when a person asks. A mail outage never touches
--       the application.
--
-- Who may change the setting: exactly who may write to candidates
-- (rec_can_manage -- owner, admin, or the person responsible). The server
-- checks the same rule; this is where it is enforced.
--
-- The product switches the receipt ON, with the standard text, when it
-- creates a recruitment, so it is visible before publication; the database
-- default is OFF, which is what every recruitment that exists today keeps
-- until a person switches it on. No row of an existing table is rewritten
-- by this migration.

-- ═══════════════════════════════════════════════════════════════════════════
-- 1. The setting, on the recruitment
-- ═══════════════════════════════════════════════════════════════════════════

ALTER TABLE public.recruitment_settings
  ADD COLUMN IF NOT EXISTS receipt_enabled    boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS receipt_subject_sv text,
  ADD COLUMN IF NOT EXISTS receipt_body_sv    text,
  ADD COLUMN IF NOT EXISTS receipt_subject_en text,
  ADD COLUMN IF NOT EXISTS receipt_body_en    text,
  ADD COLUMN IF NOT EXISTS receipt_updated_at timestamptz,
  ADD COLUMN IF NOT EXISTS receipt_updated_by uuid REFERENCES auth.users(id) ON DELETE SET NULL;

ALTER TABLE public.recruitment_settings
  ADD CONSTRAINT recruitment_settings_receipt_text_shape CHECK (
    (receipt_subject_sv IS NULL OR char_length(btrim(receipt_subject_sv)) BETWEEN 1 AND 200)
    AND (receipt_subject_en IS NULL OR char_length(btrim(receipt_subject_en)) BETWEEN 1 AND 200)
    AND (receipt_body_sv IS NULL OR char_length(btrim(receipt_body_sv)) BETWEEN 1 AND 4000)
    AND (receipt_body_en IS NULL OR char_length(btrim(receipt_body_en)) BETWEEN 1 AND 4000)
  );

COMMENT ON COLUMN public.recruitment_settings.receipt_enabled IS
  'Send an automatic receipt to every NEW application of this recruitment. '
  'Never retroactive: the receipt trigger fires on INSERT only.';
COMMENT ON COLUMN public.recruitment_settings.receipt_body_sv IS
  'The employer''s own receipt text, or NULL for the standard text '
  '(rec_receipt_default). Placeholders: {namn} {tjänst} {företag} {länk}.';

-- ═══════════════════════════════════════════════════════════════════════════
-- 2. The receipt is a message
-- ═══════════════════════════════════════════════════════════════════════════

ALTER TABLE public.recruitment_messages DROP CONSTRAINT recruitment_messages_kind_check;
ALTER TABLE public.recruitment_messages ADD CONSTRAINT recruitment_messages_kind_check
  CHECK (kind IN ('general', 'interview_invitation', 'rejection', 'offer', 'information', 'receipt'));

-- 'unknown': the e-mail was claimed for sending and the outcome never came
-- back (the server died between the provider and the settle). It is not
-- "not sent" and it is not "sent"; it is a fact a person must look at.
ALTER TABLE public.recruitment_messages DROP CONSTRAINT recruitment_messages_email_status_check;
ALTER TABLE public.recruitment_messages ADD CONSTRAINT recruitment_messages_email_status_check
  CHECK (email_status IN ('not_attempted', 'sending', 'sent', 'failed', 'not_configured', 'unknown'));

-- One receipt per application, enforced by the index rather than by code.
CREATE UNIQUE INDEX IF NOT EXISTS recruitment_messages_receipt_once_idx
  ON public.recruitment_messages (application_id) WHERE kind = 'receipt';

-- ═══════════════════════════════════════════════════════════════════════════
-- 3. The standard text, and how a template is rendered
-- ═══════════════════════════════════════════════════════════════════════════

-- The standard text promises no response time: that is the employer's to
-- promise, in their own words, if they choose to.
CREATE OR REPLACE FUNCTION public.rec_receipt_default(_language text, _part text)
RETURNS text
LANGUAGE sql
IMMUTABLE
SET search_path = public, pg_temp
AS $$
  SELECT CASE
    WHEN _language = 'en' AND _part = 'subject' THEN 'We have received your application – {job}'
    WHEN _language = 'en' AND _part = 'body' THEN
      E'Hi {name}!\n\nThank you for applying for the position {job} at {company}. We have received your application.\n\nYou can follow it and read messages from us under My applications in CQrityjob: {link}\n\nKind regards\n{company}'
    WHEN _part = 'subject' THEN 'Vi har tagit emot din ansökan – {tjänst}'
    ELSE
      E'Hej {namn}!\n\nTack för din ansökan till tjänsten {tjänst} hos {företag}. Vi har tagit emot din ansökan.\n\nDu kan följa den och läsa meddelanden från oss under Mina ansökningar i CQrityjob: {länk}\n\nVänliga hälsningar\n{företag}'
  END;
$$;
REVOKE ALL ON FUNCTION public.rec_receipt_default(text, text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.rec_receipt_default(text, text) TO authenticated;

-- Both languages' placeholders are accepted in either template. An empty
-- name takes its leading space with it, so "Hej {namn}!" becomes "Hej!".
CREATE OR REPLACE FUNCTION public.rec_render_receipt(
  _template text, _name text, _job text, _company text, _link text)
RETURNS text
LANGUAGE sql
IMMUTABLE
SET search_path = public, pg_temp
AS $$
  SELECT replace(replace(replace(replace(replace(replace(
    CASE WHEN coalesce(btrim(_name), '') = ''
         THEN regexp_replace(_template, '\s*\{(namn|name)\}', '', 'g')
         ELSE replace(replace(_template, '{namn}', btrim(_name)), '{name}', btrim(_name)) END,
    '{tjänst}', coalesce(_job, '')), '{job}', coalesce(_job, '')),
    '{företag}', coalesce(_company, '')), '{company}', coalesce(_company, '')),
    '{länk}', coalesce(_link, '')), '{link}', coalesce(_link, ''));
$$;
REVOKE ALL ON FUNCTION public.rec_render_receipt(text, text, text, text, text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.rec_render_receipt(text, text, text, text, text) TO authenticated;

-- ═══════════════════════════════════════════════════════════════════════════
-- 4. The setting is written by the people who may write to candidates
-- ═══════════════════════════════════════════════════════════════════════════

CREATE OR REPLACE FUNCTION public.rec_set_receipt_settings(
  _job_id uuid,
  _enabled boolean,
  _subject_sv text DEFAULT NULL,
  _body_sv text DEFAULT NULL,
  _subject_en text DEFAULT NULL,
  _body_en text DEFAULT NULL,
  _expected_version integer DEFAULT NULL
)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  _employer uuid;
  _row public.recruitment_settings%ROWTYPE;
  _v integer;
BEGIN
  SELECT employer_id INTO _employer FROM public.jobs WHERE id = _job_id;
  IF _employer IS NULL OR NOT public.rec_is_member(_employer) THEN
    RAISE EXCEPTION 'RECRUITMENT_NOT_FOUND' USING ERRCODE = 'no_data_found';
  END IF;
  IF NOT public.rec_can_manage(_job_id) THEN
    RAISE EXCEPTION 'RECRUITMENT_NOT_PERMITTED' USING ERRCODE = 'insufficient_privilege';
  END IF;
  _row := public.rec_settings_row(_job_id);
  IF _expected_version IS NOT NULL AND _row.version <> _expected_version THEN
    RAISE EXCEPTION 'STALE_VERSION' USING ERRCODE = 'serialization_failure';
  END IF;
  -- A template that is the standard text is stored as "standard" (NULL), so
  -- a later improvement of the standard reaches it; an edited one is kept
  -- verbatim, trimmed.
  UPDATE public.recruitment_settings
     SET receipt_enabled = coalesce(_enabled, false),
         receipt_subject_sv = nullif(btrim(coalesce(_subject_sv, '')), ''),
         receipt_body_sv    = nullif(btrim(coalesce(_body_sv, '')), ''),
         receipt_subject_en = nullif(btrim(coalesce(_subject_en, '')), ''),
         receipt_body_en    = nullif(btrim(coalesce(_body_en, '')), ''),
         receipt_updated_at = now(),
         receipt_updated_by = auth.uid(),
         version = version + 1,
         updated_at = now()
   WHERE job_id = _job_id
  RETURNING version INTO _v;
  UPDATE public.recruitment_settings
     SET receipt_subject_sv = CASE WHEN receipt_subject_sv = public.rec_receipt_default('sv', 'subject') THEN NULL ELSE receipt_subject_sv END,
         receipt_body_sv    = CASE WHEN receipt_body_sv    = public.rec_receipt_default('sv', 'body')    THEN NULL ELSE receipt_body_sv END,
         receipt_subject_en = CASE WHEN receipt_subject_en = public.rec_receipt_default('en', 'subject') THEN NULL ELSE receipt_subject_en END,
         receipt_body_en    = CASE WHEN receipt_body_en    = public.rec_receipt_default('en', 'body')    THEN NULL ELSE receipt_body_en END
   WHERE job_id = _job_id;
  RETURN _v;
END; $$;
REVOKE ALL ON FUNCTION public.rec_set_receipt_settings(uuid, boolean, text, text, text, text, integer) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.rec_set_receipt_settings(uuid, boolean, text, text, text, text, integer) TO authenticated;

-- ═══════════════════════════════════════════════════════════════════════════
-- 5. New recruitments start with the receipt on -- switched on by the
--    application when it creates the recruitment
-- ═══════════════════════════════════════════════════════════════════════════
--
-- Deliberately NOT a trigger on jobs. Every suite, fixture and walk in this
-- repository inserts vacancies and applications directly, and a trigger
-- that switched the receipt on for every new job would write a receipt
-- into each of those worlds -- and into any job created outside the
-- product. The default at the database is therefore OFF, which is also
-- what every existing recruitment keeps; the product switches it on, with
-- the standard text, in the same request that creates a recruitment
-- (createEmployerJob → rec_set_receipt_settings), so it is visible before
-- publication.

-- ═══════════════════════════════════════════════════════════════════════════
-- 6. The receipt is written at the commit of the application
-- ═══════════════════════════════════════════════════════════════════════════

CREATE OR REPLACE FUNCTION public.rec_create_application_receipt()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  _s public.recruitment_settings%ROWTYPE;
  _lang text;
  _name text;
  _job text;
  _company text;
  _link text;
  _subject text;
  _body text;
BEGIN
  IF NEW.status <> 'submitted' THEN
    RETURN NULL;
  END IF;
  SELECT * INTO _s FROM public.recruitment_settings WHERE job_id = NEW.job_id;
  IF NOT FOUND OR NOT _s.receipt_enabled THEN
    RETURN NULL;
  END IF;

  -- The candidate's own language, as their profile says; Swedish otherwise.
  SELECT CASE WHEN p.locale = 'en' THEN 'en' ELSE 'sv' END,
         split_part(btrim(coalesce(p.display_name, '')), ' ', 1)
    INTO _lang, _name
    FROM public.profiles p WHERE p.id = NEW.applicant_user_id;
  _lang := coalesce(_lang, 'sv');
  SELECT coalesce(CASE WHEN _lang = 'en' THEN j.title_en END, j.title_sv, j.title_en), e.name
    INTO _job, _company
    FROM public.jobs j JOIN public.employers e ON e.id = j.employer_id
   WHERE j.id = NEW.job_id;
  -- Site-relative on purpose: the row does not know which host serves the
  -- product, and the e-mail envelope adds it when the copy is sent.
  _link := '/my-career/applications?application=' || NEW.id::text;

  _subject := public.rec_render_receipt(
    coalesce(CASE WHEN _lang = 'en' THEN _s.receipt_subject_en ELSE _s.receipt_subject_sv END,
             public.rec_receipt_default(_lang, 'subject')),
    _name, _job, _company, _link);
  _body := public.rec_render_receipt(
    coalesce(CASE WHEN _lang = 'en' THEN _s.receipt_body_en ELSE _s.receipt_body_sv END,
             public.rec_receipt_default(_lang, 'body')),
    _name, _job, _company, _link);

  -- Never let the receipt decide the application's fate: a receipt that
  -- cannot be written is logged, and the application commits without it.
  BEGIN
    INSERT INTO public.recruitment_messages (
      application_id, job_id, employer_id, kind, subject, body, language,
      status, sent_at, sent_by, created_by, email_status, idempotency_key)
    VALUES (NEW.id, NEW.job_id, NEW.employer_id, 'receipt',
            left(_subject, 200), left(_body, 8000), _lang,
            'sent', now(), NULL, NULL, 'not_attempted', 'receipt:' || NEW.id::text)
    ON CONFLICT (application_id) WHERE kind = 'receipt' DO NOTHING;
  EXCEPTION WHEN OTHERS THEN
    RAISE WARNING 'REC_RECEIPT_NOT_WRITTEN: application % (%)', NEW.id, SQLERRM;
  END;
  RETURN NULL;
END; $$;
REVOKE ALL ON FUNCTION public.rec_create_application_receipt() FROM PUBLIC, anon, authenticated;

-- Deferred, so it runs at COMMIT with the answers in place and after the
-- required-answers backstop (which sorts before it by name) has refused or
-- let the transaction through.
DROP TRIGGER IF EXISTS job_applications_zz_receipt ON public.job_applications;
CREATE CONSTRAINT TRIGGER job_applications_zz_receipt
  AFTER INSERT ON public.job_applications
  DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW EXECUTE FUNCTION public.rec_create_application_receipt();

-- ═══════════════════════════════════════════════════════════════════════════
-- 7. The e-mail copy: claim and settle, by the candidate's own request or
--    by a person who may write to candidates
-- ═══════════════════════════════════════════════════════════════════════════

-- Who may drive a receipt's e-mail: the applicant themself (the server does
-- it on their behalf right after the submission), or the people who may
-- write to candidates. Nobody else, and never anon.
CREATE OR REPLACE FUNCTION public.rec_receipt_actor(_app public.job_applications)
RETURNS text
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  SELECT CASE
    WHEN auth.uid() IS NULL THEN NULL
    WHEN _app.applicant_user_id = auth.uid() THEN 'applicant'
    WHEN public.rec_is_member(_app.employer_id) AND public.rec_can_manage(_app.job_id) THEN 'manager'
    ELSE NULL END;
$$;
REVOKE ALL ON FUNCTION public.rec_receipt_actor(public.job_applications) FROM PUBLIC, anon, authenticated;

-- outcome: claimed | already_sent | in_progress | unknown | failed |
-- not_configured | none. Only 'claimed' hands over an address; the server
-- must then settle. A stale claim (no settle within two minutes) becomes
-- 'unknown' and stays so until a manager asks for a retry: an outcome we
-- do not know is not an outcome we may guess.
CREATE OR REPLACE FUNCTION public.rec_claim_receipt_send(_application_id uuid, _retry boolean DEFAULT false)
RETURNS TABLE (
  outcome         text,
  message_id      uuid,
  recipient_email text,
  language        text,
  subject         text,
  body            text,
  employer_name   text,
  job_title       text
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  _app public.job_applications%ROWTYPE;
  _actor text;
  _m public.recruitment_messages%ROWTYPE;
  _email text;
BEGIN
  SELECT * INTO _app FROM public.job_applications WHERE id = _application_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'APPLICATION_NOT_FOUND' USING ERRCODE = 'no_data_found';
  END IF;
  _actor := public.rec_receipt_actor(_app);
  IF _actor IS NULL THEN
    RAISE EXCEPTION 'APPLICATION_NOT_FOUND' USING ERRCODE = 'no_data_found';
  END IF;
  IF _retry AND _actor <> 'manager' THEN
    RAISE EXCEPTION 'RECRUITMENT_NOT_PERMITTED' USING ERRCODE = 'insufficient_privilege';
  END IF;

  SELECT * INTO _m FROM public.recruitment_messages
   WHERE application_id = _app.id AND kind = 'receipt' FOR UPDATE;
  IF NOT FOUND THEN
    RETURN QUERY SELECT 'none'::text, NULL::uuid, NULL::text, NULL::text, NULL::text, NULL::text, NULL::text, NULL::text;
    RETURN;
  END IF;
  IF _m.email_status = 'sent' THEN
    RETURN QUERY SELECT 'already_sent'::text, _m.id, NULL::text, _m.language, _m.subject, _m.body, NULL::text, NULL::text;
    RETURN;
  END IF;
  IF _m.email_status = 'sending' THEN
    IF _m.email_claimed_at > now() - interval '2 minutes' THEN
      RETURN QUERY SELECT 'in_progress'::text, _m.id, NULL::text, _m.language, _m.subject, _m.body, NULL::text, NULL::text;
      RETURN;
    END IF;
    -- Claimed, never settled: the outcome is unknown, and stays so.
    UPDATE public.recruitment_messages
       SET email_status = 'unknown', email_error = 'NO_SETTLE', updated_at = now()
     WHERE id = _m.id;
    _m.email_status := 'unknown';
  END IF;
  IF _m.email_status IN ('unknown', 'failed', 'not_configured') AND NOT _retry THEN
    RETURN QUERY SELECT _m.email_status, _m.id, NULL::text, _m.language, _m.subject, _m.body, NULL::text, NULL::text;
    RETURN;
  END IF;

  UPDATE public.recruitment_messages
     SET email_status = 'sending',
         email_claimed_at = now(),
         email_attempts = email_attempts + 1,
         email_error = NULL,
         updated_at = now()
   WHERE id = _m.id;

  SELECT u.email INTO _email FROM auth.users u WHERE u.id = _app.applicant_user_id;

  RETURN QUERY
  SELECT 'claimed'::text, _m.id, _email, _m.language, _m.subject, _m.body,
         e.name, coalesce(CASE WHEN _m.language = 'en' THEN j.title_en END, j.title_sv, j.title_en)
    FROM public.jobs j JOIN public.employers e ON e.id = j.employer_id
   WHERE j.id = _app.job_id;
END; $$;
REVOKE ALL ON FUNCTION public.rec_claim_receipt_send(uuid, boolean) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.rec_claim_receipt_send(uuid, boolean) TO authenticated;

CREATE OR REPLACE FUNCTION public.rec_settle_receipt_send(
  _application_id uuid,
  _result text,
  _error text DEFAULT NULL
)
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  _app public.job_applications%ROWTYPE;
  _m public.recruitment_messages%ROWTYPE;
BEGIN
  IF _result NOT IN ('sent', 'failed', 'not_configured') THEN
    RAISE EXCEPTION 'MESSAGE_RESULT_INVALID' USING ERRCODE = 'check_violation';
  END IF;
  SELECT * INTO _app FROM public.job_applications WHERE id = _application_id;
  IF NOT FOUND OR public.rec_receipt_actor(_app) IS NULL THEN
    RAISE EXCEPTION 'APPLICATION_NOT_FOUND' USING ERRCODE = 'no_data_found';
  END IF;
  SELECT * INTO _m FROM public.recruitment_messages
   WHERE application_id = _app.id AND kind = 'receipt' FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'MESSAGE_NOT_FOUND' USING ERRCODE = 'no_data_found';
  END IF;
  IF _m.email_status <> 'sending' THEN
    RETURN _m.email_status;
  END IF;
  UPDATE public.recruitment_messages
     SET email_status = _result,
         email_error = CASE WHEN _result = 'failed' THEN left(coalesce(_error, 'UNKNOWN'), 200) END,
         updated_at = now()
   WHERE id = _m.id;
  RETURN _result;
END; $$;
REVOKE ALL ON FUNCTION public.rec_settle_receipt_send(uuid, text, text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.rec_settle_receipt_send(uuid, text, text) TO authenticated;

-- ═══════════════════════════════════════════════════════════════════════════
-- 8. Apply-time proof
-- ═══════════════════════════════════════════════════════════════════════════

DO $proof$
DECLARE _f text;
BEGIN
  FOREACH _f IN ARRAY ARRAY[
    'public.rec_receipt_default(text,text)',
    'public.rec_render_receipt(text,text,text,text,text)',
    'public.rec_set_receipt_settings(uuid,boolean,text,text,text,text,integer)',
    'public.rec_claim_receipt_send(uuid,boolean)',
    'public.rec_settle_receipt_send(uuid,text,text)'
  ] LOOP
    IF has_function_privilege('anon', _f, 'EXECUTE') THEN
      RAISE EXCEPTION 'REC_RECEIPT_PROOF: anon may execute %', _f;
    END IF;
    IF NOT has_function_privilege('authenticated', _f, 'EXECUTE') THEN
      RAISE EXCEPTION 'REC_RECEIPT_PROOF: authenticated cannot execute %', _f;
    END IF;
  END LOOP;
  FOREACH _f IN ARRAY ARRAY[
    'public.rec_create_application_receipt()',
    'public.rec_receipt_actor(public.job_applications)'
  ] LOOP
    IF has_function_privilege('authenticated', _f, 'EXECUTE') OR has_function_privilege('anon', _f, 'EXECUTE') THEN
      RAISE EXCEPTION 'REC_RECEIPT_PROOF: a trigger or helper is callable directly: %', _f;
    END IF;
  END LOOP;
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgrelid = 'public.job_applications'::regclass
                  AND tgname = 'job_applications_zz_receipt' AND tgdeferrable AND tginitdeferred) THEN
    RAISE EXCEPTION 'REC_RECEIPT_PROOF: the receipt trigger is not deferred to the commit';
  END IF;
  IF public.rec_render_receipt('Hej {namn}! {tjänst} hos {företag}: {länk}', '', 'Väktare', 'AB', '/x')
     <> 'Hej! Väktare hos AB: /x' THEN
    RAISE EXCEPTION 'REC_RECEIPT_PROOF: an empty name does not render cleanly';
  END IF;
  IF position('{' in public.rec_render_receipt(public.rec_receipt_default('sv', 'body'), 'Kim', 'Väktare', 'AB', '/x')) > 0
     OR position('{' in public.rec_render_receipt(public.rec_receipt_default('en', 'body'), 'Kim', 'Guard', 'AB', '/x')) > 0 THEN
    RAISE EXCEPTION 'REC_RECEIPT_PROOF: the standard text leaves a placeholder unrendered';
  END IF;
END
$proof$;
