-- Created with supabase migration new; only the filename was moved forward
-- to the next canonical slot because this repository's ledger leads the clock.
--
-- Automatic receipts for received applications ("Autosvar vid mottagen
-- ansökan"), per recruitment.
--
-- ── WHAT IT IS, AND IS NOT ────────────────────────────────────────────────
--
-- When a candidate's application has been SAVED CORRECTLY -- the row, the
-- required answers and the rest of the same transaction -- the recruitment
-- may send one message back: "we have received your application". It is a
-- fixed text the employer wrote (or the standard text), rendered with the
-- candidate's name, the vacancy, the company and a link to the application.
-- It is not generated by a model, it says nothing about the candidate's
-- chances, and it moves nothing: the application stays exactly where it is.
--
-- ── WHERE IT LIVES ───────────────────────────────────────────────────────
--
-- In the message history that already exists (recruitment_messages), as a
-- message of kind 'receipt': the candidate sees it under Mina ansökningar
-- exactly like a message a person sent, the employer sees it on the
-- application with its delivery status, and the e-mail copy is driven by
-- the server through a claim / settle pair. Nothing is stored twice and
-- nothing is retried from a second queue.
--
-- ── THE RULES ────────────────────────────────────────────────────────────
--
--   ONE PER APPLICATION, IN THE SAME TRANSACTION   a deferred constraint
--       trigger writes the receipt at COMMIT of the application's own
--       transaction, after 20261208090000's required-answers backstop has
--       had its say. A submission that fails or is abandoned never commits,
--       so it never has a receipt. A receipt that cannot be written fails
--       that commit loudly -- there is no silent gap between "the
--       application is saved" and "its receipt is registered". A partial
--       unique index makes a second receipt for the same application
--       impossible, whatever writes it.
--   NOTHING RETROACTIVE   the trigger fires on INSERT only. Switching the
--       receipt on, or changing its text, changes what FUTURE applications
--       get; no existing application is written to.
--   THE TEXT USED IS THE TEXT KEPT   the receipt row holds the rendered
--       subject and body in the language it was sent in. A later change to
--       the template does not change it.
--   THE E-MAIL IS A SECOND CHANNEL WITH ITS OWN TRUTH   the row is created
--       with the e-mail not yet attempted. Only TRUSTED SERVER CODE
--       (service_role) may claim a send and record what the provider
--       answered: no candidate and no employer can attest "sent" through
--       the API. A person who may write to candidates may ask the server
--       for a retry; the server names that person and the database checks
--       them. Every technical attempt has an identity of its own, and an
--       answer is recorded only for the attempt it belongs to: a late
--       answer from attempt A can never overwrite attempt B.
--   UNKNOWN IS UNKNOWN   a claim whose answer never came back (timeout,
--       network, 5xx, the server died) is 'unknown' -- neither "sent" nor
--       "not sent". The provider (Resend) deduplicates on an Idempotency-Key
--       for 24 hours, so a resend under the SAME key inside that window is
--       provably safe and the recovery may do it on its own; after the
--       window nothing resends without a person accepting that the
--       candidate may receive the e-mail twice, and that resend goes under
--       a new key generation.
--   RECOVERY FROM WHAT EXISTS   rec_claim_due_receipts hands the server
--       what is due (never started, aged out, unknown inside the window,
--       rate-limited) under FOR UPDATE SKIP LOCKED, so two sweeps cannot
--       take the same receipt, with bounded attempts. It works only on
--       receipts that are registered; it generates nothing retroactively.
--
-- Who may change the setting: exactly who may write to candidates
-- (rec_can_manage -- owner, admin, or the person responsible). The server
-- checks the same rule; this is where it is enforced.
--
-- The product switches the receipt ON, with the standard text, when it
-- creates a recruitment, so it is visible before publication; the database
-- default is OFF, which is what every recruitment that exists today keeps
-- until a person switches it on. No row of an existing table is rewritten
-- by this migration.

-- ═══════════════════════════════════════════════════════════════════════════
-- 1. The setting, on the recruitment
-- ═══════════════════════════════════════════════════════════════════════════

ALTER TABLE public.recruitment_settings
  ADD COLUMN IF NOT EXISTS receipt_enabled    boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS receipt_subject_sv text,
  ADD COLUMN IF NOT EXISTS receipt_body_sv    text,
  ADD COLUMN IF NOT EXISTS receipt_subject_en text,
  ADD COLUMN IF NOT EXISTS receipt_body_en    text,
  ADD COLUMN IF NOT EXISTS receipt_updated_at timestamptz,
  ADD COLUMN IF NOT EXISTS receipt_updated_by uuid REFERENCES auth.users(id) ON DELETE SET NULL;

ALTER TABLE public.recruitment_settings
  ADD CONSTRAINT recruitment_settings_receipt_text_shape CHECK (
    (receipt_subject_sv IS NULL OR char_length(btrim(receipt_subject_sv)) BETWEEN 1 AND 200)
    AND (receipt_subject_en IS NULL OR char_length(btrim(receipt_subject_en)) BETWEEN 1 AND 200)
    AND (receipt_body_sv IS NULL OR char_length(btrim(receipt_body_sv)) BETWEEN 1 AND 4000)
    AND (receipt_body_en IS NULL OR char_length(btrim(receipt_body_en)) BETWEEN 1 AND 4000)
  );

COMMENT ON COLUMN public.recruitment_settings.receipt_enabled IS
  'Send an automatic receipt to every NEW application of this recruitment. '
  'Never retroactive: the receipt trigger fires on INSERT only.';
COMMENT ON COLUMN public.recruitment_settings.receipt_body_sv IS
  'The employer''s own receipt text, or NULL for the standard text '
  '(rec_receipt_default). Placeholders: {namn} {tjänst} {företag} {länk}.';

-- ═══════════════════════════════════════════════════════════════════════════
-- 2. The receipt is a message; an e-mail attempt has an identity
-- ═══════════════════════════════════════════════════════════════════════════

ALTER TABLE public.recruitment_messages DROP CONSTRAINT recruitment_messages_kind_check;
ALTER TABLE public.recruitment_messages ADD CONSTRAINT recruitment_messages_kind_check
  CHECK (kind IN ('general', 'interview_invitation', 'rejection', 'offer', 'information', 'receipt'));

-- 'unknown': the e-mail was claimed for sending and the outcome never came
-- back, or came back as something that is neither an acceptance nor a
-- definite refusal (a timeout, a network error, a 5xx, an idempotency
-- conflict). It is not "not sent" and it is not "sent"; it is a fact.
ALTER TABLE public.recruitment_messages DROP CONSTRAINT recruitment_messages_email_status_check;
ALTER TABLE public.recruitment_messages ADD CONSTRAINT recruitment_messages_email_status_check
  CHECK (email_status IN ('not_attempted', 'sending', 'sent', 'failed', 'not_configured', 'unknown'));

-- The logical e-mail (one per message: idempotency_key) and each technical
-- attempt (email_attempt_id) are two different identities.
--
--   email_attempt_id         the attempt in flight; a settle names it and
--                            applies only if it is still the current one
--   email_provider_id        the provider's id for the accepted e-mail
--   email_recipient          the address the logical e-mail is addressed to,
--                            fixed at the first attempt so that a retry under
--                            the same idempotency key carries the same
--                            payload (a changed payload is a 409 at Resend)
--   email_key_generation     0 for the original key; a person who accepts a
--                            possible duplicate after the provider's window
--                            bumps it, and the key sent to the provider gains
--                            the suffix ':r<n>'
--   email_key_first_used_at  when the current key generation was first sent
--                            to the provider: the start of its 24-hour window
--   email_settled_at         when the current outcome was recorded
ALTER TABLE public.recruitment_messages
  ADD COLUMN IF NOT EXISTS email_attempt_id        uuid,
  ADD COLUMN IF NOT EXISTS email_provider_id       text CHECK (email_provider_id IS NULL OR char_length(email_provider_id) <= 120),
  ADD COLUMN IF NOT EXISTS email_recipient         text CHECK (email_recipient IS NULL OR char_length(email_recipient) BETWEEN 3 AND 320),
  ADD COLUMN IF NOT EXISTS email_key_generation    integer NOT NULL DEFAULT 0 CHECK (email_key_generation BETWEEN 0 AND 50),
  ADD COLUMN IF NOT EXISTS email_key_first_used_at timestamptz,
  ADD COLUMN IF NOT EXISTS email_settled_at        timestamptz;

-- One receipt per application, enforced by the index rather than by code.
CREATE UNIQUE INDEX IF NOT EXISTS recruitment_messages_receipt_once_idx
  ON public.recruitment_messages (application_id) WHERE kind = 'receipt';
-- An attempt id is looked up by the settle; a receipt that is due is found
-- by the recovery.
CREATE INDEX IF NOT EXISTS recruitment_messages_email_attempt_idx
  ON public.recruitment_messages (email_attempt_id) WHERE email_attempt_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS recruitment_messages_receipt_due_idx
  ON public.recruitment_messages (email_status, created_at) WHERE kind = 'receipt' AND status = 'sent';

-- ═══════════════════════════════════════════════════════════════════════════
-- 3. The standard text, and how a template is rendered
-- ═══════════════════════════════════════════════════════════════════════════

-- The standard text promises no response time: that is the employer's to
-- promise, in their own words, if they choose to.
CREATE OR REPLACE FUNCTION public.rec_receipt_default(_language text, _part text)
RETURNS text
LANGUAGE sql
IMMUTABLE
SET search_path = public, pg_temp
AS $$
  SELECT CASE
    WHEN _language = 'en' AND _part = 'subject' THEN 'We have received your application – {job}'
    WHEN _language = 'en' AND _part = 'body' THEN
      E'Hi {name}!\n\nThank you for applying for the position {job} at {company}. We have received your application.\n\nYou can follow it and read messages from us under My applications in CQrityjob: {link}\n\nKind regards\n{company}'
    WHEN _part = 'subject' THEN 'Vi har tagit emot din ansökan – {tjänst}'
    ELSE
      E'Hej {namn}!\n\nTack för din ansökan till tjänsten {tjänst} hos {företag}. Vi har tagit emot din ansökan.\n\nDu kan följa den och läsa meddelanden från oss under Mina ansökningar i CQrityjob: {länk}\n\nVänliga hälsningar\n{företag}'
  END;
$$;
REVOKE ALL ON FUNCTION public.rec_receipt_default(text, text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.rec_receipt_default(text, text) TO authenticated;

-- Both languages' placeholders are accepted in either template. An empty
-- name takes its leading space with it, so "Hej {namn}!" becomes "Hej!".
CREATE OR REPLACE FUNCTION public.rec_render_receipt(
  _template text, _name text, _job text, _company text, _link text)
RETURNS text
LANGUAGE sql
IMMUTABLE
SET search_path = public, pg_temp
AS $$
  SELECT replace(replace(replace(replace(replace(replace(
    CASE WHEN coalesce(btrim(_name), '') = ''
         THEN regexp_replace(_template, '\s*\{(namn|name)\}', '', 'g')
         ELSE replace(replace(_template, '{namn}', btrim(_name)), '{name}', btrim(_name)) END,
    '{tjänst}', coalesce(_job, '')), '{job}', coalesce(_job, '')),
    '{företag}', coalesce(_company, '')), '{company}', coalesce(_company, '')),
    '{länk}', coalesce(_link, '')), '{link}', coalesce(_link, ''));
$$;
REVOKE ALL ON FUNCTION public.rec_render_receipt(text, text, text, text, text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.rec_render_receipt(text, text, text, text, text) TO authenticated;

-- ═══════════════════════════════════════════════════════════════════════════
-- 4. The setting is written by the people who may write to candidates
-- ═══════════════════════════════════════════════════════════════════════════

CREATE OR REPLACE FUNCTION public.rec_set_receipt_settings(
  _job_id uuid,
  _enabled boolean,
  _subject_sv text DEFAULT NULL,
  _body_sv text DEFAULT NULL,
  _subject_en text DEFAULT NULL,
  _body_en text DEFAULT NULL,
  _expected_version integer DEFAULT NULL
)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  _employer uuid;
  _row public.recruitment_settings%ROWTYPE;
  _v integer;
BEGIN
  SELECT employer_id INTO _employer FROM public.jobs WHERE id = _job_id;
  IF _employer IS NULL OR NOT public.rec_is_member(_employer) THEN
    RAISE EXCEPTION 'RECRUITMENT_NOT_FOUND' USING ERRCODE = 'no_data_found';
  END IF;
  IF NOT public.rec_can_manage(_job_id) THEN
    RAISE EXCEPTION 'RECRUITMENT_NOT_PERMITTED' USING ERRCODE = 'insufficient_privilege';
  END IF;
  _row := public.rec_settings_row(_job_id);
  IF _expected_version IS NOT NULL AND _row.version <> _expected_version THEN
    RAISE EXCEPTION 'STALE_VERSION' USING ERRCODE = 'serialization_failure';
  END IF;
  -- A template that is the standard text is stored as "standard" (NULL), so
  -- a later improvement of the standard reaches it; an edited one is kept
  -- verbatim, trimmed.
  UPDATE public.recruitment_settings
     SET receipt_enabled = coalesce(_enabled, false),
         receipt_subject_sv = nullif(btrim(coalesce(_subject_sv, '')), ''),
         receipt_body_sv    = nullif(btrim(coalesce(_body_sv, '')), ''),
         receipt_subject_en = nullif(btrim(coalesce(_subject_en, '')), ''),
         receipt_body_en    = nullif(btrim(coalesce(_body_en, '')), ''),
         receipt_updated_at = now(),
         receipt_updated_by = auth.uid(),
         version = version + 1,
         updated_at = now()
   WHERE job_id = _job_id
  RETURNING version INTO _v;
  UPDATE public.recruitment_settings
     SET receipt_subject_sv = CASE WHEN receipt_subject_sv = public.rec_receipt_default('sv', 'subject') THEN NULL ELSE receipt_subject_sv END,
         receipt_body_sv    = CASE WHEN receipt_body_sv    = public.rec_receipt_default('sv', 'body')    THEN NULL ELSE receipt_body_sv END,
         receipt_subject_en = CASE WHEN receipt_subject_en = public.rec_receipt_default('en', 'subject') THEN NULL ELSE receipt_subject_en END,
         receipt_body_en    = CASE WHEN receipt_body_en    = public.rec_receipt_default('en', 'body')    THEN NULL ELSE receipt_body_en END
   WHERE job_id = _job_id;
  RETURN _v;
END; $$;
REVOKE ALL ON FUNCTION public.rec_set_receipt_settings(uuid, boolean, text, text, text, text, integer) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.rec_set_receipt_settings(uuid, boolean, text, text, text, text, integer) TO authenticated;

-- ═══════════════════════════════════════════════════════════════════════════
-- 5. New recruitments start with the receipt on -- switched on by the
--    application when it creates the recruitment
-- ═══════════════════════════════════════════════════════════════════════════
--
-- Deliberately NOT a trigger on jobs. Every suite, fixture and walk in this
-- repository inserts vacancies and applications directly, and a trigger
-- that switched the receipt on for every new job would write a receipt
-- into each of those worlds -- and into any job created outside the
-- product. The default at the database is therefore OFF, which is also
-- what every existing recruitment keeps; the product switches it on, with
-- the standard text, in the same request that creates a recruitment
-- (createEmployerJob → rec_set_receipt_settings), so it is visible before
-- publication.

-- ═══════════════════════════════════════════════════════════════════════════
-- 6. The receipt is written in the application's own transaction
-- ═══════════════════════════════════════════════════════════════════════════

-- No exception handler, on purpose. The receipt is registered in the SAME
-- transaction as the application or that transaction fails: a receipt that
-- silently went missing while the application committed would be a gap
-- nobody could see. The only way a well-formed application could fail here
-- is a template that renders to nothing, and that falls back to the
-- standard text below.
CREATE OR REPLACE FUNCTION public.rec_create_application_receipt()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  _s public.recruitment_settings%ROWTYPE;
  _lang text;
  _name text;
  _job text;
  _company text;
  _link text;
  _subject text;
  _body text;
BEGIN
  IF NEW.status <> 'submitted' THEN
    RETURN NULL;
  END IF;
  SELECT * INTO _s FROM public.recruitment_settings WHERE job_id = NEW.job_id;
  IF NOT FOUND OR NOT _s.receipt_enabled THEN
    RETURN NULL;
  END IF;

  -- The candidate's own language, as their profile says; Swedish otherwise.
  SELECT CASE WHEN p.locale = 'en' THEN 'en' ELSE 'sv' END,
         split_part(btrim(coalesce(p.display_name, '')), ' ', 1)
    INTO _lang, _name
    FROM public.profiles p WHERE p.id = NEW.applicant_user_id;
  _lang := coalesce(_lang, 'sv');
  SELECT coalesce(CASE WHEN _lang = 'en' THEN j.title_en END, j.title_sv, j.title_en), e.name
    INTO _job, _company
    FROM public.jobs j JOIN public.employers e ON e.id = j.employer_id
   WHERE j.id = NEW.job_id;
  -- Site-relative on purpose: the row does not know which host serves the
  -- product, and the e-mail envelope adds it when the copy is sent.
  _link := '/my-career/applications?application=' || NEW.id::text;

  _subject := public.rec_render_receipt(
    coalesce(CASE WHEN _lang = 'en' THEN _s.receipt_subject_en ELSE _s.receipt_subject_sv END,
             public.rec_receipt_default(_lang, 'subject')),
    _name, _job, _company, _link);
  _body := public.rec_render_receipt(
    coalesce(CASE WHEN _lang = 'en' THEN _s.receipt_body_en ELSE _s.receipt_body_sv END,
             public.rec_receipt_default(_lang, 'body')),
    _name, _job, _company, _link);
  -- An own text that renders to nothing (say "{namn}" for an unnamed
  -- candidate) is replaced by the standard text rather than refusing the
  -- application.
  IF coalesce(btrim(_subject), '') = '' THEN
    _subject := public.rec_render_receipt(public.rec_receipt_default(_lang, 'subject'), _name, _job, _company, _link);
  END IF;
  IF coalesce(btrim(_body), '') = '' THEN
    _body := public.rec_render_receipt(public.rec_receipt_default(_lang, 'body'), _name, _job, _company, _link);
  END IF;

  INSERT INTO public.recruitment_messages (
    application_id, job_id, employer_id, kind, subject, body, language,
    status, sent_at, sent_by, created_by, email_status, idempotency_key)
  VALUES (NEW.id, NEW.job_id, NEW.employer_id, 'receipt',
          left(_subject, 200), left(_body, 8000), _lang,
          'sent', now(), NULL, NULL, 'not_attempted', 'receipt:' || NEW.id::text)
  ON CONFLICT (application_id) WHERE kind = 'receipt' DO NOTHING;
  RETURN NULL;
END; $$;
REVOKE ALL ON FUNCTION public.rec_create_application_receipt() FROM PUBLIC, anon, authenticated;

-- Deferred, so it runs at COMMIT with the answers in place and after the
-- required-answers backstop (which sorts before it by name) has refused or
-- let the transaction through.
DROP TRIGGER IF EXISTS job_applications_zz_receipt ON public.job_applications;
CREATE CONSTRAINT TRIGGER job_applications_zz_receipt
  AFTER INSERT ON public.job_applications
  DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW EXECUTE FUNCTION public.rec_create_application_receipt();

-- ═══════════════════════════════════════════════════════════════════════════
-- 7. The e-mail copy: claim and settle, by trusted server code only
-- ═══════════════════════════════════════════════════════════════════════════

-- The provider keeps an idempotency key for 24 hours (Resend, "Idempotency
-- keys", read 2026-09-25). A resend under the same key inside that window
-- returns the first response without sending again. One hour is kept as
-- margin for clock skew and for the request that may still be in flight.
CREATE OR REPLACE FUNCTION public.rec_receipt_window_open(_first_used_at timestamptz)
RETURNS boolean
LANGUAGE sql
STABLE
SET search_path = public, pg_temp
AS $$
  SELECT _first_used_at IS NULL OR _first_used_at > now() - interval '23 hours';
$$;
REVOKE ALL ON FUNCTION public.rec_receipt_window_open(timestamptz) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.rec_receipt_window_open(timestamptz) TO authenticated, service_role;

-- What a named person is to an application: the applicant, a person who
-- may write to candidates of that recruitment, or nobody. Evaluated for a
-- user id the SERVER names from the session, never from auth.uid(): the
-- caller of the claim is service_role.
CREATE OR REPLACE FUNCTION public.rec_receipt_actor(_app public.job_applications, _user uuid)
RETURNS text
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  SELECT CASE
    WHEN _user IS NULL THEN NULL
    WHEN _app.applicant_user_id = _user THEN 'applicant'
    WHEN public.employer_is_active_status(_app.employer_id)
     AND public.has_employer_role(_user, _app.employer_id, NULL)
     AND (public.has_employer_role(_user, _app.employer_id, ARRAY['owner', 'admin'])
          OR EXISTS (SELECT 1 FROM public.recruitment_settings s
                      WHERE s.job_id = _app.job_id AND s.responsible_user_id = _user))
      THEN 'manager'
    ELSE NULL END;
$$;
REVOKE ALL ON FUNCTION public.rec_receipt_actor(public.job_applications, uuid) FROM PUBLIC, anon, authenticated;

-- The key the provider sees for the current generation.
CREATE OR REPLACE FUNCTION public.rec_receipt_provider_key(_m public.recruitment_messages)
RETURNS text
LANGUAGE sql
IMMUTABLE
SET search_path = public, pg_temp
AS $$
  SELECT _m.idempotency_key || CASE WHEN _m.email_key_generation > 0 THEN ':r' || _m.email_key_generation::text ELSE '' END;
$$;
REVOKE ALL ON FUNCTION public.rec_receipt_provider_key(public.recruitment_messages) FROM PUBLIC, anon, authenticated;

-- Marks the row 'sending' under a NEW attempt id and returns it. Internal.
CREATE OR REPLACE FUNCTION public.rec_receipt_take_attempt(_id uuid, _applicant uuid)
RETURNS public.recruitment_messages
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE _m public.recruitment_messages%ROWTYPE;
BEGIN
  UPDATE public.recruitment_messages
     SET email_status = 'sending',
         email_attempt_id = gen_random_uuid(),
         email_claimed_at = now(),
         email_attempts = email_attempts + 1,
         email_error = NULL,
         email_recipient = coalesce(email_recipient,
                                    (SELECT u.email FROM auth.users u WHERE u.id = _applicant)),
         email_key_first_used_at = coalesce(email_key_first_used_at, now()),
         updated_at = now()
   WHERE id = _id
  RETURNING * INTO _m;
  RETURN _m;
END; $$;
REVOKE ALL ON FUNCTION public.rec_receipt_take_attempt(uuid, uuid) FROM PUBLIC, anon, authenticated;

-- outcome: claimed | already_sent | in_progress | unknown | failed |
-- not_configured | none.
--
-- Only 'claimed' hands over an address, and then the server must settle the
-- attempt it was given. _actor is the person on whose behalf the server
-- acts: NULL is the system itself (the dispatch right after a submission,
-- and the recovery), the applicant may ask for their own first send, and a
-- retry (_retry) is a manager's decision. _accept_duplicate is a manager's
-- explicit acceptance that the candidate may receive the e-mail twice; it
-- is what a resend after the provider's window requires.
--
-- A claim still 'sending' after two minutes was never settled: it becomes
-- 'unknown' here and the attempt it named can no longer be settled.
CREATE OR REPLACE FUNCTION public.rec_claim_receipt_send(
  _application_id uuid,
  _actor uuid DEFAULT NULL,
  _retry boolean DEFAULT false,
  _accept_duplicate boolean DEFAULT false
)
RETURNS TABLE (
  outcome         text,
  message_id      uuid,
  application_id  uuid,
  attempt_id      uuid,
  provider_key    text,
  recipient_email text,
  language        text,
  subject         text,
  body            text,
  employer_name   text,
  job_title       text,
  window_open     boolean,
  attempts        integer
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  _app public.job_applications%ROWTYPE;
  _who text;
  _m public.recruitment_messages%ROWTYPE;
BEGIN
  SELECT * INTO _app FROM public.job_applications WHERE id = _application_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'APPLICATION_NOT_FOUND' USING ERRCODE = 'no_data_found';
  END IF;
  IF _actor IS NOT NULL THEN
    _who := public.rec_receipt_actor(_app, _actor);
    IF _who IS NULL THEN
      RAISE EXCEPTION 'APPLICATION_NOT_FOUND' USING ERRCODE = 'no_data_found';
    END IF;
    IF (_retry OR _accept_duplicate) AND _who <> 'manager' THEN
      RAISE EXCEPTION 'RECRUITMENT_NOT_PERMITTED' USING ERRCODE = 'insufficient_privilege';
    END IF;
  ELSIF _accept_duplicate THEN
    -- Accepting a duplicate is a person's decision, never the system's.
    RAISE EXCEPTION 'RECRUITMENT_NOT_PERMITTED' USING ERRCODE = 'insufficient_privilege';
  END IF;

  SELECT m.* INTO _m FROM public.recruitment_messages m
   WHERE m.application_id = _app.id AND m.kind = 'receipt' FOR UPDATE;
  IF NOT FOUND THEN
    RETURN QUERY SELECT 'none'::text, NULL::uuid, _app.id, NULL::uuid, NULL::text, NULL::text, NULL::text, NULL::text, NULL::text, NULL::text, NULL::text, NULL::boolean, NULL::integer;
    RETURN;
  END IF;
  IF _m.email_status = 'sent' THEN
    RETURN QUERY SELECT 'already_sent'::text, _m.id, _app.id, NULL::uuid, NULL::text, NULL::text, _m.language, _m.subject, _m.body, NULL::text, NULL::text, true, _m.email_attempts;
    RETURN;
  END IF;
  IF _m.email_status = 'sending' THEN
    IF _m.email_claimed_at > now() - interval '2 minutes' THEN
      RETURN QUERY SELECT 'in_progress'::text, _m.id, _app.id, NULL::uuid, NULL::text, NULL::text, _m.language, _m.subject, _m.body, NULL::text, NULL::text, public.rec_receipt_window_open(_m.email_key_first_used_at), _m.email_attempts;
      RETURN;
    END IF;
    -- Claimed, never settled: the outcome is unknown, and the attempt that
    -- was in flight can no longer report.
    UPDATE public.recruitment_messages
       SET email_status = 'unknown', email_error = 'NO_SETTLE', email_settled_at = now(), updated_at = now()
     WHERE id = _m.id;
    _m.email_status := 'unknown';
    _m.email_error := 'NO_SETTLE';
  END IF;
  IF _m.email_status IN ('unknown', 'failed', 'not_configured') AND NOT _retry THEN
    RETURN QUERY SELECT _m.email_status, _m.id, _app.id, NULL::uuid, NULL::text, NULL::text, _m.language, _m.subject, _m.body, NULL::text, NULL::text, public.rec_receipt_window_open(_m.email_key_first_used_at), _m.email_attempts;
    RETURN;
  END IF;
  IF _m.email_status = 'unknown' AND NOT public.rec_receipt_window_open(_m.email_key_first_used_at) THEN
    IF NOT _accept_duplicate THEN
      -- Outside the provider's window a resend could reach the candidate
      -- twice. Not without a person saying so.
      RETURN QUERY SELECT 'unknown'::text, _m.id, _app.id, NULL::uuid, NULL::text, NULL::text, _m.language, _m.subject, _m.body, NULL::text, NULL::text, false, _m.email_attempts;
      RETURN;
    END IF;
    UPDATE public.recruitment_messages
       SET email_key_generation = email_key_generation + 1,
           email_key_first_used_at = NULL,
           email_provider_id = NULL,
           updated_at = now()
     WHERE id = _m.id;
  END IF;

  _m := public.rec_receipt_take_attempt(_m.id, _app.applicant_user_id);

  RETURN QUERY
  SELECT 'claimed'::text, _m.id, _app.id, _m.email_attempt_id, public.rec_receipt_provider_key(_m),
         _m.email_recipient, _m.language, _m.subject, _m.body,
         e.name, coalesce(CASE WHEN _m.language = 'en' THEN j.title_en END, j.title_sv, j.title_en),
         true, _m.email_attempts
    FROM public.jobs j JOIN public.employers e ON e.id = j.employer_id
   WHERE j.id = _app.job_id;
END; $$;
REVOKE ALL ON FUNCTION public.rec_claim_receipt_send(uuid, uuid, boolean, boolean) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.rec_claim_receipt_send(uuid, uuid, boolean, boolean) TO service_role;

-- Records what the provider answered FOR ONE ATTEMPT. Returns the row's
-- e-mail status afterwards, or 'stale' when the attempt is no longer the
-- current one -- a late answer from attempt A never touches attempt B, and
-- an answer for an attempt that aged out to 'unknown' is still that
-- attempt's genuine outcome and is taken.
CREATE OR REPLACE FUNCTION public.rec_settle_receipt_send(
  _attempt_id uuid,
  _result text,
  _error text DEFAULT NULL,
  _provider_id text DEFAULT NULL
)
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE _m public.recruitment_messages%ROWTYPE;
BEGIN
  IF _result NOT IN ('sent', 'failed', 'not_configured', 'unknown') THEN
    RAISE EXCEPTION 'MESSAGE_RESULT_INVALID' USING ERRCODE = 'check_violation';
  END IF;
  IF _attempt_id IS NULL THEN
    RAISE EXCEPTION 'MESSAGE_NOT_FOUND' USING ERRCODE = 'no_data_found';
  END IF;
  SELECT m.* INTO _m FROM public.recruitment_messages m
   WHERE m.email_attempt_id = _attempt_id AND m.kind = 'receipt' FOR UPDATE;
  IF NOT FOUND THEN
    RETURN 'stale';
  END IF;
  IF _m.email_status NOT IN ('sending', 'unknown') THEN
    RETURN _m.email_status;
  END IF;
  UPDATE public.recruitment_messages
     SET email_status = _result,
         email_error = CASE WHEN _result IN ('failed', 'unknown') THEN left(coalesce(_error, 'UNKNOWN'), 200) END,
         email_provider_id = CASE WHEN _result = 'sent' THEN left(_provider_id, 120) END,
         email_settled_at = now(),
         updated_at = now()
   WHERE id = _m.id;
  RETURN _result;
END; $$;
REVOKE ALL ON FUNCTION public.rec_settle_receipt_send(uuid, text, text, text) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.rec_settle_receipt_send(uuid, text, text, text) TO service_role;

-- ═══════════════════════════════════════════════════════════════════════════
-- 8. Recovery: what is due, handed to one sweep at a time
-- ═══════════════════════════════════════════════════════════════════════════

-- Due, in order of age:
--   never started      not_attempted, older than a minute (the request that
--                      saved the application had its chance to send)
--   aged out           sending for more than two minutes -> unknown, then as
--                      unknown
--   unknown            inside the provider's window and under the attempt
--                      cap: a resend under the same key is deduplicated by
--                      the provider. Outside the window, or when the
--                      provider answered that this key was already used
--                      with a different payload: left for a person.
--   rate-limited       failed with HTTP_429, after ten minutes, under the cap
-- Definite failures (a 4xx other than 429) and not_configured are a
-- person's to look at; the recovery does not loop on them. Rows are taken
-- FOR UPDATE SKIP LOCKED, so two concurrent sweeps never hold the same
-- receipt, and a receipt claimed by one is 'sending' to the other.
CREATE OR REPLACE FUNCTION public.rec_claim_due_receipts(
  _limit integer DEFAULT 20,
  _employer_id uuid DEFAULT NULL
)
RETURNS TABLE (
  outcome         text,
  message_id      uuid,
  application_id  uuid,
  attempt_id      uuid,
  provider_key    text,
  recipient_email text,
  language        text,
  subject         text,
  body            text,
  employer_name   text,
  job_title       text,
  window_open     boolean,
  attempts        integer
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  _m public.recruitment_messages%ROWTYPE;
  _app public.job_applications%ROWTYPE;
BEGIN
  FOR _m IN
    SELECT * FROM public.recruitment_messages m
     WHERE m.kind = 'receipt' AND m.status = 'sent'
       AND (_employer_id IS NULL OR m.employer_id = _employer_id)
       AND (
            (m.email_status = 'not_attempted' AND m.created_at < now() - interval '1 minute')
         OR (m.email_status = 'sending' AND m.email_claimed_at < now() - interval '2 minutes')
         OR (m.email_status = 'unknown' AND m.email_attempts < 5
             AND coalesce(m.email_error, '') <> 'IDEMPOTENCY_PAYLOAD_MISMATCH'
             AND public.rec_receipt_window_open(m.email_key_first_used_at)
             AND coalesce(m.email_claimed_at, m.created_at) < now() - interval '2 minutes')
         OR (m.email_status = 'failed' AND m.email_error = 'HTTP_429' AND m.email_attempts < 5
             AND m.email_claimed_at < now() - interval '10 minutes')
       )
     ORDER BY m.created_at
     LIMIT greatest(1, least(coalesce(_limit, 20), 200))
     FOR UPDATE SKIP LOCKED
  LOOP
    IF _m.email_status = 'sending' THEN
      UPDATE public.recruitment_messages
         SET email_status = 'unknown', email_error = 'NO_SETTLE', email_settled_at = now(), updated_at = now()
       WHERE id = _m.id;
      IF _m.email_attempts >= 5 OR NOT public.rec_receipt_window_open(_m.email_key_first_used_at) THEN
        CONTINUE;  -- now a person's
      END IF;
    END IF;
    SELECT * INTO _app FROM public.job_applications WHERE id = _m.application_id;
    _m := public.rec_receipt_take_attempt(_m.id, _app.applicant_user_id);
    RETURN QUERY
    SELECT 'claimed'::text, _m.id, _m.application_id, _m.email_attempt_id, public.rec_receipt_provider_key(_m),
           _m.email_recipient, _m.language, _m.subject, _m.body,
           e.name, coalesce(CASE WHEN _m.language = 'en' THEN j.title_en END, j.title_sv, j.title_en),
           true, _m.email_attempts
      FROM public.jobs j JOIN public.employers e ON e.id = j.employer_id
     WHERE j.id = _m.job_id;
  END LOOP;
END; $$;
REVOKE ALL ON FUNCTION public.rec_claim_due_receipts(integer, uuid) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.rec_claim_due_receipts(integer, uuid) TO service_role;

-- What the organisation's people should look at: receipts whose e-mail
-- the recovery will not touch again (a definite failure, an unknown
-- outcome outside the window or past the attempt cap). Read by members.
CREATE OR REPLACE FUNCTION public.rec_receipts_needing_attention(_employer_id uuid)
RETURNS integer
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  SELECT CASE WHEN public.rec_is_member(_employer_id) THEN (
    SELECT count(*)::integer FROM public.recruitment_messages m
     WHERE m.employer_id = _employer_id AND m.kind = 'receipt' AND m.status = 'sent'
       AND (
            (m.email_status = 'failed' AND NOT (m.email_error = 'HTTP_429' AND m.email_attempts < 5))
         OR (m.email_status = 'unknown'
             AND (m.email_attempts >= 5 OR m.email_error = 'IDEMPOTENCY_PAYLOAD_MISMATCH'
                  OR NOT public.rec_receipt_window_open(m.email_key_first_used_at)))
       )
  ) ELSE 0 END;
$$;
REVOKE ALL ON FUNCTION public.rec_receipts_needing_attention(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.rec_receipts_needing_attention(uuid) TO authenticated;

-- ═══════════════════════════════════════════════════════════════════════════
-- 9. The transport is shared: an ordinary message's settle takes 'unknown'
-- ═══════════════════════════════════════════════════════════════════════════
--
-- 20261207090000's rec_settle_message_send accepted sent / failed /
-- not_configured. The transport now tells a timeout, a network error and a
-- 5xx apart from a refusal, and that answer must be recordable for a
-- person's message too, instead of being written down as a failure it may
-- not be. Same permission rule as before; only the accepted results grow.
CREATE OR REPLACE FUNCTION public.rec_settle_message_send(
  _message_id uuid,
  _result text,
  _error text DEFAULT NULL
)
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE _m public.recruitment_messages%ROWTYPE;
BEGIN
  IF _result NOT IN ('sent', 'failed', 'not_configured', 'unknown') THEN
    RAISE EXCEPTION 'MESSAGE_RESULT_INVALID' USING ERRCODE = 'check_violation';
  END IF;
  SELECT * INTO _m FROM public.recruitment_messages WHERE id = _message_id FOR UPDATE;
  IF NOT FOUND OR NOT public.rec_is_member(_m.employer_id) OR NOT public.rec_can_manage(_m.job_id) THEN
    RAISE EXCEPTION 'MESSAGE_NOT_FOUND' USING ERRCODE = 'no_data_found';
  END IF;
  IF _m.email_status <> 'sending' THEN
    RETURN _m.email_status;
  END IF;
  UPDATE public.recruitment_messages
     SET email_status = _result,
         email_error = CASE WHEN _result IN ('failed', 'unknown') THEN left(coalesce(_error, 'UNKNOWN'), 200) END,
         email_settled_at = now(),
         updated_at = now()
   WHERE id = _m.id;
  RETURN _result;
END; $$;
REVOKE ALL ON FUNCTION public.rec_settle_message_send(uuid, text, text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.rec_settle_message_send(uuid, text, text) TO authenticated;

-- ═══════════════════════════════════════════════════════════════════════════
-- 10. Apply-time proof
-- ═══════════════════════════════════════════════════════════════════════════

DO $proof$
DECLARE _f text;
BEGIN
  -- Callable by signed-in people, never by anon.
  FOREACH _f IN ARRAY ARRAY[
    'public.rec_receipt_default(text,text)',
    'public.rec_render_receipt(text,text,text,text,text)',
    'public.rec_set_receipt_settings(uuid,boolean,text,text,text,text,integer)',
    'public.rec_receipts_needing_attention(uuid)',
    'public.rec_settle_message_send(uuid,text,text)'
  ] LOOP
    IF has_function_privilege('anon', _f, 'EXECUTE') THEN
      RAISE EXCEPTION 'REC_RECEIPT_PROOF: anon may execute %', _f;
    END IF;
    IF NOT has_function_privilege('authenticated', _f, 'EXECUTE') THEN
      RAISE EXCEPTION 'REC_RECEIPT_PROOF: authenticated cannot execute %', _f;
    END IF;
  END LOOP;
  -- The e-mail truth is written by trusted server code only.
  FOREACH _f IN ARRAY ARRAY[
    'public.rec_claim_receipt_send(uuid,uuid,boolean,boolean)',
    'public.rec_settle_receipt_send(uuid,text,text,text)',
    'public.rec_claim_due_receipts(integer,uuid)'
  ] LOOP
    IF has_function_privilege('anon', _f, 'EXECUTE') OR has_function_privilege('authenticated', _f, 'EXECUTE') THEN
      RAISE EXCEPTION 'REC_RECEIPT_PROOF: a signed-in person could drive the e-mail truth: %', _f;
    END IF;
    IF NOT has_function_privilege('service_role', _f, 'EXECUTE') THEN
      RAISE EXCEPTION 'REC_RECEIPT_PROOF: the server cannot execute %', _f;
    END IF;
  END LOOP;
  -- Helpers and the trigger are reachable through nothing but those.
  FOREACH _f IN ARRAY ARRAY[
    'public.rec_create_application_receipt()',
    'public.rec_receipt_actor(public.job_applications,uuid)',
    'public.rec_receipt_provider_key(public.recruitment_messages)',
    'public.rec_receipt_take_attempt(uuid,uuid)'
  ] LOOP
    IF has_function_privilege('authenticated', _f, 'EXECUTE') OR has_function_privilege('anon', _f, 'EXECUTE')
       OR has_function_privilege('service_role', _f, 'EXECUTE') THEN
      RAISE EXCEPTION 'REC_RECEIPT_PROOF: a trigger or helper is callable directly: %', _f;
    END IF;
  END LOOP;
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgrelid = 'public.job_applications'::regclass
                  AND tgname = 'job_applications_zz_receipt' AND tgdeferrable AND tginitdeferred) THEN
    RAISE EXCEPTION 'REC_RECEIPT_PROOF: the receipt trigger is not deferred to the commit';
  END IF;
  IF position('EXCEPTION' in pg_get_functiondef('public.rec_create_application_receipt()'::regprocedure)) > 0 THEN
    RAISE EXCEPTION 'REC_RECEIPT_PROOF: the receipt trigger swallows its own failure';
  END IF;
  IF public.rec_render_receipt('Hej {namn}! {tjänst} hos {företag}: {länk}', '', 'Väktare', 'AB', '/x')
     <> 'Hej! Väktare hos AB: /x' THEN
    RAISE EXCEPTION 'REC_RECEIPT_PROOF: an empty name does not render cleanly';
  END IF;
  IF position('{' in public.rec_render_receipt(public.rec_receipt_default('sv', 'body'), 'Kim', 'Väktare', 'AB', '/x')) > 0
     OR position('{' in public.rec_render_receipt(public.rec_receipt_default('en', 'body'), 'Kim', 'Guard', 'AB', '/x')) > 0 THEN
    RAISE EXCEPTION 'REC_RECEIPT_PROOF: the standard text leaves a placeholder unrendered';
  END IF;
  IF NOT public.rec_receipt_window_open(NULL) OR NOT public.rec_receipt_window_open(now() - interval '22 hours')
     OR public.rec_receipt_window_open(now() - interval '25 hours') THEN
    RAISE EXCEPTION 'REC_RECEIPT_PROOF: the idempotency window is not 24 hours less a margin';
  END IF;
END
$proof$;
