-- Security Passport — publish the approved research definitions (DATA).
--
-- GENERATED by scripts/passport-catalogue-research-build.ts. Do not edit by hand.
--
-- Depends on 20270207090000_sp_catalogue_research_import.sql, which created
-- these 140 definitions inactive. This is the PUBLICATION step: it sets
-- is_active = true on exactly the listed codes and nothing else.
--
-- RELEASE ORDER. Merge and apply this only AFTER the application that renders
-- the new credential kinds has been published (docs/passport/
-- certification-catalogue-integration.md). Publication is separate from
-- research approval and from any verification of a holder: it makes a
-- definition SELECTABLE and nothing more. legal_review_state stays 'pending',
-- allows_no_expiry stays false, and no market, grant or claim changes.

BEGIN;

UPDATE public.sp_credential_types t
   SET is_active = true
 WHERE t.code IN (
   'INTL_ANZIIF_AQF_DIP_GENERAL_INSURANCE',
   'INTL_ANZIIF_AQF_DIP_INSURANCE_BROKING',
   'INTL_ANZIIF_AQF_DIP_LOSS_ADJUSTING',
   'INTL_ANZIIF_EXEC_CERT_INSURANCE',
   'INTL_ANZIIF_FOUND_CERT_INSURANCE',
   'INTL_ATAP_CTM',
   'INTL_BCI_CBCI',
   'INTL_BCSP_ASP',
   'INTL_BCSP_CHST',
   'INTL_BCSP_CSP',
   'INTL_BCSP_OHST',
   'INTL_BCSP_SMP',
   'INTL_BCSP_STS',
   'INTL_BCSP_STSC',
   'INTL_CII_ADV_DIPLOMA_INSURANCE',
   'INTL_CII_AWARD_GENERAL_INSURANCE_NON_UK',
   'INTL_CII_CERT_INSURANCE',
   'INTL_CII_DIPLOMA_INSURANCE',
   'INTL_CILA_CERTIFICATE',
   'INTL_CILA_DIPLOMA',
   'INTL_COMPTIA_CYSA_PLUS',
   'INTL_COMPTIA_PENTEST_PLUS',
   'INTL_COMPTIA_SECURITYX',
   'INTL_COMPTIA_SECURITY_PLUS',
   'INTL_DRI_ABCP',
   'INTL_DRI_CBCA',
   'INTL_DRI_CBCLA',
   'INTL_DRI_CBCP',
   'INTL_DRI_CCRP',
   'INTL_DRI_CFCP',
   'INTL_DRI_MBCP',
   'INTL_ECCOUNCIL_CCISO',
   'INTL_ECCOUNCIL_CEH',
   'INTL_ECCOUNCIL_CHFI',
   'INTL_ECCOUNCIL_CND',
   'INTL_GARP_FRM',
   'INTL_GARP_RAI',
   'INTL_GARP_SCR',
   'INTL_GIAC_GCFA',
   'INTL_GIAC_GCFE',
   'INTL_GIAC_GCIA',
   'INTL_GIAC_GCIH',
   'INTL_GIAC_GCTI',
   'INTL_GIAC_GICSP',
   'INTL_GIAC_GPEN',
   'INTL_GIAC_GREM',
   'INTL_GIAC_GRID',
   'INTL_GIAC_GSEC',
   'INTL_IAFCI_CCCI',
   'INTL_IAFCI_CFCI',
   'INTL_IAFCI_ICIC',
   'INTL_IAHSS_CAHSO',
   'INTL_IAHSS_CHPA',
   'INTL_IAHSS_CHSO',
   'INTL_IAHSS_CHSS',
   'INTL_IALEIA_CICA',
   'INTL_IAPP_AIGP',
   'INTL_IAPP_CIPM',
   'INTL_IAPP_CIPP_A',
   'INTL_IAPP_CIPP_C',
   'INTL_IAPP_CIPP_CN',
   'INTL_IAPP_CIPP_E',
   'INTL_IAPP_CIPP_US',
   'INTL_IAPP_CIPT',
   'INTL_ICA_ADV_CERT_AML',
   'INTL_ICA_ADV_CERT_CDD',
   'INTL_ICA_ADV_CERT_GRC',
   'INTL_ICA_CERT_AML',
   'INTL_ICA_CERT_AML_INS',
   'INTL_ICA_CERT_COMP',
   'INTL_ICA_CERT_FINCRIME',
   'INTL_ICA_CERT_KYC_CDD',
   'INTL_ICA_CERT_SANCTIONS',
   'INTL_ICA_DIP_AML',
   'INTL_ICA_DIP_FINCRIME',
   'INTL_ICA_DIP_GRC',
   'INTL_IFCPP_CIPM_I',
   'INTL_IFCPP_CIPM_II',
   'INTL_IFCPP_CIPS',
   'INTL_IFCPP_CISS',
   'INTL_IFPO_CPO',
   'INTL_IFPO_CPOI',
   'INTL_IFPO_CSSM',
   'INTL_IIC_ACIP',
   'INTL_IIC_CIP',
   'INTL_IIC_FCIP',
   'INTL_INSTITUTES_ACRM',
   'INTL_INSTITUTES_ACRR',
   'INTL_INSTITUTES_AFSB',
   'INTL_INSTITUTES_AIAF',
   'INTL_INSTITUTES_AIC',
   'INTL_INSTITUTES_AINS',
   'INTL_INSTITUTES_AMIM',
   'INTL_INSTITUTES_API',
   'INTL_INSTITUTES_ARC',
   'INTL_INSTITUTES_ARE',
   'INTL_INSTITUTES_ARM',
   'INTL_INSTITUTES_ASLI',
   'INTL_INSTITUTES_AU',
   'INTL_INSTITUTES_CPCU',
   'INTL_INSTITUTES_PRC',
   'INTL_IOSH_L3_CERT_OSH',
   'INTL_IOSH_L6_DIP_OSH',
   'INTL_IOSH_MANAGING_SAFELY',
   'INTL_IRM_ERM',
   'INTL_IRM_ICORM',
   'INTL_ISACA_CCOA',
   'INTL_ISACA_CDPSE',
   'INTL_ISACA_CGEIT',
   'INTL_ISC2_CSSLP',
   'INTL_ISC2_ISSAP',
   'INTL_ISC2_ISSEP',
   'INTL_ISC2_ISSMP',
   'INTL_NEBOSH_CERT_FIRE_SAFETY',
   'INTL_NEBOSH_HSE_CERT_PROCESS_SAFETY',
   'INTL_NEBOSH_HSM_CONSTRUCTION_INTL',
   'INTL_NEBOSH_IGC',
   'INTL_NEBOSH_IIRSM_CERT_MANAGING_RISK',
   'INTL_NEBOSH_INTL_CERT_TERRORISM_PROTECTION',
   'INTL_NEBOSH_L6_INTL_DIP_OHS_MANAGEMENT',
   'INTL_NFPA_CFPS',
   'INTL_OFFSEC_OSCP',
   'INTL_OFFSEC_OSCP_PLUS',
   'INTL_OFFSEC_OSDA',
   'INTL_OFFSEC_OSEP',
   'INTL_OFFSEC_OSWE',
   'INTL_OPENGROUP_OPEN_FAIR_2_FOUNDATION',
   'INTL_PECB_ISO22301_LEAD_AUDITOR',
   'INTL_PECB_ISO22301_LEAD_IMPLEMENTER',
   'INTL_PECB_ISO27001_LEAD_AUDITOR',
   'INTL_PECB_ISO27001_LEAD_IMPLEMENTER',
   'INTL_PECB_ISO31000_LEAD_RISK_MANAGER',
   'INTL_PMI_PMI_RMP',
   'INTL_PRMIA_ASSOCIATE_PRM',
   'INTL_PRMIA_CCRM',
   'INTL_PRMIA_CYBER_RISK_MANAGEMENT',
   'INTL_PRMIA_MLARM',
   'INTL_PRMIA_PRM',
   'INTL_RIEA_CRM',
   'INTL_RIMS_RIMS_CRMP'
   )
   AND NOT t.is_active
   AND t.scope_code = 'global_professional'
   AND t.jurisdiction_code IS NULL AND t.market_pack_code IS NULL;

DO $post$
DECLARE _n integer;
BEGIN
  SELECT count(*) INTO _n FROM public.sp_credential_types t
    JOIN public.sp_catalogue_research_records r ON r.credential_code = t.code
   WHERE r.reconciliation_outcome = 'added_approved' AND t.is_active;
  IF _n <> 140 THEN RAISE EXCEPTION 'SP_RESEARCH_PUBLISH_COUNT: expected 140 published definitions, found %', _n; END IF;
  SELECT count(*) INTO _n FROM public.sp_credential_types WHERE code LIKE 'INTL\_%' AND is_active;
  IF _n <> 154 THEN RAISE EXCEPTION 'SP_RESEARCH_PUBLISH_TOTAL: expected 154 active international definitions, found %', _n; END IF;
  SELECT count(*) INTO _n FROM public.sp_credential_types WHERE is_active AND code NOT LIKE 'INTL\_%' AND scope_code = 'global_professional';
  IF _n <> 0 THEN RAISE EXCEPTION 'SP_RESEARCH_PUBLISH_STRAY: % non-research global definitions are active', _n; END IF;
END $post$;

COMMIT;
