import type { ProgrammeAreaId, Text } from "../types";

/** Fixed, versioned onboarding checklist. Never generated by AI. Editing a
 * task changes the content; bump the version when the meaning changes. */
export const PLAN_90_VERSION = "plan-90-v1";
export type PlanPeriodId = "d30" | "d60" | "d90";
export type PlanTask = {
  id: string;
  period: PlanPeriodId;
  title: Text;
  description: Text;
  area: ProgrammeAreaId | "monitoring" | "evidence";
};
export const PLAN_90_PERIODS: { id: PlanPeriodId; title: Text; range: Text; theme: Text }[] = [
  {
    id: "d30",
    title: { sv: "Dag 1–30", en: "Day 1–30" },
    range: { sv: "Förstå och kartlägga", en: "Understand & map" },
    theme: {
      sv: "Lär känna verksamheten, uppdraget och vad som måste skyddas.",
      en: "Learn the organisation, the mandate and what must be protected.",
    },
  },
  {
    id: "d60",
    title: { sv: "Dag 31–60", en: "Day 31–60" },
    range: { sv: "Bedöma", en: "Assess" },
    theme: {
      sv: "Bedöm hot, risker och hur strukturerat säkerhetsarbetet är i dag.",
      en: "Assess threats, risks and how structured the security work is today.",
    },
  },
  {
    id: "d90",
    title: { sv: "Dag 61–90", en: "Day 61–90" },
    range: { sv: "Prioritera och förankra", en: "Prioritise & align" },
    theme: {
      sv: "Omsätt gap till åtgärder, förankra prioriteringar och rapportera till ledningen.",
      en: "Turn gaps into actions, align priorities and report to management.",
    },
  },
];
export const PLAN_90_TASKS: PlanTask[] = [
  {
    id: "d30.meet-leadership",
    period: "d30",
    area: "mandate",
    title: { sv: "Träffa VD och ledningsgrupp", en: "Meet the CEO and leadership team" },
    description: {
      sv: "Fråga vad säkerhetsfunktionen förväntas skydda och möjliggöra, och vem som fattar beslut om risk.",
      en: "Ask what the security function is expected to protect and enable, and who decides on risk.",
    },
  },
  {
    id: "d30.mandate",
    period: "d30",
    area: "mandate",
    title: { sv: "Skriv ned ditt säkerhetsuppdrag", en: "Write down your security mandate" },
    description: {
      sv: "Fyll i Uppdrag & mandat: rapporteringsväg, beslutsmandat, riskacceptans och granskningsdatum.",
      en: "Complete Mission & Mandate: reporting line, decision authority, risk acceptance and review date.",
    },
  },
  {
    id: "d30.stakeholders",
    period: "d30",
    area: "mandate",
    title: { sv: "Kartlägg nyckelintressenter", en: "Map key stakeholders" },
    description: {
      sv: "HR, IT/CISO, fastighet, juridik, inköp och verksamhetschefer. Notera vem som äger vad.",
      en: "HR, IT/CISO, facilities, legal, procurement and line managers. Note who owns what.",
    },
  },
  {
    id: "d30.assets",
    period: "d30",
    area: "assets",
    title: { sv: "Identifiera skyddsvärden", en: "Identify protected assets" },
    description: {
      sv: "Lista personer, verksamhet, lokaler, information, system, leverantörer och anseende som måste skyddas, med ägare och konsekvens.",
      en: "List the people, operations, facilities, information, systems, suppliers and reputation that must be protected, with owner and consequence.",
    },
  },
  {
    id: "d30.evidence",
    period: "d30",
    area: "evidence",
    title: { sv: "Samla befintliga dokument", en: "Collect existing documents" },
    description: {
      sv: "Policyer, avtal, incidentrapporter, tidigare riskanalyser och revisionsrapporter. Registrera dem som underlag.",
      en: "Policies, contracts, incident reports, previous risk assessments and audit reports. Register them as evidence.",
    },
  },
  {
    id: "d60.baseline",
    period: "d60",
    area: "baseline",
    title: { sv: "Gör ett snabbt säkerhetsnuläge", en: "Complete the quick security baseline" },
    description: {
      sv: "Svara på de viktigaste frågorna per område. Det tar cirka 15 minuter och ger en första mognadsbild.",
      en: "Answer the key questions per domain. It takes about 15 minutes and gives a first maturity picture.",
    },
  },
  {
    id: "d60.risks",
    period: "d60",
    area: "risks",
    title: { sv: "Beskriv de viktigaste riskerna", en: "Describe the most important risks" },
    description: {
      sv: "Koppla varje risk till ett skyddsvärde, utse ägare och bedöm sannolikhet och konsekvens.",
      en: "Link each risk to a protected asset, name an owner and rate likelihood and consequence.",
    },
  },
  {
    id: "d60.monitoring",
    period: "d60",
    area: "monitoring",
    title: { sv: "Sätt upp omvärldsbevakning", en: "Set up monitoring" },
    description: {
      sv: "Formulera bevakningsfrågor och registrera de källor du litar på.",
      en: "Formulate monitoring questions and register the sources you trust.",
    },
  },
  {
    id: "d60.incidents",
    period: "d60",
    area: "baseline",
    title: { sv: "Gå igenom incidenter från senaste året", en: "Review last year's incidents" },
    description: {
      sv: "Vad hände, vad lärde ni er och vilka gap visar de? Registrera gapen manuellt.",
      en: "What happened, what was learned and which gaps do they reveal? Record the gaps manually.",
    },
  },
  {
    id: "d90.gaps",
    period: "d90",
    area: "actions",
    title: { sv: "Prioritera gapen", en: "Prioritise the gaps" },
    description: {
      sv: "Bedöm verksamhetspåverkan för varje gap och besluta vilka som blir åtgärder nu, senare eller accepteras.",
      en: "Rate the business impact of each gap and decide which become actions now, later or are accepted.",
    },
  },
  {
    id: "d90.actions",
    period: "d90",
    area: "actions",
    title: { sv: "Skapa en åtgärdsplan med ägare", en: "Create an action plan with owners" },
    description: {
      sv: "Varje åtgärd behöver ägare, prioritet och förfallodatum. Markera de som kräver ledningsbeslut.",
      en: "Every action needs an owner, a priority and a due date. Mark those that need a management decision.",
    },
  },
  {
    id: "d90.report",
    period: "d90",
    area: "reporting",
    title: { sv: "Rapportera säkerhetsläget till ledningen", en: "Report the security position to management" },
    description: {
      sv: "Skapa en ledningsrapport: läge, största risker, prioriterade åtgärder och beslut som krävs.",
      en: "Create a management report: position, major risks, priority actions and decisions required.",
    },
  },
  {
    id: "d90.cadence",
    period: "d90",
    area: "reporting",
    title: { sv: "Besluta rapporterings- och granskningsrytm", en: "Agree a reporting and review cadence" },
    description: {
      sv: "Kom överens om hur ofta läget rapporteras och när mandat, skyddsvärden och risker ses över.",
      en: "Agree how often the position is reported and when the mandate, assets and risks are reviewed.",
    },
  },
];
export function planTasks(period?: PlanPeriodId) {
  return period ? PLAN_90_TASKS.filter((task) => task.period === period) : PLAN_90_TASKS;
}
